.\" SPDX-License-Identifier: GPL-2.0-only
.TH ncollectd-zram 5 "@NCOLLECTD_DATE@" "@NCOLLECTD_VERSION@" "ncollectd zram man page"
.SH NAME
ncollectd-zram \- Documentation of ncollectd's zram plugin
.SH SYNOPSIS
\fBload-plugin\fP zram
.SH DESCRIPTION
The \fBzram\fP plugin report metrics from the compressed block device in RAM (zram).
.SH "SEE ALSO"
.BR ncollectd (1)
.BR ncollectd.conf (5)
