.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-ZRAM 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-zram
.Nd Documentation of ncollectd's zram plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP zram
\fBplugin\fP zram
.Ed
.Sh DESCRIPTION
The \fBzram\fP plugin report metrics from the compressed block device
in RAM (zram).
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
