.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-FCHOST 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-fchost
.Nd Documentation of ncollectd's fchost plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP fchost
\fBplugin\fP fchost
.Ed
.Sh DESCRIPTION
The \fBfchost\fP plugin collectd information about HBA/Fibre Channel used
in the system, collecting data from files in path \fI/sys/class/fchost\fP.
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
