.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-LUA 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-lua
.Nd Documentation of ncollectd's lua plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP lua
\fBplugin\fP lua {
    \fBbase-path\fP \fI/path/to/your/lua/scripts\fP
    \fBload-plugin\fP \fIscript.lua\fP
    \fBplugin\fP \fIname\fP {
        ...
    }
}
.Ed
.Sh DESCRIPTION
The \fBlua\fP plugin embeds a Lua interpreter into collectd and provides an
interface to collectd's plugin system.
This makes it possible to write plugins for collectd in Lua.
.Pp
The minimum required Lua version is \fI5.1\fP.
.Bl -tag -width Ds
.It \fBbase-path\fP \fI/path/to/your/lua/scripts\fP
The directory the \fBlua\fP plugin looks in to find script \fBscript\fP.
If set, this is also prepended to \fBpackage.path\fP.
.It \fBload-plugin\fP \fIscript.lua\fP
The script the \fBlua\fP plugin is going to run.
If \fBbase-path\fP is not specified, this needs to be an absolute path.
.It \fBplugin\fP \fIname\fP
This block may be used to pass on configuration settings to a Lua script.
The configuration is converted into a table which is passed to the
registered configuration callback.
.El
.Sh WRITING YOUR OWN PLUGINS
Writing your own plugins is quite simple, ncollectd manages plugins by means of
\fBdispatch functions\fP which call the appropriate \fBcallback functions\fP
registered by the plugins.
Any plugin basically consists of the implementation of these callback functions
and initializing code which registers the functions with collectd.
See the section \fBEXAMPLES\fP below for a really basic example.
The following types of \fBcallback functions\fP are implemented in the
Lua plugin (all of them are optional):
.Bl -tag -width Ds
.It \fBread functions\fP
These are used to collect the actual data.
It is called once per interval (see the \fBinterval\fP configuration option
of collectd).
Usually it will call \fBncollectd.dispatch_metric_family\fP to dispatch
the metrics to ncollectd which will pass them on to all registered
\fBwrite functions\fP.
If this function does not return 0, interval between its calls will grow
until function returns 0 again.
See the \fBmax-read-interval\fP configuration option of ncollectd.
.It \fBwrite functions\fP
These are used to write the dispatched values.
They are called once for every value that was dispatched by any plugin.
.El
.Sh METATABLES
The following metatables are used to pass values between the Lua plugin
and ncollectd:

.Bl -tag -width Ds

.It \fBMetricUnknownDouble\fP
.Bd -literal
    ncollectd.MetricUnknownDouble.new(value[, labels][, time][, interval])
.Ed
.Bl -tag -width Ds
.It \fBvalue\fP
.It \fBlabels\fP
.It \fBtime\fP
.It \fBinterval\fP
.El
.It \fBMetricUnknownInteger\fP
.Bd -literal
    ncollectd.MetricUnknownInteger.new(value[, labels][, time][, interval])
.Ed
.Bl -tag -width Ds
.It \fBvalue\fP
.It \fBlabels\fP
.It \fBtime\fP
.It \fBinterval\fP
.El
.It \fBMetricGaugeDouble\fP
.Bd -literal
    ncollectd.MetricGaugeDouble.new(value[, labels][, time][, interval])
.Ed
.Bl -tag -width Ds
.It \fBvalue\fP
.It \fBlabels\fP
.It \fBtime\fP
.It \fBinterval\fP
.El
.It \fBMetricGaugeInteger\fP
.Bd -literal
    ncollectd.MetricGaugeInteger.new(value[, labels][, time][, interval])
.Ed
.Bl -tag -width Ds
.It \fBvalue\fP
.It \fBlabels\fP
.It \fBtime\fP
.It \fBinterval\fP
.El
.It \fBMetricCounterDouble\fP
.Bd -literal
    ncollectd.MetricCounterDouble.new(value[, labels][, time][, interval])
.Ed
.Bl -tag -width Ds
.It \fBvalue\fP
.It \fBlabels\fP
.It \fBtime\fP
.It \fBinterval\fP
.El
.It \fBMetricCounterInteger\fP
.Bd -literal
    ncollectd.MetricCounterInteger.new(value[, labels][, time][, interval])
.Ed
.Bl -tag -width Ds
.It \fBvalue\fP
.It \fBlabels\fP
.It \fBtime\fP
.It \fBinterval\fP
.El
.It \fBMetricInfo\fP
.Bd -literal
    ncollectd.MetricInfo.new(info[, labels][, time][, interval])
.Ed
.Bl -tag -width Ds
.It \fBinfo\fP
.It \fBlabels\fP
.It \fBtime\fP
.It \fBinterval\fP
.El
.It \fBMetricStateSet\fP
.Bd -literal
    ncollectd.MetricStateSet.new(set[, labels][, time][, interval])
.Ed
.Bl -tag -width Ds
.It \fBset\fP
.It \fBlabels\fP
.It \fBtime\fP
.It \fBinterval\fP
.El
.It \fBMetricSummary\fP
.Bd -literal
    ncollectd.MetricSummary.new(sum, count, quantiles[, labels][, time][, interval])
.Ed
.Bl -tag -width Ds
.It \fBsum\fP
.It \fBcount\fP
.It \fBquantiles\fP
.It \fBlabels\fP
.It \fBtime\fP
.It \fBinterval\fP
.El
.It \fBMetricHistogram\fP
.Bd -literal
    ncollectd.MetricHistogram.new(sum, buckets[, labels][, time][, interval])
.Ed
.Bl -tag -width Ds
.It \fBsum\fP
.It \fBbuckets\fP
.It \fBlabels\fP
.It \fBtime\fP
.It \fBinterval\fP
.El
.It \fBMetricGaugeHistogram\fP
.Bd -literal
    ncollectd.MetricGaugeHistogram.new(sum, buckets[, labels][, time][, interval])
.Ed
.Bl -tag -width Ds
.It \fBsum\fP
.It \fBbuckets\fP
.It \fBlabels\fP
.It \fBtime\fP
.It \fBinterval\fP
.El


.It \fBMetricFamily\fP
.Bd -literal
    ncollectd.MetricFamily.new(type, name[, help][, unit][, metrics])
.Ed
.Bl -tag -width Ds
.It dispatch([time])
.It append(metrics)
.El
.Bl -tag -width Ds
.It \fBtype\fP
.It \fBname\fP
.It \fBhelp\fP
.It \fBunit\fP
.It \fBmetrics\fP
.El

.It \fBNotification\fP
.Bd -literal
    ncollectd.Notification.new(name[, severity][, time][, labels][, annotations])
.Ed
.Bl -tag -width Ds
.It dispatch()
.El
.Bl -tag -width Ds
.It \fBtype\fP
.It \fBname\fP
.It \fBhelp\fP
.It \fBunit\fP
.It \fBmetrics\fP
.El


.It \fBLOG_ERR\fP
.It \fBLOG_WARNING\fP
.It \fBLOG_NOTICE\fP
.It \fBLOG_INFO\fP
.It \fBLOG_DEBUG\fP

.It \fBMETRIC_UNKNOWN\fP
.It \fBMETRIC_GAUGE\fP
.It \fBMETRIC_COUNTER\fP
.It \fBMETRIC_STATE_SET\fP
.It \fBMETRIC_INFO\fP
.It \fBMETRIC_SUMMARY\fP
.It \fBMETRIC_HISTOGRAM\fP
.It \fBMETRIC_GAUGE_HISTOGRAM\fP

.It \fBNOTIF_FAILURE\fP
.It \fBNOTIF_WARNING\fP
.It \fBNOTIF_OKAY\fP
.EL

.Sh FUNCTIONS
The following functions are provided to Lua modules:
.Bl -tag -width Ds
.It \fBregister_*\fP(\fIcallback\fP[, \fIdata\fP][, \fIname\fP]) -> \fIidentifier\fP
There are seven different register functions to get callback for seven
different events.
With one exception all of them are called as shown above.
.Bl -tag -width Ds
.It \fIcallback\fP
Is the name of a function, a string with the name of the function or an
anonymous function that will be called every time the event is triggered.
.It \fIdata\fP
Is an optional data that will be passed back to the callback function
every time it is called.
If you omit this parameter no data is passed back to your callback.
.It \fIname\fP
Is an optional identifier for this callback.
Every callback needs a unique identifier.
.It \fIidentifier\fP
Is the full identifier assigned to this callback.
.El

.Pp
These functions are called in the various stages of the daemon (see the section
\fBWRITING YOUR OWN PLUGINS\fP above) and are passed the following arguments:
.Bl -tag -width Ds
.It \fBregister_config\fP
The only argument passed is a table withe the configuration.
Note that you cannot receive the whole config files this way, only \fBplugin\fP
blocks inside the Lua configuration block.
Additionally you will only receive blocks where your callback identifier
matches the \fBname\fP.
.It \fBregister_init\fP
The callback will be called without arguments.
.It \fBregister_read\fP(\fIcallback\fP[, \fIinterval\fI][, \fIdata\fP][, \fIname\fP]) -> \fIidentifier\fP
This function takes an additional parameter: \fIinterval\fP.
It specifies the time between calls to the callback function.
If this callback function does not return 0 the next call will be delayed by
an increasing interval.
.Pp
The callback will be called without arguments.
.It \fBregister_shutdown\fP
The callback will be called without arguments.
.It \fBregister_write\fP
The callback function will be called with one argument passed, which will be a
\fIMetricFamily\fP metatable.
For the layout of \fIMetricFamily\fP see above.
If this callback function does not return 0 the next call will be delayed by
an increasing interval.
.It \fBregister_log\fP
The arguments are \fIseverity\fP and \fImessage\fP.
The severity is an integer and small for important messages and high for less
important messages.
The least important level is \fBLOG_DEBUG\fP, the most important level
is \fBLOG_ERR\fP.
In between there are (from least to most important): \fBLOG_INFO\fP,
\fBLOG_NOTICE\fP, and \fBLOG_WARNING\fP.
\fImessage\fP is simply a string \fBwithout\fP a newline at the end.
.Pp
If this callback throws an exception it will \fBnot\fP be logged.
It will just be printed to \fBsys.stderr\fP which usually means
silently ignored.
.It \fBregister_notification\fP
The only argument passed is a \fINotification\fP metatable.
See above for the layout of this data type.
.El
.It \fBunregister_*\fP(\fIidentifier\fP)
Removes a callback or data-set from collectd's internal list of callback
functions.
Every \fIregister_*\fP function has an \fIunregister_*\fP function.
\fIIdentifier\fP is the value that was returned by the register function.
.It \fBerror, warning, notice, info, debug\fP(\fImessage\fP)
Log a message with the specified severity.
.El
.Sh EXAMPLES
A very simple read function might look like:
.Bd -literal
    function read()
        local file, error = io.open("/proc/loadavg", "r")
        if (file == nil) then
            ncollectd.error("Cannot open file: "..error)
            return -1
        end
        local content = file:read "*a"
        local load = {}
        local idx = 1
        for item in string.gmatch(content, "%d*%.?%d+") do
            load[idx] = item
            idx = idx + 1
        end
        file:close()
        
        local fam = ncollectd.MetricFamily.new("system_load", ncollectd.METRIC_GAUGE, "System load averages")
        fam:append(ncollectd.MetricGaugeDouble.new(load[1], {duration = "1m"}))
        fam:append(ncollectd.MetricGaugeDouble.new(load[2], {duration = "5m"}))
        fam:append(ncollectd.MetricGaugeDouble.new(load[3], {duration = "15m"}))
        fam:dispatch()
      
        return 0
    end

.Ed
.Pp
A very simple write function might look like:
.Bd -literal
    function write(fam)
        if (fam.type == ncollectd.METRIC_GAUGE) then
            io.write("# TYPE "..fam.name.." gauge".."\\n")
            if (fam.help ~= nil) then
                io.write("# HELP "..fam.name.." "..fam.help.."\\n")
            end
            local metrics = fam.metrics
            for i, metric in pairs(metrics) do
                io.write(fam.name.."{")
                local labels = metric.labels
                local j = 0
                for lkey, lvalue in pairs(labels) do
                    if j > 0 then
                        io.write(",")
                    end
                    j = j + 1
                    io.write("\\""..lkey.."\\"=\\""..lvalue.."\\"")
                end
                io.write("} "..metric.value.." "..math.floor(metric.time*1000).."\\n")
            end
        end
      
        return 0
    end
.Ed
.Pp
To register those functions with collectd:
.Bd -literal
    ncollectd.register_read(read)     -- pass function as variable
    ncollectd.register_write("write") -- pass by global-scope function name
.Ed
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
