.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-THERMAL 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-thermal
.Nd Documentation of ncollectd's thermal plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP thermal
\fBplugin\fP thermal {
    \fBdevice\fP  [\fIincl|include|excl|exclude\fP] \fIdevice\fP
    \fBforce-use-procfs\fP \fItrue|false\fP
}
.Ed
.Sh DESCRIPTION
The \fBthermal\fP plugin reads ACPI thermal zone information from the sysfs or
procfs file system, i. e. mostly system temperature information.
.Bl -tag -width Ds
.It \fBdevice\fP  [\fIincl|include|excl|exclude\fP] \fIdevice\fP
Selects the name of the thermal device that you want to collect or ignore.
This option may be used multiple times to specify a list of devices.
If no selection is configured at all, \fBall\fP devices are selected.
.It \fBforce-use-procfs\fP \fItrue|false\fP
By default, the \fIthermal\fP plugin tries to read the statistics from the Linux
\fIsysfs\fP interface.
If that is not available, the plugin falls back to the \fIprocfs\fP interface.
By setting this option to \fItrue\fP, you can force the plugin to use
the latter.
This option defaults to \fIfalse\fP.
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
