.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-OPENLDAP 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-openldap
.Nd Documentation of ncollectd's openldap plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP openldap
\fBplugin\fP openldap {
    \fBinstance\fP \fIname\fP {
        \fBurl\fP \fIldap://host/binddn\fP
        \fBbind-dn\fP \fIDN\fP
        \fBpassword\fP \fIpassword\fP
        \fBpassword-env\fP \fIenv-name\fP
        \fBca-cert\fP \fI/path/to/ca\fP
        \fBstart-tls\fP \fItrue|false\fP
        \fBtimeout\fP \fIseconds\fP
        \fBverify-host\fP \fItrue|false\fP
        \fBversion\fP \fIversion\fP
        \fBinterval\fP \fIseconds\fP
        \fBlabel\fP \fIkey\fP \fIvalue\fP
        \fBfilter\fP {
            ...
        }
    }
}
.Ed
.Sh DESCRIPTION
To use the \fPopenldap\fP plugin you first need to configure the \fIOpenLDAP\fP
server correctly.
The backend database \f(CWmonitor\fP needs to be loaded and working.
See
.Xr slapd-monitor 5
for the details.
.Pp
The configuration of the \fBopenldap\fP plugin consists of one or more
\fBinstance\fP blocks.
Each block requires one string argument as the instance name.
.Pp
The instance name will be used as the label instance.
In order for the plugin to work correctly, each instance name must be unique.
This is not enforced by the plugin and it is your responsibility to
ensure it is.
.Pp
The following options are accepted within each \fBinstance\fP block:
.Bl -tag -width Ds
.It \fBurl\fP \fIldap://host/binddn\fP
Sets the URL to use to connect to the OpenLDAP server.
This option is mandatory.
.It \fBbind-dn\fP \fIDN\fP
Name in the form of an LDAP distinguished name intended to be used for
authentication.
Defaults to empty string to establish an anonymous authorization.
.It \fBpassword\fP \fIpassword\fP
Password for simple bind authentication.
If this option is not set, unauthenticated bind operation is used.
.It \fBpassword-env\fP \fIenv-name\fP
Get the password for simple bind authentication from the environment
variable \fIenv-name\fP.
.It \fBca-cert\fP \fI/path/to/ca\fP
File that holds one or more SSL certificates.
If you want to use TLS/SSL you may possibly need this option.
What CA certificates are checked by default depends on the distribution
you use and can be changed with the usual ldap
client configuration mechanisms.
See
.Xr ldap.conf 5
for the details.
.It \fBstart-tls\fP \fItrue|false\fP
Defines whether TLS must be used when connecting to the OpenLDAP server.
Disabled by default.
.It \fBtimeout\fP \fIseconds\fP
Sets the timeout value for ldap operations, in seconds.
By default, the configured \fIinterval\fP is used to set the timeout.
Use \fB-1\fP to disable (infinite timeout).
.It \fBverify-host\fP \fItrue|false\fP
Enables or disables peer host name verification.
If enabled, the plugin checks if the \f(CWCommon Name\fP or a
\f(CWSubject Alternate Name\fP field of the SSL certificate matches
the host name provided by the \fBURL\fP option.
If this identity check fails, the connection is aborted.
Enabled by default.
.It \fBversion\fP \fIversion\fP
An integer which sets the LDAP protocol version number to use when connecting
to the OpenLDAP server.
Defaults to \fB3\fP for using \fILDAPv3\fP.
.It \fBinterval\fP \fIseconds\fP
Sets the interval (in seconds) in which the values will be collected from this
URL.
By default the global \fBinterval\fP setting will be used.
.It \fBlabel\fP \fIkey\fP \fIvalue\fP
Append the label \fIkey\fP=\fIvalue\fP to the submitting metrics.
.It \fBfilter\fP
Configure a filter to modify or drop the metrics.
See \fBFILTER CONFIGURATION\fP in
.Xr ncollectd.conf 5 .
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
