.\" SPDX-License-Identifier: GPL-2.0-only
.TH ncollectd-openldap 5 "@NCOLLECTD_DATE@" "@NCOLLECTD_VERSION@" "ncollectd openldap man page"
.SH NAME
ncollectd-openldap \- Documentation of ncollectd's openldap plugin
.SH SYNOPSIS
\fBload-plugin\fP openldap
.br
\fBplugin\fP openldap {
    \fBinstance\fP \fIname\fP {
        \fBurl\fP \fIldap://host/binddn\fP
        \fBbind-dn\fP \fIDN\fP
        \fBpassword\fP \fIpassword\fP
        \fBpassword-env\fP \fIenv-name\fP
        \fBca-cert\fP \fI/path/to/ca\fP
        \fBstart-tls\fP \fItrue|false\fP
        \fBtimeout\fP \fIseconds\fP
        \fBverify-host\fP \fItrue|false\fP
        \fBversion\fP \fIversion\fP
        \fBinterval\fP \fIseconds\fP
        \fBlabel\fP \fIkey\fP \fIvalue\fP
        \fBfilter\fP {
            ...
        }
    }
.br
}
.SH DESCRIPTION
To use the \fPopenldap\fP plugin you first need to configure the \fIOpenLDAP\fP
server correctly. The backend database \f(CWmonitor\fP needs to be loaded and
working. See
.BR slapd-monitor (5)
for the details.
.PP
The configuration of the \fBopenldap\fP plugin consists of one or more \fBinstance\fP
blocks. Each block requires one string argument as the instance name.
.PP
The instance name will be used as the label instance.  In order for the
plugin to work correctly, each instance name must be unique. This is not
enforced by the plugin and it is your responsibility to ensure it is.
.PP
The following options are accepted within each \fBinstance\fP block:
.PP
.TP
\fBurl\fP \fIldap://host/binddn\fP
Sets the URL to use to connect to the OpenLDAP server. This option is
mandatory.
.TP
\fBbind-dn\fP \fIDN\fP
Name in the form of an LDAP distinguished name intended to be used for
authentication. Defaults to empty string to establish an anonymous authorization.
.TP
\fBpassword\fP \fIpassword\fP
Password for simple bind authentication. If this option is not set,
unauthenticated bind operation is used.
.TP
\fBpassword-env\fP \fIenv-name\fP
Get the password for simple bind authentication from the environment variable \fIenv-name\fP.
.TP
\fBca-cert\fP \fI/path/to/ca\fP
File that holds one or more SSL certificates. If you want to use TLS/SSL you
may possibly need this option. What CA certificates are checked by default
depends on the distribution you use and can be changed with the usual ldap
client configuration mechanisms. See
.BR ldap.conf (5)
for the details.
.TP
\fBstart-tls\fP \fItrue|false\fP
Defines whether TLS must be used when connecting to the OpenLDAP server.
Disabled by default.
.TP
\fBtimeout\fP \fIseconds\fP
Sets the timeout value for ldap operations, in seconds. By default, the
configured \fIinterval\fP is used to set the timeout. Use \fB-1\fP to disable
(infinite timeout).
.TP
\fBverify-host\fP \fItrue|false\fP
Enables or disables peer host name verification. If enabled, the plugin checks
if the C<Common Name> or a C<Subject Alternate Name> field of the SSL
certificate matches the host name provided by the B<URL> option. If this
identity check fails, the connection is aborted. Enabled by default.
.TP
\fBversion\fP \fIversion\fP
An integer which sets the LDAP protocol version number to use when connecting
to the OpenLDAP server. Defaults to \fB3\fP for using \fILDAPv3\fP.
.TP
\fBinterval\fP \fIseconds\fP
Sets the interval (in seconds) in which the values will be collected from this
URL. By default the global \fBinterval\fP setting will be used.
.TP
\fBlabel\fP \fIkey\fP \fIvalue\fP
Append the label \fIkey\fP=\fIvalue\fP to the submitting metrics.
.TP
\fBfilter\fP
Configure a filter to modify or drop the metrics. See \fBFILTER CONFIGURATION\fP in
.BR ncollectd.conf(5)
.SH "SEE ALSO"
.BR ncollectd (1)
.BR ncollectd.conf (5)
