.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-MATCH_TABLE 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-match_table
.Nd Documentation of ncollectd's table match plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBmatch\fP table {
    \fBseparator\fP \fIstring\fP
    \fBskip-lines\fP \fIlines\fP
    \fBmetric-prefix\fP \fIprefix\fP
    \fBlabel\fP \fIkey\fP \fIvalue\fP
    \fBmetric\fP {
        \fBtype\fP \fIgauge\fP [\fIaverage|min|max|last|inc|add|persist\fP]|\fIcounter\fP [\fIset|add|inc\fP]
        \fBhelp\fP \fIhelp\fP
        \fBmetric\fP \fIname\fP
        \fBmetric-prefix\fP \fIprefix\fP
        \fBmetric-from\fP \fIcolumn\fP
        \fBlabel\fP \fIkey\fP \fIvalue\fP
        \fBlabel-from\fP \fIkey\fP \fIcolumn\fP
        \fBvalue-from\fP \fIcolumn\fP
    }
}
.Ed
.Sh DESCRIPTION
The \fBmatch_table\fP plugin provides generic means to parse tabular data
and dispatch user specified values.
Values are selected based on column numbers.
.Pp
The configuration consists of one or more \fBtable\fP blocks, each of which
configures one file to parse.
Within each \fBtable\fP block, there are one or more \fBresult\fP blocks,
which configure which data to select and how to interpret it.
.Pp
The following options are available inside a \fBmatch\fP block:
.Bl -tag -width Ds
.It \fBseparator\fP \fIstring\fP
Any character of string is interpreted as a delimiter between the different
columns of the table.
A sequence of two or more contiguous delimiters in the table is considered
to be a single delimiter, i. e. there cannot be any empty columns.
The default value is \f(CW" \\t"\fP.
.Pp
A horizontal tab, newline and carriage return may be specified by \f(CW\\t\fP,
\f(CW\\n\fP and \f(CW\\r\fP respectively.
Please note that the double backslashes are required because of ncollectd's
config parsing.
.It \fBskip-lines\fP \fIlines\fP
Skip the number of \fIlines\fP at the beginning of the file.
.It \fBmetric-prefix\fP \fIprefix\fP
Prepends the \fIprefix\fP to the metric name in the block \fBresult\fP.
.It \fBlabel\fP \fIkey\fP \fIvalue\fP
Append the label \fIkey\fP=\fIvalue\fP to the submitting metrics.
Can appear multiple time in the \fBtable\fP block.
.It \fBmetric\fP
.Bl -tag -width Ds
.It \fBtype\fP \fIgauge\fP [\fIaverage|min|max|last|inc|add|persist\fP]|\fIcounter\fP [\fIset|add|inc\fP]
.Bl -tag -width Ds
.It \fBgauge\fP
The value is a gauge, you must specify also the type of the gauge:
.Bl -tag -width Ds
.It \fBaverage\fP
Calculate the average
.It \fBmin\fP
Use the smallest number only.
.It \fBmax\fP
Use the greatest number only.
.It \fBlast\fP
Use the last number found.
.It \fBinc\fP
Increase the internal counter by one.
.It \fBadd\fP
Add the matched value to the internal counter.
.It \fBpersist\fP
Use the last number found.
The number is not reset at the end of an interval.
It is continuously reported until another number is matched.
.El
.It \fBcounter\fP
The value is a counter, you must specify also the type of the counter:
.Bl -tag -width Ds
.It \fBset\fP
Simply sets the internal counter to this value.
.It \fBadd\fP
Add the matched value to the internal counter.
.It \fBinc\fP
Increase the internal counter by one.
.El
.El
.It \fBhelp\fP \fIhelp\fP
Set metric help.
.It \fBmetric\fP \fIname\fP
Set metric name.
.It \fBlabel\fP \fIkey\fP \fIvalue\fP
Append the label \fIkey\fP=\fIvalue\fP to the submitting metrics.
.It \fBmetric-prefix\fP \fIprefix\fP
Prepend the \fIprefix\fP to the metrics found in the \fBmetric-from\fP.
.It \fBmetric-from\fP \fIcolumn\fP
Configure to read the metric from the column with the zero-based index.
.It \fBlabel-from\fP \fIkey\fP \fIcolumn\fP
Set the label \fIkey\fP with the value from the column with the zero-based index.
.It \fBvalue-from\fP \fIcolumn\fP
Configure to read the value from the column with the zero-based index.
.El
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
