.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-XFRM 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-xfrm
.Nd Documentation of ncollectd's xfrm plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP xfrm
\fBplugin\fP xfrm
.Ed
.Sh DESCRIPTION
The \fBxfrm\fP plugin collectd metrics from IP framework for transforming
packets in the Linux Kernel.
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
