.\" SPDX-License-Identifier: GPL-2.0-only
.TH ncollectd-xfrm 5 "@NCOLLECTD_DATE@" "@NCOLLECTD_VERSION@" "ncollectd xfrm man page"
.SH NAME
ncollectd-xfrm \- Documentation of ncollectd's xfrm plugin
.SH SYNOPSIS
\fBload-plugin\fP xfrm
.SH DESCRIPTION
The \fBxfrm\fP plugin collectd metrics from IP framework for transforming packets
in the Linux Kernel.
.SH "SEE ALSO"
.BR ncollectd (1)
.BR ncollectd.conf (5)
