.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-SYSTEMD_RESOLVED 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-systemd_resolved
.Nd Documentation of ncollectd's systemd_resolved plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP systemd_resolved
\fBplugin\fP systemd_resolved
.Ed
.Sh DESCRIPTION
The \fBsystemd_resolved\fP plugin collects statistics from
\fBsystemd-resolved\fP.
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
