.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-EPICS 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-epics
.Nd Documentation of ncollectd's epics plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP epics
\fBplugin\fP epics {
    \fBmetric-prefix\fP \fIprefix\fP
    \fBlabel\fP \fIkey\fP \fIvalue\fP
    \fBmetric\fP {
        \fBmetric\fP \fImetric\fP
        \fBhelp\fP \fIhelp\fP
        \fBtype\fP [\fIgauge\fP | \fIcounter\fP]
        \fBlabel\fP \fIkey\fP \fIindex\fP
        \fBlabel-from\fP \fIkey\fP \fIpv-name\fP
        \fBvalue-from\fP \fIpv-name\fP [\fIindex\fP]
    }
}
.Ed
.Sh DESCRIPTION
The \fBepics\fP plugin collects data from EPICS (Experimental Physics and
Industrial Control System) message bus.
.Pp
Note that in addition to the plugin configuration, the host OS has to be
configured to be part of the message bus: caRepeater daemon is up and running
and appropriate EPICS environment variables are set, if required.
Consult EPICS documentation for details.
.Pp
The plugin configuration consists of multiple \fBmetric\fP blocks,
each per monitored EPICS Process Variable (PV).
The variables are constantly monitored and their values are latched once per
plugin interval.
.Bl -tag -width Ds
.It \fBmetric-prefix\fP \fIprefix\fP
Prepends \fIprefix\fP to the metrics name.
.It \fBlabel\fP \fIkey\fP \fIvalue\fP
Append the label \fIkey\fP=\fIvalue\fP to all metrics.
.It \fBmetric\fP
The metric block defines a metric to collect from the EPICS message bus.
.Bl -tag -width Ds
.It \fBmetric\fP \fImetric\fP
Set the metric name.
.It \fBhelp\fP \fIhelp\fP
Set the \fBhelp\fP text for the metric.
.It \fBtype\fP [\fIgauge\fP | \fIcounter\fP]
The \fBtype\fP that's used for each metric returned.
Must be \fIgauge\fP or \fIcounter\fP,
.It \fBlabel\fP \fIkey\fP \fIindex\fP
Append the label \fIkey\fP=\fIvalue\fP to the submitting metrics.
Can appear multiple time in the \fBmetric\fP block.
.It \fBlabel-from\fP \fIkey\fP \fIpv-name\fP
String-typed PV can be monitored as a label.
For instance, this can potentially be useful for tracking an experiment ID.
.It \fBvalue-from\fP \fIpv-name\fP [\fIindex\fP]
Especifies the PV to collect the value of the metric.
If the index not set is 0.
.El
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
