.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-MATCH_REGEX 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-match_regex
.Nd Documentation of ncollectd's regex match plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBmatch\fP regex {
    \fBmetric-prefix\fP \fIprefix\fP
    \fBlabel\fP \fIkey\fP \fIvalue\fP
    \fBmetric\fP {
        \fBregex\fP \fIregex\fP
        \fBexclude-regex\fP \fIregexp\fP
        \fBtype\fP [\fIgauge\fP [\fIaverage|min|max|last|inc|add|persist\fP] | \fIcounter\fP [\fIset|add|inc\fP]]
        \fBmetric\fP \fImetric\fP
        \fBhelp\fP \fIhelp\fP
        \fBlabel\fP \fIkey\fP \fIindex\fP
        \fBmetric-prefix\fP \fIprefix\fP
        \fBmetric-from\fP \fIindex\fP
        \fBlabel-from\fP \fIkey\fP \fIindex\fP
        \fBvalue-from\fP \fIindex\fP
        \fBtime-from\fP \fIindex\fP
    }
}
.Ed
.Sh DESCRIPTION
The \fBmatch_regex\fP plugin parses data matching regular expressions.
.Bl -tag -width Ds
.It \fBmetric-prefix\fP \fIprefix\fP
.It \fBlabel\fP \fIkey\fP \fIvalue\fP
.It \fBmetric\fP
.Bl -tag -width Ds
.It \fBregex\fP \fIregex\fP
Sets the regular expression to use for matching against a line.
.It \fBexclude-regex\fP \fIregexp\fP
Sets an optional regular expression to use for excluding lines from the match.
.It \fBtype\fP [\fIgauge\fP [\fIaverage|min|max|last|inc|add|persist\fP] | \fIcounter\fP [\fIset|add|inc\fP]]
.Bl -tag -width Ds
.It \fBgauge\fP
The value is a gauge, you must specify also the type of the gauge:
.Bl -tag -width Ds
.It \fBaverage\fP
Calculate the average
.It \fBmin\fP
Use the smallest number only.
.It \fBmax\fP
Use the greatest number only.
.It \fBlast\fP
Use the last number found.
.It \fBinc\fP
Increase the internal counter by one.
.It \fBadd\fP
Add the matched value to the internal counter.
.It \fBpersist\fP
Use the last number found.
The number is not reset at the end of an interval.
It is continuously reported until another number is matched.
.El
.It \fBcounter\fP
The value is a counter, you must specify also the type of the counter:
.Bl -tag -width Ds
.It \fBset\fP
Simply sets the internal counter to this value.
.It \fBadd\fP
Add the matched value to the internal counter.
.It \fBinc\fP
Increase the internal counter by one.
.El
.El
.It \fBmetric\fP \fImetric\FP
.It \fBhelp\fP \fIhelp\fP
.It \fBlabel\fP \fIkey\fP \fIindex\fP
.It \fBmetric-prefix\fP \fIprefix\fP
.It \fBmetric-from\fP \fIindex\fP
.It \fBlabel-from\fP \fIkey\fP \fIindex\fP
.It \fBvalue-from\fP \fIindex\fP
.It \fBtime-from\fP \fIindex\fP
.El
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
