.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-SENSORS 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-sensors
.Nd Documentation of ncollectd's sensors plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP sensors
\fBplugin\fP sensors {
    \fBsensor-config-file\fP \fI/path/to/config\fP
    \fBuse-labels\fP \fItrue|false\fP
}
.Ed
.Sh DESCRIPTION
The \fBsensors\fP plugin uses \fIlm_sensors\fP in Linux systems
to retrieve sensor-values.
This means that all the needed modules have to be loaded and lm_sensors
has to be configured (most likely by editing \f(CW/etc/sensors.conf\fP.
Read
.Xr sensors.conf 5
for details.
.Bl -tag -width Ds
.It \fBsensor-config-file\fP \fI/path/to/config\fP
Read the \fIlm_sensors\fP configuration from \fI/path/to/config\fP.
When unset (recommended), the library's default will be used.
Only for Linux systems.
.It \fBuse-labels\fP \fItrue|false\fP
Configures how sensor readings are reported.
When set to \fBtrue\fP, sensor readings are reported using their descriptive
label (e.g. "VCore").
When set to \fBfalse\fP (the default) the sensor name is used ("in0").
Only for Linux systems.
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
