/* SPDX-License-Identifier: GPL-2.0-only   */

#pragma once

enum {
    FAM_SENSOR_VOLTAGE_VOLTS,
    FAM_SENSOR_FAN_SPEED_RPM,
    FAM_SENSOR_TEMPERATURE_CELSIUS,
    FAM_SENSOR_POWER_WATTS,
    FAM_SENSOR_POWER_AVERAGE_WATTS,
    FAM_SENSOR_CURRENT_AMPS,
    FAM_SENSOR_HUMIDITY,
    FAM_SENSOR_INTRUSION_ALARM,
    FAM_SENSOR_MAX,
};

