.\" SPDX-License-Identifier: GPL-2.0-only
.TH ncollectd-nfconntrack 5 "@NCOLLECTD_DATE@" "@NCOLLECTD_VERSION@" "ncollectd nfconntrack man page"
.SH NAME
ncollectd-nfconntrack \- Documentation of ncollectd's nfconntrack plugin
.SH SYNOPSIS
\fBload-plugin\fP nfconntrack
.SH DESCRIPTION
The \fBnfconntrack\fP plugin collect statistics from the conntrack table reading the file
\fI/proc/net/stat/nf_conntrack\fP.
.SH "SEE ALSO"
.BR ncollectd (1)
.BR ncollectd.conf (5)
