.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-NOTIFY_NAGIOS 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-notify_nagios
.Nd Documentation of ncollectd's notify_nagios plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP notify_nagios
\fBplugin\fP notify_nagios {
    \fBcommand-file\fP \fIpath\fP
}
.Ed
.Sh DESCRIPTION
The \fBnotify_nagios\fP plugin writes notifications to Nagios'
\fIcommand file\fP as a \fIpassive service check result\fP.
.Pp
Available configuration options:
.Bl -tag -width Ds
.It \fBcommand-file\fP \fIpath\fP
Sets the \fIcommand file\fP to write to.
Defaults to \f(CW/usr/local/nagios/var/rw/nagios.cmd\fP.
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
