.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-BONDING 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-bonding
.Nd Documentation of ncollectd's bonding plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP bonding
\fBplugin\fP bonding
.Ed
.Sh DESCRIPTION
The \fBbonding\fP plugin reports the number of slave interfaces on
a bonding device and the number of those interfaces that are active.
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
