.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-SENDMAIL 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-sendmail
.Nd Documentation of ncollectd's sendmail plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP sendmail
\fBplugin\fP sendmail {
    \fBinstance\fP \fIname\fP {
        \fBconfig-path\fP \fIconfig-file-path\fP
        \fBqueue-path\fP \fIqueue-path\fP
        \fBhistogram-queue-size-buckets\fP [\fIbucket\fP] ...
        \fBhistogram-queue-age-buckets\fP [\fIbucket\fP] ...
        \fBlabel\fP \fIkey\fP \fIvalue\fP
        \fBinterval\fP \fIinterval\fP
        \fBfilter\fP {
            ...
        }
    }
}
.Ed
.Sh DESCRIPTION
The \fBsendmail\fP plugin will collect statistics from a \fIsendmail\fP MTA
using stastus file.
.Pp
The plugin configuration consists of one or more \fBinstance\fP blocks which
specify one \fIsendmail\fP MTA each.
Within the \fBinstance\fP blocks, the following options are allowed:
.Bl -tag -width Ds
.It \fBconfig-path\fP \fIconfig-file-path\fP
Set the sendmail config file path to get the mailers name and status file path.
The default value is \f(CW/etc/mail/sendmail.cf\fP.
.It \fBqueue-path\fP \fIqueue-path\fP
Set the path for de queue directory.
The default value is \f(CW/var/spool/mqueue\fP.
.It \fBhistogram-queue-size-buckets\fP [\fIbucket\fP] ...
Define the list of buckets for queue size histogram.
.It \fBhistogram-queue-age-buckets\fP [\fIbucket\fP] ...
Define the list of buckets for queue age histogram.
.It \fBlabel\fP \fIkey\fP \fIvalue\fP
Append the label \fIkey\fP=\fIvalue\fP to the submitting metrics.
.It \fBinterval\fP \fIinterval\fP
Sets the interval (in seconds) in which the values will be collected from this
instance.
By default the global \fBinterval\fP setting will be used.
.It \fBfilter\fP
Configure a filter to modify or drop the metrics.
See \fBFILTER CONFIGURATION\fP in
.El
.Xr ncollectd.conf 5 .
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
