.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-SOFTNET 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-softnet
.Nd Documentation of ncollectd's softnet plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP softnet
\fBplugin\fP softnet
.Ed
.Sh DESCRIPTION
The \fBsoftnet\fP plugin collect data of the packets recived based on CPU cores,
reading the file \fI/proc/net/softnet_stat\fP.
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
