.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-BTRFS 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-btrfs
.Nd Documentation of ncollectd's btrfs plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP brtfs
\fBplugin\fP brtfs {
    \fBrefresh-mounts\fP \fItrue|false\fP
}
.Ed
.Sh DESCRIPTION
The \fBbtrfs\fP plugin reports statistics of mounted btrfs filesystems.
.Pp
The plugin has the following options:
.Bl -tag -width Ds
.It \fBrefresh-mounts\fP \fItrue|false\fP
Not caching the mount points, refresh in every read.
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
