.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-STATSD 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-statsd
.Nd Documentation of ncollectd's statsd plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP statsd
\fBplugin\fP statsd {
    \fBinstance\fP \fIname\fP {
        \fBhost\fP \fIhost\fP
        \fBport\fP \fIport\fP
        \fBdelete-counters\fP \fItrue|false\fP
        \fBdelete-timers\fP \fItrue|false\fP
        \fBdelete-gauges\fP \fItrue|false\fP
        \fBdelete-sets\fP \fItrue|false\fP
        \fBtimer-buckets\fP \fIbucket\fP [[\fIbucket\fP] ...]
        \fBinterval\fP \fIseconds\fP
        \fBmetric-prefix\fP \fIprefix\fP
        \fBlabel\fP \fIkey\fP \fIvalue\fP
        \fBfilter\fP {
            ...
        }
    }
}
.Ed
.Sh DESCRIPTION
The \fBstatsd\fP plugin listens to a UDP socket, reads "events" in the statsd
protocol and dispatches rates or other aggregates of these numbers periodically.
.Pp
The plugin implements the \fIcounter\fP, \fItimer\fP, \fIgauge\fP and \fIset\fP
statds metrics.
.Pp
The configuration of the \fBstatsd\fP plugin consists of one or more
\fBinstance\fP blocks.
Each block requires one string argument as the instance name.
The following configuration options are valid:
.Bl -tag -width Ds
.It \fBhost\fP \fIhost\fP
Bind to the hostname / address \fIhost\fP.
By default, the plugin will bind to the "any" address, i.e. accept packets sent
to any of the hosts addresses.
.It \fBport\fP \fIport\fP
UDP port to listen to.
This can be either a service name or a port number.
Defaults to \f(CW8125\fP.
.It \fBdelete-counters\fP \fItrue|false\fP
.It \fBdelete-timers\fP \fItrue|false\fP
.It \fBdelete-gauges\fP \fItrue|false\fP
.It \fBdelete-sets\fP \fItrue|false\fP
These options control what happens if metrics are not updated in an interval.
If set to \fIfalse\fP, the default, metrics are dispatched unchanged, i.e. the
rate of counters and size of sets will be zero, timers report \f(CWNaN\fP
and gauges are unchanged.
If set to \fBtrue\fP, the such metrics are not dispatched and removed from
the internal cache.
.It \fBtimer-buckets\fP \fIbucket\fP [[\fIbucket\fP] ...]
Config the buckets for the timer histograms.
.It \fBinterval\fP \fIseconds\fP
Sets the interval (in seconds) in which the values will be collected
from this instance.
.It \fBmetric-prefix\fP \fIprefix\fP
Prefix the metrics name with this strings.
.It \fBlabel\fP \fIkey\fP \fIvalue\fP
Append the label \fIkey\fP=\fIvalue\fP to the submitting metrics.
.It \fBfilter\fP
Configure a filter to modify or drop the metrics.
See \fBFILTER CONFIGURATION\fP in
.Xr ncollectd.conf 5 .
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
