FROM rockylinux/rockylinux:10
# EPEL
# libesmtp-devel libipmctl-devel libmodbus-devel  slurm-devel
RUN dnf install -y dnf-plugins-core epel-release && \
    dnf config-manager --set-enabled crb && \
    dnf install -y rpm-build git xz gcc cpp make cmake flex bison gperf kernel-headers \
                   pkgconf-pkg-config c-ares-devel curl-devel java-devel jpackage-utils \
                   libpcap-devel libxml2-devel lm_sensors-devel mariadb-connector-c-devel \
                   net-snmp-devel openldap-devel openssl-devel postgresql-devel xfsprogs-devel \
                   cups-devel systemd-devel libatasmart-devel libmicrohttpd-devel libnftnl-devel \
                   librabbitmq-devel librdkafka-devel libvirt-devel lua-devel OpenIPMI-devel \
                   unixODBC-devel varnish-libs-devel perl-ExtUtils-Embed python3-devel \
                   hiredis-devel mongo-c-driver-devel gpsd-devel \
                   libmemcached-awesome-devel qpid-proton-c-devel freetds-devel \
                   mosquitto-devel nut-devel && \
    dnf clean all && \
    rm -rf /var/cache/yum
