.\" SPDX-License-Identifier: GPL-2.0-only
.TH ncollectd-slabinfo 5 "@NCOLLECTD_DATE@" "@NCOLLECTD_VERSION@" "ncollectd slabinfo man page"
.SH NAME
ncollectd-slabinfo \- Documentation of ncollectd's slabinfo plugin
.SH SYNOPSIS
\fBload-plugin\fP slabinfo
.SH DESCRIPTION
The \fBslabinfo\fP plugin collect information about kernel caches reading the file
\f(CW/proc/slabinfo\fP.
.SH "SEE ALSO"
.BR ncollectd (1)
.BR ncollectd.conf (5)
