.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-SLABINFO 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-slabinfo
.Nd Documentation of ncollectd's slabinfo plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP slabinfo
\fBplugin\fP slabinfo
.Ed
.Sh DESCRIPTION
The \fBslabinfo\fP plugin collect information about kernel caches reading the
file \f(CW/proc/slabinfo\fP.
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
