.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-ARPCACHE 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-arpcache
.Nd Documentation of ncollectd's arpcache plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP arpcache
\fBplugin\fP arpcache
.Ed
.Sh DESCRIPTION
The \fBarpcache\fP plugin collect statistics around neighbor cache and ARP,
reading the files \fI/proc/net/stat/arp_cache\fP for IPv4 and
\fI/proc/net/stat/ndisc_cache\fP for IPV6.
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
