.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-WRITE_REDIS 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-write_redis
.Nd Documentation of ncollectd's write_redis plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP write_redis
\fBplugin\fP write_redis {
    \fBinstance\fP \fIname\fP {
        \fBhost\fP \fIhostname\fP
        \fBport\fP \fIport\fP
        \fBsocket\fP \fIsocket-path\fP
        \fBpassword\fP \fIpassword\fP
        \fBpassword-env\fP \fIenv-name\fP
        \fBtimeout\fP \fIseconds\fP
        \fBdatabase\fP \fIdatabase\fP
        \fBretention\fP \fIseconds\fP
        \fBstore-rates\fP \fItrue|false\fP
    }
}
.Ed
.Sh DESCRIPTION
The \fBwrite_redis\fP plugin writes metrics to a redis db with the
RedisTimeSeries module.
.Pp
The plugin has the following options:
.Bl -tag -width Ds
.It \fBhost\fP \fIhostname\fP
The \fBhost\fP option is the hostname or IP-address where the Redis instance is
running on.
.It \fBport\fP \fIport\fP
The \fBport\fP option is the TCP port on which the Redis instance accepts
connections.
Either a service name of a port number may be given.
.It \fBsocket\fP \fIsocket-path\fP
Connect to Redis using the UNIX domain socket at \fIpath\fP.
If this setting is given, the \fBhost\fP and \fBport\fP settings are ignored.
.It \fBpassword\fP \fIpassword\fP
Use \fIpassword\fP to authenticate when connecting to \fIredis\fP.
.It \fBpassword-env\fP \fIenv-name\fP
Get the password to authenticate from the environment variable \fIenv-name\fP.
.It \fBtimeout\fP \fIseconds\fP
.It \fBdatabase\fP \fIdatabase\fP
This index selects the Redis logical database to use for query.
Defaults to \fB0\fP.
.It \fBretention\fP \fIseconds\fP
The maximum retention period for the metrics.
.It \fBstore-rates\fP \fItrue|false\fP
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
