.\" SPDX-License-Identifier: GPL-2.0-only
.TH ncollectd-arp 5 "@NCOLLECTD_DATE@" "@NCOLLECTD_VERSION@" "ncollectd arp man page"
.SH NAME
ncollectd-arp \- Documentation of ncollectd's arp plugin
.SH SYNOPSIS
\fBload-plugin\fP arp
.SH DESCRIPTION
The \fBarp\fP plugin counts the number or entries in the kernel ARP table per interface,
reading the file \fI/proc/net/arp\fP.
.SH "SEE ALSO"
.BR ncollectd (1)
.BR ncollectd.conf (5)
