.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-ISCSI 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-iscsi
.Nd Documentation of ncollectd's iscsi plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP \fIiscsi\fP
\fBplugin\fP \fIiscsi\fP
.Ed
.Sh DESCRIPTION
The \fBiscsi\fP plugin collect metrics from the kernels iSCSI target interface.
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
