.\" SPDX-License-Identifier: GPL-2.0-only
.TH ncollectd-iscsi 5 "@NCOLLECTD_DATE@" "@NCOLLECTD_VERSION@" "ncollectd iscsi man page"
.SH NAME
ncollectd-iscsi \- Documentation of ncollectd's iscsi plugin
.SH SYNOPSIS
\fBload-plugin\fP \fIiscsi\fP
.br
\fBplugin\fP \fIiscsi\fP
.SH DESCRIPTION
The \fBiscsi\fP plugin collect metrics from the kernels iSCSI target interface.
.SH "SEE ALSO"
.BR ncollectd (1)
.BR ncollectd.conf (5)
