=encoding UTF-8

=head1 NAME

ncollectd-cpu - Documentation of ncollectd's C<Conntrack plugin>

=head2 Plugin C<conntrack>

This plugin collects IP conntrack statistics.

=over 4

=item B<OldFiles>

Assume the B<conntrack_count> and B<conntrack_max> files to be found in
F</proc/sys/net/ipv4/netfilter> instead of F</proc/sys/net/netfilter/>.

=back

=head1 SEE ALSO

L<collectd(1)>,
L<collectd.conf(5)>

=cut
