.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-KEEPALIVED 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-keepalived
.Nd Documentation of ncollectd's keepalived plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP keepalived
\fBplugin\fP keepalived {
    \fBinstance\fP \fIinstance\fP {
        \fBpid-path\fP \fI/path/to/pid\fP
        \fBstats-path\fP \fI/path/fo/stats\fP
        \fBdata-path\fP \fI/path/to/data\fP
        \fBlabel\fP \fIkey\fP \fIvalue\fP
        \fBinterval\fP \fIseconds\fP
        \fBfilter\fP {
            ...
        }
    }
}
.Ed
.Sh DESCRIPTION
The \fBkeepalived\fP plugin collect metrics from a keepalived process.
.Pp
The following options are accepted within each \fBinstance\fP block:
.Bl -tag -width Ds
.It \fBpid-path\fP \fI/path/to/pid\fP
Use the specified pidfile for the keepalived.
Default to \fI/var/run/keepalived.pid\fP.
.It \fBstats-path\fP \fI/path/to/stats\fP
Default to \fI/tmp/keepalived.stats\fP
.It \fBdata-path\fP \fI/path/to/data\fP
Default to \fI/tmp/keepalived.data\fP
.It \fBlabel\fP \fIkey\fP \fIvalue\fP
Append the label \fIkey\fP=\fIvalue\fP to the submitting metrics.
.It \fBinterval\fP \fIseconds\fP
Sets the interval (in seconds) in which the values will be collected
from this instance.
.It \fBfilter\fP
Configure a filter to modify or drop the metrics.
See \fBFILTER CONFIGURATION\fP in
.Xr ncollectd.conf 5 .
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
