{
 "title": "Apache",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "label_values(apache_up,hostname)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(apache_up{hostname=\"$hostname\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Apache Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apache_uptime_seconds{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Apache Up/Down",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 21, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "apache_up{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "up"
    },
    {
     "expr": "apache_up{hostname=\"${hostname}\",instance=\"${instance}\"} == bool 0",
     "legendFormat": "down"
    }
   ]
  },
  {
   "title": "Apache requests/s - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "rate(apache_requests_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "request/s"
    }
   ]
  },
  {
   "title": "Apache connections - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "apache_connections{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Apache bytes/s - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(apache_bytes_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "bytes/s"
    }
   ]
  },
  {
   "title": "Apache Workers - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "apache_workers{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Apache Scoreboard - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "apache_scoreboard{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Apache processes - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "apache_processes{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "processes"
    }
   ]
  }
 ]
}