{
 "title": "Battery",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "label_values(system_uptime_seconds,hostname)"
    }
   },
   {
    "name": "battery",
    "label": "Battery",
    "query": {
     "query": "label_values(system_battery_capacity{hostname=\"$hostname\"},battery)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Battery capacity - ${hostname} - ${battery}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * system_battery_capacity_charged{hostname=\"${hostname}\",battery=\"${battery}\"} / system_battery_capacity_design{hostname=\"${hostname}\",battery=\"${battery}\"}",
     "legendFormat": "charged"
    },
    {
     "expr": "100 * (system_battery_capacity_full{hostname=\"${hostname}\",battery=\"${battery}\"} - system_battery_capacity_charged{hostname=\"${hostname}\",battery=\"${battery}\"}) / system_battery_capacity_design{hostname=\"${hostname}\",battery=\"${battery}\"}",
     "legendFormat": "discharged"
    },
    {
     "expr": "100 * (system_battery_capacity_design{hostname=\"${hostname}\",battery=\"${battery}\"} - system_battery_capacity_full{hostname=\"${hostname}\",battery=\"${battery}\"}) / system_battery_capacity_design{hostname=\"${hostname}\",battery=\"${battery}\"}",
     "legendFormat": "degraded"
    }
   ]
  },
  {
   "title": "Battery voltage - ${hostname} - ${battery}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "system_battery_voltage{hostname=\"${hostname}\",battery=\"${battery}\"}",
     "legendFormat": "voltage"
    }
   ]
  },
  {
   "title": "Battery current - ${hostname} - ${battery}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "system_battery_current{hostname=\"${hostname}\",battery=\"${battery}\"}",
     "legendFormat": "current"
    }
   ]
  }
 ]
}