{
 "title": "Bind",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "hostname", "label": "Hostname", "query": { "query": "label_values(bind_up,hostname)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(bind_up{hostname=\"$hostname\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Bind Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-bind_boot_time_seconds{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bind Config Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-bind_config_time_seconds{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bind Up/Down",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "bind_up{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "up"
    },
    {
     "expr": "bind_up{hostname=\"${hostname}\",instance=\"${instance}\"} == bool 0",
     "legendFormat": "down"
    }
   ]
  },
  {
   "title": "Bind incoming queries - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "rate(bind_incoming_queries_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "{{qtype}}"
    }
   ]
  },
  {
   "title": "Bind Incoming Queries Protocol - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "rate(bind_incoming_queries_udp_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "UDP"
    },
    {
     "expr": "rate(bind_incoming_queries_tcp_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "TCP"
    }
   ]
  },
  {
   "title": "Bind Query Errors - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "rate(bind_query_errors_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "{{error}}"
    }
   ]
  },
  {
   "title": "Bind Query recursions - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "rate(bind_query_recursions_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "recursions"
    }
   ]
  },
  {
   "title": "Bind Responses - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(bind_responses_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Bind response RCODE - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "rate(bind_response_rcodes_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "{{rcode}}"
    }
   ]
  },
  {
   "title": "Bind Resolver Queries - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "rate(bind_resolver_queries_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "{{view}} - {{type}}"
    }
   ]
  },
  {
   "title": "Bind Resolver Cache RRSets - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "bind_resolver_cache_rrsets{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "{{view}} - {{type}}"
    }
   ]
  },
  {
   "title": "Bind Resolver Cache Query - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "rate(bind_resolver_cache_query_hits_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "{{view}} - hits"
    },
    {
     "expr": "rate(bind_resolver_cache_query_misses_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "{{view}} - misses"
    }
   ]
  },
  {
   "title": "Bind Resolver Cache - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "rate(bind_resolver_cache_hits_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "{{view}} - hits"
    },
    {
     "expr": "rate(bind_resolver_cache_misses_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "{{view}} - misses"
    }
   ]
  },
  {
   "title": "Bind Resolver Response Truncated - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "rate(bind_resolver_response_truncated_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "{{view}} - hits"
    }
   ]
  },
  {
   "title": "Bind Resolver Errors - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "rate(bind_resolver_resolver_errors_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "{{view}} - {{error}}"
    }
   ]
  },
  {
   "title": "Bind Memory Used - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(bind_memory_use_bytes_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Bind Memory - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "bind_memory_malloced_bytes{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "malloced"
    },
    {
     "expr": "bind_memory_in_use_bytes{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "in use"
    },
    {
     "expr": "bind_memory_context_size_bytes{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "context"
    },
    {
     "expr": "bind_memory_lost_bytes{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "lost"
    }
   ]
  },
  {
   "title": "Bind Socket Accept - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(bind_socket_accept_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Bind Socket Accept Fail - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(bind_socket_accept_fail_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Bind Socket Connect - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(bind_socket_connect_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Bind Socket Connect Fail - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(bind_socket_connect_fail_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}