{
 "title": "CGroups",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "label_values(system_cgroups_processes,hostname)"
    }
   },
   {
    "name": "cgroup",
    "label": "cgroup",
    "query": {
     "query": "label_values(system_cgroups_processes{hostname=\"$hostname\"},cgroup)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPUs - ${hostname} - ${cgroup}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(system_cgroups_cpu_system_seconds_total{hostname=\"${hostname}\",cgroup=\"${cgroup}\"}[$__rate_interval])",
     "legendFormat": "system"
    },
    {
     "expr": "rate(system_cgroups_cpu_user_seconds_total{hostname=\"${hostname}\",cgroup=\"${cgroup}\"}[$__rate_interval])",
     "legendFormat": "user"
    },
    {
     "expr": "system_cgroups_cpu_max_seconds{hostname=\"${hostname}\",cgroup=\"${cgroup}\"}[$__rate_interval]",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Number of process - ${hostname} - ${cgroup}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_cgroups_processes{hostname=\"${hostname}\",cgroup=\"${cgroup}\"}",
     "legendFormat": "process"
    }
   ]
  },
  {
   "title": "CPU Throttled time - ${hostname} - ${cgroup}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(system_cgroups_cpu_throttled_seconds_total{hostname=\"${hostname}\",cgroup=\"${cgroup}\"}[$__rate_interval])",
     "legendFormat": "throttled time"
    }
   ]
  },
  {
   "title": "CPU Throttled times/sec - ${hostname} - ${cgroup}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(system_cgroups_cpu_throttled_total{hostname=\"${hostname}\",cgroup=\"${cgroup}\"}[$__rate_interval])",
     "legendFormat": "throttled times"
    }
   ]
  },
  {
   "title": "Memory - ${hostname} - ${cgroup}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "system_cgroups_memory_bytes{hostname=\"${hostname}\",cgroup=\"${cgroup}\"}",
     "legendFormat": "memory"
    },
    {
     "expr": "system_cgroups_memory_max_bytes{hostname=\"${hostname}\",cgroup=\"${cgroup}\"}",
     "legendFormat": "memory max"
    }
   ]
  },
  {
   "title": "Swap - ${hostname} - ${cgroup}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "system_cgroups_swap_bytes{hostname=\"${hostname}\",cgroup=\"${cgroup}\"}",
     "legendFormat": "swap"
    },
    {
     "expr": "system_cgroups_swap_max_bytes{hostname=\"${hostname}\",cgroup=\"${cgroup}\"}",
     "legendFormat": "swap max"
    }
   ]
  },
  {
   "title": "Memory detail - ${hostname} - ${cgroup}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "system_cgroups_memory_anonymous_active_bytes{hostname=\"${hostname}\",cgroup=\"${cgroup}\"}",
     "legendFormat": "anonymous active"
    },
    {
     "expr": "system_cgroups_memory_anonymous_inactive_bytes{hostname=\"${hostname}\",cgroup=\"${cgroup}\"}",
     "legendFormat": "anoymous inactive"
    },
    {
     "expr": "system_cgroups_memory_page_cache_inactive_bytes{hostname=\"${hostname}\",cgroup=\"${cgroup}\"}",
     "legendFormat": "page cache inactive"
    },
    {
     "expr": "system_cgroups_memory_page_cache_active_bytes{hostname=\"${hostname}\",cgroup=\"${cgroup}\"}",
     "legendFormat": "page cache active"
    },
    {
     "expr": "system_cgroups_memory_kernel_stack_bytes{hostname=\"${hostname}\",cgroup=\"${cgroup}\"}",
     "legendFormat": "kernel stack"
    },
    {
     "expr": "system_cgroups_memory_slab_reclaimable_bytes{hostname=\"${hostname}\",cgroup=\"${cgroup}\"}",
     "legendFormat": "slab reclaimable"
    },
    {
     "expr": "system_cgroups_memory_slab_unreclaimable_bytes{hostname=\"${hostname}\",cgroup=\"${cgroup}\"}",
     "legendFormat": "slab unreclaimable"
    },
    {
     "expr": "system_cgroups_memory_page_tables_bytes{hostname=\"${hostname}\",cgroup=\"${cgroup}\"}",
     "legendFormat": "page tables"
    },
    {
     "expr": "system_cgroups_memory_socket_bytes{hostname=\"${hostname}\",cgroup=\"${cgroup}\"}",
     "legendFormat": "socket"
    },
    {
     "expr": "system_cgroups_memory_swap_cached_bytes{hostname=\"${hostname}\",cgroup=\"${cgroup}\"}",
     "legendFormat": "swap cached"
    },
    {
     "expr": "system_cgroups_memory_max_bytes{hostname=\"${hostname}\",cgroup=\"${cgroup}\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Memory pages events - ${hostname} - ${cgroup}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "pages/sec" } },
   "targets": [
    {
     "expr": "rate(system_cgroups_memory_page_faults_total{hostname=\"${hostname}\",cgroup=\"${cgroup}\"}[$__rate_interval])",
     "legendFormat": "faults"
    },
    {
     "expr": "rate(system_cgroups_memory_page_major_faults_total{hostname=\"${hostname}\",cgroup=\"${cgroup}\"}[$__rate_interval])",
     "legendFormat": "major faults"
    },
    {
     "expr": "rate(system_cgroups_memory_page_refills_total{hostname=\"${hostname}\",cgroup=\"${cgroup}\"}[$__rate_interval])",
     "legendFormat": "refills"
    },
    {
     "expr": "rate(system_cgroups_memory_page_scans_total{hostname=\"${hostname}\",cgroup=\"${cgroup}\"}[$__rate_interval])",
     "legendFormat": "scans"
    },
    {
     "expr": "rate(system_cgroups_memory_page_steals_total{hostname=\"${hostname}\",cgroup=\"${cgroup}\"}[$__rate_interval])",
     "legendFormat": "steals"
    },
    {
     "expr": "rate(system_cgroups_memory_page_activates_total{hostname=\"${hostname}\",cgroup=\"${cgroup}\"}[$__rate_interval])",
     "legendFormat": "activates"
    },
    {
     "expr": "rate(system_cgroups_memory_page_deactivates_total{hostname=\"${hostname}\",cgroup=\"${cgroup}\"}[$__rate_interval])",
     "legendFormat": "deactivates"
    },
    {
     "expr": "rate(system_cgroups_memory_page_lazy_free_total{hostname=\"${hostname}\",cgroup=\"${cgroup}\"}[$__rate_interval])",
     "legendFormat": "lazy free"
    },
    {
     "expr": "rate(system_cgroups_memory_page_lazy_freed_total{hostname=\"${hostname}\",cgroup=\"${cgroup}\"}[$__rate_interval])",
     "legendFormat": "lazy freed"
    }
   ]
  },
  {
   "title": "Memory events - ${hostname} - ${cgroup}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "rate(system_cgroups_memory_event_low_total{hostname=\"${hostname}\",cgroup=\"${cgroup}\"}[$__rate_interval])",
     "legendFormat": "low"
    },
    {
     "expr": "rate(system_cgroups_memory_event_high_total{hostname=\"${hostname}\",cgroup=\"${cgroup}\"}[$__rate_interval])",
     "legendFormat": "high"
    },
    {
     "expr": "rate(system_cgroups_memory_event_max_total{hostname=\"${hostname}\",cgroup=\"${cgroup}\"}[$__rate_interval])",
     "legendFormat": "max"
    },
    {
     "expr": "rate(system_cgroups_memory_event_oom_total{hostname=\"${hostname}\",cgroup=\"${cgroup}\"}[$__rate_interval])",
     "legendFormat": "oom"
    },
    {
     "expr": "rate(system_cgroups_memory_event_oom_kill_total{hostname=\"${hostname}\",cgroup=\"${cgroup}\"}[$__rate_interval])",
     "legendFormat": "oom_kill"
    },
    {
     "expr": "rate(system_cgroups_memory_event_oom_group_kill_total{hostname=\"${hostname}\",cgroup=\"${cgroup}\"}[$__rate_interval])",
     "legendFormat": "oom_group_kill"
    }
   ]
  },
  {
   "title": "Memory workingset - ${hostname} - ${cgroup}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "pages/s" } },
   "targets": [
    {
     "expr": "rate(system_cgroups_memory_workingset_refault_anonymous_total{hostname=\"${hostname}\",cgroup=\"${cgroup}\"}[$__rate_interval])",
     "legendFormat": "refault anonymous"
    },
    {
     "expr": "rate(system_cgroups_memory_workingset_refault_file_total{hostname=\"${hostname}\",cgroup=\"${cgroup}\"}[$__rate_interval])",
     "legendFormat": "refault file"
    },
    {
     "expr": "rate(system_cgroups_memory_workingset_activate_anonymous_total{hostname=\"${hostname}\",cgroup=\"${cgroup}\"}[$__rate_interval])",
     "legendFormat": "activate anonymous"
    },
    {
     "expr": "rate(system_cgroups_memory_workingset_activate_file_total{hostname=\"${hostname}\",cgroup=\"${cgroup}\"}[$__rate_interval])",
     "legendFormat": "activate file"
    },
    {
     "expr": "rate(system_cgroups_memory_workingset_restore_anonymous_total{hostname=\"${hostname}\",cgroup=\"${cgroup}\"}[$__rate_interval])",
     "legendFormat": "restore anonymous"
    },
    {
     "expr": "rate(system_cgroups_memory_workingset_restore_file_total{hostname=\"${hostname}\",cgroup=\"${cgroup}\"}[$__rate_interval])",
     "legendFormat": "restore file"
    },
    {
     "expr": "rate(system_cgroups_memory_workingset_nodereclaim_total{hostname=\"${hostname}\",cgroup=\"${cgroup}\"}[$__rate_interval])",
     "legendFormat": "noderelcaim"
    }
   ]
  },
  {
   "title": "IO bytes/s - ${hostname} - ${cgroup}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(system_cgroups_io_read_bytes_total{hostname=\"${hostname}\",cgroup=\"${cgroup}\"}[$__rate_interval])",
     "legendFormat": "read {{major}}:{{minor}}"
    },
    {
     "expr": "rate(system_cgroups_io_write_bytes_total{hostname=\"${hostname}\",cgroup=\"${cgroup}\"}[$__rate_interval])",
     "legendFormat": "write {{major}}:{{minor}}"
    },
    {
     "expr": "rate(system_cgroups_io_discarted_bytes_total{hostname=\"${hostname}\",cgroup=\"${cgroup}\"}[$__rate_interval])",
     "legendFormat": "discarted {{major}}:{{minor}}"
    }
   ]
  },
  {
   "title": "IO/s - ${hostname} - ${cgroup}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "io/s" } },
   "targets": [
    {
     "expr": "rate(system_cgroups_io_read_ios_total{hostname=\"${hostname}\",cgroup=\"${cgroup}\"}[$__rate_interval])",
     "legendFormat": "read {{major}}:{{minor}}"
    },
    {
     "expr": "rate(system_cgroups_io_write_ios_total{hostname=\"${hostname}\",cgroup=\"${cgroup}\"}[$__rate_interval])",
     "legendFormat": "write {{major}}:{{minor}}"
    },
    {
     "expr": "rate(system_cgroups_io_discarted_ios_total{hostname=\"${hostname}\",cgroup=\"${cgroup}\"}[$__rate_interval])",
     "legendFormat": "discarted {{major}}:{{minor}}"
    }
   ]
  }
 ]
}