{
 "title": "HAProxy Servers",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "label_values(haproxy_up,hostname)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(haproxy_up{hostname=\"$hostname\"},instance)"
    }
   },
   {
    "name": "proxy",
    "label": "backend",
    "query": {
     "query": "label_values(haproxy_backend_status{hostname=\"$hostname\", instance=\"$instance\"},proxy)"
    }
   },
   {
    "name": "server",
    "label": "server",
    "query": {
     "query": "label_values(haproxy_server_status{hostname=\"$hostname\", instance=\"$instance\", proxy=\"$proxy\"},server)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "HAproxy  Server Status - ${hostname} - ${instance} - ${proxy} - ${server}",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(MIN without (haproxy_server_status)(haproxy_server_status{hostname=\"${hostname}\",instance=\"${instance}\",proxy=\"${proxy}\",server=\"${server}\",haproxy_server_status=\"DOWN\"}) * 1) + (MIN without (haproxy_server_status)(haproxy_server_status{hostname=\"${hostname}\",instance=\"${instance}\",proxy=\"${proxy}\",server=\"${server}\",haproxy_server_status=\"UP\"}) * 2) + (MIN without (haproxy_server_status)(haproxy_server_status{hostname=\"${hostname}\",instance=\"${instance}\",proxy=\"${proxy}\",server=\"${server}\",haproxy_server_status=\"MAINT\"}) * 3) + (MIN without (haproxy_server_status)(haproxy_server_status{hostname=\"${hostname}\",instance=\"${instance}\",proxy=\"${proxy}\",server=\"${server}\",haproxy_server_status=\"DRAIN\"}) * 4) + (MIN without (haproxy_server_status)(haproxy_server_status{hostname=\"${hostname}\",instance=\"${instance}\",proxy=\"${proxy}\",server=\"${server}\",haproxy_server_status=\"NOLB\"}) * 5) + (MIN without (haproxy_server_status)(haproxy_server_status{hostname=\"${hostname}\",instance=\"${instance}\",proxy=\"${proxy}\",server=\"${server}\",haproxy_server_status=\"no check\"}) * 6)",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "HAproxy Server Queue - ${hostname} - ${instance} - ${proxy} - ${server}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "haproxy_server_current_queue{hostname=\"${hostname}\",instance=\"${instance}\",proxy=\"${proxy}\",server=\"${server}\"}",
     "legendFormat": "queue"
    }
   ]
  },
  {
   "title": "HAproxy Server Current Sessions - ${hostname} - ${instance} - ${proxy} - ${server}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "haproxy_server_current_sessions{hostname=\"${hostname}\",instance=\"${instance}\",proxy=\"${proxy}\",server=\"${server}\"}",
     "legendFormat": "sessions"
    }
   ]
  },
  {
   "title": "HAproxy Server In/Out Bytes - ${hostname} - ${instance} - ${proxy} - ${server}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(haproxy_server_bytes_in_total{hostname=\"${hostname}\",instance=\"${instance}\",proxy=\"${proxy}\",server=\"${server}\"}[$__rate_interval])",
     "legendFormat": "In"
    },
    {
     "expr": "rate(haproxy_server_bytes_out_total{hostname=\"${hostname}\",instance=\"${instance}\",proxy=\"${proxy}\",server=\"${server}\"}[$__rate_interval])",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "HAproxy Server responses/s - ${hostname} - ${instance} - ${proxy} - ${server}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "rate(haproxy_server_http_responses_total{hostname=\"${hostname}\",instance=\"${instance}\",proxy=\"${proxy}\",server=\"${server}\"}[$__rate_interval])",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "HAProxy Server SSL Sessions/s - ${hostname} - ${instance} - ${proxy} - ${server}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(haproxy_server_ssl_sessions_total{hostname=\"${hostname}\",instance=\"${instance}\",proxy=\"${proxy}\",server=\"${server}\"}[$__rate_interval])",
     "legendFormat": "ssl sessions/s"
    },
    {
     "expr": "rate(haproxy_server_ssl_reused_sessions_total{hostname=\"${hostname}\",instance=\"${instance}\",proxy=\"${proxy}\",server=\"${server}\"}[$__rate_interval])",
     "legendFormat": "ssl reuse sessions/s"
    }
   ]
  },
  {
   "title": "HAproxy  Server SSL Handshake/s - ${hostname} - ${instance} - ${proxy} - ${server}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "rate(haproxy_server_ssl_failed_handshake_total{hostname=\"${hostname}\",instance=\"${instance}\",proxy=\"${proxy}\",server=\"${server}\"}[$__rate_interval])",
     "legendFormat": "Failed handshake/s"
    }
   ]
  },
  {
   "title": "HAProxy Server connections/s - ${hostname} - ${instance} - ${proxy} - ${server}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "rate(haproxy_server_connection_errors_total{hostname=\"${hostname}\",instance=\"${instance}\",proxy=\"${proxy}\",server=\"${server}\"}[$__rate_interval])",
     "legendFormat": "errors/s"
    },
    {
     "expr": "rate(haproxy_server_connection_attempts_total{hostname=\"${hostname}\",instance=\"${instance}\",proxy=\"${proxy}\",server=\"${server}\"}[$__rate_interval])",
     "legendFormat": "attempts/s"
    },
    {
     "expr": "rate(haproxy_server_connection_reuses_total{hostname=\"${hostname}\",instance=\"${instance}\",proxy=\"${proxy}\",server=\"${server}\"}[$__rate_interval])",
     "legendFormat": "reuses/s"
    }
   ]
  }
 ]
}