{
 "title": "HAProxy Frontends",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "label_values(haproxy_up,hostname)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(haproxy_up{hostname=\"$hostname\"},instance)"
    }
   },
   {
    "name": "proxy",
    "label": "frontend",
    "query": {
     "query": "label_values(haproxy_frontend_current_sessions{hostname=\"$hostname\", instance=\"$instance\"},proxy)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "HAproxy  Frontend Status - ${hostname} - ${instance} - ${proxy}",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "MIN without (haproxy_frontend_status)(haproxy_frontend_status{hostname=\"${hostname}\",instance=\"${instance}\",proxy=\"${proxy}\",haproxy_frontend_status=\"DOWN\"} * 1)+ MIN without (haproxy_frontend_status)(haproxy_frontend_status{hostname=\"${hostname}\",instance=\"${instance}\",proxy=\"${proxy}\",haproxy_frontend_status=\"UP\"} * 2)",
     "legendFormat": "status"
    }
   ]
  },
  {
   "title": "HAProxy Frontend connections/s - ${hostname} - ${instance} - ${proxy}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "rate(haproxy_frontend_connections_total{hostname=\"${hostname}\",instance=\"${instance}\",proxy=\"${proxy}\"}[$__rate_interval])",
     "legendFormat": "connections/s"
    },
    {
     "expr": "rate(haproxy_frontend_denied_connections_total{hostname=\"${hostname}\",instance=\"${instance}\",proxy=\"${proxy}\"}[$__rate_interval])",
     "legendFormat": "denied connections/s"
    }
   ]
  },
  {
   "title": "HAProxy Frontend request/s - ${hostname} - ${instance} - ${proxy}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "rate(haproxy_frontend_http_requests_total{hostname=\"${hostname}\",instance=\"${instance}\",proxy=\"${proxy}\"}[$__rate_interval])",
     "legendFormat": "request/s"
    }
   ]
  },
  {
   "title": "HAproxy Frontend In/Out Bytes - ${hostname} - ${instance} - ${proxy}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(haproxy_frontend_bytes_in_total{hostname=\"${hostname}\",instance=\"${instance}\",proxy=\"${proxy}\"}[$__rate_interval])",
     "legendFormat": "In"
    },
    {
     "expr": "rate(haproxy_frontend_bytes_out_total{hostname=\"${hostname}\",instance=\"${instance}\",proxy=\"${proxy}\"}[$__rate_interval])",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "HAproxy Frontend responses/s - ${hostname} - ${instance} - ${proxy}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "rate(haproxy_frontend_http_responses_total{hostname=\"${hostname}\",instance=\"${instance}\",proxy=\"${proxy}\"}[$__rate_interval])",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "HAproxy Frontend Sessions/s - ${hostname} - ${instance} - ${proxy}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(haproxy_frontend_sessions_total{hostname=\"${hostname}\",instance=\"${instance}\",proxy=\"${proxy}\"})",
     "legendFormat": "sessions/s"
    },
    {
     "expr": "rate(haproxy_frontend_denied_sessions_total{hostname=\"${hostname}\",instance=\"${instance}\",proxy=\"${proxy}\"})",
     "legendFormat": "denied sessions/s"
    }
   ]
  },
  {
   "title": "HAproxy Frontend Current Sessions - ${hostname} - ${instance} - ${proxy}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "haproxy_frontend_current_sessions{hostname=\"${hostname}\",instance=\"${instance}\",proxy=\"${proxy}\"}",
     "legendFormat": "sessions"
    }
   ]
  },
  {
   "title": "HAProxy Frontend SSL Sessions/s - ${hostname} - ${instance} - ${proxy}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "rate(haproxy_frontend_ssl_sessions_total{hostname=\"${hostname}\",instance=\"${instance}\",proxy=\"${proxy}\"}[$__rate_interval])",
     "legendFormat": "ssl sessions/s"
    },
    {
     "expr": "rate(haproxy_frontend_ssl_reused_sessions_total{hostname=\"${hostname}\",instance=\"${instance}\",proxy=\"${proxy}\"}[$__rate_interval])",
     "legendFormat": "ssl reuse sessions/s"
    }
   ]
  },
  {
   "title": "HAproxy  Frontend Failed SSL Handshake/s - ${hostname} - ${instance} - ${proxy}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "rate(haproxy_frontend_ssl_failed_handshake_total{hostname=\"${hostname}\",instance=\"${instance}\",proxy=\"${proxy}\"}[$__rate_interval])",
     "legendFormat": "Failed handshake/s"
    }
   ]
  }
 ]
}