{
 "title": "HAProxy",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "label_values(haproxy_up,hostname)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(haproxy_up{hostname=\"$hostname\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "HAproxy Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "haproxy_process_uptime_seconds{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 21, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "haproxy_up{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "UP/DOWN"
    }
   ]
  },
  {
   "title": "HAproxy requests/s - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "rate(haproxy_process_requests_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "request/s"
    }
   ]
  },
  {
   "title": "HAproxy bytes/s - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(haproxy_process_bytes_out_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "bytes/s"
    }
   ]
  },
  {
   "title": "HAproxy connections - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "haproxy_process_current_connections{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "connections"
    },
    {
     "expr": "haproxy_process_current_ssl_connections{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "ssl connections"
    }
   ]
  },
  {
   "title": "Haproxy conections/s - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "rate(haproxy_process_connections_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "connections/s"
    }
   ]
  },
  {
   "title": "HAProxy Request/s - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "rate(haproxy_process_requests_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "request/s"
    }
   ]
  },
  {
   "title": "HAproxy  Tasks - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "haproxy_process_current_tasks{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "Tasks"
    }
   ]
  }
 ]
}