{
 "title": "MySQL",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "label_values(mysql_up,hostname)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(mysql_up{hostname=\"$hostname\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "MySQL connections - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mysql_threads_connected{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "connections"
    }
   ]
  },
  {
   "title": "MySQL connections/s - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mysql_connections_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "connections/s"
    }
   ]
  },
  {
   "title": "MySQL Questions/s  - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mysql_questions_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "questions/s"
    }
   ]
  },
  {
   "title": "MySQL Thread Cache - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mysql_threads_cached{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "cached"
    },
    {
     "expr": "mysql_threads_created{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "created"
    }
   ]
  },
  {
   "title": "MySQL Temporary Objects  - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mysql_created_tmp_tables_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "create tmp tables/s"
    },
    {
     "expr": "rate(mysql_created_tmp_disk_tables_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "create tmp disk tables/s"
    },
    {
     "expr": "rate(mysql_created_tmp_files_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "create tmp files/s"
    }
   ]
  },
  {
   "title": "MySQL Select types  - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mysql_select_range_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "select range/s"
    },
    {
     "expr": "rate(mysql_select_range_check_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "select range check/s"
    },
    {
     "expr": "rate(mysql_select_scan_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "select scan/s"
    },
    {
     "expr": "rate(mysql_select_full_join_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "select full join/s"
    },
    {
     "expr": "rate(mysql_select_full_range_join_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "select full range join/s"
    }
   ]
  },
  {
   "title": "MySQL Sorts  - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mysql_sort_rows_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "sort rows/s"
    },
    {
     "expr": "rate(mysql_sort_range_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "sort range/s"
    },
    {
     "expr": "rate(mysql_sort_merge_passes_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "sort merge passes/s"
    },
    {
     "expr": "rate(mysql_sort_scan_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "sort scan/s"
    }
   ]
  },
  {
   "title": "MySQL Slow Queries  - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mysql_slow_queries_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "slow queries/s"
    }
   ]
  },
  {
   "title": "MySQL Aborted Connections - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mysql_aborted_connects_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "aborted connects (attempts)/s"
    },
    {
     "expr": "rate(mysql_aborted_clients_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "aborted clients (timeout)/s"
    }
   ]
  },
  {
   "title": "MySQL Table Locks - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mysql_table_locks_immediate_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "table locks immediate"
    },
    {
     "expr": "rate(mysql_table_locks_waited_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "table locks waited"
    }
   ]
  },
  {
   "title": "MySQL Network Traffic  - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(mysql_received_bytes_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "received"
    },
    {
     "expr": "rate(mysql_sent_bytes_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "MySQL Internal Memory  - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {}
   ]
  },
  {
   "title": "MySQL Commands - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mysql_commands_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "{{command}}/s"
    }
   ]
  },
  {
   "title": "MySQL Handlers - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mysql_handlers_total{hostname=\"${hostname}\",instance=\"${instance}\",handler!~\"commit|rollback|savepoint.*|prepare\"}[$__rate_interval])",
     "legendFormat": "{{handler}}/s"
    }
   ]
  },
  {
   "title": "MySQL Transaction Handlers - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mysql_handlers_total{hostname=\"${hostname}\",instance=\"${instance}\",handler=~\"commit|rollback|savepoint.*|prepare\"}[$__rate_interval])",
     "legendFormat": "{{handler}}/s"
    }
   ]
  },
  {
   "title": "MySQL Queries in cache - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mysql_qcache_queries_in_cache{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "queries in cache"
    }
   ]
  },
  {
   "title": "MySQL Query Cache Activity - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mysql_qcache_hits_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "hits/s"
    },
    {
     "expr": "rate(mysql_qcache_inserts_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "inserts/s"
    },
    {
     "expr": "rate(mysql_qcache_not_cached_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "not cached/s"
    },
    {
     "expr": "rate(mysql_qcache_lowmem_prunes_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "prunes/s"
    }
   ]
  },
  {
   "title": "MySQL File Openings - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mysql_opened_files_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "openings"
    }
   ]
  },
  {
   "title": "MySQL Queries Memory - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mysql_qcache_free_bytes{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "MySQL Open Tables - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mysql_open_tables{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "open tables"
    }
   ]
  },
  {
   "title": "MySQL Open Table Definition - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mysql_open_table_definitions{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "open table definitios"
    }
   ]
  },
  {
   "title": "MySQL Opened Table Definition - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mysql_opened_table_definitions_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "opened table definitions/s"
    }
   ]
  }
 ]
}