{
 "title": "Ncollectd",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "label_values(system_uptime_seconds,hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ncollectd_uptime_seconds_total{hostname=\"${hostname}\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "Ncollectd dispatched/s - ${hostname}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(ncollectd_metrics_dispached_total{hostname=\"${hostname}\"}[$__rate_interval])",
     "legendFormat": "metrics/s"
    },
    {
     "expr": "rate(ncollectd_notifications_dispached_total{hostname=\"${hostname}\"}[$__rate_interval])",
     "legendFormat": "notifications/s"
    }
   ]
  },
  {
   "title": "Write queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ncollectd write queue drops - ${hostname}",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(ncollectd_write_queue_dropped_total{hostname=\"${hostname}\"}[$__rate_interval])",
       "legendFormat": "drops/s"
      }
     ]
    },
    {
     "title": "Ncollectd write queue size - ${hostname}",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "ncollectd_write_queue_length{hostname=\"${hostname}\"}",
       "legendFormat": "write queue"
      }
     ]
    }
   ]
  },
  {
   "title": "Notify queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ncollectd notify queue drops - ${hostname}",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(ncollectd_notify_queue_dropped_total{hostname=\"${hostname}\"}[$__rate_interval])",
       "legendFormat": "drops/s"
      }
     ]
    },
    {
     "title": "Ncollectd notify queue size - ${hostname}",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "ncollectd_notify_queue_length{hostname=\"${hostname}\"}",
       "legendFormat": "notify queue"
      }
     ]
    }
   ]
  },
  {
   "title": "Plugin reads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ncollectd plugin read calls - ${hostname}",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(ncollectd_plugin_read_calls_total{hostname=\"${hostname}\"}[$__rate_interval])",
       "legendFormat": "{{plugin}}"
      }
     ]
    },
    {
     "title": "Ncollectd plugin read fails - ${hostname}",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "changes(ncollectd_plugin_read_failures_total{hostname=\"${hostname}\"}[$__rate_interval])",
       "legendFormat": "{{plugin}}"
      }
     ]
    },
    {
     "title": "Ncollectd plugin read time per call - ${hostname}",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(ncollectd_plugin_read_time_seconds_total{hostname=\"${hostname}\"}[$__rate_interval]/ncollectd_plugin_read_calls_total{hostname=\"${hostname}\"}[$__rate_interval])",
       "legendFormat": "{{plugin}}"
      }
     ]
    },
    {
     "title": "Ncollectd plugin read user cpu per call - ${hostname}",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(ncollectd_plugin_read_cpu_user_seconds_total{hostname=\"${hostname}\"}[$__rate_interval]/ncollectd_plugin_read_calls_total{hostname=\"${hostname}\"}[$__rate_interval])",
       "legendFormat": "{{plugin}}"
      }
     ]
    },
    {
     "title": "Ncollectd plugin read system cpu per call - ${hostname}",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(ncollectd_plugin_read_cpu_system_seconds_total{hostname=\"${hostname}\"}[$__rate_interval]/ncollectd_plugin_read_calls_total{hostname=\"${hostname}\"}[$__rate_interval])",
       "legendFormat": "{{plugin}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Plugin writes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ncollectd plugin write calls - ${hostname}",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(ncollectd_plugin_write_calls_total{hostname=\"${hostname}\"}[$__rate_interval])",
       "legendFormat": "{{plugin}}"
      }
     ]
    },
    {
     "title": "Ncollectd plugin write failures - ${hostname}",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "changes(ncollectd_plugin_write_failures_total{hostname=\"${hostname}\"}[$__rate_interval])",
       "legendFormat": "{{plugin}}"
      }
     ]
    },
    {
     "title": "Ncollectd plugin write time per call - ${hostname}",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(ncollectd_plugin_write_time_seconds_total{hostname=\"${hostname}\"}[$__rate_interval]/ncollectd_plugin_write_calls_total{hostname=\"${hostname}\"}[$__rate_interval])",
       "legendFormat": "{{plugin}}"
      }
     ]
    },
    {
     "title": "Ncollectd plugin write user cpu per call - ${hostname}",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(ncollectd_plugin_write_cpu_user_seconds_total{hostname=\"${hostname}\"}[$__rate_interval]/ncollectd_plugin_write_calls_total{hostname=\"${hostname}\"}[$__rate_interval])",
       "legendFormat": "{{plugin}}"
      }
     ]
    },
    {
     "title": "Ncollectd plugin write system cpu per call - ${hostname}",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(ncollectd_plugin_write_cpu_system_seconds_total{hostname=\"${hostname}\"}[$__rate_interval]/ncollectd_plugin_write_calls_total{hostname=\"${hostname}\"}[$__rate_interval])",
       "legendFormat": "{{plugin}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Plugin notifications",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ncollectd plugin notification calls - ${hostname}",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(ncollectd_plugin_notify_calls_total{hostname=\"${hostname}\"}[$__rate_interval])",
       "legendFormat": "{{plugin}}"
      }
     ]
    },
    {
     "title": "Ncollectd plugin notification failures - ${hostname}",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(ncollectd_plugin_notify_failures_total{hostname=\"${hostname}\"}[$__rate_interval])",
       "legendFormat": "{{plugin}}"
      }
     ]
    },
    {
     "title": "Ncollectd plugin notify time per call - ${hostname}",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(ncollectd_plugin_notify_time_seconds_total{hostname=\"${hostname}\"}[$__rate_interval]/ncollectd_plugin_notify_calls_total{hostname=\"${hostname}\"}[$__rate_interval])",
       "legendFormat": "{{plugin}}"
      }
     ]
    },
    {
     "title": "Ncollectd plugin notify user cpu per call - ${hostname}",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(ncollectd_plugin_notify_cpu_user_seconds_total{hostname=\"${hostname}\"}[$__rate_interval]/ncollectd_plugin_notify_calls_total{hostname=\"${hostname}\"}[$__rate_interval])",
       "legendFormat": "{{plugin}}"
      }
     ]
    },
    {
     "title": "Ncollectd plugin notify system cpu per call - ${hostname}",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(ncollectd_plugin_notify_cpu_system_seconds_total{hostname=\"${hostname}\"}[$__rate_interval]/ncollectd_plugin_notify_calls_total{hostname=\"${hostname}\"}[$__rate_interval])",
       "legendFormat": "{{plugin}}"
      }
     ]
    }
   ]
  }
 ]
}