{
 "title": "Nginx",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "label_values(nginx_up,hostname)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(nginx_up{hostname=\"$hostname\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Nginx Up/Down",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "nginx_up{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "up"
    },
    {
     "expr": "nginx_up{hostname=\"${hostname}\",instance=\"${instance}\"} == bool 0",
     "legendFormat": "down"
    }
   ]
  },
  {
   "title": "Nginx requests/s - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "request/s"
    }
   ]
  },
  {
   "title": "Ngninx connections - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "nginx_connections_active{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "active"
    },
    {
     "expr": "nginx_connections_reading{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "reading"
    },
    {
     "expr": "nginx_connections_waiting{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "waiting"
    },
    {
     "expr": "nginx_connections_writing{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "writing"
    }
   ]
  },
  {
   "title": "Nginx connections/s - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "conn/s" } },
   "targets": [
    {
     "expr": "rate(nginx_connections_accepted_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "connections/s"
    }
   ]
  },
  {
   "title": "Nginx in-flight request - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "delta(nginx_connections_accepted_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])-delta(nginx_connections_handled_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "in-flight request"
    }
   ]
  }
 ]
}