{
 "title": "Ping",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "label_values(system_uptime_seconds,hostname)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(apache_up{hostname=\"$hostname\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Ping avg - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "ping_latency_avg_seconds{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "from {{source}} to {{destination}}"
    }
   ]
  },
  {
   "title": "Ping stdev - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "ping_latency_stddev_seconds{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "from {{source}} to {{destination}}"
    }
   ]
  },
  {
   "title": "Ping drop% - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "ping_drop_ratio{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "from {{source}} to {{destination}}"
    }
   ]
  }
 ]
}