{
 "title": "Postgresql",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "hostname", "label": "Hostname", "query": { "query": "label_values(pg_up,hostname)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(pg_up{hostname=\"$hostname\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cpu usage % per core - ${hostname}",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "clamp(100 - (sum(rate(system_cpu_usage_seconds_total{hostname=\"${hostname}\",state=~\"idle|wait\"}[$__rate_interval])) without (state) * 100 ), 1e-7, 100)",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Load - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "system_load_1m{hostname=\"${hostname}\"}",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "system_load_5m{hostname=\"${hostname}\"}",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "system_load_15m{hostname=\"${hostname}\"}",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Database backends - ${hostname} - ${instance}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "pg_database_backends{hostname=\"${hostname}\",instance=\"${instance}\"}",
       "legendFormat": "{{database}}"
      }
     ]
    },
    {
     "title": "Database max transaction time - ${hostname} - ${instance}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "pg_activity_max_tx_seconds{hostname=\"${hostname}\",instance=\"${instance}\"}",
       "legendFormat": "{{database}} - {{state}}"
      }
     ]
    },
    {
     "title": "Database connections activity - ${hostname} - ${instance}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "pg_activity_connections{hostname=\"${hostname}\",instance=\"${instance}\"}",
       "legendFormat": "{{database}} - {{state}}"
      }
     ]
    },
    {
     "title": "Database connections - ${hostname} - ${instance}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "pg_settings_max_connections{hostname=\"${hostname}\",instance=\"${instance}\"}",
       "legendFormat": "max connections"
      },
      {
       "expr": "sum(pg_activity_connections{hostname=\"${hostname}\",instance=\"${instance}\"})",
       "legendFormat": "connections"
      }
     ]
    },
    {
     "title": "Database size - ${hostname} - ${instance}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "pg_database_size_bytes{hostname=\"${hostname}\",instance=\"${instance}\"}",
       "legendFormat": "{{database}}"
      }
     ]
    },
    {
     "title": "Database commits/rollbacks - ${hostname} - ${instance}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "xact/s" } },
     "targets": [
      {
       "expr": "rate(pg_database_xact_commit_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
       "legendFormat": "{{database}} - commits"
      },
      {
       "expr": "rate(pg_database_xact_rollback_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
       "legendFormat": "{{database}} - rollbacks"
      }
     ]
    },
    {
     "title": "Database blocks Read/Hit - ${hostname} - ${instance}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "blocks/s" } },
     "targets": [
      {
       "expr": "rate(pg_database_blks_read_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
       "legendFormat": "{{database}} - reads"
      },
      {
       "expr": "rate(pg_database_blks_hit_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
       "legendFormat": "{{database}} - hits"
      }
     ]
    },
    {
     "title": "Database rows - ${hostname} - ${instance}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "tuples/s" } },
     "targets": [
      {
       "expr": "rate(pg_database_returned_rows_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
       "legendFormat": "{{database}} - returned"
      },
      {
       "expr": "rate(pg_database_fetched_rows_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
       "legendFormat": "{{database}} - feched"
      },
      {
       "expr": "rate(pg_database_inserted_rows_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
       "legendFormat": "{{database}} - inserted"
      },
      {
       "expr": "rate(pg_database_updated_rows_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
       "legendFormat": "{{database}} - updated"
      },
      {
       "expr": "rate(pg_database_deleted_rows_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
       "legendFormat": "{{database}} - deleted"
      }
     ]
    },
    {
     "title": "Database temp files - ${hostname} - ${instance}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "files/s" } },
     "targets": [
      {
       "expr": "rate(pg_database_temp_files_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
       "legendFormat": "{{database}}"
      }
     ]
    },
    {
     "title": "Database temp bytes/s - ${hostname} - ${instance}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(pg_database_temp_bytes_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
       "legendFormat": "{{database}}"
      }
     ]
    },
    {
     "title": "Database locks - ${hostname} - ${instance}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "pg_database_locks{hostname=\"${hostname}\",instance=\"${instance}\"}",
       "legendFormat": "{{database}} - {{mode}}"
      }
     ]
    },
    {
     "title": "Database deadlocks - ${hostname} - ${instance}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "deadlocks/s" } },
     "targets": [
      {
       "expr": "rate(pg_database_deadlocks_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
       "legendFormat": "{{database}}"
      }
     ]
    },
    {
     "title": "Database conflits - ${hostname} - ${instance}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "queries/s" } },
     "targets": [
      {
       "expr": "rate(pg_database_conflicts_tablespace_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
       "legendFormat": "{{database}} - tablespace"
      },
      {
       "expr": "rate(pg_database_conflicts_lock_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
       "legendFormat": "{{database}} - lock"
      },
      {
       "expr": "rate(pg_database_conflicts_snapshot_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
       "legendFormat": "{{database}} - snapshot"
      },
      {
       "expr": "rate(pg_database_conflicts_bufferpin_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
       "legendFormat": "{{database}} - bufferpin"
      },
      {
       "expr": "rate(pg_database_conflicts_deadlock_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
       "legendFormat": "{{database}} - deadlock"
      }
     ]
    },
    {
     "title": "Database read Time - ${hostname} - ${instance}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(pg_database_blk_read_time_seconds_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
       "legendFormat": "{{database}}"
      }
     ]
    },
    {
     "title": "Database write time - ${hostname} - ${instance}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(pg_database_blk_write_time_seconds_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
       "legendFormat": "{{database}}"
      }
     ]
    },
    {
     "title": "Database sessions - ${hostname} - ${instance}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "sessions/s" } },
     "targets": [
      {
       "expr": "rate(pg_database_sessions_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
       "legendFormat": "{{database}} - sessions"
      },
      {
       "expr": "rate(pg_database_sessions_abandoned_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
       "legendFormat": "{{database}} - abandoned"
      },
      {
       "expr": "rate(pg_database_sessions_fatal_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
       "legendFormat": "{{database}} - fatal"
      },
      {
       "expr": "rate(pg_database_sessions_killed_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
       "legendFormat": "{{database}} - killed"
      }
     ]
    },
    {
     "title": "Database active time - ${hostname} - ${instance}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(pg_database_active_time_seconds_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
       "legendFormat": "{{database}}"
      }
     ]
    },
    {
     "title": "Database session time - ${hostname} - ${instance}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(pg_database_session_time_seconds_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
       "legendFormat": "{{database}}"
      }
     ]
    },
    {
     "title": "Database idle in transaction time - ${hostname} - ${instance}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(pg_database_idle_in_transaction_time_seconds_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
       "legendFormat": "{{database}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SLRU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "SLRU blocks read - ${hostname} - ${instance}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "blocks/s" } },
     "targets": [
      {
       "expr": "rate(pg_slru_blocks_read_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "SLRU blocks written - ${hostname} - ${instance}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "blocks/s" } },
     "targets": [
      {
       "expr": "rate(pg_slru_blocks_written_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "SLRU blocks zeroed - ${hostname} - ${instance}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "blocks/s" } },
     "targets": [
      {
       "expr": "rate(pg_slru_blocks_zeroed_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "SLRU blocks hit - ${hostname} - ${instance}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "blocks/s" } },
     "targets": [
      {
       "expr": "rate(pg_slru_blocks_hit_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "SLRU blocks exists - ${hostname} - ${instance}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "blocks/s" } },
     "targets": [
      {
       "expr": "rate(pg_slru_blocks_exists_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "SLRU blocks flushes - ${hostname} - ${instance}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "blocks/s" } },
     "targets": [
      {
       "expr": "rate(pg_slru_flushes_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "SLRU blocks truncates - ${hostname} - ${instance}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "blocks/s" } },
     "targets": [
      {
       "expr": "rate(pg_slru_truncates_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Buffer cleans/s- ${hostname} - ${instance}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "cleans/s" } },
     "targets": [
      {
       "expr": "rate(pg_bgwriter_buffers_clean_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
       "legendFormat": "cleans"
      }
     ]
    },
    {
     "title": "Buffer allocs/s- ${hostname} - ${instance}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "allocs/s" } },
     "targets": [
      {
       "expr": "rate(pg_bgwriter_buffers_alloc_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
       "legendFormat": "allocs"
      }
     ]
    },
    {
     "title": "Buffer backend - ${hostname} - ${instance}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "allocs/s" } },
     "targets": [
      {
       "expr": "rate(pg_bgwriter_buffers_backend_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
       "legendFormat": "backend"
      }
     ]
    }
   ]
  },
  {
   "title": "IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Database IO read bytes - ${hostname} - ${instance}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum (rate(pg_io_read_bytes_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])) by (backend)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Database IO read time - ${hostname} - ${instance}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum (rate(pg_io_read_time_seconds_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])) by (backend)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Database IO write bytes - ${hostname} - ${instance}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum (rate(pg_io_write_bytes_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])) by (backend)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Database IO write time - ${hostname} - ${instance}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum (rate(pg_io_write_time_seconds_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])) by (backend)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Database IO writebacks bytes - ${hostname} - ${instance}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum (rate(pg_io_writebacks_bytes_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])) by (backend)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Database IO writebacks time - ${hostname} - ${instance}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum (rate(pg_io_writebacks_time_seconds_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])) by (backend)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Database IO extends bytes - ${hostname} - ${instance}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum (rate(pg_io_extends_bytes_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])) by (backend)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Database IO extends time - ${hostname} - ${instance}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum (rate(pg_io_extends_time_seconds_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])) by (backend)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Database IO fsyncs  - ${hostname} - ${instance}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum (rate(pg_io_fsyncs_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])) by (backend)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Database IO fsyncs time - ${hostname} - ${instance}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum (rate(pg_io_fsyncs_time_seconds_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])) by (backend)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Database IO hits  - ${hostname} - ${instance}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum (rate(pg_io_hits_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])) by (backend)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Database IO evictions  - ${hostname} - ${instance}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum (rate(pg_io_evictions_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])) by (backend)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Database IO reuses  - ${hostname} - ${instance}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum (rate(pg_io_reuses_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])) by (backend)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "WAL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Database WAL files archived  - ${hostname} - ${instance}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "delta(pg_archiver_archived_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
       "legendFormat": "WAL files archived"
      }
     ]
    }
   ]
  },
  {
   "title": "BGWriter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Database bgwriter buffers alloc/s - ${hostname} - ${instance}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "allocs/s" } },
     "targets": [
      {
       "expr": "rate(pg_bgwriter_buffers_alloc_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
       "legendFormat": "allocs/s"
      }
     ]
    },
    {
     "title": "Database bgwriter buffers backend - ${hostname} - ${instance}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "allocs/s" } },
     "targets": [
      {
       "expr": "rate(pg_bgwriter_buffers_backend_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
       "legendFormat": "buffers/s"
      },
      {
       "expr": "rate(pg_bgwriter_buffers_backend_fsync_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
       "legendFormat": "buffers fsync/s"
      }
     ]
    },
    {
     "title": "Database bgwriter buffers clean - ${hostname} - ${instance}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "buffers/s" } },
     "targets": [
      {
       "expr": "rate(pg_bgwriter_buffers_clean_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
       "legendFormat": "buffers/s"
      }
     ]
    },
    {
     "title": "Database bgwriter stopped clean - ${hostname} - ${instance}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "delta(pg_bgwriter_maxwritten_clean_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
       "legendFormat": "stopped"
      }
     ]
    }
   ]
  },
  {
   "title": "Checkpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Database checkpoint scheduled - ${hostname} - ${instance}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "delta(pg_checkpoints_timed_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
       "legendFormat": "checkpoint scheluled"
      }
     ]
    },
    {
     "title": "Database checkpoint requested - ${hostname} - ${instance}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "delta(pg_checkpoints_req_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
       "legendFormat": "checkpoint requested"
      }
     ]
    },
    {
     "title": "Database checkpoint write time - ${hostname} - ${instance}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(pg_checkpoint_write_time_seconds_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
       "legendFormat": "write time"
      }
     ]
    },
    {
     "title": "Database checkpoint sync time - ${hostname} - ${instance}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(pg_checkpoint_sync_time_seconds_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
       "legendFormat": "sync time"
      }
     ]
    },
    {
     "title": "Database checkpoint buffers written - ${hostname} - ${instance}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "buffers/s" } },
     "targets": [
      {
       "expr": "rate(pg_checkpoint_buffers_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
       "legendFormat": "buffers/s"
      }
     ]
    }
   ]
  },
  {
   "title": "Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Slot Active - ${hostname} - ${instance}",
     "type": "state-timeline",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "pg_replication_slot_active{hostname=\"${hostname}\",instance=\"${instance}\"}",
       "legendFormat": "{{slot}} - {{database}}"
      }
     ]
    },
    {
     "title": "WAL LSN Diff - ${hostname} - ${instance}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "pg_replication_slot_wal_lsn_diff_bytes{hostname=\"${hostname}\",instance=\"${instance}\"}",
       "legendFormat": "{{slot}} - {{database}}"
      }
     ]
    },
    {
     "title": "Replication Lag bytes - ${hostname} - ${instance}",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "pg_replication_wal_write_lag_bytes{hostname=\"${hostname}\",instance=\"${instance}\"}",
       "legendFormat": "write - {{application}} - {{client_addr}}"
      },
      {
       "expr": "pg_replication_wal_flush_lag_bytes{hostname=\"${hostname}\",instance=\"${instance}\"}",
       "legendFormat": "flush - {{application}} - {{client_addr}}"
      },
      {
       "expr": "pg_replication_wal_send_lag_bytes{hostname=\"${hostname}\",instance=\"${instance}\"}",
       "legendFormat": "send - {{application}} - {{client_addr}}"
      },
      {
       "expr": "pg_replication_wal_replay_lag_bytes{hostname=\"${hostname}\",instance=\"${instance}\"}",
       "legendFormat": "replay - {{application}} - {{client_addr}}"
      }
     ]
    },
    {
     "title": "Replication Lag seconds - ${hostname} - ${instance}",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "pg_replication_wal_write_lag_seconds{hostname=\"${hostname}\",instance=\"${instance}\"}",
       "legendFormat": "write - {{application}} - {{client_addr}}"
      },
      {
       "expr": "pg_replication_wal_flush_lag_seconds{hostname=\"${hostname}\",instance=\"${instance}\"}",
       "legendFormat": "flush - {{application}} - {{client_addr}}"
      },
      {
       "expr": "pg_replication_wal_replay_lag_seconds{hostname=\"${hostname}\",instance=\"${instance}\"}",
       "legendFormat": "replay - {{application}} - {{client_addr}}"
      }
     ]
    },
    {
     "title": "Replication State - ${hostname} - ${instance}",
     "type": "state-timeline",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "MIN without(pg_replication_state)(pg_replication_state{hostname=\"${hostname}\",instance=\"${instance}\",pg_replication_state=\"startup\"}*1)+\nMIN without(pg_replication_state)(pg_replication_state{hostname=\"${hostname}\",instance=\"${instance}\",pg_replication_state=\"catchup\"}*2)+\nMIN without(pg_replication_state)(pg_replication_state{hostname=\"${hostname}\",instance=\"${instance}\",pg_replication_state=\"streaming\"}*3)+\nMIN without(pg_replication_state)(pg_replication_state{hostname=\"${hostname}\",instance=\"${instance}\",pg_replication_state=\"backup\"}*4)+\nMIN without(pg_replication_state)(pg_replication_state{hostname=\"${hostname}\",instance=\"${instance}\",pg_replication_state=\"stopping\"}*5)",
       "legendFormat": "{{application}} - {{client_addr}}"
      }
     ]
    },
    {
     "title": "Replication Sync State - ${hostname} - ${instance}",
     "type": "state-timeline",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "MIN without(pg_replication_sync_state)(pg_replication_sync_state{hostname=\"${hostname}\",instance=\"${instance}\",pg_replication_sync_state=\"async\"}*1)+\nMIN without(pg_replication_sync_state)(pg_replication_sync_state{hostname=\"${hostname}\",instance=\"${instance}\",pg_replication_sync_state=\"potential\"}*2)+\nMIN without(pg_replication_sync_state)(pg_replication_sync_state{hostname=\"${hostname}\",instance=\"${instance}\",pg_replication_sync_state=\"sync\"}*3)+\nMIN without(pg_replication_sync_state)(pg_replication_sync_state{hostname=\"${hostname}\",instance=\"${instance}\",pg_replication_sync_state=\"quorum\"}*4)",
       "legendFormat": "{{application}} - {{client_addr}}"
      }
     ]
    }
   ]
  }
 ]
}