{
 "title": "Processes",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "label_values(system_uptime_seconds,hostname)"
    }
   },
   {
    "name": "name",
    "label": "name",
    "query": {
     "query": "label_values(system_process_num_process{hostname=\"$hostname\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Number of process - ${hostname} - ${name}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_process_num_process{hostname=\"${hostname}\",name=\"${name}\"}",
     "legendFormat": "process"
    }
   ]
  },
  {
   "title": "Number of threads - ${hostname} - ${name}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_process_num_threads{hostname=\"${hostname}\",name=\"${name}\"}",
     "legendFormat": "threads"
    }
   ]
  },
  {
   "title": "CPUs  - ${hostname} - ${name}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(system_process_cpu_system_seconds_total{hostname=\"${hostname}\",name=\"${name}\"}[$__rate_interval])",
     "legendFormat": "system"
    },
    {
     "expr": "rate(system_process_cpu_user_seconds_total{hostname=\"${hostname}\",name=\"${name}\"}[$__rate_interval])",
     "legendFormat": "user"
    }
   ]
  },
  {
   "title": "Context Switches  - ${hostname} - ${name}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "cs/s" } },
   "targets": [
    {
     "expr": "rate(system_process_contextswitch_involuntary_total{hostname=\"${hostname}\",name=\"${name}\"}[$__rate_interval])",
     "legendFormat": "involuntary"
    },
    {
     "expr": "rate(system_process_contextswitch_voluntary_total{hostname=\"${hostname}\",name=\"${name}\"}[$__rate_interval])",
     "legendFormat": "voluntary"
    }
   ]
  },
  {
   "title": "CPU Schedule  - ${hostname} - ${name}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(system_process_sched_running_seconds_total{hostname=\"${hostname}\",name=\"${name}\"}[$__rate_interval])",
     "legendFormat": "running"
    },
    {
     "expr": "rate(system_process_sched_waiting_seconds_total{hostname=\"${hostname}\",name=\"${name}\"}[$__rate_interval])",
     "legendFormat": "waiting"
    }
   ]
  },
  {
   "title": "Number of timeslices run on the cpu per second  - ${hostname} - ${name}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(system_process_sched_timeslices_total{hostname=\"${hostname}\",name=\"${name}\"}[$__rate_interval])",
     "legendFormat": "slices"
    }
   ]
  },
  {
   "title": "Memory code/data - ${hostname} - ${name}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "system_process_vmem_code_bytes{hostname=\"${hostname}\",name=\"${name}\"}",
     "legendFormat": "code"
    },
    {
     "expr": "system_process_vmem_data_bytes{hostname=\"${hostname}\",name=\"${name}\"}",
     "legendFormat": "data"
    }
   ]
  },
  {
   "title": "Memory resident - ${hostname} - ${name}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "system_process_vmem_size_bytes{hostname=\"${hostname}\",name=\"${name}\"}",
     "legendFormat": "size"
    },
    {
     "expr": "system_process_vmem_rss_bytes{hostname=\"${hostname}\",name=\"${name}\"}",
     "legendFormat": "rss"
    }
   ]
  },
  {
   "title": "Page faults - ${hostname} - ${name}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "faults/s" } },
   "targets": [
    {
     "expr": "rate(system_process_vmem_majflt_total{hostname=\"${hostname}\",name=\"${name}\"}[$__rate_interval])",
     "legendFormat": "major"
    },
    {
     "expr": "rate(system_process_vmem_minflt_total{hostname=\"${hostname}\",name=\"${name}\"}[$__rate_interval])",
     "legendFormat": "minor"
    }
   ]
  },
  {
   "title": "Read/Write Bytes - ${hostname} - ${name}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(system_process_io_rchar_bytes_total{hostname=\"${hostname}\",name=\"${name}\"}[$__rate_interval])",
     "legendFormat": "read"
    },
    {
     "expr": "rate(system_process_io_wchar_bytes_total{hostname=\"${hostname}\",name=\"${name}\"}[$__rate_interval])",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Read/Write System Calls - ${hostname} - ${name}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "syscall/s" } },
   "targets": [
    {
     "expr": "rate(system_process_io_syscr_total{hostname=\"${hostname}\",name=\"${name}\"}[$__rate_interval])",
     "legendFormat": "read"
    },
    {
     "expr": "rate(system_process_io_syscw_total{hostname=\"${hostname}\",name=\"${name}\"}[$__rate_interval])",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Read/Write Disk - ${hostname} - ${name}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(system_process_io_diskr_bytes_total{hostname=\"${hostname}\",name=\"${name}\"}[$__rate_interval])",
     "legendFormat": "read"
    },
    {
     "expr": "rate(system_process_io_diskw_bytes_total{hostname=\"${hostname}\",name=\"${name}\"}[$__rate_interval])",
     "legendFormat": "write"
    }
   ]
  }
 ]
}