{
 "title": "Redis",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "label_values(redis_up,hostname)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(redis_up{hostname=\"$hostname\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Redis Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_uptime_seconds{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis Up/Down",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 21, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "redis_up{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "up"
    },
    {
     "expr": "redis_up{hostname=\"${hostname}\",instance=\"${instance}\"} == bool 0",
     "legendFormat": "down"
    }
   ]
  },
  {
   "title": "Mode",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "MIN without(redis_mode)(redis_mode{hostname=\"${hostname}\",instance=\"${instance}\",redis_mode=\"cluster\"}*1) + MIN without(redis_mode)(redis_mode{hostname=\"${hostname}\",instance=\"${instance}\",redis_mode=\"sentinel\"}*2) + MIN without(redis_mode)(redis_mode{hostname=\"${hostname}\",instance=\"${instance}\",redis_mode=\"standalone\"}*3)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Role",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_role{hostname=\"${hostname}\",instance=\"${instance}\",redis_role=\"master\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Master Link",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_master_link_up{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Master Last IO",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_master_last_io_seconds{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Master Sync In Progress",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_master_sync_in_progress{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Master Failover State",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "MIN without(redis_master_failover_state)(redis_master_failover_state{hostname=\"${hostname}\",instance=\"${instance}\",redis_master_failover_state=\"no-failover\"}*1) + MIN without(redis_master_failover_state)(redis_master_failover_state{hostname=\"${hostname}\",instance=\"${instance}\",redis_master_failover_state=\"failover-in-progress\"}*2) + MIN without(redis_master_failover_state)(redis_master_failover_state{hostname=\"${hostname}\",instance=\"${instance}\",redis_master_failover_state=\"waiting-for-sync\"}*3)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Slave State",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "MIN without(redis_slave_state)(redis_slave_state{hostname=\"${hostname}\",instance=\"${instance}\",redis_slave_state=\"wait_bgsave\"}*1) + MIN without(redis_slave_state)(redis_slave_state{hostname=\"${hostname}\",instance=\"${instance}\",redis_slave_state=\"send_bulk\"}*2) + MIN without(redis_slave_state)(redis_slave_state{hostname=\"${hostname}\",instance=\"${instance}\",redis_slave_state=\"online\"}*3)",
     "legendFormat": "{{slave_address}}"
    }
   ]
  },
  {
   "title": "Slave Lag",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_slave_lag{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "{{slave_address}}"
    }
   ]
  },
  {
   "title": "Slave Offset",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_slave_offset{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "{{slave_address}}"
    }
   ]
  },
  {
   "title": "Slave replication offset",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_slave_replication_offset{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Clients - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "redis_clients_connected{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "connected"
    },
    {
     "expr": "redis_clients_blocked{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "blocked"
    },
    {
     "expr": "redis_clients_tracking{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "tracking"
    },
    {
     "expr": "redis_clients_in_timeout_table{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "in timeout table"
    },
    {
     "expr": "redis_cluster_connections{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "cluster"
    }
   ]
  },
  {
   "title": "Connections per second - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "rate(redis_connections_received_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "received"
    },
    {
     "expr": "rate(redis_rejected_connections_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "rejected"
    }
   ]
  },
  {
   "title": "CPU - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(redis_cpu_sys_main_thread_seconds_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "Sys Main"
    },
    {
     "expr": "rate(redis_cpu_user_main_thread_seconds_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "User Main"
    },
    {
     "expr": "rate(redis_cpu_sys_children_seconds_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "Sys Children"
    },
    {
     "expr": "rate(redis_cpu_user_children_seconds_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "User Children"
    }
   ]
  },
  {
   "title": "Network - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(redis_input_bytes_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "input"
    },
    {
     "expr": "rate(redis_output_bytes_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "output"
    }
   ]
  },
  {
   "title": "Errors - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "redis_errors{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "{{error}}"
    }
   ]
  },
  {
   "title": "Commands per second - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "rate(redis_commands_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "{{cmd}}"
    }
   ]
  },
  {
   "title": "Commands processed per second - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "rate(redis_commands_processed_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "processed"
    }
   ]
  },
  {
   "title": "Commands duration - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(redis_commands_duration_seconds_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "{{cmd}}"
    }
   ]
  },
  {
   "title": "DB keys - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "redis_db_keys{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "keys - db {{db}}"
    },
    {
     "expr": "redis_db_keys_expiring{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "keys expiring - db {{db}}"
    }
   ]
  },
  {
   "title": "Memory Used - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "redis_memory_used_bytes{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "used"
    },
    {
     "expr": "redis_memory_used_peak_bytes{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "peak"
    }
   ]
  },
  {
   "title": "Events processed per second - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "rate(redis_reads_processed_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__interval])",
     "legendFormat": "reads"
    },
    {
     "expr": "rate(redis_writes_processed_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__interval])",
     "legendFormat": "writes"
    }
   ]
  },
  {
   "title": "Memory DataSet - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "redis_memory_used_dataset_bytes{hostname=\"${hostname}\",instance=\"${instance}\"}",
     "legendFormat": "dataset"
    }
   ]
  },
  {
   "title": "Keys HIT/MISS per second - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(redis_keyspace_hits_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "Hits"
    },
    {
     "expr": "rate(redis_keyspace_misses_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "Misses"
    }
   ]
  },
  {
   "title": "Keys Expired/Evicted per second - ${hostname} - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(redis_expired_keys_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "Expired"
    },
    {
     "expr": "rate(redis_evicted_keys_total{hostname=\"${hostname}\",instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "Evited"
    }
   ]
  }
 ]
}