.\" SPDX-License-Identifier: GPL-2.0-only
.TH ncollectd-lvm 5 "@NCOLLECTD_DATE@" "@NCOLLECTD_VERSION@" "ncollectd lvm man page"
.SH NAME
ncollectd-lvm \- Documentation of ncollectd's lvm plugin
.SH SYNOPSIS
\fBload-plugin\fP lvm
\fBplugin\fP lvm
.SH DESCRIPTION
The \fBlvm\fP plugin collects metrics form the Logical Volume Manager (LVM),
of the usage of Volume Grousp (VG) and Logical Volumes (LV).
.SH "SEE ALSO"
.BR ncollectd (1)
.BR ncollectd.conf (5)
