.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-LVM 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-lvm
.Nd Documentation of ncollectd's lvm plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP lvm
\fBplugin\fP lvm
.Ed
.Sh DESCRIPTION
The \fBlvm\fP plugin collects metrics form the Logical Volume Manager (LVM),
of the usage of Volume Grousp (VG) and Logical Volumes (LV).
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
