plugin_option(PLUGIN_VARNISH "Varnish cache statistics" ON)

set(BUILD_PLUGIN_VARNISH 0)

if(PLUGIN_VARNISH)
    find_package(LibVarnishapi)
    if (LIBVARNISHAPI_FOUND)
        if (LIBVARNISHAPI_VERSION LESS 3)
            set(BUILD_PLUGIN_VARNISH_REASON "varnish version must be > 2" PARENT_SCOPE)
        else()
            set(BUILD_PLUGIN_VARNISH 1)
        endif()
    else()
        set(BUILD_PLUGIN_VARNISH_REASON "libvarnish not found" PARENT_SCOPE)
    endif()
endif()

set(BUILD_PLUGIN_VARNISH ${BUILD_PLUGIN_VARNISH} PARENT_SCOPE)

if(BUILD_PLUGIN_VARNISH)
    gperf_generate(varnish_stats.gperf "${CMAKE_CURRENT_BINARY_DIR}/varnish_stats.h" VARNISH_STATS_H)
    set(PLUGIN_VARNISH_SRC varnish.c varnish_fam.c varnish_fam.h varnish_flags.h ${VARNISH_STATS_H})
    add_library(varnish MODULE ${PLUGIN_VARNISH_SRC})
    target_link_libraries(varnish PRIVATE libmetric libutils LibVarnishapi::LibVarnishapi)
    if((LIBVARNISHAPI_VERSION EQUAL 6) OR (LIBVARNISHAPI_VERSION GREATER 6))
        target_compile_definitions(varnish PUBLIC HAVE_VARNISH_V6)
    elseif(LIBVARNISHAPI_VERSION EQUAL 5)
        target_compile_definitions(varnish PUBLIC HAVE_VARNISH_V5)
    elseif(LIBVARNISHAPI_VERSION EQUAL 4)
        target_compile_definitions(varnish PUBLIC HAVE_VARNISH_V4)
    elseif(LIBVARNISHAPI_VERSION EQUAL 3)
        target_compile_definitions(varnish PUBLIC HAVE_VARNISH_V3)
    endif()
    set_target_properties(varnish PROPERTIES PREFIX "")

    if((LIBVARNISHAPI_VERSION EQUAL 6) OR (LIBVARNISHAPI_VERSION GREATER 6))
        add_executable(test_plugin_varnish EXCLUDE_FROM_ALL varnish_test.c ${PLUGIN_VARNISH_SRC})
        target_compile_definitions(test_plugin_varnish PUBLIC HAVE_VARNISH_V6)
        target_link_libraries(test_plugin_varnish libtest libconfig libmetric libutils m LibVarnishapi::LibVarnishapi)
        add_dependencies(build_tests test_plugin_varnish)
        add_test(NAME test_plugin_varnish COMMAND test_plugin_varnish WORKING_DIRECTORY ${CMAKE_SOURCE_DIR})
    endif()

    install(TARGETS varnish DESTINATION ${CMAKE_INSTALL_LIBDIR}/ncollectd/)
    configure_file(ncollectd-varnish.5 ncollectd-varnish.5 @ONLY)
    install(FILES ${CMAKE_CURRENT_BINARY_DIR}/ncollectd-varnish.5 DESTINATION ${CMAKE_INSTALL_MANDIR}/man5)
endif()
