=encoding UTF-8

=head1 NAME

ncollectd-varnish - Documentation of ncollectd's C<varnish plugin>

=head2 Plugin C<varnish>

The I<varnish plugin> collects information about Varnish, an HTTP accelerator.
It collects a subset of the values displayed by L<varnishstat(1)>, and
organizes them in categories which can be enabled or disabled. Currently only
metrics shown in L<varnishstat(1)>'s I<MAIN> section are collected. The exact
meaning of each metric can be found in L<varnish-counters(7)>.

Synopsis:

 <Plugin "varnish">
   <Instance "example">
     CollectBackend     true
     CollectBan         false
     CollectCache       true
     CollectConnections true
     CollectDirectorDNS false
     CollectESI         false
     CollectFetch       false
     CollectHCB         false
     CollectObjects     false
     CollectPurge       false
     CollectSession     false
     CollectSHM         true
     CollectSMA         false
     CollectSMS         false
     CollectSM          false
     CollectStruct      false
     CollectTotals      false
     CollectUptime      false
     CollectVCL         false
     CollectVSM         false
     CollectWorkers     false
     CollectLock        false
     CollectMempool     false
     CollectManagement  false
     CollectSMF         false
     CollectVBE         false
     CollectMSE         false
   </Instance>
 </Plugin>

The configuration consists of one or more E<lt>B<Instance>E<nbsp>I<Name>E<gt>
blocks. I<Name> is the parameter passed to "varnishd -n". If left empty, it
will collectd statistics from the default "varnishd" instance (this should work
fine in most cases).

Inside each E<lt>B<Instance>E<gt> blocks, the following options are recognized:

=over 4

=item B<CollectBackend> B<true>|B<false>

Back-end connection statistics, such as successful, reused,
and closed connections. True by default.

=item B<CollectBan> B<true>|B<false>

Statistics about ban operations, such as number of bans added, retired, and
number of objects tested against ban operations. Only available with Varnish
3.x and above. False by default.

=item B<CollectCache> B<true>|B<false>

Cache hits and misses. True by default.

=item B<CollectConnections> B<true>|B<false>

Number of client connections received, accepted and dropped. True by default.

=item B<CollectDirectorDNS> B<true>|B<false>

DNS director lookup cache statistics. Only available with Varnish 3.x. False by
default.

=item B<CollectESI> B<true>|B<false>

Edge Side Includes (ESI) parse statistics. False by default.

=item B<CollectFetch> B<true>|B<false>

Statistics about fetches (HTTP requests sent to the backend). False by default.

=item B<CollectHCB> B<true>|B<false>

Inserts and look-ups in the crit bit tree based hash. Look-ups are
divided into locked and unlocked look-ups. False by default.

=item B<CollectObjects> B<true>|B<false>

Statistics on cached objects: number of objects expired, nuked (prematurely
expired), saved, moved, etc. False by default.

=item B<CollectPurge> B<true>|B<false>

Statistics about purge operations, such as number of purges added, retired, and
number of objects tested against purge operations. Only available with Varnish
2.x. False by default.

=item B<CollectSession> B<true>|B<false>

Client session statistics. Number of past and current sessions, session herd and
linger counters, etc. False by default. Note that if using Varnish 4.x, some
metrics found in the Connections and Threads sections with previous versions of
Varnish have been moved here.

=item B<CollectSHM> B<true>|B<false>

Statistics about the shared memory log, a memory region to store
log messages which is flushed to disk when full. True by default.

=item B<CollectSMA> B<true>|B<false>

malloc or umem (umem_alloc(3MALLOC) based) storage statistics. The umem storage
component is Solaris specific. Note: SMA, SMF and MSE share counters, enable
only the one used by the Varnish instance. Available with Varnish 2.x,
varnish 4.x and above (Not available in varnish 3.x).
False by default.

=item B<CollectSMS> B<true>|B<false>

synth (synthetic content) storage statistics. This storage
component is used internally only. False by default.

=item B<CollectSM> B<true>|B<false>

file (memory mapped file) storage statistics. Only available with Varnish 2.x,
in varnish 4.x and above use CollectSMF.
False by default.

=item B<CollectStruct> B<true>|B<false>

Current varnish internal state statistics. Number of current sessions, objects
in cache store, open connections to backends (with Varnish 2.x), etc. False by
default.

=item B<CollectTotals> B<true>|B<false>

Collects overview counters, such as the number of sessions created,
the number of requests and bytes transferred. False by default.

=item B<CollectUptime> B<true>|B<false>

Varnish uptime. Only available with Varnish 3.x and above. False by default.

=item B<CollectVCL> B<true>|B<false>

Number of total (available + discarded) VCL (config files). False by default.

=item B<CollectVSM> B<true>|B<false>

Collect statistics about Varnish's shared memory usage (used by the logging and
statistics subsystems). Only available with Varnish 4.x. False by default.

=item B<CollectWorkers> B<true>|B<false>

Collect statistics about worker threads. False by default.

=item B<CollectVBE> B<true>|B<false>

Backend counters. Only available with Varnish 4.x and above. False by default.

=item B<CollectSMF> B<true>|B<false>

file (memory mapped file) storage statistics. Only available with Varnish 4.x and above.
Note: SMA, SMF and MSE share counters, enable only the one used by the Varnish
instance. Used to be called SM in Varnish 2.x. False by default.

=item B<CollectManagement> B<true>|B<false>

Management process counters. Only available with Varnish 4.x and above. False by default.

=item B<CollectLock> B<true>|B<false>

Lock counters. Only available with Varnish 4.x and above. False by default.

=item B<CollectMempool> B<true>|B<false>

Memory pool counters. Only available with Varnish 4.x and above. False by default.

=item B<CollectMSE> B<true>|B<false>

Varnish Massive Storage Engine 2.0 (MSE2) is an improved storage backend for
Varnish, replacing the traditional malloc and file storages. Only available
with Varnish-Plus 4.x and above. Note: SMA, SMF and MSE share counters, enable only the
one used by the Varnish instance. False by default.

=item B<CollectGOTO> B<true>|B<false>

vmod-goto counters. Only available with Varnish Plus 6.x. False by default.

=back

=head1 SEE ALSO

L<ncollectd(1)>,
L<ncollectd.conf(5)>

=cut

