.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-PCAP 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-pcap
.Nd Documentation of ncollectd's pcap plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP pcap
\fBplugin\fP pcap {
    \fBinstance\fP \fIname\fP {
        \fBinterface\fP \fIinterface\fP
        \fBpromiscuous\fP \fItrue|false\fP
        \fBignore-source\fP \fIsource\fP
        \fBignore-destination\fP \fIdestination\fP
        \fBfilter\fP \fIexpression\fP
        \fBlabel\fP \fIkey\fP \fIvalue\fP
        \fBinterval\fP \fIseconds\fP
        \fBfilter\fP {
            ...
        }
    }
}
.Ed
.Sh DESCRIPTION
The \fBpcap\fP plugin uses libpcap to get a copy of all traffic on the
selected interfaces.
.Pp
The \fBpcap\fP plugin supports the following options:
.Bl -tag -width Ds
.It \fBinterface\fP \fIinterface\fP
This option sets the interface that should be used.
If this option is not set, or set to "any", the plugin will try
to get packets from all interfaces.
This may not work on certain platforms, such as Mac OS X.
.It \fBpromiscuous\fP \fItrue|false\fP
Put the interface in promiscuous mode.
.It \fBignore-source\fP \fIsource\fP
Ignore packets that originate from this address.
.It \fBignore-destination\fP \fIdestination\fP
Ignore packets that has destination this address.
.It \fBfilter\fP \fIexpression\fP
Process the packets on a network interface that match the boolean
\fIexpression\fP (see
.Xr pcap-filter 7
for the expression syntax).
.It \fBlabel\fP \fIkey\fP \fIvalue\fP
Append the label \fIkey\fP=\fIvalue\fP to the submitting metrics.
Can appear multiple times in the \fBinstance\fP block.
.It \fBinterval\fP \fIseconds\fP
Sets the interval (in seconds) in which the values will be collected from this
instance.
By default the global \fBinterval\fP setting will be used.
.It \fBfilter\fP
Configure a filter to modify or drop the metrics.
See \fBFILTER CONFIGURATION\fP in
.Xr ncollectd.conf 5 .
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
