.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-UNAME 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-uname
.Nd Documentation of ncollectd's uname plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP uname
\fBplugin\fP uname
.Ed
.Sh DESCRIPTION
The \fBuname\fP plugin allow to get the system information info.
The same that the \f(CWuname\fP commands returns.
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
