.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-INFO 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-info
.Nd Documentation of ncollectd's info plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP info
\fBplugin\fP info {
    \fBmetric\fP "\fIname\fP" {
        \fBhelp\fP "\fIhelp\fP"
        \fBlabel\fP \fIkey\fP \fIvalue\fP
        \fBinfo\fP \fIkey\fP \fIvalue\fP
    }
}
.Ed
.Sh DESCRIPTION
The \fBinfo\fP plugin allow to define static info metrics.
By default sends the metric \fBncollectd_info\fP with the ncollectd version.
.Pp
The configuration of the \fBinfo\fP plugin consists of one or more \fBmetric\fP
blocks.
Each block requires one string argument as the metric name.
.Pp
The following options are accepted within each \fBmetric\fP mblock:
.Bl -tag -width Ds
.It \fBhelp\fP \fIhelp\fP
Set the \fBhelp\fP text for the metric.
.It \fBlabel\fP \fIkey\fP \fIvalue\fP
Append the label \fIkey\fP=\fIvalue\fP to the metric.
Can appear multiple times.
.It \fBinfo\fP \fIkey\fP \fIvalue\fP
Append the info \fIkey\fP=\fIvalue\fP to the metric.
Can appear multiple times.
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
