.\" SPDX-License-Identifier: GPL-2.0-only
.TH ncollectd-ksm 5 "@NCOLLECTD_DATE@" "@NCOLLECTD_VERSION@" "ncollectd ksm man page"
.SH NAME
ncollectd-ksm \- Documentation of ncollectd's ksm plugin
.SH SYNOPSIS
\fBload-plugin\fP ksm
.SH DESCRIPTION
The \fBksm\fP plugin collect statistics from the Kernel Same-page Merging (KSM).
.SH "SEE ALSO"
.BR ncollectd (1)
.BR ncollectd.conf (5)
