.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-KSM 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-ksm
.Nd Documentation of ncollectd's ksm plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP ksm
\fBplugin\fP ksm
.Ed
.Sh DESCRIPTION
The \fBksm\fP plugin collect statistics from the Kernel Same-page Merging (KSM).
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
