.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-LOGIND 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-logind
.Nd Documentation of ncollectd's logind plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP logind
\fBplugin\fP logind {
    \fBgroup-by\fP \fI[seat|remote|type|class] ...\fP
}
.Ed
.Sh DESCRIPTION
The \fBlogind\fP plugin collects information from systemd-login logins.
.Pp
The following configuration options are available:
.Bl -tag -width Ds
.It \fBgroup-by\fP \fI[seat|remote|type|class] ...\fP
Select how login grouping is performed.
Multiple criteria can be specified.
If the string \fIAll\fP is used, al criterias are selected.
If a criterion begins with "!" it is deselected.
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
