.\" SPDX-License-Identifier: GPL-2.0-only
.TH ncollectd-logind 5 "@NCOLLECTD_DATE@" "@NCOLLECTD_VERSION@" "ncollectd logind man page"
.SH NAME
ncollectd-logind \- Documentation of ncollectd's logind plugin
.SH SYNOPSIS
\fBload-plugin\fP logind
.br
\fBplugin\fP logind {
    \fBgroup-by\fP \fI[seat|remote|type|class] ...\fP
.br
}
.SH DESCRIPTION
The \fBlogind\fP plugin collects information from systemd-login logins.
.PP
The following configuration options are available:
.TP
\fBgroup-by\fP \fI[seat|remote|type|class] ...\fP
Select how login grouping is performed. Multiple criteria can be specified.
If the string \fIAll\fP is used, al criterias are selected. If a criterion begins with "!" it is deselected.
By default \fIremote\fP is used.

.SH "SEE ALSO"
.BR ncollectd (1)
.BR ncollectd.conf (5)
