.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-WRITE_MQTT 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-write_mqtt
.Nd Documentation of ncollectd's write_mqtt plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP write_mqtt
\fBplugin\fP write_mqtt {
    \fBinstance\fP \fIname\fP {
        \fBhost\fP \fIhostname\fP
        \fBport\fP \fIport\fP
        \fBtopic\fP \fItopic\fP
        \fBclient-id\fP \fIclient-id\fP
        \fBuser\fP \fIuser\fP
        \fBpassword\fP \fIuser\fP
        \fBqos\fP \fI0|1|2\fP
        \fBstore-rates\fP \fItrue|flase\fP
        \fBretain\fP \fItrue|flase\fP
        \fBca-cert\fP \fIfile\fP
        \fBcertificate-file\fP \fIfile\fP
        \fBcertificate-key-file\fP \fIfile\fP
        \fBtls-protocol\fP \fIprotocol\fP
        \fBcipher-suite\fP \fIciper-suite\fP
        \fBformat-metric\fP \fIinfluxdb|graphite|json|kairosdb|opentsdb|openmetrics|opentelemetry|remote\fP
        \fBformat-notification\fP \fItext|json|protob\fP
        \fBwrite\fP \fImetrics|notifications\fP
    }
}
.Ed
.Sh DESCRIPTION
The \fBwrite_mqtt\fP plugin can send metrics or notifications to a MQTT Broker.
.Pp
Within each \fBinstance\fP block, the following options are available:
.Bl -tag -width Ds
.It \fBhost\fP \fIhostname\fP
Hostname of the MQTT broker to connect to.
.It \fBport\fP \fIport\fP
Port number or service name of the MQTT broker to connect to.
.It \fBtopic\fP \fItopic\fP
Configures the topic to publish the messages.
.It \fBclient-id\fP \fIclient-id\fP
MQTT client ID to use.
Defaults to the hostname used by \fBncollectd\fP.
.It \fBuser\fP \fIuser\fP
Username used when authenticating to the MQTT broker.
.It \fBuser-env\fP \fIenv-name\fP
Get the username used when authenticating to the MQTT broker from
the environment variable
\fIenv-name\fP.
.It \fBpassword\fP \fIuser\fP
Password used when authenticating to the MQTT broker.
.It \fBpassword-env\fP \fIenv-name\fP
Get the password used when authenticating to the MQTT broker from
the environment variable
\fIenv-name\fP.
.It \fBqos\fP \fI0|1|2\fP
Sets the \fIQuality of Service\fP, with the values \fI0\fP, \fI1\fP
and \fI2\fP meaning:
.Bl -tag -width Ds
.It \fB0\fP
At most once
.It \fB1\fP
At least once
.It \fB2\fP
Exactly once
.El
.It \fBstore-rates\fP \fItrue|flase\fP
.It \fBretain\fP \fItrue|flase\fP
Controls whether the MQTT broker will retain (keep a copy of) the last message
sent to each topic and deliver it to new subscribers.
Defaults to \fIfalse\fP.
.It \fBca-cert\fP \fIfile\fP
Path to the PEM-encoded CA certificate file.
Setting this option enables TLS communication with the MQTT broker, and as such,
\fBport\fP should be the TLS-enabled port of the MQTT broker.
This option enables the use of TLS.
.It \fBcertificate-file\fP \fIfile\fP
Path to the PEM-encoded certificate file to use as client certificate when
connecting to the MQTT broker.
Only valid if \fBca-cert\fP and \fBcertificate-key-file\fP are also set.
.It \fBcertificate-key-file\fP \fIfile\fP
Path to the unencrypted PEM-encoded key file corresponding to
\fBcertificate-file\fP.
Only valid if \fBca-cert\fP and \fBcertificate-file\fP are also set.
.It \fBtls-protocol\fP \fIprotocol\fP
If configured, this specifies the string protocol version (e.g. \f(CWtlsv1\fP,
\f(CWtlsv1.2\fP) to use for the TLS connection to the broker.
If not set a default version is used which depends on the version of OpenSSL
the Mosquitto library was linked against.
Only valid if \fBca-cert\fP is set.
.It \fBcipher-suite\fP \fIciper-suite\fP
A string describing the ciphers available for use.
See
.Xr ciphers 1
and the
\f(CWopenssl ciphers\fP utility for more information.
If unset, the default ciphers will be used.
Only valid if \fBca-cert\fP is set.
.It \fBformat-metric\fP \fIinfluxdb|graphite|json|kairosdb|opentsdb|openmetrics|remote\fP
Selects the format in which metrics are written.
.Bl -tag -width Ds
.It \fBinfluxdb\fP [\fIsec|msec|usec|nsec\fP]
Format the metrics with the influxdb line format.
.It \fBgraphite\fP
Format the metrics with the graphite plaintext format.
.It \fBjson\fP
Format the metrics as json message.
.It \fBkairosdb\fP [\fItelnet [sec|msec]|json\fP]
Format the metrics with the karirosdb text format or json format.
.It \fBopentsdb\fP [telnet|json]
Format the metrics with the opentsdb text format or json format.
.It \fBopenmetrics\fP [text|protob]
Format the metrics with the openmetrics text format.
.It \fBopentelemetry\fP [json]
Format the metrics with the opentelemetry json format.
.It \fBremote\fP [metadata]
Format the metrics with the protocol buffer remote format.
.El
.It \fBformat-notification\fP \fItext|json|protob\fP
Selects the format in which notifications are written.
.It \fBwrite\fP \fImetrics|notifications\fP
If set to \fImetrics\fP (the default) the plugin will handle metrics.
If set to \fInotifications\fP the plugin will handle notifications.
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
