.\" SPDX-License-Identifier: GPL-2.0-only
.TH ncollectd-uptime 5 "@NCOLLECTD_DATE@" "@NCOLLECTD_VERSION@" "ncollectd uptime man page"
.SH NAME
ncollectd-uptime \- Documentation of ncollectd's uptime plugin
.SH SYNOPSIS
\fBload-plugin\fP uptime
.SH DESCRIPTION
The \fBuptime\fP plugin keeps track of the system uptime, providing
informations such as the average running time or the maximum reached
uptime over a certain period of time. It can be useful especially
on Linux based routers/firewalls.
.SH "SEE ALSO"
.BR ncollectd (1)
.BR ncollectd.conf (5)
