.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-UPTIME 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-uptime
.Nd Documentation of ncollectd's uptime plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP uptime
\fBplugin\fP uptime
.Ed
.Sh DESCRIPTION
The \fBuptime\fP plugin keeps track of the system uptime, providing
information such as the average running time or the maximum reached
uptime over a certain period of time.
It can be useful especially on Linux based routers/firewalls.
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
