=encoding UTF-8

=head1 NAME

ncollectd-df - Documentation of ncollectd's C<Df plugin>

=head2 Plugin C<df>

=over 4

=item B<Device> I<Device>

Select partitions based on the devicename.

See F</"IGNORELISTS"> for details.

=item B<MountPoint> I<Directory>

Select partitions based on the mountpoint.

See F</"IGNORELISTS"> for details.

=item B<FSType> I<FSType>

Select partitions based on the filesystem type.

See F</"IGNORELISTS"> for details.

=item B<IgnoreSelected> B<true>|B<false>

Invert the selection: If set to true, all partitions B<except> the ones that
match any one of the criteria are collected. By default only selected
partitions are collected if a selection is made. If no selection is configured
at all, B<all> partitions are selected.

=item B<LogOnce> B<false>|B<false>

Only log stat() errors once.

=item B<ReportInodes> B<true>|B<false>

Enables or disables reporting of free, reserved and used inodes. Defaults to
inode collection being disabled.

Enable this option if inodes are a scarce resource for you, usually because
many small files are stored on the disk. This is a usual scenario for mail
transfer agents and web caches.

=item B<ValuesAbsolute> B<true>|B<false>

Enables or disables reporting of free and used disk space in 1K-blocks.
Defaults to B<true>.

=item B<ValuesPercentage> B<false>|B<true>

Enables or disables reporting of free and used disk space in percentage.
Defaults to B<false>.

This is useful for deploying I<collectd> on the cloud, where machines with
different disk size may exist. Then it is more practical to configure
thresholds based on relative disk size.

=back

=head1 SEE ALSO

L<collectd(1)>,
L<collectd.conf(5)>

=cut
