.\" SPDX-License-Identifier: GPL-2.0-only
.TH ncollectd-avccache 5 "@NCOLLECTD_DATE@" "@NCOLLECTD_VERSION@" "ncollectd avccache man page"
.SH NAME
ncollectd-avccache \- Documentation of ncollectd's avccache plugin
.SH SYNOPSIS
\fBload-plugin\fP avccache
.SH DESCRIPTION
The \fBavccache\fP plugin collect statistics of SELinux AVC from the file
\fI/sys/fs/selinux/avc/cache_stats\fP.
.SH "SEE ALSO"
.BR ncollectd (1)
.BR ncollectd.conf (5)
