.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-AVCCACHE  5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-avccache
.Nd Documentation of ncollectd's avccache plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP avccache
\fBplugin\fP avccache
.Ed
.Sh DESCRIPTION
The \fBavccache\fP plugin collect statistics of SELinux AVC from the file
\fI/sys/fs/selinux/avc/cache_stats\fP.
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
