.\" SPDX-License-Identifier: GPL-2.0-only
.TH ncollectd-ipc 5 "@NCOLLECTD_DATE@" "@NCOLLECTD_VERSION@" "ncollectd ipc man page"
.SH NAME
ncollectd-ipc \- Documentation of ncollectd's ipc plugin
.SH SYNOPSIS
\fBload-plugin\fP ipc
.SH DESCRIPTION
The \fBipc\fP plugin collect metrics from the System V IPC about messages, semaphores,
and shared memory.
.SH "SEE ALSO"
.BR ncollectd (1)
.BR ncollectd.conf (5)
