.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-XFS 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-xfs
.Nd Documentation of ncollectd's xfs plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP xfs
\fBplugin\fP xfs {
    \fBdevice\fP [\fIincl|include|excl|exclude\fP] \fIdevice\fP
    \fBcollect\fP \fIflags\fP
}
.Ed
.Sh DESCRIPTION
The \fBxfs\fP plugin collect metrics from xfs filesystems.
.Pp
The following configuration options are available:
.Bl -tag -width Ds
.It \fBdevice\fP [\fIincl|include|excl|exclude\fP] \fIdevice\fP
Select the filesystem based on the devicename.
See \fBINCLUDE AND EXCLUDE LISTS\fP in
.Xr ncollectd.conf 5 .
.It \fBcollect\fP \fIflags\fP
.Bl -tag -width Ds
.It \fIextentalloc\fP
.It \fIabt\fP
.It \fIblkmap\fP
.It \fIbmbt\fP
.It \fIdir\fP
.It \fItrans\fP
.It \fIig\fP
.It \fIlog\fP
.It \fIpushail\fP
.It \fIsstrat\fP
.It \fIrw\fP
.It \fIattr\fP
.It \fIicluster\fP
.It \fIvnodes\fP
.It \fIbuf\fP
.It \fIabtb2\fP
.It \fIabtc2\fP
.It \fIbmbt2\fP
.It \fIibt2\fP
.It \fIfibt2\fP
.It \fIrmapbt\fP
.It \fIrefcntbt\fP
.It \fIqm\fP
.It \fIxpc\fP
.It \fIdefer_relog\fP
.El
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
