.\" SPDX-License-Identifier: GPL-2.0-only
.TH ncollectd-protocols 5 "@NCOLLECTD_DATE@" "@NCOLLECTD_VERSION@" "ncollectd protocols man page"
.SH NAME
ncollectd-protocols \- Documentation of ncollectd's protocols plugin
.SH SYNOPSIS
\fBload-plugin\fP protocols
.br
\fBplugin\fP protocols {
    \fBcollect\fP \fI[ip|icmp|udp|udplite|udplite6|ip6|icmp6|udp6|tcp|mptcp|sctp]\fP
    \fBfilter\fP {
        ...
    }
.br
}
.SH DESCRIPTION
The \fBprotocols\fP plugin collects a lot of information about various
network protocols, such as \fIIP\fP, \fITCP\fP, \fIUDP\fP, etc.
.PP
Available configuration options:
.PP
.TP
\fBcollect\fP \fI[ip|icmp|udp|udplite|udplite6|ip6|icmp6|udp6|tcp|mptcp|sctp]\fP
.RS
.TP
\fBip\fP
.TP
\fBicmp\fP
.TP
\fBudp\fP
.TP
\fBudplite\fP
.TP
\fBudplite6\fP
.TP
\fBip6\fP
.TP
\fBicmp6\fP
.TP
\fBudp6\fP
.TP
\fBtcp\fP
.TP
\fBmptcp\fP
.TP
\fBsctp\fP
.RE
.TP
\fBfilter\fP
Configure a filter to modify or drop the metrics. See \fBFILTER CONFIGURATION\fP in
.BR ncollectd.conf(5)
.SH "SEE ALSO"
.BR ncollectd (1)
.BR ncollectd.conf (5)
