.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-PROTOCOLS 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-protocols
.Nd Documentation of ncollectd's protocols plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP protocols
\fBplugin\fP protocols {
    \fBcollect\fP \fI[ip|icmp|udp|udplite|udplite6|ip6|icmp6|udp6|tcp|mptcp|sctp]\fP
    \fBfilter\fP {
        ...
    }
}
.Ed
.Sh DESCRIPTION
The \fBprotocols\fP plugin collects a lot of information about various
network protocols, such as \fIIP\fP, \fITCP\fP, \fIUDP\fP, etc.
.Pp
Available configuration options:
.Bl -tag -width Ds
.It \fBcollect\fP \fI[ip|icmp|udp|udplite|udplite6|ip6|icmp6|udp6|tcp|mptcp|sctp]\fP
.Bl -tag -width Ds
.It \fBip\fP
.It \fBicmp\fP
.It \fBudp\fP
.It \fBudplite\fP
.It \fBudplite6\fP
.It \fBip6\fP
.It \fBicmp6\fP
.It \fBudp6\fP
.It \fBtcp\fP
.It \fBmptcp\fP
.It \fBsctp\fP
.El
.It \fBfilter\fP
Configure a filter to modify or drop the metrics.
See \fBFILTER CONFIGURATION\fP in
.Xr ncollectd.conf 5 .
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
