/* SPDX-License-Identifier: GPL-2.0-only                             */
/* SPDX-FileCopyrightText: Copyright (C) 2022-2024 Manuel Sanmartín  */
/* SPDX-FileContributor: Manuel Sanmartín <manuel.luis at gmail.com> */

#pragma once

enum {
    FAM_SCTP_CURRENT_ESTABLISHED,
    FAM_SCTP_ACTIVE_ESTABLISHED,
    FAM_SCTP_PASSIVE_ESTABLISHED,
    FAM_SCTP_ABORTEDS,
    FAM_SCTP_SHUTDOWNS,
    FAM_SCTP_OUT_OF_BLUES,
    FAM_SCTP_CHECKSUM_ERRORS,
    FAM_SCTP_OUT_CTRL_CHUNKS,
    FAM_SCTP_OUT_ORDER_CHUNKS,
    FAM_SCTP_OUT_UNORDER_CHUNKS,
    FAM_SCTP_IN_CTRL_CHUNKS,
    FAM_SCTP_IN_ORDER_CHUNKS,
    FAM_SCTP_IN_UNORDER_CHUNKS,
    FAM_SCTP_FRAGMENTED_USER_MSGS,
    FAM_SCTP_OUT_PACKETS,
    FAM_SCTP_REASSEMBLED_USER_MSGS,
    FAM_SCTP_IN_PACKETS,
    FAM_SCTP_T1_INIT_EXPIREDS,
    FAM_SCTP_T1_COOKIE_EXPIREDS,
    FAM_SCTP_T2_SHUTDOWN_EXPIREDS,
    FAM_SCTP_T3_RTX_EXPIREDS,
    FAM_SCTP_T4_RTO_EXPIREDS,
    FAM_SCTP_T5_SHUTDOWN_GUARD_EXPIREDS,
    FAM_SCTP_DELAY_SACK_EXPIREDS,
    FAM_SCTP_AUTOCLOSE_EXPIREDS,
    FAM_SCTP_T3_RETRANSMITS,
    FAM_SCTP_PMTUD_RETRANSMITS,
    FAM_SCTP_FAST_RETRANSMITS,
    FAM_SCTP_IN_PKT_SOFTIRQ,
    FAM_SCTP_IN_PKT_BACKLOG,
    FAM_SCTP_IN_PKT_DISCARDS,
    FAM_SCTP_IN_DATA_CHUNK_DISCARDS,
    FAM_SCTP_MAX,
};
