.\" SPDX-License-Identifier: GPL-2.0-only
.TH ncollectd-battery 5 "@NCOLLECTD_DATE@" "@NCOLLECTD_VERSION@" "ncollectd battery man page"
.SH NAME
ncollectd-battery \- Documentation of ncollectd's battery plugin
.SH SYNOPSIS
\fBload-plugin\fP battery
.br
\fBplugin\fP battery
.SH DESCRIPTION
The \fBbattery\fP plugin reports the remaining capacity, power and voltage of
laptop batteries.
.SH "SEE ALSO"
.BR ncollectd (1)
.BR ncollectd.conf (5)
