.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-BATTERY 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-battery
.Nd Documentation of ncollectd's battery plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP battery
\fBplugin\fP battery
.Ed
.Sh DESCRIPTION
The \fBbattery\fP plugin reports the remaining capacity, power and voltage of
laptop batteries.
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
