.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-CERTMONGER 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-certmonger
.Nd Documentation of ncollectd's certmonger plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP certmonger
\fBplugin\fP certmonger {
    \fBrequest\fP [\fIincl|include|excl|exclude\fP] \fIname\fP
    \fBfilter\fP {
        ...
    }
}
.Ed
.Sh DESCRIPTION
The \fBcertmonger\fP plugin collects information of certificates tracked
by
.Xr certmonger 8 .
.Pp
The following configuration options are available:
.Bl -tag -width Ds
.It \fBrequest\fP [\fIincl|include|excl|exclude\fP] \fIname\fP
Select the request \fIname\fP.
See \fBINCLUDE AND EXCLUDE LISTS\fP in
.Xr ncollectd.conf 5 .
.It \fBfilter\fP
Configure a filter to modify or drop the metrics.
See \fBFILTER CONFIGURATION\fP in
.Xr ncollectd.conf 5
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
