COMMENT-main =             system metrics collection engine
COMMENT-apache =           ncollectd apache plugin
COMMENT-ats =              ncollectd ats plugin
COMMENT-bind =             ncollectd bind plugin
COMMENT-cert =             ncollectd cert plugin
COMMENT-dns =              ncollectd dns plugin
COMMENT-ds389 =            ncollectd ds389 plugin
COMMENT-haproxy =          ncollectd haproxy plugin
COMMENT-http =             ncollectd http plugin
COMMENT-jolokia =          ncollectd jolokia plugin
COMMENT-ldap =             ncollectd ldap plugin
COMMENT-lua =              ncollectd lua plugin
COMMENT-match_xpath =      ncollectd match_xpath plugin
COMMENT-mosquitto =        ncollectd mosquitto plugin
COMMENT-mssql =            ncollectd mssql plugin
COMMENT-mysql =            ncollectd mysql plugin
COMMENT-nginx =            ncollectd nginx plugin
COMMENT-nginx_vts =        ncollectd nginx_vts plugin
COMMENT-notify_snmp =      ncollectd notify_snmp plugin
COMMENT-nsd =              ncollectd nsd plugin
COMMENT-nut =              ncollectd nut plugin
COMMENT-odbc =             ncollectd odbc plugin
COMMENT-openldap =         ncollectd openldap plugin
COMMENT-pcap =             ncollectd pcap plugin
COMMENT-pgbouncer =        ncollectd pgbouncer plugin
COMMENT-pgpool =           ncollectd pgpool plugin
COMMENT-postgresql =       ncollectd postgresql plugin
COMMENT-proxysql =         ncollectd proxysql plugin
COMMENT-python =           ncollectd python plugin
COMMENT-redfish =          ncollectd redfish plugin
COMMENT-redis =            ncollectd redis plugin
COMMENT-scraper =          ncollectd scraper plugin
COMMENT-sigrok =           ncollectd sigrok plugin
COMMENT-snmp =             ncollectd snmp plugin
COMMENT-squid =            ncollectd squid plugin
COMMENT-unbound =          ncollectd unbound plugin
COMMENT-varnish =          ncollectd varnish plugin
COMMENT-virt =             ncollectd virt plugin
COMMENT-write_amqp =       ncollectd write_amqp plugin
COMMENT-write_exporter =   ncollectd write_exporter plugin
COMMENT-write_http =       ncollectd write_http plugin
COMMENT-write_mqtt =       ncollectd write_mqtt plugin
COMMENT-write_postgresql = ncollectd write_postgresql plugin
COMMENT-write_redis =      ncollectd write_redis plugin

V = 0.0.1

DISTNAME =                 ncollectd-$V
PKGNAME-main =             ncollectd-$V
PKGNAME-apache =           ncollectd-apache-$V
PKGNAME-ats =              ncollectd-ats-$V
PKGNAME-bind =             ncollectd-bind-$V
PKGNAME-cert =             ncollectd-cert-$V
PKGNAME-dns =              ncollectd-dns-$V
PKGNAME-ds389 =            ncollectd-ds389-$V
PKGNAME-haproxy =          ncollectd-haproxy-$V
PKGNAME-http =             ncollectd-http-$V
PKGNAME-jolokia =          ncollectd-jolokia-$V
PKGNAME-ldap =             ncollectd-ldap-$V
PKGNAME-lua =              ncollectd-lua-$V
PKGNAME-match_xpath =      ncollectd-match_xpath-$V
PKGNAME-mosquitto =        ncollectd-mosquitto-$V
PKGNAME-mssql =            ncollectd-mssql-$V
PKGNAME-mysql =            ncollectd-mysql-$V
PKGNAME-nginx =            ncollectd-nginx-$V
PKGNAME-nginx_vts =        ncollectd-nginx_vts-$V
PKGNAME-notify_snmp =      ncollectd-notify_snmp-$V
PKGNAME-nsd =              ncollectd-nsd-$V
PKGNAME-nut =              ncollectd-nut-$V
PKGNAME-odbc =             ncollectd-odbc-$V
PKGNAME-openldap =         ncollectd-openldap-$V
PKGNAME-pcap =             ncollectd-pcap-$V
PKGNAME-pgbouncer =        ncollectd-pgbouncer-$V
PKGNAME-pgpool =           ncollectd-pgpool-$V
PKGNAME-postgresql =       ncollectd-postgresql-$V
PKGNAME-proxysql =         ncollectd-proxysql-$V
PKGNAME-python =           ncollectd-python-$V
PKGNAME-redfish =          ncollectd-redfish-$V
PKGNAME-redis =            ncollectd-redis-$V
PKGNAME-scraper =          ncollectd-scraper-$V
PKGNAME-sigrok =           ncollectd-sigrok-$V
PKGNAME-snmp =             ncollectd-snmp-$V
PKGNAME-squid =            ncollectd-squid-$V
PKGNAME-unbound =          ncollectd-unbound-$V
PKGNAME-varnish =          ncollectd-varnish-$V
PKGNAME-virt =             ncollectd-virt-$V
PKGNAME-write_amqp =       ncollectd-write_amqp-$V
PKGNAME-write_exporter =   ncollectd-write_exporter-$V
PKGNAME-write_http =       ncollectd-write_http-$V
PKGNAME-write_mqtt =       ncollectd-write_mqtt-$V
PKGNAME-write_postgresql = ncollectd-write_postgresql-$V
PKGNAME-write_redis =      ncollectd-write_redis-$V

CATEGORIES = sysutils

REVISION-main =             0
REVISION-apache =           0
REVISION-ats =              0
REVISION-bind =             0
REVISION-cert =             0
REVISION-dns =              0
REVISION-ds389 =            0
REVISION-haproxy =          0
REVISION-http =             0
REVISION-jolokia =          0
REVISION-ldap =             0
REVISION-lua =              0
REVISION-match_xpath =      0
REVISION-mosquitto =        0
REVISION-mssql =            0
REVISION-mysql =            0
REVISION-nginx =            0
REVISION-nginx_vts =        0
REVISION-notify_snmp =      0
REVISION-nsd =              0
REVISION-nut =              0
REVISION-odbc =             0
REVISION-openldap =         0
REVISION-pcap =             0
REVISION-pgbouncer =        0
REVISION-pgpool =           0
REVISION-postgresql =       0
REVISION-proxysql =         0
REVISION-python =           0
REVISION-redfish =          0
REVISION-redis =            0
REVISION-scraper =          0
REVISION-sigrok =           0
REVISION-snmp =             0
REVISION-squid =            0
REVISION-unbound =          0
REVISION-varnish =          0
REVISION-virt =             0
REVISION-write_amqp =       0
REVISION-write_exporter =   0
REVISION-write_http =       0
REVISION-write_mqtt =       0
REVISION-write_postgresql = 0
REVISION-write_redis =      0

HOMEPAGE = http://www.ncollectd.org/
# SITES = http://www.ncollectd.org/

# GPLv2
PERMIT_PACKAGE = Yes

MASTER_SITES = ${HOMEPAGE}/files/
EXTRACT_SUFX = .tar.xz

MODULES = devel/cmake
MODULES += lang/python
MODPY_RUNDEP = No
MODULES += lang/lua

MULTI_PACKAGES = -main -apache -ats -bind -cert -dns -ds389 -haproxy -http \
		-jolokia -lua -ldap -match_xpath -mosquitto -mssql -mysql -nginx \
		-nginx_vts -notify_snmp -nut -nsd -odbc -openldap -pcap -pgbouncer \
		-pgpool -postgresql -proxysql -python -redfish -redis \
		-scraper -sigrok -snmp -squid -unbound -varnish -virt -write_amqp \
		-write_exporter -write_http -write_mqtt -write_postgresql \
		-write_redis

WANTLIB-apache =               curl pthread
LIB_DEPENDS-apache =           net/curl
RUN_DEPENDS-apache =           ncollectd-$V:${BASE_PKGPATH},-main

WANTLIB-ats =                  curl pthread
LIB_DEPENDS-ats =              net/curl
RUN_DEPENDS-ats =              ncollectd-$V:${BASE_PKGPATH},-main

WANTLIB-bind =                 curl pthread xml2
LIB_DEPENDS-bind =             net/curl textproc/libxml
RUN_DEPENDS-bind =             ncollectd-$V:${BASE_PKGPATH},-main

WANTLIB-cert =                 ssl pthread
RUN_DEPENDS-cert =             ncollectd-$V:${BASE_PKGPATH},-main

WANTLIB-dns =                  cares m pthread
LIB_DEPENDS-dns =              net/libcares
RUN_DEPENDS-dns =              ncollectd-$V:${BASE_PKGPATH},-main

WANTLIB-ds389 =                lber ldap pthread
LIB_DEPENDS-ds389 =            databases/openldap
RUN_DEPENDS-ds389 =            ncollectd-$V:${BASE_PKGPATH},-main

WANTLIB-haproxy =              curl pthread
LIB_DEPENDS-haproxy =          net/curl
RUN_DEPENDS-haproxy =          ncollectd-$V:${BASE_PKGPATH},-main

WANTLIB-http =                 curl pthread
LIB_DEPENDS-http =             net/curl
RUN_DEPENDS-http =             ncollectd-$V:${BASE_PKGPATH},-main

WANTLIB-jolokia =              curl pthread
LIB_DEPENDS-jolokia =          net/curl
RUN_DEPENDS-jolokia =          ncollectd-$V:${BASE_PKGPATH},-main

WANTLIB-ldap =                 lber ldap pthread
LIB_DEPENDS-ldap =             databases/openldap
RUN_DEPENDS-ldap =             ncollectd-$V:${BASE_PKGPATH},-main

WANTLIB-lua =                  ${MODLUA_WANTLIB} m pthread
LIB_DEPENDS-lua =              ${MODLUA_LIB_DEPENDS}
RUN_DEPENDS-lua =              ncollectd-$V:${BASE_PKGPATH},-main

WANTLIB-match_xpath =          xml2 pthread
LIB_DEPENDS-match_xpath =      textproc/libxml
RUN_DEPENDS-match_xpath =      ncollectd-$V:${BASE_PKGPATH},-main

WANTLIB-mosquitto =            mosquitto pthread
LIB_DEPENDS-mosquitto =        net/mosquitto
RUN_DEPENDS-mosquitto =        ncollectd-$V:${BASE_PKGPATH},-main

WANTLIB-mssql =                sybdb pthread
LIB_DEPENDS-mssql =            databases/freetds
RUN_DEPENDS-mssql =            ncollectd-$V:${BASE_PKGPATH},-main

WANTLIB-mysql =                mariadb pthread
LIB_DEPENDS-mysql =            databases/mariadb
RUN_DEPENDS-mysql =            ncollectd-$V:${BASE_PKGPATH},-main

WANTLIB-nginx =                curl pthread
LIB_DEPENDS-nginx =            net/curl
RUN_DEPENDS-nginx =            ncollectd-$V:${BASE_PKGPATH},-main

WANTLIB-nginx_vts =            curl pthread
LIB_DEPENDS-nginx_vts =        net/curl
RUN_DEPENDS-nginx_vts =        ncollectd-$V:${BASE_PKGPATH},-main

WANTLIB-notify_snmp =          netsnmp pthread
LIB_DEPENDS-notify_snmp =      net/net-snmp
RUN_DEPENDS-notify_snmp =      ncollectd-$V:${BASE_PKGPATH},-main

WANTLIB-nut =                  pthread upsclient
LIB_DEPENDS-nut =              sysutils/nut
RUN_DEPENDS-nut =              ncollectd-$V:${BASE_PKGPATH},-main

WANTLIB-nsd =                  ssl pthread
RUN_DEPENDS-nsd =              ncollectd-$V:${BASE_PKGPATH},-main

WANTLIB-odbc =                 iodbc pthread
LIB_DEPENDS-odbc =             databases/iodbc
RUN_DEPENDS-odbc =             ncollectd-$V:${BASE_PKGPATH},-main

WANTLIB-openldap =             lber ldap pthread
LIB_DEPENDS-openldap =         databases/openldap
RUN_DEPENDS-openldap =         ncollectd-$V:${BASE_PKGPATH},-main

WANTLIB-pcap =                 pcap pthread
RUN_DEPENDS-pcap =             ncollectd-$V:${BASE_PKGPATH},-main

WANTLIB-pgbouncer =            pq pthread
LIB_DEPENDS-pgbouncer =        databases/postgresql
RUN_DEPENDS-pgbouncer =        ncollectd-$V:${BASE_PKGPATH},-main

WANTLIB-pgpool =               pq pthread
LIB_DEPENDS-pgpool =           databases/postgresql
RUN_DEPENDS-pgpool =           ncollectd-$V:${BASE_PKGPATH},-main

WANTLIB-postgresql =           pq pthread
LIB_DEPENDS-postgresql =       databases/postgresql
RUN_DEPENDS-postgresql =       ncollectd-$V:${BASE_PKGPATH},-main

WANTLIB-proxysql =             mariadb pthread
LIB_DEPENDS-proxysql =         databases/mariadb
RUN_DEPENDS-proxysql =         ncollectd-$V:${BASE_PKGPATH},-main

WANTLIB-python =               ${MODPY_WANTLIB} pthread
LIB_DEPENDS-python =           ${MODPY_LIB_DEPENDS}
RUN_DEPENDS-python =           ncollectd-$V:${BASE_PKGPATH},-main ${MODPY_RUN_DEPENDS}

WANTLIB-redfish =              curl pthread
LIB_DEPENDS-redfish =          net/curl
RUN_DEPENDS-redfish =          ncollectd-$V:${BASE_PKGPATH},-main

WANTLIB-redis =                hiredis pthread
LIB_DEPENDS-redis =            databases/libhiredis
RUN_DEPENDS-redis =            ncollectd-$V:${BASE_PKGPATH},-main

WANTLIB-scraper =              curl pthread
LIB_DEPENDS-scraper =          net/curl
RUN_DEPENDS-scraper =          ncollectd-$V:${BASE_PKGPATH},-main

WANTLIB-sigrok =               glib-2.0 pthread sigrok
LIB_DEPENDS-sigrok =           comms/sigrok/libsigrok devel/glib2
RUN_DEPENDS-sigrok =           ncollectd-$V:${BASE_PKGPATH},-main

WANTLIB-snmp =                 netsnmp pthread
LIB_DEPENDS-snmp =             net/net-snmp
RUN_DEPENDS-snmp =             ncollectd-$V:${BASE_PKGPATH},-main

WANTLIB-squid =                curl pthread
LIB_DEPENDS-squid =            net/curl
RUN_DEPENDS-squid =            ncollectd-$V:${BASE_PKGPATH},-main

WANTLIB-unbound =              ssl pthread
RUN_DEPENDS-unbound =          ncollectd-$V:${BASE_PKGPATH},-main

WANTLIB-varnish =              varnishapi pthread
LIB_DEPENDS-varnish =          www/varnish
RUN_DEPENDS-varnish =          ncollectd-$V:${BASE_PKGPATH},-main

WANTLIB-virt =                 pthread virt xml2
LIB_DEPENDS-virt =             sysutils/libvirt
RUN_DEPENDS-virt =             ncollectd-$V:${BASE_PKGPATH},-main

WANTLIB-write_amqp =           rabbitmq pthread
LIB_DEPENDS-write_amqp =       net/rabbitmq-c
RUN_DEPENDS-write_amqp =       ncollectd-$V:${BASE_PKGPATH},-main

WANTLIB-write_exporter =       microhttpd pthread
LIB_DEPENDS-write_exporter =   www/libmicrohttpd
RUN_DEPENDS-write_exporter =   ncollectd-$V:${BASE_PKGPATH},-main

WANTLIB-write_http =           curl pthread
LIB_DEPENDS-write_http =       net/curl
RUN_DEPENDS-write_http =       ncollectd-$V:${BASE_PKGPATH},-main

WANTLIB-write_mqtt =           mosquitto pthread
LIB_DEPENDS-write_mqtt =       net/mosquitto
RUN_DEPENDS-write_mqtt =       ncollectd-$V:${BASE_PKGPATH},-main

WANTLIB-write_postgresql =     pq pthread
LIB_DEPENDS-write_postgresql = databases/postgresql
RUN_DEPENDS-write_postgresql = ncollectd-$V:${BASE_PKGPATH},-main

WANTLIB-write_redis =          hiredis pthread
LIB_DEPENDS-write_redis =      databases/libhiredis
RUN_DEPENDS-write_redis =      ncollectd-$V:${BASE_PKGPATH},-main


WANTLIB += c kvm m pthread

ENABLED_PLUGINS =	apache apcups ats beanstalkd bind ceph cert chrony cpu df dns \
	dnsmasq ds389 exec fcgi filecount freeradius haproxy http info interface \
	javascript jolokia kea keepalived ldap load log_file log_gelf log_syslog lua \
	match_csv match_jsonpath match_regex match_table match_xpath memcached memory \
	mosquitto mssql mysql nagios_check nginx nginx_vts notify_exec notify_nagios \
	notify_snmp nsd ntpd nut odbc olsrd openldap openntpd openvpn pcap pdns pf \
	pgbouncer pgpool ping postfix postgresql processes proxysql python \
	recursor redfish redis routeros scraper sendmail sigrok snmp squid statsd \
	swap table tail tcpconns uname unbound uptime uuid varnish virt write_amqp \
	write_exporter write_file write_http write_log write_mqtt write_postgresql \
	write_redis write_tcp write_udp zookeeper

CONFIGURE_ARGS += -DENABLE_ALL_PLUGINS=OFF

.for _plugin in ${ENABLED_PLUGINS}
CONFIGURE_ARGS += -DPLUGIN_${_plugin:U}:BOOL=ON
.endfor

CONFIGURE_ENV += PYTHON_CONFIG='${LOCALBASE}/bin/python${MODPY_VERSION}-config' \
			CPPFLAGS='-I${LOCALBASE}/include' \
			LDFLAGS='-L${LOCALBASE}/lib -pthread'

.include <bsd.port.mk>
