.\" SPDX-License-Identifier: GPL-2.0-only
.TH ncollectd-cifs 5 "@NCOLLECTD_DATE@" "@NCOLLECTD_VERSION@" "ncollectd cifs man page"
.SH NAME
ncollectd-cifs \- Documentation of ncollectd's cifs plugin
.SH SYNOPSIS
\fBload-plugin\fP cifs
.SH DESCRIPTION
The \fBcifs\fP plugin collectd statistics of mounted cifs filesystems.
.SH "SEE ALSO"
.BR ncollectd (1)
.BR ncollectd.conf (5)
