.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-CIFS 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-cifs
.Nd Documentation of ncollectd's cifs plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP cifs
\fBplugin\fP cifs
.Ed
.Sh DESCRIPTION
The \fBcifs\fP plugin collectd statistics of mounted cifs filesystems.
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
