.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-ZSWAP 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-zswap
.Nd Documentation of ncollectd's zswap plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP zswap
\fBplugin\fP zswap
.Ed
.Sh DESCRIPTION
The \fBzswap\fP plugin collect statistics from zswap.
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
