.\" SPDX-License-Identifier: GPL-2.0-only
.TH ncollectd-zswap 5 "@NCOLLECTD_DATE@" "@NCOLLECTD_VERSION@" "ncollectd zswap man page"
.SH NAME
ncollectd-zswap \- Documentation of ncollectd's zswap plugin
.SH SYNOPSIS
\fBload-plugin\fP zswap
.SH DESCRIPTION
The \fBzswap\fP plugin collect statistics from zswap.
.SH "SEE ALSO"
.BR ncollectd (1)
.BR ncollectd.conf (5)
