.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-POSTFIX 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-postfix
.Nd Documentation of ncollectd's postfix plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP postfix
\fBplugin\fP postfix {
    \fBinstance\fP \fIname\fP {
        \fBunit\fP \fIunit-name\fP
        \fBlog-path\fP \fIpath-to-log\fP
        \fBlog-from\fP \fIfile|systemd\fP
        \fBshowq-path\fP \fIpath-to-showq-socket\fP
        \fBhistogram-time-buckets\fP [\fIbucket\fP] ...
        \fBhistogram-queue-size-buckets\fP [\fIbucket\fP] ...
        \fBhistogram-queue-age-buckets\fP [\fIbucket\fP] ...
        \fBhistogram-qmgr-inserts-nrcpt-buckets\fP [\fIbucket\fP] ...
        \fBhistogram-qmgr-inserts-size-buckets\fP [\fIbucket\fP] ...
        \fBtimeout\fP \fIseconds\fP
        \fBlabel\fP \fIkey\fP \fIvalue\fP
        \fBinterval\fP \fIseconds\fP
        \fBfilter\fP {
            ...
        }
    }
}
.Ed
.Sh DESCRIPTION
The \fBpostfix\fP plugin will collect statistics from a \fIpostfix\fP server
reading the logs and access the showq socket to list the mail queue.
.Pp
The plugin configuration consists of one or more \fBinstance\fP blocks which
specify one \fIpostfix\fP instance.
Within the \fBinstance\fP blocks, the following options are allowed:
.Bl -tag -width Ds
.It \fBunit\fP \fIunit-name\fP
Set the unit name from which to read the logs stored in the journal.
The default value is \f(CWpostfix.service\fP.
.It \fBlog-path\fP \fIpath-to-log\fP
Set file path from which to read the logs.
The default value is \f(CW/var/log/mail.log\fP.
.It \fBlog-from\fP \fIfile|systemd\fP
Define from with source to read the postfix logs.
By default if systemd is detected the logs will be read from the journal.
.It \fBshowq-path\fP \fIpath-to-showq-socket\fP
Set the path to the showq postfix socket.
The default value is \f(CW/var/spool/postfix/public/showq\fP.
.It \fBhistogram-time-buckets\fP [\fIbucket\fP] ...
Define the list of buckets for time based histograms.
.It \fBhistogram-queue-size-buckets\fP [\fIbucket\fP] ...
Define the list of buckets for queue size histogram.
.It \fBhistogram-queue-age-buckets\fP [\fIbucket\fP] ...
Define the list of buckets for queue age histogram.
.It \fBhistogram-qmgr-inserts-nrcpt-buckets\fP [\fIbucket\fP] ...
Define the list of buckets for qmgr number of receipients per message histogram.
.It \fBhistogram-qmgr-inserts-size-buckets\fP [\fIbucket\fP] ...
Define the list of buckets for qmgr inserts histogram.
.It \fBtimeout\fP \fIseconds\fP
Set the timeout in seconds for read the showq socket.
.It \fBlabel\fP \fIkey\fP \fIvalue\fP
Append the label \fIkey\fP=\fIvalue\fP to the submitting metrics.
.It \fBinterval\fP \fIseconds\fP
Sets the interval (in seconds) in which the values will be collected from this
instance.
By default the global \fBinterval\fP setting will be used.
.It \fBfilter\fP
Configure a filter to modify or drop the metrics.
See \fBFILTER CONFIGURATION\fP in
.Xr ncollectd.conf 5 .
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
