.\" SPDX-License-Identifier: GPL-2.0-only
.TH ncollectd-freeradius 5 "@NCOLLECTD_DATE@" "@NCOLLECTD_VERSION@" "ncollectd freeradius man page"
.SH NAME
ncollectd-freeradius \- Documentation of ncollectd's freeradius plugin
.SH SYNOPSIS
\fBload-plugin\fP freeradius
.br
\fBplugin\fP freeradius {
    \fBinstance\fP \fIinstance\fP {
        \fBhost\fP \fIhostname\fP
        \fBport\fP \fIport\fP
        \fBsecret\fP \fIsecret\fP
        \fBtimeout\fP \fIseconds\fP
        \fBlabel\fP "\fIkey\fP" "\fIvalue\fP"
        \fBinterval\fP \fIseconds\fP
        \fBfilter\fP {
             ...
        }
    }
.br
}
.SH DESCRIPTION
The \fBfreeradius\fP plugin connects to an instance of \fBfreeradius\fP to collect
server statistics about certain operations it is doing, such as the number of authentication
and accounting requests, how many accepts and failures, and server queue lengths.
Sending a specially-crafted RADIUS Status-Server packet to a "status" virtual server.
.PP
The configuration of the \fBfreeradius\fP plugin consists of one or more
\fBinstance\fP blocks. Each block requires one string argument
as the instance name.
The following options are accepted within each \fBinstance\fP block:
.TP
\fBhost\fP \fIhostname\fP
Hostname of the host running \fBfreeradius\fP "status" virtual server. Defaults to \fIlocalhost\fP.
.TP
\fBport\fP \fIport\fP
TCP port of the "status" virtual server to connect to. Defaults to \fB18121\fP.
.TP
\fBsecret\fP \fIsecret\fP
\fISecret\fP used to calculate message-authenticator.
.TP
\fBtimeout\fP \fIseconds\fP
The \fBtimeout\fP option sets the overall timeout for the request to the freeradius server.
.TP
\fBlabel\fP \fIkey\fP \fIvalue\fP
Append the label \fIkey\fP=\fIvalue\fP to the submitting metrics.
.TP
\fBinterval\fP \fIseconds\fP
Sets the interval (in seconds) in which the values will be collected.
By default the global \fBinterval\fP setting will be used.
.TP
\fBfilter\fP ...
Configure a filter to modify or drop the metrics. See \fBFILTER CONFIGURATION\fP in
.BR ncollectd.conf(5)
.SH "SEE ALSO"
.BR ncollectd (1)
.BR ncollectd.conf (5)
