.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-SQUID 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-squid
.Nd Documentation of ncollectd's squid plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP squid
\fBplugin\fP squid {
    \fBinstance\fP \fIname\fP {
        \fBurl\fP \fIurl\fP
        \fBuser\fP \fIuser\fP
        \fBuser-env\fP \fIenv-name\fP
        \fBpassword\fP \fIpassword\fP
        \fBpassword-env\fP \fIenv-name\fP
        \fBdigest\fP \fItrue|false\fP
        \fBverify-peer\fP \fItrue|false\fP
        \fBverify-host\fP \fItrue|false\fP
        \fBca-cert\fP \fI/path/to/ca\fP
        \fBheader\fP \fIheader\fP
        \fBlabel\fP \fIkey\fP \fIvalue\fP
        \fBinterval\fP \fIseconds\fP
        \fBfilter\fP {
            ...
        }
    }
}
.Ed
.Sh DESCRIPTION
The \fBsquid\fP plugin read Squid metrics over http orfrom an unix socket.
.Pp
In the \fBplugin\fP block, there may be one or more \fBinstance\fP blocks.
The following options are valid within \fBinstance\fP blocks:
.Bl -tag -width Ds
.It \fBurl\fP \fIurl\fP
URL to access the Squid cachemgr.
.It \fBuser\fP \fIuser\fP
Username to use if authorization is required to read the url.
.It \fBuser-env\fP \fIenv-name\fP
Get the username to use if authorization is required to read the url from the
environment variable \fIenv-name\fP.
.It \fBpassword\fP \fIpassword\fP
Password to use if authorization is required to read the url.
.It \fBpassword-env\fP \fIenv-name\fP
Get the password to use if authorization is required to read the url from the
environment variable \fIenv-name\fP.
.It \fBdigest\fP \fItrue|false\fP
Enable HTTP digest authentication.
.It \fBverify-peer\fP \fItrue|false\fP
Enable or disable peer SSL certificate verification.
See
.Lk http://curl.haxx.se/docs/sslcerts.html
for details.
Enabled by default.
.It \fBverify-host\fP \fItrue|false\fP
Enable or disable peer host name verification.
If enabled, the plugin checks if the \f(CWCommon Name\fP or a
\f(CWSubject Alternate Name\fP field of the SSL certificate matches the
host name provided by the \fBurl\fP option.
If this identity check fails, the connection is aborted.
Obviously, only works when connecting to a SSL enabled server.
Enabled by default.
.It \fBca-cert\fP \fI/path/to/ca\fP
File that holds one or more SSL certificates.
If you want to use HTTPS you will possibly need this option.
What CA certificates come bundled with libcurl and are checked by default
depends on the distribution you use.
.It \fBheader\fP \fIheader\fP
A HTTP header to add to the request.
Multiple headers are added if this option is specified more than once.
.It \fBlabel\fP \fIkey\fP \fIvalue\fP
Append the label \fIkey\fP=\fIvalue\fP to the submitting metrics.
Can appear multiple time in the \fBinstance\fP block.
.It \fBinterval\fP \fIseconds\fP
Sets the interval (in seconds) in which the values will be collected from this
URL.
By default the global \fBinterval\fP setting will be used.
.It \fBfilter\fP
Configure a filter to modify or drop the metrics.
See \fBFILTER CONFIGURATION\fP in
.Xr ncollectd.conf 5 .
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
