.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-JOLOKIA 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-jolokia
.Nd Documentation of ncollectd's jolokia plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP jolokia
\fBplugin\fP jolokia {
    \fBinstance\fP \fIname\fP {
        \fBurl\fP \fIurl\fP
        \fBuser\fP \fIuser\fP
        \fBuser-env\fP \fIenv-name\fP
        \fBpassword\fP \fIpassword\fP
        \fBpassword-env\fP \fIenv-name\fP
        \fBverify-peer\fP \fItrue|false\fP
        \fBverify-host\fP \fItrue|false\fP
        \fBca-cert\fP \fI/path/to/ca\fP
        \fBheader\fP \fIheader\fP
        \fBtimeout\fP \fIseconds\fP
        \fBlabel\fP \fIkey\fP \fIvalue\fP
        \fBinterval\fP \fIseconds\fP
        \fBmetric-prefix\fP \fIprefix\fP
        \fBmbean\fP \fIname\fP {
            \fBpath\fP \fIpath\fP
            \fBmetric-prefix\fP \fIprefix\fP
            \fBlabel\fP \fIkey\fP \fIvalue\fP
            \fBlabel-from\fP \fIkey\fP \fIvalue-from\fP
            \fBattribute\fP \fIname\fP {
                \fBmetric\fP \fImetric\fP
                \fBtype\fP \fIgauge|unknown|counter|info\fP
                \fBlabel\fP \fIkey\fP \fIvalue\fP
                \fBlabel-from\fP \fIkey\fP \fIvalue-from\fP
                \fBhelp\fP \fIhelp\fP
            }
        }
        \fBfilter\fP {
            ...
        }
    }
}
.Ed
.Sh DESCRIPTION
The \fBjolokia\fP plugin collects values from MBeanServevr - servlet engines
equipped with the jolokia (
.Lk https://jolokia.org
) MBean.
It sends a pre-configured JSON-Postbody to the servlet via HTTP commanding
the jolokia Bean to reply with a single JSON equipped with all JMX counters
requested.
By reducing TCP roundtrips in comparison to conventional JMX clients that
query one value via tcp at a time, it can return hundreds of values in one
roundtrip.
Moreof - no java binding is required in collectd to do so.
.Bl -tag -width Ds
.It \fBurl\fP \fIurl\fP
.It \fBuser\fP \fIuser\fP
Username to use if authorization is required to read the page.
.It \fBuser-env\fP \fIenv-name\fP
Get the username to use if authorization is required to read the page from the
environment variable \fIenv-name\fP
.It \fBpassword\fP \fIpassword\fP
Password to use if authorization is required to read the page.
.It \fBpassword-env\fP \fIenv-name\fP
Get the Password to use if authorization is required to read the page from the
environment variable \fIenv-name\fP
.It \fBverify-peer\fP \fItrue|false\fP
Enable or disable peer SSL certificate verification.
See
.Lk http://curl.haxx.se/docs/sslcerts.html
for details.
Enabled by default.
.It \fBverify-host\fP \fItrue|false\fP
Enable or disable peer host name verification.
If enabled, the plugin checks if the \f(CWCommon Name\fP or a
\f(CWSubject Alternate Name\fP field of the SSL certificate matches the host
name provided by the \fBurl\fP option.
If this identity check fails, the connection is aborted.
Obviously, only works when connecting to a SSL enabled server.
Enabled by default.
.It \fBca-cert\fP \fI/path/to/ca\fP
File that holds one or more SSL certificates.
If you want to use HTTPS you will possibly need this option.
What CA certificates come bundled with \fBlibcurl\fP
and are checked by default depends on the distribution you use.
.It \fBheader\fP \fIheader\fP
A HTTP header to add to the request.
Multiple headers are added if this option
is specified more than once.
.It \fBtimeout\fP \fIseconds\fP
The \fBtimeout\fP option sets the overall timeout for HTTP requests
to \fBurl\fP, in seconds.
By default, the configured \fBinterval\fP is used to set the timeout.
.It \fBlabel\fP \fIkey\fP \fIvalue\fP
Append the label \fIkey\fP=\fIvalue\fP to the submitting metrics.
Can appear multiple times.
.It \fBinterval\fP \fIseconds\fP
Sets the interval (in seconds) in which the values will be collected from this
URL.
By default the global \fBinterval\fP setting will be used.
.It \fBmetric-prefix\fP \fIprefix\fP
Prepends \fIprefix\fP to the metric name.
.It \fBmbean\fP \fIname\fP
One \fBmbean\fP block configures the translation of the gauges of one bean
to their respective collectd names, where \fIname\fP sets the main name.
.Bl -tag -width Ds
.It \fBpath\fP \fIpath\fP
.It \fBmetric-prefix\fP \fIprefix\fP
Prepends \fIprefix\fP to the metric name.
.It \fBlabel\fP \fIkey\fP \fIvalue\fP
Append the label \fIkey\fP=\fIvalue\fP to the submitting metrics.
Can appear multiple times.
.It \fBlabel-from\fP \fIkey\fP \fIvalue-from\fP
.It \fBattribute\fP \fIname\fP
A bean can contain several attributes.
Each one can be matched by a attribute block or be ignored.
.Bl -tag -width Ds
.It \fBmetric\fP \fImetric\fP
.It \fBtype\fP \fIgauge|unknown|counter|info\fP
.It \fBlabel\fP \fIkey\fP \fIvalue\fP
Append the label \fIkey\fP=\fIvalue\fP to the submitting metrics.
Can appear multiple times.
.It \fBlabel-from\fP \fIkey\fP \fIvalue-from\fP
.It \fBhelp\fP \fIhelp\fP
.El
.El
.It \fBfilter\fP
Configure a filter to modify or drop the metrics.
See \fBFILTER CONFIGURATION\fP in
.Xr ncollectd.conf 5 .
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
