.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-MATCH_XPATH 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-match_xpath
.Nd Documentation of ncollectd's xpath match plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBmatch\fP xpath {
    \fBmetric-prefix\fP \fIprefix\fP
    \fBlabel\fP \fIkey\fP \fIvalue\fP
    \fBnamespace\fP \fIprefix\fP \fIurl\fP
    \fBmetric\fP {
        \fBxpath\fP \fIxpath-expresion\fP
        \fBtype\fP [\fIgauge\fP [\fIaverage|min|max|last|inc|add|persist\fP] | \fIcounter\fP [\fIset|add|inc\fP]]
        \fBmetric\fP \fImetric\fP
        \fBhelp\fP \fIhelp\fP
        \fBlabel\fP \fIkey\fP \fIvalue\fP
        \fBmetric-prefix\fP \fIprefix\fP
        \fBmetric-from\fP \fIxpath-expresion\fP
        \fBlabel-from\fP \fIkey\fP \fIxpath-expresion\fP
        \fBvalue-from\fP \fIxpath-expresion\fP
        \fBtime-from\fP \fIxpath-expresion\fP
    }
}
.Ed
.Sh DESCRIPTION
The \fBxpath\fP match plugin parser data as Extensible Markup Language (XML).
The parsed tree is then traversed according to the user's configuration,
using the XML Path Language (XPath).
.Bl -tag -width Ds
.It \fBmetric-prefix\fP \fIprefix\fP
Prepend the \fIprefix\fP to the metrics found in the \fBmetric\fP blocks.
.It \fBlabel\fP \fIkey\fP \fIvalue\fP
Append the label \fIkey\fP=\fIvalue\fP to the submitting metrics.
.It \fBnamespace\fP \fIprefix\fP \fIurl\fP
If an XPath expression references namespaces, they must be specified with
this option.
\fIPrefix\fP is the "namespace prefix" used in the XML document.
\fIURL\fP is the "namespace name", an URI reference uniquely identifying
the namespace.
The option can be repeated to register multiple namespaces.
.Pp
Examples:
.Bd -literal
    namespace "s" "http://schemas.xmlsoap.org/soap/envelope/";
    namespace "m" "http://www.w3.org/1998/Math/MathML";
.Ed
.It \fBmetric\fP
.Bl -tag -width Ds
.It \fBxpath\fP \fIxpath-expresion\fP
Specifies how to get one type of information.
The string argument must be a valid XPath expression which returns a list
of "base elements".
.It \fBtype\fP [\fIgauge\fP [\fIaverage|min|max|last|inc|add|persist\fI] | \fIcounter\fP [\fIset|add|inc\fP]]
.Bl -tag -width Ds
.It \fBgauge\fP
The value is a gauge, you must specify also the type of the gauge:
.Bl -tag -width Ds
.It \fBaverage\fP
Calculate the average
.It \fBmin\fP
Use the smallest number only.
.It \fBmax\fP
Use the greatest number only.
.It \fBlast\fP
Use the last number found.
.It \fBinc\fP
Increase the internal counter by one.
.It \fBadd\fP
Add the matched value to the internal counter.
.It \fBpersist\fP
Use the last number found.
The number is not reset at the end of an interval.
It is continously reported until another number is matched.
.El
.It \fBcounter\fP
The value is a counter, you must specify also the type of the counter:
.Bl -tag -width Ds
.It \fBset\fP
Simply sets the internal counter to this value.
.It \fBadd\fP
Add the matched value to the internal counter.
.It \fBinc\fP
Increase the internal counter by one.
.El
.El
.It \fBmetric\fP \fImetric\fP
Set the metric name.
.It \fBhelp\fP \fIhelp\fP
Set the  metric help.
.It \fBlabel\fP \fIkey\fP \fIvalue\fP
Append the label \fIkey\fP=\fIvalue\fP to the submitting metrics.
.It \fBmetric-prefix\fP \fIprefix\fP
The prefix to prepend to the metric name obtained with \fBmetric-from\fP.
.It \fBmetric-from\fP \fIxpath-expresion\fP
Specifies a XPath expression to use for the metric name.
.It \fBlabel-from\fP \fIkey\fP \fIxpath-expresion\fP
Specifies a XPath expression to use for value of the label \fIkey\fP.
.It \fBvalue-from\fP \fIxpath-expresion\fP
Specifies a XPath expression to use for reading the value.
This option is required.
.It \fBtime-from\fP \fIxpath-expresion\fP
Specifies a XPath expression to use for determining the
timestamp of the metric.
.El
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
