.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-WRITE_LOG 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-write_log
.Nd Documentation of ncollectd's write_log plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP write_log
\fBplugin\fP write_log {
    \fBformat-metric\fP \fIinfluxdb|graphite|json|kairosdb|opentsdb|openmetrics|opentelemetry|remote\fP
}
.Ed
.Sh DESCRIPTION
The \fBwrite_log plugin\fP plugin writes metrics as INFO log messages.
.Pp
The plugin has the following options:
.Bl -tag -width Ds
.It \fBformat-metric\fP \fIinfluxdb|graphite|json|kairosdb|opentsdb|openmetrics|remote\fP
Selects the format in which metrics are written.
.Bl -tag -width Ds
.It \fBinfluxdb\fP [\fIsec|msec|usec|nsec\fP]
Format the metrics with the influxdb line format.
.It \fBgraphite\fP
Format the metrics with the graphite plaintext format.
.It \fBjson\fP
Format the metrics as json message.
.It \fBkairosdb\fP [\fItelnet [sec|msec]|json\fP]
Format the metrics with the karirosdb text format or json format.
.It \fBopentsdb\fP [telnet|json]
Format the metrics with the opentsdb text format or json format.
.It \fBopenmetrics\fP [text|protob]
Format the metrics with the openmetrics text format.
.It \fBopentelemetry\fP [json]
Format the metrics with the opentelemetry json format.
.It \fBremote\fP [metadata]
Format the metrics with the protocol buffer remote format.
.El
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
