.\" SPDX-License-Identifier: GPL-2.0-only
.TH ncollectd-drbd 5 "@NCOLLECTD_DATE@" "@NCOLLECTD_VERSION@" "ncollectd drbd man page"
.SH NAME
ncollectd-drbd \- Documentation of ncollectd's drbd plugin
.SH SYNOPSIS
\fBload-plugin\fP drbd
.SH DESCRIPTION
The \fBdrbd\fP plugin collect statistics from the Distributed Replicated Block Device (DRBD)
reading the file \fI/proc/drbd\fP.
.SH "SEE ALSO"
.BR ncollectd (1)
.BR ncollectd.conf (5)
