.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-ROUTEROS 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-routeros
.Nd Documentation of ncollectd's routeros plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP routeros
\fBplugin\fP routeros {
    \fBinstance\fP \fIname\fP {
        \fBhost\fP \fIhost\fP
        \fBport\fP \fIport\fP
        \fBuser\fP \fIuser\fP
        \fBuser-env\fP \fIenv-name\fP
        \fBpassword\fP \fIpassword\fP
        \fBpassword-env\fP \fIenv-name\fP
        \fBinterval\fP \fIseconds\fP
        \fBfilter\fP {
            ...
        }
    }
}
.Ed
.Sh DESCRIPTION
The \fBrouteros\fP plugin connects to a device running \fIRouterOS\fP, the
Linux-based operating system for routers by \fIMikroTik\fP.
The configuration supports querying multiple routers:
.Pp
The \fBrouteros\fP plugin consists of one or more \fBinstance\fP blocks.
Within each block, the following options are understood:
.Bl -tag -width Ds
.It \fBhost\fP \fIhost\fP
Hostname or IP-address of the router to connect to.
.It \fBport\fP \fIport\fP
Port name or port number used when connecting.
If left unspecified, the default will be chosen by \fIlibrouteros\fP,
currently "8728".
This option expects a string argument, even when a numeric port number is given.
.It \fBuser\fP \fIuser\fP
Use the user name \fIuser\fP to authenticate.
Defaults to "admin".
.It \fBuser-env\fP \fIenv-name\fP
Get the user name \fIuser\fP to authenticate from the environment
variable \fIenv-name\fP.
.It \fBpassword\fP \fIpassword\fP
Set the password used to authenticate.
.It \fBpassword-env\fP \fIenv-name\fP
Get the password used to authenticate from the environment
variable \fIenv-name\fP.
.It \fBinterval\fP \fIseconds\fP
Sets the interval (in seconds) in which the values will be collected
from this instance.
By default the global \fBinterval\fP setting will be used.
.It \fBfilter\fP
Configure a filter to modify or drop the metrics.
See \fBFILTER CONFIGURATION\fP in
.Xr ncollectd.conf 5 .
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
