.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-CPU 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-cpu
.Nd Documentation of ncollectd's cpu plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP cpu
\fBplugin\fP cpu {
    \fBreport-guest-state\fP \fIfalse|true\fP
    \fBsubtract-guest-state\fP \fIfalse|true\fP
    \fBreport-topology\fP \fIfalse|true\fP
}
.Ed
.Sh DESCRIPTION
The \fBcpu\fP plugin collects CPU usage metrics.
.Pp
The following configuration options are available:
.Bl -tag -width Ds
.It \fBreport-guest-state\fP \fIfalse|true\fP
When set to \fBtrue\fP, reports the \*(lqguest\*(rq and \*(lqguest_nice\*(rq
CPU states.
Defaults to \fBfalse\fP.
.It \fBsubtract-guest-state\fP \fIfalse|true\fP
This option is only considered when \fBreport-guest-state\fP is set to
\fBtrue\fP.
\*(lqguest\*(rq and \*(lqguest_nice\*(rq are included in respectively
\*(lquser\*(rq and \*(lqnice\*(rq.
If set to \fBtrue\fP, \*(lqguest\*(rq will be subtracted from \*(lquser\*(rq and
\*(lqguest_nice\*(rq will be subtracted from \*(lqnice\*(rq.
Defaults to \fBtrue\fP.
.It \fBreport-topology\fP \fIfalse|true\fP
When set to \fBtrue\fP in Linux, reports the cpu topology as labels:
\fInode\fP, \fIcode\fP, \fIsocket\fP, \fIbook\fP and \fIdrawer\fP.
Defaults to \fBfalse\fP.
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
