.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-WRITE_UDP 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-write_udp
.Nd Documentation of ncollectd's write_udp plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP write_udp
\fBplugin\fP write_udp {
    \fBinstance\fP \fIname\fP {
        \fBhost\fP \fIhost\fP
        \fBport\fP \fIport\fP
        \fBttl\fP \fIttl\fP
        \fBpacket-max-size\fP \fIsize\fP
        \fBflush-interval\fP \fIseconds\fP
        \fBflush-timeout\fP \fIseconds\fP
        \fBformat-metric\fP \fIinfluxdb|graphite|kairosdb|opentsdb\fP
    }
}
.Ed
.Sh DESCRIPTION
The \fBwrite_udp\fP plugin send the metrics as UDP packets.
.Pp
The following options are accepted within each \fBinstance\fP block:
.Bl -tag -width Ds
.It \fBhost\fP \fIhost\fP
Hostname or address to connect to.
Defaults to localhost.
.It \fBport\fP \fIport\fP
Service name or port number to connect to.
.It \fBttl\fP \fIttl\fP
.It \fBpacket-max-size\fP \fIsize\fP
.It \fBflush-interval\fP \fIseconds\fP
.It \fBflush-timeout\fP \fIseconds\fP
.It \fBformat-metric\fP \fIinfluxdb|graphite|kairosdb|opentsdb\fP
Selects the format in which metrics are written.
.Bl -tag -width Ds
.It \fBinfluxdb\fP [\fIsec|msec|usec|nsec\fP]
Format the metrics with the influxdb line format.
.It \fBgraphite\fP
Format the metrics with the graphite plaintext format.
.It \fBkairosdb\fP [\fIsec|msec\fP]
Format the metrics with the karirosdb text format.
.It \fBopentsdb\fP
Format the metrics with the opentsdb text format.
.El
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
