.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-PGBOUNCER 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-pgbouncer
.Nd Documentation of ncollectd's pgbouncer plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP pgbouncer
\fBplugin\fP pgbouncer {
    \fBinstance\fP \fIinstance\fP {
        \fBhost\fP \fIhost\fP
        \fBport\fP \fIport\fP
        \fBdatabase\fP \fIdatabase\fP
        \fBuser\fP \fIuser\fP
        \fBuser-env\fP \fIenv-name\fP
        \fBpassword\fP \fIpassword\fP
        \fBpassword-env\fP \fIenv-name\fP
        \fBssl-mode\fP \fIdisable|allow|prefer|require\fP
        \fBinterval\fP \fIseconds\fP
        \fBlabel\fP \fIkey\fP \fIvalue\fP
        \fBfilter\fP {
            ...
        }
    }
}
.Ed
.Sh DESCRIPTION
The \fBpgbouncer\fP plugin queries statistics from Pgbouncer server.
It keeps a persistent connection to all configured databases and tries to
reconnect if the connection has been interrupted.
A connection is configured by specifying a \fBinstance\fP block as
described below.
.Bl -tag -width Ds
.It \fBinstance\fP \fIinstance\fP
The \fBinstance\fP block defines one Pgbouncer server for which to collect
statistics.
.Bl -tag -width Ds
.It \fBhost\fP \fIhost\fP
Specify the hostname or IP of the Pgbouncer server to connect to.
If the value begins with a slash, it is interpreted as the directory name
in which to look for the UNIX domain socket.
.It \fBport\fP \fIport\fP
Specify the TCP port or the local UNIX domain socket file extension of the
server.
.It \fBdatabase\fP \fIdatabase\fP
The database to connect.
The default value is \fIpgbouncer\fP.
.It \fBuser\fP \fIuser\fP
Specify the username to be used when connecting to the server.
.It \fBuser-env\fP \fIenv-name\fP
Get the username to be used when connecting to the server from the
environment variable \fIenv-name\fP.
.It \fBpassword\fP \fIpassword\fP
Specify the password to be used when connecting to the server.
.It \fBpassword-env\fP \fIenv-name\fP
Get the password to be used when connecting to the server from the
environment variable \fIenv-name\fP.
.It \fBssl-mode\fP \fIdisable|allow|prefer|require\fP
Specify whether to use an SSL connection when contacting the server.
The following modes are supported:
.Bl -tag -width Ds
.It \fBdisable\fP
Do not use SSL at all.
.It \fBallow\fP
First, try to connect without using SSL.
If that fails, try using SSL.
.It \fBprefer\fP \fI(default)\fP
First, try to connect using SSL.
If that fails, try without using SSL.
.It \fBrequire\fP
Use SSL only.
.El
.It \fBinterval\fP \fIseconds\fP
Specify the interval with which the database should be queried.
The default is to use the global \fBinterval\fP setting.
.It \fBlabel\fP \fIkey\fP \fIvalue\fP
Append the label \fIkey\fP=\fIvalue\fP to the submitting metrics.
Can appear multiple time in the \fBdatabase\fP block.
.It \fBfilter\fP
Configure a filter to modify or drop the metrics.
See \fBFILTER CONFIGURATION\fP in
.Xr ncollectd.conf 5 .
.El
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
