.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-SNMP 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-snmp
.Nd Documentation of ncollectd's snmp plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP snmp
\fBplugin\fP snmp {
    \fBtable\fP \fItable\fP {
        \fBtype\fP \fIcounter|gauge\fP
        \fBhelp\fP \fIhelp\fP
        \fBmetric\fP \fImetric\fP
        \fBlabel\fP \fIkey\fP \fIvalue\fP
        \fBlabel-from\fP \fIkey\fP \fIOID\fP
        \fBlabel-suffix\fP \fIkey\fP
        \fBvalue\fP \fIOID\fP
        \fBshift\fP \fIvalue\fP
        \fBscale\fP \fIvalue\fP
        \fBcount\fP \fItrue|false\fP
        \fBfilter-oid\fP \fIOID\fP
        \fBfilter-value\fP  [\fIincl|include|excl|exclude\fP] \fIvalue\fP
    }
    \fBdata\fP \fIdata\fP {
        \fBtype\fP \fIcounter|gauge\fP
        \fBhelp\fP \fIhelp\fP
        \fBmetric\fP \fImetric\fP
        \fBlabel\fP \fIkey\fP \fIvalue\fP
        \fBlabel-from\fP \fIkey\fP \fIOID\fP
        \fBvalue\fP \fIOID\fP
        \fBshift\fP \fIvalue\fP
        \fBscale\fP \fIvalue\fP
    }
    \fBhost\fP \fIhost\fP {
        \fBaddress\fP \fIip-address|hostname\fP
        \fBcommunity\fP \fIcommunity\fP
        \fBversion\fP \fI1|2|3\fP
        \fBtimeout\fP \fIseconds\fP
        \fBretries\fP \fIinteger\fP
        \fBinterval\fP \fIseconds\fP
        \fBusername\fP \fIusername\fP
        \fBauth-protocol\fP \fImd5|sha\fP
        \fBprivacy-protocol\fP \fIaes|des\fP
        \fBauth-passphrase\fP \fIpassphrase\fP
        \fBprivacy-passphrase\fP \fIpassphrase\fP
        \fBsecurity-level\fP \fIauthpriv|authnopriv|noauthnopriv\fP
        \fBlocal-cert\fP \fIfingerprint|fileprefix\fP
        \fBpeer-cert\fP \fIfingerprint|fileprefix\fP
        \fBtrust-cert\fP \fIfingerprint|fileprefix\fP
        \fBpeer-hostname\fP \fIhostname\fP
        \fBcontext\fP \fIcontext\fP
        \fBbulk-size\fP \fIinteger\fP
        \fBmetric-prefix\fP \fImetric-prefix\fP
        \fBlabel\fP \fIkey\fP \fIvalue\fP
        \fBcollect\fP \fIdata|table\fP [\fIdata|table\fP ...]
    }
}
.Ed
.Sh DESCRIPTION
The \fPsnmp\fP plugin queries other hosts using SNMP, the simple network
management protocol, and translates the value it receives to ncollectd's
internal format and dispatches them.
Depending on the write plugins you have loaded they may be written to disk
or submitted to another instance or whatever you configured.
.Pp
Because querying a host via SNMP may produce a timeout the "complex reads"
polling method is used.
The \fBread-threads\fP parameter in the main configuration influences the
number of parallel polling jobs which can be undertaken.
If you expect timeouts or some polling to take a long time, you should
increase this parameter.
Note that other plugins also use the same threads.
.Pp
Since the aim of the \fBsnmp\fP plugin is to provide a generic interface
to SNMP, its configuration is not trivial and may take some time.
.Pp
Since the \f(CWNet-SNMP\fP library is used you can use all the environment
variables that are interpreted by that package.
See
.Xr snmpcmd 1
for more details.
.Pp
There are three types of blocks that can be contained in the \fBsnmp\fP plugin
block: \fBtable\fP, \fBdata\fP, and \fBhost\fP:
.Bl -tag -width Ds
.It \fBtable\fP \fItable\fP
The \fBtable\fP block defines a list of table of values that are
to be queried.
The following options can be set:
.Bl -tag -width Ds
.It \fBcount\fP \fItrue|false\fP
Instead of dispatching one value per table entry containing the \fIOID\fP given
in the \fBvalue\fP option, just dispatch a single count giving the
number of entries that would have been dispatched.
This is especially useful when combined with the filtering options (see below)
to count the number of entries in a Table matching certain criteria.
.Pp
When \fBtable\fP is used, the OIDs given to \fBvalues\fP,
\fBlabel-from\fP \fBfilter-ioid\fP (see below) are queried using the
\f(CWGETNEXT\fP SNMP command until the subtree is left.
After all the lists (think: all columns of the table) have been read,
either (\fBcount\fP set to \fIfalse\fP) \fBseveral\fP value sets will
be dispatched or (\fBcount\fP set to \fItrue\fP) one single value will
be dispatched.
.Pp
For example, if you want to query the number of users on a system, you can use
\f(CWHOST-RESOURCES-MIB::hrSystemNumUsers.0\fP.
This is one value and belongs to one value list, therefore you  must use
\fBdata\fP block.
Please note that, in this case, you have to include the sequence number
(zero in this case) in the OID.
.Pp
Counter example: If you want to query the interface table provided by the
\f(CWIF-MIB\fP, e.g. the bytes transmitted.
There are potentially many interfaces, so you will want to user is a \fBtable\fP
block.
.It \fBtype\fP \fIcounter|gauge|unknown\fP
The \fBtype\fP that's used for each value read.
Must be \fIgauge\fP, \fIcounter\fP or \fPunknown\fP.
If not set is \fPunknown\fP.
.It \fBhelp\fP \fIhelp\fP
Set the \fBhelp\fP text for the metric.
.It \fBmetric\fP \fImetric\fP
Set the metric name.
.It \fBlabel\fP \fIkey\fP \fIvalue\fP
Append the label \fIkey\fP=\fIvalue\fP to the submitting metrics.
Can appear multiple times.
.It \fBlabel-from\fP \fIkey\fP \fIOID\fP
Append the label with \fIkey\fP and value from the queried \fIOID\fP.
The \fIOID\fP is interpreted as an SNMP-prefix that will return a list
of values.
An example would be the \f(CWIF-MIB::ifDescr\fP subtree.
.Xr variables 5
from the SNMP distribution describes the format of OIDs.
.It \fBlabel-suffix\fP \fIkey\fP
Append the label with \fIkey\fP and the \fIvalue\fB the suffix from
the queried \fIOID\fP.
.It \fBvalue\fP \fIOID\fP
Configures the values to be queried from the SNMP host.
.Xr variables 5
from the SNMP distribution describes the format of OIDs.
.Pp
The \fIOID\fP must be the prefix of all the values to query, e.g.
\f(CWIF-MIB::ifInOctets\fP for all the counters of incoming traffic.
This subtree is walked (using \f(CWGETNEXT\fP) until a value from outside the
subtree is returned.
.It \fBshift\fP \fIvalue\fP
\fIValue\fP is added to gauge-values returned by the SNMP-agent after they have
been multiplied by any \fBscale\fP value.
If, for example, a thermometer returns degrees Kelvin you could specify a shift
of \fB273.15\fP here to store values in degrees Celsius.
The default value is, of course, \fB0.0\fP.
.Pp
This value is not applied to counter-values.
.It \fBscale\fP \fIvalue\fP
The gauge-values returned by the SNMP-agent are multiplied by  \fIvalue\fP.
This is useful when values are transferred as a fixed point real number.
For example, thermometers may transfer \fB243\fP but actually mean \fB24.3\fP,
so you can specify a scale value of \fB0.1\fP to correct this.
The default value is, of course, \fB1.0\fP.
.Pp
This value is not applied to counter-values.
.It \fBfilter-oid\fP \fIOID\fP
.It \fBfilter-value\fP  [\fIincl|include|excl|exclude\fP] \fIvalue\fP
When \fBtable\fP is set to \fItrue\fP, these options allow to configure
filtering based on MIB values.
.Pp
The \fBfilter-oid\fP declares \fIOID\fP to fill table column with values.
The \fBfilter-value\fP declares values to do match.
Whether table row will be collected or ignored depends on the
\fBfilter-value\fP setting.
As with other plugins that use the daemon's include/exclude functionality,
a string that starts and ends with a slash is interpreted as a
regular expression.
.Pp
If no selection is configured at all, \fBall\fP table rows are selected.
.El
.It \fBdata\fP \fIdata\fP
The \fBdata\fP block defines a list of values or a table of values that are
to be queried.
The OID given to \fBvalue\fP (see below) are queried using the \f(CWNGET\fP
SNMP command (see
.Xr snmpget 1
) and transmitted to mcollectd.
The following options can be set:
.Bl -tag -width Ds
.It \fBtype\fP \fIcounter|gauge|unknown\fP
The \fBtype\fP that's used for each value read.
Must be \fIgauge\fP, \fIcounter\fP or \fPunknown\fP.
If not set is \fPunknown\fP.
.It \fBhelp\fP \fIhelp\fP
Set the \fBhelp\fP text for the metric.
.It \fBmetric\fP \fImetric\fP
Set the metric name.
.It \fBlabel\fP \fIkey\fP \fIvalue\fP
Append the label \fIkey\fP=\fIvalue\fP to the submitting metrics.
Can appear multiple times.
.It \fBlabel-from\fP \fIkey\fP \fIOID\fP
Append the label with \fIkey\fP and value from the queried \fIOID\fP.
.It \fBvalue\fP \fIOID\fP
Configures the values to be queried from the SNMP host.
.Xr variables 5
from the SNMP distribution describes the format of OIDs.
.Pp
The \fIOID\fP must be the OID of exactly one value, e.g.
\f(CWIF-MIB::ifInOctets.3\fP for the third counter of incoming traffic.
.It \fBshift\fP \fIvalue\fP
\fIValue\fP is added to gauge-values returned by the SNMP-agent after they have
been multiplied by any \fBscale\fP value.
If, for example, a thermometer returns degrees Kelvin you could specify a shift
of \fB273.15\fP here to store values in degrees Celsius.
The default value is, of course, \fB0.0\fP.
.Pp
This value is not applied to counter-values.
.It \fBscale\fP \fIvalue\fP
The gauge-values returned by the SNMP-agent are multiplied by  \fIvalue\fP.
This is useful when values are transferred as a fixed point real number.
For example, thermometers may transfer \fB243\fP but actually mean \fB24.3\fP,
so you can specify a scale value of \fB0.1\fP to correct this.
The default value is, of course, \fB1.0\fP.
.Pp
This value is not applied to counter-values.
.El
.It \fBhost\fP \fIhost\fP
The \fBhost\fP block defines which hosts to query, which SNMP community and
version to use and which of the defined \fBdata\fP to query.
.Bl -tag -width Ds
.It \fBaddress\fP \fIip-address|hostname\fP
Set the address to connect to.
Address may include transport specifier and/or port number.
.It \fBcommunity\fP \fIcommunity\fP
Pass \fIcommunity\fP to the host. (ignored for SNMPv3).
.It \fBversion\fP \fI1|2|3\fP
Set the SNMP version to use.
When giving \fI2\fP version \fI2c\fP is actually used.
.It \fBtimeout\fP \fIseconds\fP
How long to wait for a response.
The \f(CWNet-SNMP\fP library default is 1 second.
.It \fBretries\fP \fIinteger\fP
The number of times that a query should be retried after the timeout expires.
The \f(CWNet-SNMP\fP library default is 5.
.It \fBinterval\fP \fIseconds\fP
Collect data from this host every \fIseconds\fP seconds.
This option is meant for devices with not much CPU power, e.g. network
equipment such as switches, embedded devices, rack monitoring systems and so on.
.It \fBusername\fP \fIusername\fP
Sets the \fIusername\fP to use for SNMPv3 User-based Security Model
(USM) security.
.It \fBauth-protocol\fP \fImd5|sha\fP
Selects the authentication protocol for SNMPv3 User-based Security Model
(USM) security.
.It \fBprivacy-protocol\fP \fIaes|des\fP
Selects the privacy (encryption) protocol for SNMPv3 User-based Security Model
(USM) security.
.It \fBauth-passphrase\fP \fIpassphrase\fP
Sets the authentication passphrase for SNMPv3 User-based Security Model
(USM) security.
.It \fBprivacy-passphrase\fP \fIpassphrase\fP
Sets the privacy (encryption) passphrase for SNMPv3 User-based Security Model
(USM) security.
.It \fBsecurity-level\fP \fIauthpriv|authnopriv|noauthnopriv\fP
Selects the security level for SNMPv3 User-based Security Model (USM) security.
.It \fBlocal-cert\fP \fIfingerprint|fileprefix\fP
Sets the fingerprint or the filename prefix of the local certificate,
key, and (if supported) intermediate certificates for SNMPv3 Transport
Security Model (TSM) security.
.It \fBpeer-cert\fP \fIfingerprint|fileprefix\fP
Sets the fingerprint or the filename prefix of the self signed remote peer
certificate to be accepted as presented by the SNMPv3 server for SNMPv3
Transport Security Model (TSM) security.
.It \fBtrust-cert\fP \fIfingerprint|fileprefix\fP
Sets the fingerprint or the filename prefix of the certificate authority
certificates to be trusted by ncollectd-snmp for SNMPv3 Transport Security
Model (TSM) security.
This option can only be specified once.
From \f(CWNet-SNMP\fP v5.10 onwards, all certificates in files matching the
given filename prefix are trusted.
.It \fBpeer-hostname\fP \fIhostname\fP
If specified, the hostname of the SNMPv3 server will be checked against the
peer certificate presented by the SNMPv3 server.
.It \fBcontext\fP \fIcontext\fP
Sets the \fIcontext\fP for SNMPv3 security.
.It \fBbulk-size\fP \fIinteger\fP
Configures the size of SNMP bulk transfers.
The default is 0, which disables bulk transfers altogether.
.It \fBmetric-prefix\fP \fImetric-prefix\fP
Prepends \fIprefix\fP to the metric name in the \fBdata\fP block.
.It \fBlabel\fP \fIkey\fP \fIvalue\fP
Append the label \fIkey\fP=\fIvalue\fP to the submitting metrics.
Can appear multiple times.
.It \fBcollect\fP \fIdata\fP [\fIdata\fP ...]
Defines which values to collect. \fIdata\fP refers to one of the
\fBdata\fP block above.
Since the config file is read top-down you need to define the data before
using it here.
.El
.El
.Sh SECURITY
SNMP provides various security levels, ranging from open SNMPv1 and SNMPv2c,
to the secure SNMPv3 User-based Security Model (USM) and Transport Security
Model (TSM) options.
.Ss "SNMPv1 / SNMPv2c Security"
When \fBversion\fP 1 or 2 is used, anyone with knowledge of the community
string can connect to the SNMP server.
.Pp
No authentication or privacy is supported in these modes.
.Ss "SNMPv3 User-based Security Model (USM) Security"
When \fBaddress\fP prefixes such as \fIudp:\fP or \fIudp6:\fP are used
along with \fBversion\fP 3 and the \fBusername\fP option, USM security
is enabled.
.Pp
Security in this mode is based on shared secrets, and can offer
optional authentication and privacy.
.Pp
The digest and encryption algorithms specified by \fBauth-protocol\fP and
\fBprivacy-protocol\fP must match those on the SNMPv3 server.
.Pp
The user credentials used by the SNMPv3 server are specified by the
\fBusername\fP option.
.Ss "SNMPv3 Transport Security Model (TSM) Security"
When TLS/DTLS \fBaddress\fP prefixes such as \fIdtlsudp:\fP or \fIdtlsudp6:\fP
are used along with the \fBlocal-cert\fP option, TSM security is enabled.
.Pp
Security in this mode is based on X509 certificates and public/private keys.
The SNMPv3 server and ncollectd-snmp client authenticate and secure the
connection through server and client certificates.
The SNMPv3 server will decide the user credentials to be applied based on
the attributes of the client certificate presented by ncollectd-snmp in
\fBlocal-cert\fP.
.Pp
The certificates and keys are stored in any of the series of certificate
store paths supported by the \f(CWNet-SNMP\fP library, and are scanned and
indexed for performance.
The path cannot be specified directly via ncollectd-snmp.
.Pp
Certificates are chosen by specifying the fingerprint of the certificate
or the name prefix of the file the certificate is stored in.
The algorithm used for the fingerprint matches the algorithm used to sign
the certificate.
.Pp
Files containing keys must have no group or world permissions, otherwise the
contents of the files will be silently ignored.
.Pp
If a filename prefix is used, certificates are picked up from files with
specific prefixes known to \f(CWNet-SNMP\fP matching the filename prefix.
This value is not a path.
For example, if a filename prefix of "router-cert" is specified, files called
\fIrouter-cert.pem\fP, \fIrouter-cert.crt\fP, \fIrouter-cert.cer\fP,
\fIrouter-cert.cert\fP, \fIrouter-cert.der\fP, \fIrouter-cert.key\fP and
\fIrouter-cert.private\fP will be scanned for certificates and keys.
.Pp
The \f(CWNet-SNMP\fP library v5.9 and older has limited support for certificates
other than self signed certificates.
Intermediate certificates are ignored by these older versions of
\f(CWNet-SNMP\fP, and only the first certificate in each file is recognised.
\f(CWNet-SNMP\fP v5.10 and higher recognise concatenated intermediate
certificates in files, as well as multiple CA certificates specified in
one file, such as the \fItls-ca-bundle.pem\fP available on many platforms.
This allows certificates to be used that have been provided by a
PKI, either privately or through a public certificate authority.
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
