.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-UBI 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-ubi
.Nd Documentation of ncollectd's ubi plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP ubi
\fBplugin\fP ubi {
    \fBdevice\fP [\fIincl|include|excl|exclude\fP] \fIname\fP
}
.Ed
.Sh DESCRIPTION
The \fBubi\fP plugin collects some statistics about the
UBI (Unsorted Block Image).
Values collected are the number of bad physical eraseblocks on
the underlying MTD (Memory Technology Device) and the maximum erase
counter value concerning one volume.
.Pp
See following links for details:
.Lk http://www.linux-mtd.infradead.org/doc/ubi.html
.Lk http://www.linux-mtd.infradead.org/doc/ubifs.html
.Lk https://www.kernel.org/doc/Documentation/ABI/stable/sysfs-class-ubi
.Pp
The plugin has the following options:
.Bl -tag -width Ds
.It \fBdevice\fP [\fIincl|include|excl|exclude\fP] \fIname\fP
Select the device \fIname\fP of the UBI volume.
See \fBINCLUDE AND EXCLUDE LISTS\fP in
.Xr ncollectd.conf 5 .
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
