.\" SPDX-License-Identifier: GPL-2.0-only
.TH ncollectd-sockstat 5 "@NCOLLECTD_DATE@" "@NCOLLECTD_VERSION@" "ncollectd sockstat man page"
.SH NAME
ncollectd-sockstat \- Documentation of ncollectd's sockstat plugin
.SH SYNOPSIS
\fBload-plugin\fP sockstat
.SH DESCRIPTION
The \fBsockstat\fP plugin collect socket statistics from the files
\fI/proc/net/sockstat\fP and \fI/proc/net/sockstat6\fP
.SH "SEE ALSO"
.BR ncollectd (1)
.BR ncollectd.conf (5)
