.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-SOCKSTAT 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-sockstat
.Nd Documentation of ncollectd's sockstat plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP sockstat
\fBplugin\fP sockstat
.Ed
.Sh DESCRIPTION
The \fBsockstat\fP plugin collect socket statistics from the files
\fI/proc/net/sockstat\fP and \fI/proc/net/sockstat6\fP
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
