.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-WRITE_MONGODB 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-write_mongodb
.Nd Documentation of ncollectd's write_mongodb plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP write_mongodb
\fBplugin\fP write_mongodb {
    \fBinstance\fP \fIinstance\fP {
        \fBhost\fP \fIhost\fP
        \fBport\fP \fIport\fP
        \fBdatabase\fP \fIdatabase\fP
        \fBuser\fP \fIuser\fP
        \fBuser-env\fP \fIenv-name\fP
        \fBpassword\fP \fIpassword\fP
        \fBpassword-env\fP \fIenv-name\fP
        \fBstore-rates\fP \fItrue|false\fP
        \fBmetric-collection\fP \fIcollection-name\fP
        \fBmetric-timestamp-field\fP \fItimestamp-field-name\fP
        \fBmetric-metadata-field\fP \fImetadata-field-name\fP
        \fBmetric-value-field\fP \fIvalue-field-name\fP
        \fBnotification-collection\fP \fIcollection-name\fP
        \fBnotification-name-field\fP \fIname-field-name\fP
        \fBnotification-severity-field\fP \fIseverity-field-name\fP
        \fBnotification-timestamp-field\fP \fItimestamp-field-name\fP
        \fBnotification-labels-field\fP \fIlabels-field-name\fP
        \fBnotification-annotations-field\fP \fIannotations-field-name\fP
        \fBwrite\fP \fImetrics|notifications\fP
        \fBttl\fP \fIseconds\fP
        \fBbulk-size\fP \fIsize\fP
    }
}
.Ed
.Sh DESCRIPTION
The \fBwrite_mongodb\fP plugin will insert metrics in a \fIMongoDB\fP,
a schema-less NoSQL database.
.Pp
Within each \fBinstance\fP block, the following options are available:
.Bl -tag -width Ds
.It \fBhost\fP \fIhost\fP
Hostname or address to connect to.
Defaults to \f(CWlocalhost\fP.
.It \fBport\fP \fIport\fP
Service name or port number to connect to.
Defaults to \f(CW27017\fP.
.It \fBdatabase\fP \fIdatabase\fP
.It \fBuser\fP \fIuser\fP
.It \fBuser-env\fP \fIenv-name\fP
.It \fBpassword\fP \fIpassword\fP
Sets the information used when authenticating to a \fIMongoDB\fP database.
The fields are optional (in which case no authentication is attempted),
but if you want to use authentication all three fields must be set.
.It \fBpassword-env\fP \fIenv-name\fP
Get the password fox authenticating to a \fIMongoDB\fP database from the
environment variable \fIenv-name\fP.
.It \fBstore-rates\fP \fItrue|false\fP
.It \fBmetric-collection\fP \fIcollection-name\fP
The collection name to write the metrics.
The default name is "metrics".
.It \fBmetric-timestamp-field\fP \fItimestamp-field-name\fP
The name of the field which contains the date in each time series document.
The default name is "timestamp".
.It \fBmetric-metadata-field\fP \fImetadata-field-name\fP
The name of the field which contains the labels in each time series document.
The default name is "metadata".
.It \fBmetric-value-field\fP \fIvalue-field-name\fP
The name of the field witch contains the value in each time series document.
The default name is "value".
.It \fBnotification-collection\fP \fIcollection-name\fP
The collection name to write the notifications.
The default name is "notifications".
.It \fBnotification-name-field\fP \fIname-field-name\fP
The name of the field which contains the notification name.
The default name is "name".
.It \fBnotification-severity-field\fP \fIseverity-field-name\fP
The name of the field which contains the notification severity.
The default name is "severity".
.It \fBnotification-timestamp-field\fP \fItimestamp-field-name\fP
The name of the field which contains the date of the notification.
The default name is "timestamp".
.It \fBnotification-labels-field\fP \fIlabels-field-name\fP
The name of the field which contains the labels of the notification.
The default name is "labels".
.It \fBnotification-annotations-field\fP \fIannotations-field-name\fP
The name of the field which contains the annotations of the notification.
The default name is "annotations".
.It \fBwrite\fP \fImetrics|notifications\fP
If set to \fImetrics\fP (the default) the plugin will handle metrics.
If set to \fInotifications\fP the plugin will handle notifications.
.It \fBttl\fP \fIseconds\fP
Automatic removal of metrics older than a specified number of seconds.
.It \fBbulk-size\fP \fIsize\fP
The number of inserts in the bulk operation.
The default number is 512.
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
