.\" SPDX-License-Identifier: GPL-2.0-only
.TH ncollectd-meminfo 5 "@NCOLLECTD_DATE@" "@NCOLLECTD_VERSION@" "ncollectd meminfo man page"
.SH NAME
ncollectd-meminfo \- Documentation of ncollectd's meminfo plugin
.SH SYNOPSIS
\fBload-plugin\fP meminfo
.SH DESCRIPTION
The \fBmeminfo\fP plugin reports the metrics from the \fI/proc/meminfo\fP file.
.SH "SEE ALSO"
.BR ncollectd (1)
.BR ncollectd.conf (5)
