.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-MEMINFO 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-meminfo
.Nd Documentation of ncollectd's meminfo plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP meminfo
\fBplugin\fP meminfo
.Ed
.Sh DESCRIPTION
The \fBmeminfo\fP plugin reports the metrics from the \fI/proc/meminfo\fP file.
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
