.\" SPDX-License-Identifier: GPL-2.0-only
.TH ncollectd-uuid 5 "@NCOLLECTD_DATE@" "@NCOLLECTD_VERSION@" "ncollectd uuid man page"
.SH NAME
ncollectd-uuid \- Documentation of ncollectd's uuid plugin
.SH SYNOPSIS
\fBload-plugin\fP uuid
.br
\fBplugin\fP uuid {
    \fBuuid-file\fP \fIpath\fP
.br
}
.SH DESCRIPTION
The \fBuuid\fP plugin if loaded, causes the Hostname to be taken from the machine's
UUID. The UUID is a universally unique designation for the machine, usually
taken from the machine's BIOS. This is most useful if the machine is running in
a virtual environment such as Xen, in which case the UUID is preserved across
shutdowns and migration.
.PP
The following methods are used to find the machine's UUID, in order:
.RS
.IP \(bu 2
Check \fI/etc/uuid\fP (or \fBuuid-file\fP).
.IP \(bu 2
Check for UUID from HAL (
.UR http://www.freedesktop.org/wiki/Software/hal
.UE
) if present.
.IP \(bu 2
Check for UUID from Xen hypervisor.
.IP \(bu 2
If no UUID can be found then the hostname is not modified.
.RE
.PP
The plugin has de following options:
.TP
\fBuuid-file\fP \fIpath\fP
Take the UUID from the given file (default \fI/etc/uuid\fP).
.SH "SEE ALSO"
.BR ncollectd (1)
.BR ncollectd.conf (5)
