.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-KAFKA 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-kafka
.Nd Documentation of ncollectd's kafka plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP kafka
\fBplugin\fP kafka {
    \fBinstance\fP \fIinstance\fP {
        \fBproperty\fP \fIkey\fP \fIvalue\fP
        \fBlabel\fP \fIkey\fP \fIvalue\fP
        \fBinterval\fP \fIseconds\fP
        \fBfilter\fP {
            ...
        }
    }
}
.Ed
.Sh DESCRIPTION
The \fBkafka\fP plugin collect metrics from a kafka cluster.
.Pp
The plugin support the following options:
.Bl -tag -width Ds
.It \fBproperty\fP \fIkey\fP \fIvalue\fP
Configure the kafka client through properties, you almost always will
want to set \fBmetadata.broker.list\fP to your Kafka broker list.
.It \fBlabel\fP \fIkey\fP \fIvalue\fP
Append the label \fIkey\fP=\fIvalue\fP to the submitting metrics.
.It \fBinterval\fP \fIseconds\fP
Sets the interval (in seconds) in which the values will be collected
from this instance.
.It \fBfilter\fP
Configure a filter to modify or drop the metrics.
See \fBFILTER CONFIGURATION\fP in
.Xr ncollectd.conf 5 .
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
