.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-EDAC 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-edac
.Nd Documentation of ncollectd's edac plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP edac
\fBplugin\fP edac
.Ed
.Sh DESCRIPTION
The \fBedac\fP plugin collect report correctable and uncorrectable memory
errors from the Error Detection And Correction (EDAC) kernel subsystem.
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
