.\" SPDX-License-Identifier: GPL-2.0-only
.TH ncollectd-edac 5 "@NCOLLECTD_DATE@" "@NCOLLECTD_VERSION@" "ncollectd edac man page"
.SH NAME
ncollectd-edac \- Documentation of ncollectd's edac plugin
.SH SYNOPSIS
\fBload-plugin\fP edac
.SH DESCRIPTION
The \fBedac\fP plugin collect report correctable and uncorrectable memory errors from
the Error Detection And Correction (EDAC) kernel subsystem.
.SH "SEE ALSO"
.BR ncollectd (1)
.BR ncollectd.conf (5)
