.\" SPDX-License-Identifier: GPL-2.0-only
.TH ncollectd-schedstat 5 "@NCOLLECTD_DATE@" "@NCOLLECTD_VERSION@" "ncollectd schedstat man page"
.SH NAME
ncollectd-schedstat \- Documentation of ncollectd's schedstat plugin
.SH SYNOPSIS
\fBload-plugin\fP schedstat
.SH DESCRIPTION
The \fBschedstat\fP plugin collectd scheduling metrics from \fI/proc/schedstat\fP.
.SH "SEE ALSO"
.BR ncollectd (1)
.BR ncollectd.conf (5)
