.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-RTCACHE 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-rtcache
.Nd Documentation of ncollectd's rtcache plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP rtcache
\fBplugin\fP rtcache
.Ed
.Sh DESCRIPTION
The \fBrtcache\fP plugin collect routing cache statistics
from the file \fI/proc/net/stat/rt_cache\fP.
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
