.\" SPDX-License-Identifier: GPL-2.0-only
.TH ncollectd-rtcache 5 "@NCOLLECTD_DATE@" "@NCOLLECTD_VERSION@" "ncollectd rtcache man page"
.SH NAME
ncollectd-rtcache \- Documentation of ncollectd's rtcache plugin
.SH SYNOPSIS
\fBload-plugin\fP rtcache
.SH DESCRIPTION
The \fBrtcache\fP plugin collect routing cache statistics
from the file \fI/proc/net/stat/rt_cache\fP.
.SH "SEE ALSO"
.BR ncollectd (1)
.BR ncollectd.conf (5)
