.\" SPDX-License-Identifier: GPL-2.0-only
.TH ncollectd-zone 5 "@NCOLLECTD_DATE@" "@NCOLLECTD_VERSION@" "ncollectd zone man page"
.SH NAME
ncollectd-zone \- Documentation of ncollectd's zone plugin
.SH DESCRIPTION
The \fBzone\fP plugin collect metrics of cpu and memory from Solaris zones.
.SH "SEE ALSO"
.BR ncollectd (1)
.BR ncollectd.conf (5)
