.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-MONGODB 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-mongodb
.Nd Documentation of ncollectd's mongodb plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP \fImongodb\fP
\fBplugin\fP \fImongodb\fP {
    \fBinstance\fP \fIinstance\fP {
        \fBhost\fP \fIhost\fP
        \fBport\fP \fIport\fP
        \fBuser\fP \fIuser\fP
        \fBuser-env\fP \fIenv-name\fP
        \fBpassword\fP \fIpassword\fP
        \fBpassword-env\fP \fIenv-name\fP
        \fBprefer-secondary-query\fP \fItrue|false\fP
        \fBlabel\fP \fIkey\fP \fIvalue\fP
        \fBinterval\fP \fIseconds\fP
        \fBfilter\fP {
            ...
        }
    }
}
.Ed
.Sh DESCRIPTION
The \fBmongodb\fP plugin will collect stats from \fIMongoDB\fP,
a schema-less NoSQL database.
.Pp
The following options are available:
.Bl -tag -width Ds
.It \fBhost\fP \fIhost\fP
Hostname or address to connect to.
Defaults to \f(CWlocalhost\fP.
.It \fBport\fP \fIport\fP
Service name or port number to connect to.
Defaults to \f(CW27017\fP.
.It \fBuser\fP \fIuser\fP
.It \fBuser-env\fP \fIenv-name\fP
.It \fBpassword\fP \fIpassword\fP
Sets the information used when authenticating to a \fIMongoDB\fP database.
The fields are optional (in which case no authentication is attempted),
but if you want to use authentication all three fields must be set.
.It \fBpassword-env\fP \fIenv-name\fP
Get the password to authenticating to a \fIMongoDB\fP database from the
environment variable \fIenv-name\fP.
.It \fBprefer-secondary-query\fP \fItrue|false\fP
.It \fBlabel\fP \fIkey\fP \fIvalue\fP
Append the label \fIkey\fP=\fIvalue\fP to the submitting metrics.
Can appear multiple time in the \fBinstance\fP block.
.It \fBinterval\fP \fIseconds\fP
Sets the interval (in seconds) in which the values will be collected from this
instanced.
By default the global \fBinterval\fP setting will be used.
.It \fBfilter\fP
Configure a filter to modify or drop the metrics.
See \fBFILTER CONFIGURATION\fP in
.Xr ncollectd.conf 5 .
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
