.\" SPDX-License-Identifier: GPL-2.0-only
.TH ncollectd-synproxy 5 "@NCOLLECTD_DATE@" "@NCOLLECTD_VERSION@" "ncollectd synproxy man page"
.SH NAME
ncollectd-synproxy \- Documentation of ncollectd's synproxy plugin
.SH SYNOPSIS
\fBload-plugin\fP synproxy
.SH DESCRIPTION
The \fBsynproxy\fP plugin collect metrics from the netfilter module Synproxy reading
the file \f(CW/proc/net/stat/synproxy\fP.
.SH "SEE ALSO"
.BR ncollectd (1)
.BR ncollectd.conf (5)
