.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-SYNPROXY 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-synproxy
.Nd Documentation of ncollectd's synproxy plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP synproxy
\fBplugin\fP synproxy
.Ed
.Sh DESCRIPTION
The \fBsynproxy\fP plugin collect metrics from the netfilter module Synproxy
reading the file \f(CW/proc/net/stat/synproxy\fP.
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
