.\" SPDX-License-Identifier: GPL-2.0-only
.TH ncollectd-nftables 5 "@NCOLLECTD_DATE@" "@NCOLLECTD_VERSION@" "ncollectd nftables man page"
.SH NAME
ncollectd-nftables \- Documentation of ncollectd's nftables plugin
.SH SYNOPSIS
\fBload-plugin\fP nftables
.br
\fBplugin\fP nftables {
    \fBcounter\fP  \fIip|ip6|arp|birdge|netdev|inet\fP [\fItable\fP] [\fIcounter\fP]
.br
}
.SH DESCRIPTION
The \fBnftables\fP plugin collects information about the packet and byte count
of named counters inside your ruleset.
.PP
The plugin has the following options:
.PP
.TP
\fBcounter\fP  \fIip|ip6|arp|birdge|netdev|inet\fP [\fItable\fP] [\fIcounter\fP]
If only the \fIfamily\fP is specified all named counters on the family tables are collected.
If \fIfamily\fP and \fItable\fP are specified, only the counters for this table are collectd.
You can optionally specify the \fIcounter\fP name to collect a specific counter.
.SH "SEE ALSO"
.BR ncollectd (1)
.BR ncollectd.conf (5)
