.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-LOCKS 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-locks
.Nd Documentation of ncollectd's locks plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP locks
\fBplugin\fP locks
.Ed
.Sh DESCRIPTION
The \fBlocks\fP plugin collect the file locks and locks pending
from \fI/proc/locks\fP.
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
