.\" SPDX-License-Identifier: GPL-2.0-only
.TH ncollectd-locks 5 "@NCOLLECTD_DATE@" "@NCOLLECTD_VERSION@" "ncollectd locks man page"
.SH NAME
ncollectd-locks \- Documentation of ncollectd's locks plugin
.SH SYNOPSIS
\fBload-plugin\fP locks
.SH DESCRIPTION
The \fBlocks\fP plugin collect the file locks and locks pending from \fI/proc/locks\fP.
.SH "SEE ALSO"
.BR ncollectd (1)
.BR ncollectd.conf (5)
