.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-NOTIFY_EXEC 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-notify_exec
.Nd Documentation of ncollectd's notify_exec plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP notify_exec
\fBplugin\fP notify_exec {
    \fBformat\fP \fItext|json|protob|env|environment\fP
    \fBif-match\fP \fImatch\fP {
        \fBcmd\fP \fIprogram\fP [\fIargs\fP] ...
        \fBuser\fP \fIusername\fP
        \fBgroup\fP \fIgroupname\fP
        \fBenv\fP \fIkey\fP \fIvalue\fP
        \fBformat\fP \fItext|json|protob|env|environment\fP
    }
}
.Ed
.Sh DESCRIPTION
The \fBnotify_exec\fP plugin forks off an executable to dispatch
notifications to the outside world.
.Bl -tag -width Ds
.It \fBif-match\fP \fImatch\fP
The program is forked once for each notification that is handled by the daemon.
The notification is passed to the program on \f(CWSTDIN\fP in a fashion similar
to HTTP-headers.
This program is not serialized, so that several instances of this program may
run at once if multiple notifications are received.
.Bl -tag -width Ds
.It \fBcmd\fP \fIprogram\fP [\fIargs\fP] ...
.It \fBuser\fP \fIusername\fP
Execute the executable \fBcmd\fP as user \fIuser\fP.
.It \fBgroup\fP \fIgroupname\fP
If the \fBgroup\fP is set, the effective group of the executed program
is set to that group.
Please note that in order to change the user and/or group the daemon needs
superuser privileges.
If the daemon is run as an unprivileged user you must specify the same
user/group here.
If the daemon is run with superuser privileges, you must supply a non-root
user here.
.It \fBenv\fP \fIkey\fP \fIvalue\fP
Set the eviroment variable \f(CWkey=value\fP for the executed program.
.It \fBformat\fP \fItext|json|protob|env|environment\fP
How the notification is passed to the program.
.El
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
