.\" SPDX-License-Identifier: GPL-2.0-only
.TH ncollectd-netstat_udp 5 "@NCOLLECTD_DATE@" "@NCOLLECTD_VERSION@" "ncollectd netstat_udp man page"
.SH NAME
ncollectd-netstat_udp \- Documentation of ncollectd's netstat_udp plugin
.SH DESCRIPTION
The \fBnetstat_udp\fP plugin read udp metrics in NetBSD systems.
.SH "SEE ALSO"
.BR ncollectd (1)
.BR ncollectd.conf (5)
