.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-WRITE_AMQP1 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-write_amqp1
.Nd Documentation of ncollectd's write_amqp1 plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP write_amqp1
\fBplugin\fP write_amqp1 {
    \fBinstance\fP \fIname\fP {
        \fBhost\fP \fIhost\fP
        \fBport\fP \fIport\fP
        \fBuser\fP \fIuser\fP
        \fBuser-env\fP \fIenv-name\fP
        \fBpassword\fP \fIpassword\fP
        \fBpassword-env\fP \fIenv-name\fP
        \fBaddress\fP \fIaddress\fP
        \fBretry-delay\fP \fIretry-delay\fP
        \fBformat\fP \fIFORMAT\fP
        \fBpre-settle\fP \fItrue|false\fP
        \fBformat-metric\fP \fIinfluxdb|graphite|json|kairosdb|opentsdb|openmetrics|opentelemetry|remote\fP
        \fBformat-notification\fP \fItext|json|protob\fP
        \fBwrite\fP \fImetrics|notifications\fP
    }
}
.Ed
.Sh DESCRIPTION
The \fBwrite_amqp1\fP plugin can be used to send metrics or notifications
using an AMQP 1.0 message intermediary.
.Pp
The following options are accepted within each \fBinstance\fP block:
.Bl -tag -width Ds
.It \fBhost\fP \fIhost\fP
Hostname or IP-address of the AMQP 1.0 intermediary.
Defaults to the default behavior of the underlying communications library,
\fIlibqpid-proton\fP, which is "localhost".
.It \fBport\fP \fIport\fP
Service name or port number on which the AMQP 1.0 intermediary accepts
connections.
This argument must be a string, even if the numeric form is used.
Defaults to "5672".
.It \fBuser\fP \fIuser\fP
.It \fBuser-env\fP \fIenv-name\fP
.It \fBpassword\fP \fIpassword\fP
Credentials used to authenticate to the AMQP 1.0 intermediary.
By default "guest"/"guest" is used.
.It \fBpassword-env\fP \fIenv-name\fP
Get the credentials used to authenticate to the AMQP 1.0 intermediary from
the environment variable \fIenv-name\fP.
.It \fBaddress\fP \fIaddress\fP
This option specifies the prefix for the send-to value in the message.
.It \fBretry-delay\fP \fIretry-delay\fP
When the AMQP1 connection is lost, defines the time in seconds to wait
before attempting to reconnect.
Defaults to 1, which implies attempt to reconnect at 1 second intervals.
.It \fBpre-settle\fP \fItrue|false\fP
If set to \fIfalse\fP (the default), the plugin will wait for a message
acknowledgement from the messaging bus before sending the next
message.
This indicates transfer of ownership to the messaging system.
If set to \fItrue\fP, the plugin will not wait for a message
acknowledgement and the message may be dropped prior to transfer of
ownership.
.It \fBformat-metric\fP \fIinfluxdb|graphite|json|kairosdb|opentsdb|openmetrics|remote\fP
Selects the format in which messages are sent to the intermediary.
.Bl -tag -width Ds
.It \fBinfluxdb\fP [\fIsec|msec|usec|nsec\fP]
.It \fBgraphite\fP
.It \fBjson\fP
.It \fBkairosdb\fP [\fItelnet [sec|msec]|json\fP]
.It \fBopentsdb\fP [telnet|json]
.It \fBopenmetrics\fP [text|protob]
.It \fBopentelemetry\fP [json]
.It \fBremote\fP [metadata]
.El
.It \fBformat-notification\fP \fItext|json|protob\fP
Selects the format in which notifications are sent to the intermediary.
.It \fBwrite\fP \fImetrics|notifications\fP
If set to \fImetrics\fP (the default) the plugin will handle metrics.
If set to \fInotifications\fP the plugin will handle notifications.
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
