.\" SPDX-License-Identifier: GPL-2.0-only
.TH ncollectd-zoneinfo 5 "@NCOLLECTD_DATE@" "@NCOLLECTD_VERSION@" "ncollectd zoneinfo man page"
.SH NAME
ncollectd-zoneinfo \- Documentation of ncollectd's zoneinfo plugin
.SH SYNOPSIS
\fBload-plugin\fP zoneinfo
.SH DESCRIPTION
The \fBzoneinfo\fP plugin collectd information about memory zones reading the file
\fI/proc/zoneinfo\fP.
.SH "SEE ALSO"
.BR ncollectd (1)
.BR ncollectd.conf (5)
