.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-ZONEINFO 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-zoneinfo
.Nd Documentation of ncollectd's zoneinfo plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP zoneinfo
\fBplugin\fP zoneinfo
.Ed
.Sh DESCRIPTION
The \fBzoneinfo\fP plugin collectd information about memory zones reading
the file \fI/proc/zoneinfo\fP.
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
