.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-PROCESSES 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-processes
.Nd Documentation of ncollectd's processes plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP processes
\fBplugin\fP processes {
    \fBcollect\fP \fIflags\fP ...
    \fBprocess\fP \fIname\fP {
        \fBcollect\fP \fIflags\fP ...
        \fBfilter\fP {
            ...
        }
    }
    \fBprocess-match\fP \fIname\fP \fI/regex/\fP {
        \fBcollect\fP \fIflags\fP ...
        \fBfilter\fP {
            ...
        }
    }
    \fBprocess-pidfile\fP \fIname\fP \fIpidfile-path\fP {
        \fBcollect\fP \fIflags\fP ...
        \fBfilter\fP {
            ...
        }
    }
}
.Ed
.Sh DESCRIPTION
The \fBprocesses\fP plugin collects information about processes of local system.
.Pp
By default, with no process matches configured, only general statistics is
collected: the number of processes in each state and fork rate.
.Pp
Process matches can be configured by \fBprocess\fP and \fBprocess-match\fP
options.
These may also be a block in which further options may be specified.
.Pp
The statistics collected for matched processes are:
.Bl -bullet
.It
size of the resident segment size (RSS)
.It
user-time and system-time used
.It
number of processes
.It
number of threads
.It
number of open files (under Linux)
.It
number of memory mapped files (under Linux)
.It
io data (under Linux),
requires the capabilities: \f(CWCAP_DAC_OVERRIDE\fP and \f(CWCAP_SYS_PTRACE\fP
.It
context switches (under Linux)
.It
minor and major pagefaults
.It
delay Accounting information (Linux only, requires libmnl)
.El
.Pp
The \fBprocesses\fP plugin has the following options:
.Bl -tag -width Ds
.It \fBprocess\fP \fIname\fP
Select more detailed statistics of processes matching this name.
Some platforms have a limit on the length of process names.
\fIname\fP must stay below this limit.
In Linux the \fIname\fP it's chequed against the second field of
\f(CW/proc/pid/stat\fP, the filename of the executable, in parentheses.
.It \fBprocess-match\fP \fIname\fP \fIregex\fP
Select more detailed statistics of processes matching the specified \fIregex\fP
(see.
.Xr regex 7
for details).
The statistics of all matching processes are summed up and dispatched to the
daemon using the specified \fIname\fP as an identifier.
This allows one to "group" several processes together.
.It \fBprocess-pidfile\fP \fIname\fP \fIpidfile-path\fP
 Select more detailed statistics of processes matching and specified \fIPID\fP
contained in the file \fIpidfile-path\fP.
.It \fBcollect\fP \fIflags\fP ...
Must be defined before \fBprocess\fP and \fBprocess-match\fP.
See \fBCOLLECT FLAGS\fP from
.Xr ncollectd.conf 5 .
.Bl -tag -width Ds
.It \fBdelay_accounting\fP
If enabled, collect Linux Delay Accounting information for matching processes.
Delay Accounting provides the time processes wait for the CPU to become
available, for I/O operations to finish, for pages to be swapped in and for
freed pages to be reclaimed.
Disabled by default.
.Pp
This option is only available on Linux, requires the \fBlibmnl\fP library and
requires the \f(CWCAP_NET_ADMIN\fP capability at runtime.
.It \fBfile_descriptor\fP
Collect number of file descriptors of matched processes.
Disabled by default.
.It \fBmemory_maps\fP
Collect the number of memory mapped files of the process.
The limit for this number is configured via \fI/proc/sys/vm/max_map_count\fP in
the Linux kernel.
.El
.Pp
The \fBcollect\fP options may be used inside
\fBprocess\fP and \fBprocess-match\fP blocks.
When used there, these options affect reporting the corresponding processes
only.
Outside of \fBprocess\fP, \fBprocess-match\fP and \fBprocess-pidfile\fP blocks
these options set the default value for subsequent matches.
.El
.Pp
.Bl -tag -width Ds
Inside \fBprocess\fP, \fBprocess-match\fP and \fBprocess-pidfile\fP blocks
we can define a filter:
.It \fBfilter\fP
Configure a filter to modify or drop the metrics.
See \fBFILTER CONFIGURATION\fP in
.Xr ncollectd.conf 5
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
