.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-PRESSURE 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-pressure
.Nd Documentation of ncollectd's pressure plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP pressure
\fBplugin\fP pressure
.Ed
.Sh DESCRIPTION
The \fBpressure\fP plugin monitors the pressure stall information (PSI) for cpu,
io and memory.
Avaliable for Linux since kernel 4.20.
This provides visibility into how resource-constrained the system is.
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
