.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-MATCH_CSV 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-match_csv
.Nd Documentation of ncollectd's csv match plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBmatch\fP csv {
    \fBmetric-prefix\fP \fIprefix\fP
    \fBlabel\fP \fIkey\fP \fIvalue\fP
    \fBtime-from\fP \fIindex\fP
    \fBfield-separator\fP \fIchar\fP
    \fBmetric\fP {
        \fBmetric\fP  \fImetric\fP
        \fBhelp\fP \fIhelp\fP
        \fBtype\fP \fIgauge\fP [\fIaverage|min|max|last|inc|add|persist\fP]|\fIcounter\fP [\fIset|add|inc\fP]
        \fBlabel\fP \fIkey\fP \fIvalue\fP
        \fBmetric-prefix\fP \fIprefix\fP
        \fBmetric-from\fP \fIindex\fP
        \fBlabel-from\fP \fIkey\fP \fIindex\fP
        \fBvalue-from\fP \fIindex\fP
    }
}
.Ed
.Sh DESCRIPTION
The \fBmatch_csv\fP plugin parse lines in the CSV format,
.Bl -tag -width Ds
.It \fBmetric-prefix\fP \fIprefix\fP
Prepend the \fIprefix\fP to the metrics found in the \fBmetric\fP blocks.
.It \fBlabel\fP \fIkey\fP \fIvalue\fP
Append the label \fIkey\fP=\fIvalue\fP to the submitting metrics.
.It \fBtime-from\fP \fIindex\fP
Configure to read the timestamp of the metric from the field with the
zero-based index.
.It \fBfield-separator\fP \fIchar\fP
Any character a delimiter between the different columns of the table.
.It \fBmetric\fP
.Bl -tag -width Ds
.It \fBmetric\fP \fImetric\fP
Set metric name.
.It \fBhelp\fP \fIhelp\fP
Set metric help.
.It \fBtype\fP \fIgauge\fP [\fIaverage|min|max|last|inc|add|persist\fP]|\fIcounter\fP [\fIset|add|inc\fP]
.Bl -tag -width Ds
.It \fBgauge\fP
The value is a gauge, you must specify also the type of the gauge:
.Bl -tag -width Ds
.It \fBaverage\fP
Calculate the average
.It \fBmin\fP
Use the smallest number only.
.It \fBmax\fP
Use the greatest number only.
.It \fBlast\fP
Use the last number found.
.It \fBinc\fP
Increase the internal counter by one.
.It \fBadd\fP
Add the matched value to the internal counter.
.It \fBpersist\fP
Use the last number found.
The number is not reset at the end of an interval.
It is continuously reported until another number is matched.
.El
.It \fBcounter\fP
The value is a counter, you must specify also the type of the counter:
.Bl -tag -width Ds
.It \fBset\fP
Simply sets the internal counter to this value.
.It \fBadd\fP
Add the matched value to the internal counter.
.It \fBinc\fP
Increase the internal counter by one.
.El
.El
.It \fBlabel\fP \fIkey\fP \fIvalue\fP
Append the label \fIkey\fP=\fIvalue\fP to the submitting metrics.
.It \fBmetric-prefix\fP \fIprefix\fP
Prepend the \fIprefix\fP to the metrics found in the \fBmetric-from\fP.
.It \fBmetric-from\fP \fIindex\fP
Configure to read the metric from the field with the zero-based index.
.It \fBlabel-from\fP \fIkey\fP \fIindex\fP
Set the label \fIkey\fP with the value from the field with the zero-based index.
.It \fBvalue-from\fP \fIindex\fP
Configure to read the value from the field with the zero-based index.
.El
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
