.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-CGROUPS 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-cgroups
.Nd Documentation of ncollectd's cgroups plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP cgroups
\fBplugin\fP cgroups {
    \fBcgroup\fP [\fIincl|include|excl|exclude\fP] \fIcgroup\fP
    \fBfilter\fP {
        ...
    }
}
.Ed
.Sh DESCRIPTION
The \fBcgroups\fP plugin collects CPU, IO and memory metrics from
the groups configured in Control Groups V1 or Control Groups V2.
.Pp
The plugin has the following options:
.Bl -tag -width Ds
.It \fBcgroup\fP [\fIincl|include|excl|exclude\fP] \fIcgroup\fP
Select \fIcgroup\fP based on the name.
By default only selected cgroups are collected if a selection is made.
If no selection is configured at all, \fBall\fP cgroups are selected.
.It \fBfilter\fP
Configure a filter to modify or drop the metrics.
See \fBFILTER CONFIGURATION\fP in
.Xr ncollectd.conf 5
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
