.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-CGROUPS 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-cgroups
.Nd Documentation of ncollectd's cgroups plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP cgroups
\fBplugin\fP cgroups {
    \fBcgroup\fP [\fIincl|include|excl|exclude\fP] \fIcgroup\fP
}
.Ed
.Sh DESCRIPTION
The \fBcgroups\fP plugin collects the CPU user/system time for each
\fIcgroup\fP by reading the \fIcpuacct.stat\fP files in the first
cpuacct-mountpoint (typically \fI/sys/fs/cgroup/cpu.cpuacct\fP on
machines using systemd).
.Pp
The plugin has the following options:
.Bl -tag -width Ds
.It \fBcgroup\fP [\fIincl|include|excl|exclude\fP] \fIcgroup\fP
Select \fIcgroup\fP based on the name.
By default only selected cgroups are collected if a selection is made.
If no selection is configured at all, \fBall\fP cgroups are selected.
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
