.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-GPU_INTEL 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-gpu_intel
.Nd Documentation of ncollectd's gpu_intel plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP gpu_intel
\fBplugin\fP gpu_intel {
    \fBcollect\fP \fIflags\fP
    \fBlog-gpu-info\fP \fItrue|false\fP
    \fBmetrics-output\fP \fIstring\fP
    \fBsamples\fP \fIsamples\fP
}
.Ed
.Sh DESCRIPTION
This plugin is available on Linux only.
It uses level-Zero Sysman API to read GPU information.
.Pp
Options below give overview of what information it could provide, but
the information actually available through it depends on what is
supported by the underlying GPU HW, its kernel driver, and Level-Zero
Sysman backend (compute) driver implementation.
.Bl -tag -width Ds
.It \fBcollect\fP \fIflags\fP
.Bl -tag -width Ds
.It \fBengine\fP
Engine utilization metrics collection.
.It \fBengine_single\fP
Utilization metrics collection for single engines i.e. provide
utilization information only for engine groups.
.It \fBfabric\fP
Fabric port metrics collection.
.It \fBfrequency\fP
Actual / requested frequency metrics collection.
.It \fBmemory\fP
Memory usage metrics collection.
.It \fBmemory_bandwidth\fP
Memory bandwidth metrics collection.
.It \fBpower\fP
Power usage metrics collection.
.It \fBpower_ratio\fP
.It \fBerrors\fP
RAS (Reliability, Availability, and Serviceability) error
metrics collection.
.It \fBseparate_errors\fP
Each error sub-category being reported separately, and just
report total error counters for higher level "correctable" and
"uncorrectable" errors.
.It \fBtemperature\fP
Temperature metrics collection.
.It \fBthrottle_time\fP
Frequency throttling time metric collection.
.El
.It \fBlog-gpu-info\fP \fItrue|false\fP
If enabled, plugin logs at start some information about plugin
settings, all the GPUs detected through Sysman API, and enables
"pci_dev" PCI device ID label for the metrics.
.It \fBmetrics-output\fP \fIstring\fP
Set of "base", "rate", and "ratio" strings, separated by comma, colon,
slash or space.
.Pp
Base metric can be either a counter (e.g. error count) that only
increases, or one that can also decrease (e.g. temperature).
The other options are values derived from base metric value.
.Pp
Several of the metric types support multiple output variants for their values.
This option specifies which ones of them are to be reported.
.Pp
Default is to report all variants ("base:rate:ratio"). To reduce
amount of data, it is better to configure just the relevant ones for
given use (e.g. "base:ratio" or "rate:ratio").
Note that some of the metric types support only two of these variants,
whereas metrics supporting only single variant ignore this option.
.Pp
Base metric variant (e.g. HW energy usage as Joules counter) is
preferred by Prometheus as doing rate calculations in Prometheus is
more flexible.
However, because collectd stores counters internally as integers instead
of floating point, counter metrics are given in microjoules / microseconds
instead of their (joule / second) SI base units
(required by OpenMetrics spec), for better accuracy.
.Pp
Rate metric variant is directly human readable, and available for
metrics where it makes sense (e.g. bytes per second, Watts and RPMs).
.Pp
Ratio variant is a utilization metric.
It can be reported only for metric types which are either based on time
(e.g. GPU engine use time), or for which Sysman provides a
limit / maximum value.
Some metrics may give over 100% ratios if their limit applies over longer
time than the query interval (could happen e.g. with power limits).
.It \fBsamples\fP \fIsamples\fP
How many values to collect (at specified plugin Interval) for sampled
metrics, before submitting their (potentially aggregate) metric
values.
This means that the actual GPU metrics submit interval is
\f(CWinterval * samples\fP.
Currently GPU frequency and GPU memory values are sampled (like this),
because their values can have very large fluctuations multiple times
per second.
When Samples is larger than 1, min + max are calculated for the sampled
values and submitted instead of the read values themselves.
.Pp
Most of the other metric values are either counters, or change much
slower, and are read only at submit intervals.
If collecting of the sampled values is disabled, it is better to
set Samples to 1 (default).
.El
.Sh "SEE ALSO"
.Xr ncollectd  1 ,
.Xr ncollectd.conf 5
