.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-WRITE_POSTGRESQL 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-write_postgresql
.Nd Documentation of ncollectd's write_postgresql plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP write postgresql
\fBplugin\fP write_postgresql {
    \fBinstance\fP \fIinstance\fP {
        \fBhost\fP \fIhost\fP
        \fBport\fP \fIport\fP
        \fBdatabase\fP \fIdatabase\fP
        \fBuser\fP \fIuser\fP
        \fBuser-env\fP \fIenv-name\fP
        \fBpassword\fP \fIpassword\fP
        \fBpassword-env\fP \fIenv-name\fP
        \fBssl-mode\fP \fIdisable|allow|prefer|require\fP
        \fBkrb-srv-name\fP \fIname\fP
        \fBservice\fP \fIservice\fP
        \fBinterval\fP \fIseconds\fP
        \fBcommit-interval\fP \fIseconds\fP
        \fBwrite\fP \fImetrics|notifications\fP
        \fBstatement\fP \fIsql-statement\fP
    }
}
.Ed
.Sh DESCRIPTION
The \fBwrite_postgresql\fP plugin writes metrics in a PostgreSQL databases.
It keeps a persistent connection to all configured databases and tries to
reconnect if the connection has been interrupted.
A database is configured by specifying a \fBinstance\fP block as described
below.
.Pp
The following options are accepted within each \fBinstance\fP block:
.Bl -tag -width Ds
.It \fBhost\fP \fIhost\fP
Specify the hostname or IP of the PostgreSQL server to connect to.
If the value begins with a slash, it is interpreted as the directory name in
which to look for the UNIX domain socket.
.It \fBport\fP \fIport\fP
Specify the TCP port or the local UNIX domain socket file extension of the
server.
.It \fBdatabase\fP \fIdatabase\fP
Database name to connect.
.It \fBuser\fP \fIuser\fP
Specify the username to be used when connecting to the server.
.It \fBuser-env\fP \fIenv-name\fP
Get the username to be used when connecting to the server from the environment
variable
\fIenv-name\fP.
.It \fBpassword\fP \fIpassword\fP
Specify the password to be used when connecting to the server.
.It \fBpassword-env\fP \fIenv-name\fP
Get the the password to be used when connecting to the server from the
environment variable
\fIenv-name\fP.
.It \fBssl-mode\fP \fIdisable|allow|prefer|require\fP
Specify whether to use an SSL connection when contacting the server.
The following modes are supported:
.Bl -tag -width Ds
.It \fBdisable\fP
Do not use SSL at all.
.It \fBallow\fP
First, try to connect without using SSL.
If that fails, try using SSL.
.It \fBprefer\fP \fI(default)\fP
First, try to connect using SSL.
If that fails, try without using SSL.
.It \fBrequire\fP
Use SSL only.
.El
.It \fBkrb-srv-name\fP \fIname\fP
Specify the Kerberos service name to use when authenticating with Kerberos 5
or GSSAPI.
See the sections "Kerberos authentication" and "GSSAPI" of the
\fBPostgreSQL Documentation\fP for details.
.It \fBservice\fP \fIservice\fP
Specify the PostgreSQL service name to use for additional parameters.
That service has to be defined in \fIpg_service.conf\fP and holds additional
connection parameters.
See the section "The Connection Service File" in the
\fBPostgreSQL Documentation\fP for details.
.It \fBinterval\fP \fIseconds\fP
Specify the interval with which the full callback in called to commit the data.
The default is to use the global \fBinterval\fP setting.
.It \fBcommit-interval\fP \fIseconds\fP
This option causes a writer to put several updates into a single transaction.
This transaction will last for the specified amount of time.
By default, each SQL statement will be executed in a separate transaction.
Each transaction generates a fair amount of overhead which can, thus,
be reduced by activating this option.
.It \fBwrite\fP \fImetrics|notifications\fP
If set to \fImetrics\fP (the default) the plugin will handle metrics.
If set to \fInotifications\fP the plugin will handle notifications.
.It \fBstatement\fP \fIsql-statement\fP
This mandatory option specifies the SQL statement that will be executed
for each submitted value.
A single SQL statement is allowed only.
Anything after the first semicolon will be ignored.
.Bl -tag -width Ds
.It \fBMetrics\fP
Four parameters will be passed to the statement and should be specified
as tokens $1, $2, through $4 in the statement string.
In general, it is advisable to create and call a custom function in the
PostgreSQL database for this purpose.
.Pp
The following values are made available through those parameters:
.Bl -tag -width Ds
.It \fB$1\fP
The metric name.
.It \fB$2\fP
The metric labels as an array of pairs.
.It \fB$3\fP
The value of the metric.
.It \fB$4\fP
The timestamp of the queried value as an RFC 3339-formatted local time.
.El
.It \fBNotifications\fP
Five parameters will be passed to the statement and should be specified as
tokens $1, $2, through $5 in the statement string.
In general, it is advisable to create and call a custom function in the
PostgreSQL database for this purpose.
.Pp
The following values are made available through those parameters:
.Bl -tag -width Ds
.It \fB$1\fP
The notification name.
.It \fB$2\fP
The notification labels as an array of pairs.
.It \fB$3\fP
The notification annotations as an array of pairs.
.It \fB$4\fP
The severity of the notification as string:
\fIFAILURE\fP, \fIWARNING\fP or \fIOKAY\fP
.It \fB$5\fP
The timestamp of the notification as an RFC 3339-formatted local time.
.El
.El
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
