.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-SWAP 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-swap
.Nd Documentation of ncollectd's swap plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP swap
\fBplugin\fP swap {
    \fBreport-by-device\fP \fItrue|false\fP
}
.Ed
.Sh DESCRIPTION
The \fBswap\fP plugin collects information about used and available swap space.
On \fILinux\fP and \fISolaris\fP, the following options are available:
.Bl -tag -width Ds
.It \fBreport-by-device\fP \fItrue|false\fP
Configures how to report physical swap devices.
If set to \fBfalse\fP (the default), the summary over all swap devices is
reported only, i.e. the globally used and available space over all devices.
If \fBtrue\fP is configured, the used and available space of each device
will be reported separately.
.Pp
This option is only available if the \fBswap\fP plugin can read
\fI/proc/swaps\fP (under Linux) or use the
.Xr swapctl 2
mechanism (under \fISolaris\fP).
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
