.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-WIREGUARD 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-wireguard
.Nd Documentation of ncollectd's wireguard plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP wireguard
\fBplugin\fP wireguard
.Ed
.Sh DESCRIPTION
The \fBwireguard\fP plugin collect statistics of wireguard vpn tunnels.
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
