.\" SPDX-License-Identifier: GPL-2.0-only
.TH ncollectd-wireguard 5 "@NCOLLECTD_DATE@" "@NCOLLECTD_VERSION@" "ncollectd wireguard man page"
.SH NAME
ncollectd-wireguard \- Documentation of ncollectd's wireguard plugin
.SH SYNOPSIS
\fBload-plugin\fP wireguard
\fBplugin\fP wireguard
.SH DESCRIPTION
The \fBwireguard\fP plugin collect statistics of wireguard vpn tunnels.
.SH "SEE ALSO"
.BR ncollectd (1)
.BR ncollectd.conf (5)
