.\" SPDX-License-Identifier: GPL-2.0-only
.TH ncollectd-memory 5 "@NCOLLECTD_DATE@" "@NCOLLECTD_VERSION@" "ncollectd memory man page"
.SH NAME
ncollectd-memory \- Documentation of ncollectd's memory plugin
.SH SYNOPSIS
\fBload-plugin\fP memory
.SH DESCRIPTION
The \fBmemory\fP plugin reports the free memory and different kinds of used memory in the system.
.SH "SEE ALSO"
.BR ncollectd (1)
.BR ncollectd.conf (5)
