.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-MEMORY 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-memory
.Nd Documentation of ncollectd's memory plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP memory
\fBplugin\fP memory
.Ed
.Sh DESCRIPTION
The \fBmemory\fP plugin reports the free memory and different kinds
of used memory in the system.
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
