enum {
	HA_STAT_PXNAME,
	HA_STAT_SVNAME,
	HA_STAT_QCUR,
	HA_STAT_QMAX,
	HA_STAT_SCUR,
	HA_STAT_SMAX,
	HA_STAT_SLIM,
	HA_STAT_STOT,
	HA_STAT_BIN ,
	HA_STAT_BOUT,
	HA_STAT_DREQ,
	HA_STAT_DRESP,
	HA_STAT_EREQ,
	HA_STAT_ECON,
	HA_STAT_ERESP,
	HA_STAT_WRETR,
	HA_STAT_WREDIS,
	HA_STAT_STATUS,
	HA_STAT_WEIGHT,
	HA_STAT_ACT,
	HA_STAT_BCK,
	HA_STAT_CHKFAIL,
	HA_STAT_CHKDOWN,
	HA_STAT_LASTCHG,
	HA_STAT_DOWNTIME,
	HA_STAT_QLIMIT,
	HA_STAT_PID,
	HA_STAT_IID,
	HA_STAT_SID,
	HA_STAT_THROTTLE,
	HA_STAT_LBTOT,
	HA_STAT_TRACKED,
	HA_STAT_TYPE,
	HA_STAT_RATE,
	HA_STAT_RATE_LIM,
	HA_STAT_RATE_MAX,
	HA_STAT_CHECK_STATUS,
	HA_STAT_CHECK_CODE,
	HA_STAT_CHECK_DURATION,
	HA_STAT_HRSP_1XX,
	HA_STAT_HRSP_2XX,
	HA_STAT_HRSP_3XX,
	HA_STAT_HRSP_4XX,
	HA_STAT_HRSP_5XX,
	HA_STAT_HRSP_OTHER,
	HA_STAT_HANAFAIL,
	HA_STAT_REQ_RATE,
	HA_STAT_REQ_RATE_MAX,
	HA_STAT_REQ_TOT,
	HA_STAT_CLI_ABRT,
	HA_STAT_SRV_ABRT,
	HA_STAT_COMP_IN,
	HA_STAT_COMP_OUT,
	HA_STAT_COMP_BYP,
	HA_STAT_COMP_RSP,
	HA_STAT_LASTSESS,
	HA_STAT_LAST_CHK,
	HA_STAT_LAST_AGT,
	HA_STAT_QTIME,
	HA_STAT_CTIME,
	HA_STAT_RTIME,
	HA_STAT_TTIME,
	HA_STAT_AGENT_STATUS,
	HA_STAT_AGENT_CODE,
	HA_STAT_AGENT_DURATION,
	HA_STAT_CHECK_DESC,
	HA_STAT_AGENT_DESC,
	HA_STAT_CHECK_RISE,
	HA_STAT_CHECK_FALL,
	HA_STAT_CHECK_HEALTH,
	HA_STAT_AGENT_RISE,
	HA_STAT_AGENT_FALL,
	HA_STAT_AGENT_HEALTH,
	HA_STAT_ADDR,
	HA_STAT_COOKIE,
	HA_STAT_MODE,
	HA_STAT_ALGO,
	HA_STAT_CONN_RATE,
	HA_STAT_CONN_RATE_MAX,
	HA_STAT_CONN_TOT,
	HA_STAT_INTERCEPTED,
	HA_STAT_DCON,
	HA_STAT_DSES,
	HA_STAT_WREW,
	HA_STAT_CONNECT,
	HA_STAT_REUSE,
	HA_STAT_CACHE_LOOKUPS,
	HA_STAT_CACHE_HITS,
	HA_STAT_SRV_ICUR,
	HA_STAT_SRV_ILIM,
	HA_STAT_QT_MAX,
	HA_STAT_CT_MAX,
	HA_STAT_RT_MAX,
	HA_STAT_TT_MAX,
	HA_STAT_EINT,
	HA_STAT_IDLE_CONN_CUR,
	HA_STAT_SAFE_CONN_CUR,
	HA_STAT_USED_CONN_CUR,
	HA_STAT_NEED_CONN_EST,
	HA_STAT_UWEIGHT,
	HA_STAT_MAX,
};

#if 0
enum {
    HA_EXT_STATUS_H2_HEADERS_RCVD,
    HA_EXT_STATUS_H2_DATA_RCVD,
    HA_EXT_STATUS_H2_SETTINGS_RCVD,
    HA_EXT_STATUS_H2_RST_STREAM_RCVD,
    HA_EXT_STATUS_H2_GOAWAY_RCVD,
    HA_EXT_STATUS_H2_CONN_PROTO_ERR,
    HA_EXT_STATUS_H2_STRM_PROTO_ERR,
    HA_EXT_STATUS_H2_RST_STREAM_RESP,
    HA_EXT_STATUS_H2_GOAWAY_RESP,
    HA_EXT_STATUS_H2_OPEN_CONN,
    HA_EXT_STATUS_H2_OPEN_STREAM,
    HA_EXT_STATUS_H2_TOTAL_CONN,
    HA_EXT_STATUS_H2_TOTAL_STREAM,
    HA_EXT_STATUS_H2_MAX,
};


    .name = "h2_headers_rcvd",
    .type = METRIC_TYPE_COUNTER,
    .help = "Total number of received HEADERS frames"
  },
    .name = "h2_data_rcvd",
    .type = METRIC_TYPE_COUNTER,
    .help = "Total number of received DATA frames"
  },
    .name = "h2_settings_rcvd",
    .type = METRIC_TYPE_COUNTER,
    .help = "Total number of received SETTINGS frames"
  },
    .name = "h2_rst_stream_rcvd",
    .type = METRIC_TYPE_COUNTER,
    .help = "Total number of received RST_STREAM frames"
  },
    .name = "h2_goaway_rcvd",
    .type = METRIC_TYPE_COUNTER,
    .help = "Total number of received GOAWAY frames"
  },
    .name = "h2_detected_conn_protocol_errors",
    .type = METRIC_TYPE_COUNTER,
    .help = "Total number of connection protocol errors"
  },
    .name = "h2_detected_strm_protocol_errors",
    .type = METRIC_TYPE_COUNTER,
    .help = "Total number of stream protocol errors"
  },
    .name = "h2_rst_stream_resp",
    .type = METRIC_TYPE_COUNTER,
    .help = "Total number of RST_STREAM sent on detected error"
  },
    .name = "h2_goaway_resp",
    .type = METRIC_TYPE_COUNTER,
    .help = "Total number of GOAWAY sent on detected error"
  },
    .name = "h2_open_connections",
    .type = METRIC_TYPE_GAUGE,
    .help = "Count of currently open connections"
  },
    .name = "h2_backend_open_streams",
    .type = METRIC_TYPE_GAUGE,
    .help = "Count of currently open streams"
  },
    .name = "h2_total_connections",
    .type = METRIC_TYPE_COUNTER,
    .help = "Total number of connections"
  },
    .name = "h2_backend_total_streams",
    .type = METRIC_TYPE_COUNTER,
    .help = "Total number of streams",
  },


h2_headers_rcvd
h2_data_rcvd
h2_settings_rcvd
h2_rst_stream_rcvd
h2_goaway_rcvd
h2_detected_conn_protocol_errors
h2_detected_strm_protocol_errors
h2_rst_stream_resp
h2_goaway_resp
h2_open_connections
h2_backend_open_streams
h2_total_connections
h2_backend_total_streams

#endif

/*
enum {
    DNS_STAT_ID,
    DNS_STAT_PID,
    DNS_STAT_SENT,
    DNS_STAT_SND_ERROR,
    DNS_STAT_VALID,
    DNS_STAT_UPDATE,
    DNS_STAT_CNAME,
    DNS_STAT_CNAME_ERROR,
    DNS_STAT_ANY_ERR,
    DNS_STAT_NX,
    DNS_STAT_TIMEOUT,
    DNS_STAT_REFUSED,
    DNS_STAT_OTHER,
    DNS_STAT_INVALID,
    DNS_STAT_TOO_BIG,
    DNS_STAT_TRUNCATED,
    DNS_STAT_OUTDATED,
    DNS_STAT_END,
};

static struct name_desc dns_stats[] = {
    [DNS_STAT_ID]          = { .name = "id",          .desc = "ID" },
    [DNS_STAT_PID]         = { .name = "pid",         .desc = "Parent ID" },
    [DNS_STAT_SENT]        = { .name = "sent",        .desc = "Sent" },
    [DNS_STAT_SND_ERROR]   = { .name = "send_error",  .desc = "Send error" },
    [DNS_STAT_VALID]       = { .name = "valid",       .desc = "Valid" },
    [DNS_STAT_UPDATE]      = { .name = "update",      .desc = "Update" },
    [DNS_STAT_CNAME]       = { .name = "cname",       .desc = "CNAME" },
    [DNS_STAT_CNAME_ERROR] = { .name = "cname_error", .desc = "CNAME error" },
    [DNS_STAT_ANY_ERR]     = { .name = "any_err",     .desc = "Any errors" },
    [DNS_STAT_NX]          = { .name = "nx",          .desc = "NX" },
    [DNS_STAT_TIMEOUT]     = { .name = "timeout",     .desc = "Timeout" },
    [DNS_STAT_REFUSED]     = { .name = "refused",     .desc = "Refused" },
    [DNS_STAT_OTHER]       = { .name = "other",       .desc = "Other" },
    [DNS_STAT_INVALID]     = { .name = "invalid",     .desc = "Invalid" },
    [DNS_STAT_TOO_BIG]     = { .name = "too_big",     .desc = "Too big" },
    [DNS_STAT_TRUNCATED]   = { .name = "truncated",   .desc = "Truncated" },
    [DNS_STAT_OUTDATED]    = { .name = "outdated",    .desc = "Outdated" },
};
*/
