.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-HAPROXY 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-haproxy
.Nd Documentation of ncollectd's haproxy plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP haproxy
\fBplugin\fP haproxy {
    \fBinstance\fP \fIinstance\fP {
        \fBurl\fP \fIurl\fP
        \fBsocket-path\fP \fIpath\fP
        \fBuser\fP \fIusername\fP
        \fBuser-env\fP \fIenv-name\fP
        \fBpassword\fP \fIpassword\fP
        \fBpassword-env\fP \fIenv-name\fP
        \fBdigest\fP \fItrue|false\fP
        \fBverify-peer\fP \fItrue|false\fP
        \fBverify-host\fP \fItrue|false\fP
        \fBca-cert\fP \fI/path/to/cert\fP
        \fBheader\fP \fIHeader\fP
        \fBlabel\fP \fIkey\fP \fIvalue\fP
        \fBinterval\fP \fIseconds\fP
        \fBfilter\fP {
            ...
        }
    }
}
.Ed
.Sh DESCRIPTION
The \fBhaproxy\fP plugin plugin uses the \fBlibcurl\fP to read HAProxy
metrics over http.
Also can retrieve HAProxy metrics from an unix socket.
.Pp
In the \fBplugin\fP block, there may be one or more \fBinstance\fP blocks.
The following options are valid within \fBinstance\fP blocks:
.Bl -tag -width Ds
.It \fBurl\fP \fIurl\fP
URL of the HAProxy csv stats.
.It \fBsocket-path\fP \fIpath\fP
Path to HAProxy stats socket.
.It \fBuser\fP \fIusername\fP
Username to use if authorization is required to read the url.
.It \fBuser-env\fP \fIenv-name\fP
Get the username to use if authorization is required to read the url from
the environment variable \fIenv-name\fP.
.It \fBpassword\fP \fIpassword\fP
Password to use if authorization is required to read the url.
.It \fBpassword-env\fP \fIenv-name\fP
Get the password to use if authorization is required to read the url from
the environment variable \fIenv-name\fP.
.It \fBdigest\fP \fItrue|false\fP
Enable HTTP digest authentication.
.It \fBverify-peer\fP \fItrue|false\fP
Enable or disable peer SSL certificate verification.
See
.Lk http://curl.haxx.se/docs/sslcerts.html
for details.
Enabled by default.
.It \fBverify-host\fP \fItrue|false\fP
Enable or disable peer host name verification.
If enabled, the plugin checks if the \f(CWCommon Name\fP or a
\f(CWSubject Alternate Name\fP field of the SSL certificate matches the
host name provided by the \fBurl\fP option.
If this identity check fails, the connection is aborted.
Obviously, only works when connecting to a SSL enabled server.
Enabled by default.
.It \fBca-cert\fP \fI/path/to/cert\fP
File that holds one or more SSL certificates.
If you want to use HTTPS you will possibly need this option.
What CA certificates come bundled with \fIlibcurl\fP and are checked by
default depends on the distribution you use.
.It \fBheader\fP \fIHeader\fP
A HTTP header to add to the request.
Multiple headers are added if this option
is specified more than once.
.It \fBlabel\fP \fIkey\fP \fIvalue\fP
Append the label \fIkey\fP=\fIvalue>\fP to the submitting metrics.
Can appear multiple time in the \fBinstance\fP block.
.It \fBinterval\fP \fIseconds\fP
Sets the interval (in seconds) in which the values will be collected from this
instance.
By default the global \fBinterval\fP setting will be used.
.It \fBfilter\fP
Configure a filter to modify or drop the metrics.
See \fBFILTER CONFIGURATION\fP in
.Xr ncollectd.conf 5 .
.El
.Sh "SEE ALSO"
.Xr ncollectd  1 ,
.Xr ncollectd.conf 5
