.\" SPDX-License-Identifier: GPL-2.0-only
.TH ncollectd-haproxy 5 "@NCOLLECTD_DATE@" "@NCOLLECTD_VERSION@" "ncollectd haproxy man page"
.SH NAME
ncollectd-haproxy \- Documentation of ncollectd's haproxy plugin
.SH SYNOPSIS
\fBload-plugin\fP haproxy
.br
\fBplugin\fP haproxy {
    \fBinstance\fP \fIinstance\fP {
        \fBurl\fP \fIurl\fP
        \fBsocket-path\fP \fIpath\fP
        \fBuser\fP \fIusername\fP
        \fBpassword\fP \fIpassword\fP
        \fBdigest\fP \fItrue|false\fP
        \fBverify-peer\fP \fItrue|false\fP
        \fBverify-host\fP \fItrue|false\fP
        \fBca-cert\fP \fI/path/to/cert\fP
        \fBheader\fP \fIHeader\fP
        \fBlabel\fP \fIkey\fP \fIvalue\fP
        \fBinterval\fP \fIseconds\fP
        \fBfilter\fP {
            ...
        }
    }
.br
}
.SH DESCRIPTION
The \fBhaproxy\fP plugin plugin uses the \fBlibcurl\fP to read HAProxy
metrics over http. Also can retrive HAProxy metrics from an unix socket.
.PP
In the \fBplugin\fP block, there may be one or more \fBinstance\fP blocks.
The following options are valid within \fBinstance\fP blocks:
.PP
.TP
\fBurl\fP \fIurl\fP
URL of the HAProxy csv stats.
.TP
\fBsocket-path\fP \fIpath\fP
Path to HAProxy stats socket.
.TP
\fBuser\fP \fIusername\fP
Username to use if authorization is required to read the url.
.TP
\fBpassword\fP \fIpassword\fP
Password to use if authorization is required to read the url.
.TP
\fBdigest\fP \fItrue|false\fP
Enable HTTP digest authentication.
.TP
\fBverify-peer\fP \fItrue|false\fP
Enable or disable peer SSL certificate verification. See
.UR http://curl.haxx.se/docs/sslcerts.html
.UE
for details. Enabled by default.
.TP
\fBverify-host\fP \fItrue|false\fP
Enable or disable peer host name verification. If enabled, the plugin checks if
the \f(CWCommon Name\fP or a \f(CWSubject Alternate Name\fP field of the SSL certificate
matches the host name provided by the \fBurl\fP option. If this identity check
fails, the connection is aborted. Obviously, only works when connecting to a
SSL enabled server. Enabled by default.
.TP
\fBca-cert\fP \fI/path/to/cert\fP
File that holds one or more SSL certificates. If you want to use HTTPS you will
possibly need this option. What CA certificates come bundled with \fIlibcurl\fP
and are checked by default depends on the distribution you use.
.TP
\fBheader\fP \fIHeader\fP
A HTTP header to add to the request. Multiple headers are added if this option
is specified more than once.
.TP
\fBlabel\fP \fIkey\fP \fIvalue\fP
Append the label \fIkey\fP=\fIvalue>\fP to the submitting metrics. Can appear
multiple time in the \fBinstance\fP block.
.TP
\fBinterval\fP \fIseconds\fP
Sets the interval (in seconds) in which the values will be collected from this
instance. By default the global \fBinterval\fP setting will be used.
.TP
\fBfilter\fP
Configure a filter to modify or drop the metrics. See \fBFILTER CONFIGURATION\fP in
.BR ncollectd.conf(5)
.SH "SEE ALSO"
.BR ncollectd (1)
.BR ncollectd.conf (5)
