.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-QUOTA 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-quota
.Nd Documentation of ncollectd's quota plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP quota
\fBplugin\fP quota {
    \fBdevice\fP [\fIincl|include|excl|exclude\fP] \fIdevice-name\fP
    \fBmount-point\fP [\fIincl|include|excl|exclude\fP] \fImount-point\fP
    \fBfs-type\fP [\fIincl|include|excl|exclude\fP] \fIfs-type\fP
    \fBuser-id\fP [\fIincl|include|excl|exclude\fP]  \fIuid\fP
    \fBuser-name\fP [\fIincl|include|excl|exclude\fP] \fIusername\fP
    \fBreport-by-user-name\fP \fItrue|false\fP
}
.Ed
.Sh DESCRIPTION
The \fBquota\fP plugin collect metrics of filesystems quota.
.Pp
The plugin supports the following options:
.Bl -tag -width Ds
.It \fBdevice\fP [\fIincl|include|excl|exclude\fP] \fIdevicename\fP
Select filesystems based on the devicename.
See \fBINCLUDE AND EXCLUDE LISTS\fP in
.Xr ncollectd.conf 5 .
.It \fBmount-point\fP [\fIincl|include|excl|exclude\fP] \fImount-point\fP
Select filesystems based on the mountpoint.
See \fBINCLUDE AND EXCLUDE LISTS\fP in
.Xr ncollectd.conf 5 .
.It \fBfs-type\fP [\fIincl|include|excl|exclude\fP] \fIfs-type\fP
Select filesystems based on the filesystem type.
See \fBINCLUDE AND EXCLUDE LISTS\fP in
.Xr ncollectd.conf 5 .
.It \fBuser-id\fP [\fIincl|include|excl|exclude\fP]  \fIuid\fP
Select users quotas based on the uid.
See \fBINCLUDE AND EXCLUDE LISTS\fP in
.Xr ncollectd.conf 5 .
.It \fBuser-name\fP [\fIincl|include|excl|exclude\fP] \fIusername\fP
Select users quotas based on the username.
See \fBINCLUDE AND EXCLUDE LISTS\fP in
.Xr ncollectd.conf 5 .
.It \fBreport-by-user-name\fP \fItrue|false\fP
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
