.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-WIRELESS 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-wireless
.Nd Documentation of ncollectd's wireless plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP wireless
\fBplugin\fP wireless
.Ed
.Sh DESCRIPTION
The \fBwireless\fP plugin collectd statistics of the signal
in wireless interfaces.
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
