.\" SPDX-License-Identifier: GPL-2.0-only
.TH ncollectd-wireless 5 "@NCOLLECTD_DATE@" "@NCOLLECTD_VERSION@" "ncollectd wireless man page"
.SH NAME
ncollectd-wireless \- Documentation of ncollectd's wireless plugin
.SH SYNOPSIS
\fBload-plugin\fP wireless
.SH DESCRIPTION
The \fBwireless\fP plugin collectd statistics of the signal in wireless interfaces.
.SH "SEE ALSO"
.BR ncollectd (1)
.BR ncollectd.conf (5)
