.\" SPDX-License-Identifier: GPL-2.0-only
.TH ncollectd-vmem 5 "@NCOLLECTD_DATE@" "@NCOLLECTD_VERSION@" "ncollectd vmem man page"
.SH NAME
ncollectd-vmem \- Documentation of ncollectd's vmem plugin
.SH SYNOPSIS
\fBload-plugin\fP vmem
.br
\fBplugin\fP vmem
.SH DESCRIPTION
The \fBvmem\fP plugin collects information about the usage of virtual memory.
.SH "SEE ALSO"
.BR ncollectd (1)
.BR ncollectd.conf (5)
