.\" SPDX-License-Identifier: GPL-2.0-only
.TH ncollectd-tail 5 "@NCOLLECTD_DATE@" "@NCOLLECTD_VERSION@" "ncollectd tail man page"
.SH NAME
ncollectd-tail \- Documentation of ncollectd's tail plugin
.SH SYNOPSIS
\fBload-plugin\fP tail
.br
\fBplugin\fP tail {
    \fBfile\fP \fIfilename\fP {
        \fBinterval\fP \fIseconds\fP
        \fBmatch\fP \fImatch\fP {
            ...
        }
        \fBfilter\fP {
            ...
        }
    }
.br
}
.SH DESCRIPTION
The \fBtail\fP plugin reads files and process the lines using a match plugin.

The configuration consists of one or more \fBfile\fP blocks that define a
\fBfilename\fB to read a match plugin to process the lines.

The \fBfile\fP block has the following options:
.TP
\fBinterval\fP \fIseconds\fP
Configures the interval in which to read lines from this file.
Defaults to the plugin's default interval.
.TP
\fBmatch\fP \fImatch\fP
Configure the \fImatch\fP plugin to process the lines of the file.
.TP
\fBfilter\fP
Configure a filter to modify or drop the metrics. See \fBFILTER CONFIGURATION\fP in
.BR ncollectd.conf(5)
.SH "SEE ALSO"
.BR ncollectd (1)
.BR ncollectd.conf (5)
