.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-WLM 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-wlm
.Nd Documentation of ncollectd's wlm plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP wlm
\fBplugin\fP wlm {
    \fBclass\fP [\fIincl|include|excl|exclude\fP] \fIname\fP
}
.Ed
.Sh DESCRIPTION
The \fBwlm\fP plugin reads statistics from the \fIWorkload Manager\fP.
.Pp
The following configuration options are available:
.Bl -tag -width Ds
.It \fBclass\fP [\fIincl|include|excl|exclude\fP] \fIname\fP
Select worload manager class based on the class name.
See \fBINCLUDE AND EXCLUDE LISTS\fP in
.Xr ncollectd.conf 5 .
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
