.\" SPDX-License-Identifier: GPL-2.0-only
.TH ncollectd-apache 5 "@NCOLLECTD_DATE@" "@NCOLLECTD_VERSION@" "ncollectd apache man page"
.SH NAME
ncollectd-apache \- Documentation of ncollectd's apache plugin
.SH SYNOPSIS
\fBload-plugin\fP apache
.br
\fBplugin\fP apache {
    \fBinstance\fP "\fIhost\fP" {
        \fBurl\fP "\fIhttp://host/mod_status?auto\fP"
        \fBuser\fP "\fIusername\fP"
        \fBpassword\fP "\fIpassword\fP"
        \fBverify-peer\fP \fItrue|false\fP
        \fBverify-host\fP \fItrue|false\fP
        \fBca-cert\fP "\fIfile\fP"
        \fBssl-ciphers\fP "\fIlist of ciphers\fP"
        \fBtimeout\fP \fIseconds\fP
        \fBlabel\fP "\fIkey\fP" "\fIvalue\fP"
        \fBinterval\fP \fIseconds\fP
    }
.br
}
.SH DESCRIPTION
To configure the \fBapache\fP plugin you first need to configure the Apache
webserver correctly. The Apache-plugin \fImod_status needs\fP to be loaded and
working and the \f(CBExtendedStatus\fP directive needs to be \fBenabled\fP. You can use
the following snipped to base your Apache config upon:
.PP
.EX
ExtendedStatus on
<IfModule mod_status.c>
    <Location /mod_status>
        SetHandler server-status
    </Location>
</IfModule>
.EE
.PP
Since its \fBmod_status\fP module is very similar to Apache's, \fBlighttpd\fP is
also supported. It introduces a new field, called \fIBusyServers\fP, to count the
number of currently connected clients. This field is also supported.
.PP
The configuration of the \fBapache\fP plugin consists of one or more
\fBinstance\fP blocks. Each block requires one string argument
as the instance name. For example:
.PP
.EX
plugin "apache" {
    instance "www1" {
        url "http://www1.example.com/mod_status?auto"
    }
    instance "www2" {
        url "http://www2.example.com/mod_status?auto"
    }
}
.EE
.PP
The instance name will be used as \fIinstance\fP label in the metrics.
In order for the plugin to work correctly, each instance name must be unique.
This is not enforced by the plugin and it is your responsibility to ensure it.
.PP
The following options are accepted within each \fBinstance\fP block:
.PP
.TP
\fBurl\fP \fIhttp://host/mod_status?auto\fP
Sets the URL of the \fImod_status\fP output. This needs to be the output generated
by \fBExtendedStatus on\fP and it needs to be the machine readable output
generated by appending the \fI?auto\fP argument. This option is \fImandatory\fP.
.TP
\fBuser\fP \fIusername\fP
Optional user name needed for authentication.
.TP
\fBpassword\fP \fIpassword\fP
Optional password needed for authentication.
.TP
\fBverify\-peer\fP \fBtrue|false\fP
Enable or disable peer SSL certificate verification. See
.UR http://curl.haxx.se/docs/sslcerts.html
.UE
for details. Enabled by default.
.TP
\fBverify-host\fP \fItrue|false\fP
Enable or disable peer host name verification. If enabled, the plugin checks
if the \fICommon Name\fP or a \fISubject Alternate Name\fP field of the SSL
certificate matches the host name provided by the \fBURL\fP option. If this
identity check fails, the connection is aborted. Obviously, only works when
connecting to a SSL enabled server. Enabled by default.
.TP
\fBca-cert\fP \fIfile\fP
File that holds one or more SSL certificates. If you want to use HTTPS you will
possibly need this option. What CA certificates come bundled with \fIlibcurl\fP
and are checked by default depends on the distribution you use.
.TP
\fBssl-ciphers\fP \fIlist of ciphers\fP
Specifies which ciphers to use in the connection. The list of ciphers
must specify valid ciphers. See
.UR http://www.openssl.org/docs/apps/ciphers.html
.UE
for details.
.TP
\fBtimeout\fP \fIseconds\fP
The \fBtimeout\fP option sets the overall timeout for HTTP requests to \fBURL\fP, in
seconds. By default, the configured \fBinterval\fP is used to set the timeout.
.TP
\fBlabel\fP \fIkey\fP \fIvalue\fP
Append the label \fIkey\fP=\fIvalue\fP to the submitting metrics.
.TP
\fBinterval\fP \fIseconds\fP
Sets the interval (in seconds) in which the values will be collected from this
URL. By default the global \fBinterval\fP setting will be used.
.SH "SEE ALSO"
.BR ncollectd (1)
.BR ncollectd.conf (5)
