.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-SSSD 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-sssd
.Nd Documentation of ncollectd's sssd plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP sssd
\fBplugin\fP sssd
.Ed
.Sh DESCRIPTION
The \fBsssd\fP plugin collects information from SSSD daemon.
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
