.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-MD 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-md
.Nd Documentation of ncollectd's md plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP md
\fBplugin\fP md {
    \fBdevice\fP [\fIincl|include|excl|exclude\fP] \fIdevice-name\fP
}
.Ed
.Sh DESCRIPTION
The \fBmd\fP plugin reports the number of disks in various states in Linux
software RAID devices.
.Pp
The plugin support the following option:
.Bl -tag -width Ds
.It \fBdevice\fP [\fIincl|include|excl|exclude\fP] \fIdevice-name\fP
Select md devices based on device name.
The \fIdevice-name\fP is the basename of the device, i. e. the name of
the block device without the leading \f(CW/dev/\fP.
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
