=encoding UTF-8

=head1 NAME

ncollectd-md - Documentation of ncollectd's C<Md plugin>

=head2 Plugin C<md>

The C<md plugin> collects information from Linux Software-RAID devices (md).

All reported values are of the type C<md_disks>. Reported type instances are
I<active>, I<failed> (present but not operational), I<spare> (hot stand-by) and
I<missing> (physically absent) disks.

=over 4

=item B<Device> I<Device>

Select md devices based on device name. The I<device name> is the basename of
the device, i.e. the name of the block device without the leading C</dev/>.
See B<IgnoreSelected> for more details.

See F</"IGNORELISTS"> for details.

=item B<IgnoreSelected> B<true>|B<false>

Invert device selection: If set to B<true>, all md devices B<except> those
listed using B<Device> are collected. If B<false> (the default), only those
listed are collected. If no configuration is given, the B<md> plugin will
collect data from all md devices.

=back

=head1 SEE ALSO

L<collectd(1)>,
L<collectd.conf(5)>

=cut
