/* SPDX-License-Identifier: GPL-2.0-only                             */
/* SPDX-FileCopyrightText: Copyright (C) 2022-2024 Manuel Sanmartín  */
/* SPDX-FileContributor: Manuel Sanmartín <manuel.luis at gmail.com> */

#pragma once

enum {
    FAM_INTERFACE_STATE_UP,
    FAM_INTERFACE_ADMIN_STATE_UP,
    FAM_INTERFACE_CARRIER,
    FAM_INTERFACE_CARRIER_UP,
    FAM_INTERFACE_CARRIER_DOWN,

    FAM_INTERFACE_RX_PACKETS,
    FAM_INTERFACE_RX_BYTES,
    FAM_INTERFACE_RX_DROPPED,
    FAM_INTERFACE_RX_ERRORS,
    FAM_INTERFACE_RX_NOHANDLER,
    FAM_INTERFACE_RX_COMPRESSED,

    FAM_INTERFACE_RX_LENGTH_ERRORS,
    FAM_INTERFACE_RX_OVER_ERRORS,
    FAM_INTERFACE_RX_CRC_ERRORS,
    FAM_INTERFACE_RX_FRAME_ERRORS,
    FAM_INTERFACE_RX_FIFO_ERRORS,
    FAM_INTERFACE_RX_MISSED_ERRORS,

    FAM_INTERFACE_TX_PACKETS,
    FAM_INTERFACE_TX_BYTES,
    FAM_INTERFACE_TX_DROPPED,
    FAM_INTERFACE_TX_ERRORS,
    FAM_INTERFACE_TX_COMPRESSED,

    FAM_INTERFACE_TX_ABORTED_ERRORS,
    FAM_INTERFACE_TX_CARRIER_ERRORS,
    FAM_INTERFACE_TX_FIFO_ERRORS,
    FAM_INTERFACE_TX_HEARTBEAT_ERRORS,
    FAM_INTERFACE_TX_WINDOW_ERRORS,

    FAM_INTERFACE_MULTICAST,
    FAM_INTERFACE_COLLISIONS,

    FAM_INTERFACE_VF_LINK_VLAN,
    FAM_INTERFACE_VF_LINK_QOS,
    FAM_INTERFACE_VF_LINK_SPOOFCHECK,
    FAM_INTERFACE_VF_LINK_STATE,
    FAM_INTERFACE_VF_LINK_TXRATE,
    FAM_INTERFACE_VF_LINK_MIN_TXRATE,
    FAM_INTERFACE_VF_LINK_MAX_TXRATE,
    FAM_INTERFACE_VF_LINK_RSS_QUERY_EN,
    FAM_INTERFACE_VF_LINK_TRUST,
    FAM_INTERFACE_VF_RX_PACKETS,
    FAM_INTERFACE_VF_TX_PACKETS,
    FAM_INTERFACE_VF_RX_BYTES,
    FAM_INTERFACE_VF_TX_BYTES,
    FAM_INTERFACE_VF_BROADCAST,
    FAM_INTERFACE_VF_MULTICAST,
    FAM_INTERFACE_VF_RX_DROPPED,
    FAM_INTERFACE_VF_TX_DROPPED,

    FAM_INTERFACE_MAX,
};
