.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-CONTEXTSWITCH 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-contextswitch
.Nd Documentation of ncollectd's contextswitch plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP contextswitch
\fBplugin\fP contextswitch
.Ed
.Sh DESCRIPTION
The \fBcontextswitch\fP plugin collects the number of context switches
that occur in the system.
.Pp
A context switch is described as the kernel suspending execution of one
process on the CPU and resuming execution of some other process that had
previously been suspended.
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
