.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-DCPMM 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-dcpmm
.Nd Documentation of ncollectd's dcpmm plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP dcpmm
\fBplugin\fP dcpmm
.Ed
.Sh DESCRIPTION
The \fBdcpmm\fP plugin will collect Intel(R) Optane(TM) DC Persistent Memory
related performance statistics.
The plugin requires root privileges to perform the statistics collection.
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
