.\" SPDX-License-Identifier: GPL-2.0-only
.TH ncollectd-dcpmm 5 "@NCOLLECTD_DATE@" "@NCOLLECTD_VERSION@" "ncollectd dcpmm man page"
.SH NAME
ncollectd-dcpmm \- Documentation of ncollectd's dcpmm plugin
.SH SYNOPSIS
\fBload-plugin\fP dcpmm
.SH DESCRIPTION
The \fBdcpmm\fP plugin will collect Intel(R) Optane(TM) DC Persistent Memory related performance
statistics. The plugin requires root privileges to perform the statistics collection.
.SH "SEE ALSO"
.BR ncollectd (1)
.BR ncollectd.conf (5)
