.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-GPU_NVIDIA 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-gpu_nvidia
.Nd Documentation of ncollectd's gpu_nvidia plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP gpu_nvidia
\fBplugin\fP gpu_nvidia {
    \fBgpu-index\fP \fIindex\fP
    \fBignore-gpu-selected\fP \fItrue|false\fP
}
.Ed
.Sh DESCRIPTION
The \fBgpu_nvidia\fP plugin efficiently collects various statistics from the
system's NVIDIA GPUs using the NVML library.
Currently collected are fan speed, core temperature, percent load, percent
memory used, compute and memory frequencies, and power consumption.
.Bl -tag -width Ds
.It \fBgpu-index\fP \fIindex\fP
If one or more of these options is specified, only GPUs at that index (as
determined by nvidia-utils through \fInvidia-smi\fP) have statistics collected.
If no instance of this option is specified, all GPUs are monitored.
.It \fBignore-gpu-selected\fP \fItrue|false\fP
If set to \fBtrue\fP, all detected GPUs \fBexcept\fP the ones at indices
specified by \fBgpu-index\fP entries are collected.
For greater clarity, setting \fBignore-gpu-selected\fP without any
\fBgpu-index\fP directives will result in \fBno\fP statistics being collected.
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
