.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-WRITE_FILE 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-write_file
.Nd Documentation of ncollectd's write_file plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP write_file
\fBplugin\fP write_file {
    \fBinstance\fP \fIname\fP {
        \fBformat-metric\fP \fIinfluxdb|graphite|json|kairosdb|opentsdb|openmetrics|opentelemetry|remote\fP
        \fBformat-notification\fP \fItext|json|protob\fP
        \fBwrite\fP \fImetrics|notifications\fP
        \fBfile\fP "\fIfile-name\fP"
    }
}
.Ed
.Sh DESCRIPTION
The \fBwrite_file\fP plugin writes the metrics to a file.
.Pp
The plugin has the following options:
.Bl -tag -width Ds
.It .Bl -tag -width Ds
\fBformat-metric\fP \fIinfluxdb|graphite|json|kairosdb|opentsdb|openmetrics|remote\fP
Selects the format in which metrics are written.
.Bl -tag -width Ds
.It \fBinfluxdb\fP [\fIsec|msec|usec|nsec\fP]
Format the metrics with the influxdb line format.
.It \fBgraphite\fP
Format the metrics with the graphite plaintext format.
.It \fBjson\fP
Format the metrics as json message.
.It \fBkairosdb\fP [\fItelnet [sec|msec]|json\fP]
Format the metrics with the karirosdb text format or json format.
.It \fBopentsdb\fP [telnet|json]
Format the metrics with the opentsdb text format or json format.
.It \fBopenmetrics\fP [text|protob]
Format the metrics with the openmetrics text format.
.It \fBopentelemetry\fP [json]
Format the metrics with the opentelemetry json format.
.It \fBremote\fP [metadata]
Format the metrics with the protocol buffer remote format.
.El
.It \fBformat-notification\fP \fItext|json|protob\fP
Selects the format in which notifications are written.
.It \fBwrite\fP \fImetrics|notifications\fP
If set to \fImetrics\fP (the default) the plugin will handle metrics.
If set to \fInotifications\fP the plugin will handle notifications.
.It \fBfile\fP "\fIfile-name\fP"
If the filename is \fIstderr\fP the metrics are send to standard error,
if the filename is \fIstdout\fP the metrics are send to standard output.
If the option \fBfile\fP is not set the metrics are send to the standard output.
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
