.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-MATCH_JSONPATH 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-match_jsonpath
.Nd Documentation of ncollectd's jsonpath match plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBmatch\fP jsonpath {
    \fBmetric-prefix\fP \fIprefix\fP
    \fBlabel\fP \fIkey\fP \fIvalue\fP
    \fBmetric\fP {
        \fBpath\fP \fIpath\fP
        \fBmetric-prefix\fP \fIprefix\fP
        \fBmetric\fP \fImetric\fP
        \fBmetric-path\fP \fIpath\fP
        \fBmetric-root-path\fP \fIpath\fP
        \fBtype\fP \fIgauge\fP [\fIaverage|min|max|last|inc|add|persist\fP]|\fIcounter\fP [\fIset|add|inc\fP]
        \fBhelp\fP \fIhelp\fP
        \fBhelp-path\fP \fIpath\fP
        \fBhelp-root-path\fP \fIpath\fP
        \fBlabel\fP \fIkey\fP \fIvalue\fP
        \fBlabel-path\fP \fIkey\fP \fIpath\fP
        \fBlabel-root-path\fP \fIkey\fP \fIpath\fP
        \fBvalue-path\fP \fIpath\fP
        \fBvalue-root-path\fP \fIpath\fP
        \fBtime-path\fP \fIpath\fP
        \fBtime-root-path\fP \fIpath\fP
    }
}
.Ed
.Sh DESCRIPTION
The \fBmatch_jsonpath\fP plugin parse text in json format using jsonpath
selectors.
.Bl -tag -width Ds
.It \fBmetric-prefix\fP \fIprefix\fP
Prepend the \fIprefix\fP to the metrics found in the \fBmetric\fP blocks.
.It \fBlabel\fP \fIkey\fP \fIvalue\fP
Append the label \fIkey\fP=\fIvalue\fP to the submitting metrics.
.It \fBmetric\fP
.Bl -tag -width Ds
.It \fBpath\fP \fIpath\fP
Use the jsonpath selector \fIpath\fP to extract metrics.
.It \fBmetric-prefix\fP \fIprefix\fP
Prepend the \fIprefix\fP to the metrics found.
.It \fBmetric\fP \fImetric\fP
Set the metric name.
.It \fBmetric-path\fP \fIpath\fP
Set metric value from the jsonpath selector \fIpath\fP in the current node.
.It \fBmetric-root-path\fP \fIpath\fP
Set metric value from the jsonpath selector \fIpath\fP in the root node.
.It \fBtype\fP \fIgauge\fP [\fIaverage|min|max|last|inc|add|persist\fP]|\fIcounter\fP [\fIset|add|inc\fP]
.Bl -tag -width Ds
.It \fBgauge\fP
The value is a gauge, you must specify also the type of the gauge:
.Bl -tag -width Ds
.It \fBaverage\fP
Calculate the average
.It \fBmin\fP
Use the smallest number only.
.It \fBmax\fP
Use the greatest number only.
.It \fBlast\fP
Use the last number found.
.It \fBinc\fP
Increase the internal counter by one.
.It \fBadd\fP
Add the matched value to the internal counter.
.It \fBpersist\fP
Use the last number found.
The number is not reset at the end of an interval.
It is continously reported until another number is matched.
.El
.It \fBcounter\fP
The value is a counter, you must specify also the type of the counter:
.Bl -tag -width Ds
.It \fBset\fP
Simply sets the internal counter to this value.
.It \fBadd\fP
Add the matched value to the internal counter.
.It \fBinc\fP
Increase the internal counter by one.
.El
.El
.It \fBhelp\fP \fIhelp\fP
Set metric help.
.It \fBhelp-path\fP \fIpath\fP
Set metric help from the jsonpath selector \fIpath\fP in the current node.
.It \fBhelp-root-path\fP \fIpath\fP
Set metric help from the jsonpath selector \fIpath\fP in the root node.
.It \fBlabel\fP \fIkey\fP \fIvalue\fP
Append the label \fIkey\fP=\fIvalue\fP to the submitting metrics.
.It \fBlabel-path\fP \fIkey\fP \fIpath\fP
Set the label \fIkey\fP with the value from the jsonpath selector \fIpath\fP
in the current node.
.It \fBlabel-root-path\fP \fIkey\fP \fIpath\fP
Set the label \fIkey\fP with the value from the jsonpath selector \fIpath\fP
in the root node.
.It \fBvalue-path\fP \fIpath\fP
Set metric value from the jsonpath selector \fIpath\fP in the current node.
.It \fBvalue-root-path\fP \fIpath\fP
Set metric value from the jsonpath selector \fIpath\fP in the root node.
.It \fBtime-path\fP \fIpath\fP
Set metric timestamp in seconds from the jsonpath selector \fIpath\fP
in the current node.
.It \fBtime-root-path\fP \fIpath\fP
Set metric timestamp in seconds from the jsonpath selector \fIpath\fP
in the root node.
.El
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
