=encoding UTF-8

=head1 NAME

ncollectd-hugepages - Documentation of ncollectd's C<hugepages plugin>

=head2 Plugin C<hugepages>

To collect B<hugepages> information, ncollectd reads directories
"/sys/devices/system/node/*/hugepages" and "/sys/kernel/mm/hugepages".
Reading of these directories can be disabled by the following
options (default is enabled).

=over 4

=item B<ReportPerNodeHP> B<true>|B<false>

If enabled, information will be collected from the hugepage
counters in "/sys/devices/system/node/*/hugepages".
This is used to check the per-node hugepage statistics on
a NUMA system.

=item B<ReportRootHP> B<true>|B<false>

If enabled, information will be collected from the hugepage
counters in "/sys/kernel/mm/hugepages".
This can be used on both NUMA and non-NUMA systems to check
the overall hugepage statistics.

=item B<ValuesPages> B<true>|B<false>

Whether to report hugepages metrics in number of pages.
Defaults to B<true>.

=item B<ValuesBytes> B<false>|B<true>

Whether to report hugepages metrics in bytes.
Defaults to B<false>.

=back

=head1 SEE ALSO

L<ncollectd(1)>,
L<ncollectd.conf(5)>

=cut

