.\" SPDX-License-Identifier: GPL-2.0-only
.TH ncollectd-write_kafka 5 "@NCOLLECTD_DATE@" "@NCOLLECTD_VERSION@" "ncollectd write_kafka man page"
.SH NAME
ncollectd-write_kafka \- Documentation of ncollectd's write_kafka plugin
.SH SYNOPSIS
\fBload-plugin\fP write_kafka
.br
\fBplugin\fP write_kafka {
    \fBinstance\fP \fIname\fP {
        \fBtopic\fP \fItopic\fP
        \fBproperty\fP \fIkey\fP \fIvalue\fP
        \fBkey\fP \fIkey\fP
        \fBformat-metric\fP \fIinfluxdb|graphite|json|kairosdb|opentsdb|openmetrics|remote\fP
        \fBformat-notification\fP \fItext|json|protob\fP
        \fBwrite\fP \fImetrics|notifications\fP
    }
.br
}
.SH DESCRIPTION
The \fBwrite_kafka\fP plugin send metric and notifications to a \fIKafka\fP topic, a distributed
queue.
.PP
The plugin's configuration consists of one or more \fBinstance\fP blocks. Each block
is given a unique \fIname\fP and specifies one kafka producer.
.PP
Inside the \fBinstance\fP block, the following options are understood:
.PP
.TP
\fBtopic\fP \fItopic\fP
Set the topic to send messages.
.TP
\fBproperty\fP \fIkey\fP \fIvalue\fP
Configure the kafka producer through properties, you almost always will
want to set \fBmetadata.broker.list\fP to your Kafka broker list.
.TP
\fBkey\fP \fIkey\fP
Use the specified string as a partitioning key for the topic. Kafka breaks
topic into partitions and guarantees that for a given topology, the same
consumer will be used for a specific key. The special (case insensitive)
string \fBrandom\fP can be used to specify that an arbitrary partition should
be used.
.TP
\fBformat-metric\fP \fIinfluxdb|graphite|json|kairosdb|opentsdb|openmetrics|remote\fP
Selects the format in which metrics are written.
.RS
.TP
\fBinfluxdb\fP [\fIsec|msec|usec|nsec\fP]
Format the metrics with the influxdb line format.
.TP
\fBgraphite\fP
Format the metrics with the graphite plaintext format.
.TP
\fBjson\fP
Format the metrics as json message.
.TP
\fBkairosdb\fP [\fItelnet [sec|msec]|json\fP]
Format the metrics with the karirosdb text format or json format.
.TP
\fBopentsdb\fP [telnet|json]
Format the metrics with the opentsdb text format or json format.
.TP
\fBopenmetrics\fP [text|protob]
Format the metrics with the openmetrics text formar.
.TP
\fBremote\fP [metadata]
Format the metrics with the protocol buffer remote format.
.RE
.TP
\fBformat-notification\fP \fItext|json|protob\fP
Selects the format in which notifications are written.
.TP
\fBwrite\fP \fImetrics|notifications\fP
If set to \fImetrics\fP (the default) the plugin will handle metrics.
If set to \fInotifications\fP the plugin will handle notifications.
.SH "SEE ALSO"
.BR ncollectd (1)
.BR ncollectd.conf (5)
