.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-LOG_GELF 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-log_gelf
.Nd Documentation of ncollectd's log_gelf plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP log_gelf
\fBplugin\fP log_gelf {
    \fBinstance\fP \fIname\fP {
        \fBlog-level\fP \fIdebug|info|notice|warning|err\fP
        \fBhost\fP \fIhost\fP
        \fBport\fP \fIport\fP
        \fBpacket-size\fP \fIsize\fP
        \fBttl\fP \fIttl\fP
        \fBcompress\fP \fItrue|false\fP
    }
}
.Ed
.Sh DESCRIPTION
The \fBlog_gelf\fP plugin receives log messages from the daemon and send
them in the Graylog Extended Log Format (GELF) via UDP.
.Pp
The plugin has de following options:
.Bl -tag -width Ds
.It \fBlog-level\fP \fIdebug|info|notice|warning|err\fP
Sets the log-level.
If, for example, set to \fBnotice\fP, then all events with severity
\fBnotice\fP, \fBwarning\fP, or \fBerr\fP will be written
to the logfile.
.Pp
Please note that \fBdebug\fP is only available if ncollectd has been compiled
with debugging support.
.It \fBhost\fP \fIhost\fP
Set the destination address to send the metrics.
Default to localhost.
.It \fBport\fP \fIport\fP
Set the destination port.
The default port is 12201.
.It \fBpacket-size\fP \fIsize\fP
Set maximum packet size in bytes.
Default to 1420 bytes.
.It \fBttl\fP \fIttl\fP
Set the IP packet TTL.
Default to 255.
.It \fBcompress\fP \fItrue|false\fP
If the the playload is compressed.
Default to true.
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
