.\" SPDX-License-Identifier: GPL-2.0-only
.TH ncollectd-zfs 5 "@NCOLLECTD_DATE@" "@NCOLLECTD_VERSION@" "ncollectd zfs man page"
.SH NAME
ncollectd-zfs \- Documentation of ncollectd's zfs plugin
.SH SYNOPSIS
\fBload-plugin\fP zfs
.SH DESCRIPTION
The \fBzfs\fP plugin collects information about the Adaptive Replacement Cache (ARC)
of the Zeta File-System (ZFS). It reports information such as the cache size, the various
hits and misses and the transferred data.
.SH "SEE ALSO"
.BR ncollectd (1)
.BR ncollectd.conf (5)
