.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-DNS 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-dns
.Nd Documentation of ncollectd's dns plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP dns
\fBplugin\fP dns {
    \fBinstance\fP \fIinstance\fP {
        \fBserver\fP \fIserver\fP
        \fBdomain\fP \fIdomain\fP
        \fBudp-port\fP \fIport\fP
        \fBtcp-port\fP \fIport\fP
        \fBuse-vc\fP \fItrue|false\fP
        \fBuse-tcp\fP \fItrue|false\fP
        \fBprimary\fP \fItrue|false\fP
        \fBignore-truncated\fP \fItrue|false\fP
        \fBrecurse\fP \fItrue|false\fP
        \fBsearch\fP \fItrue|false\fP
        \fBaliases\fP \fItrue|false\fP
        \fBedns\fP \fItrue|false\fP
        \fBedns-size\fP \fIsize\fP
        \fBresolvconf-path\fP \fIpath-to-resolv.conf\fP
        \fBtimeout\fP \fIseconds\fP
        \fBtries\fP \fItries\fP
        \fBndots\fP \fIndots\fP
        \fBrotate\fP \fItrue|false\fP
        \fBlabel\fP \fIkey\fP \fIvalue\fP
        \fBinterval\fP \fIseconds\fP
        \fBquery\fP \fIquery\fP {
            \fBclass\fP \fIIN|CHAOS|HS|ANY\fP
            \fBtype\fP \fIA|AAAA|NS|MX|...\fP
            \fBconvert-ptr\fP \fItrue|false\fP
            \fBconvert-ptr-bit-string\fP \fItrue|false\fP
            \fBlabel\fP \fIkey\fP \fIvalue\fP
            \fBvalidate\fP \fIexpression\fP
        }
        \fBfilter\fP {
            ...
        }
    }
}
.Ed
.Sh DESCRIPTION
The \fBdns\fP plugin generate metrics with dns queries.
.Pp
The following options are accepted within each \fBinstance\fP block:
.Bl -tag -width Ds
.It \fBserver\fP \fIserver\fP
The servers to contact, instead of the servers specified in resolv.conf
or the local named.
.It \fBdomain\fP \fIdomain\fP
The domains to search, instead of the domains specified in resolv.conf
or the domain derived from the kernel hostname variable.
.It \fBudp-port\fP \fIport\fP
The port to use for queries over UDP, in network byte order.
The default value is 53, the standard name service port.
.It \fBtcp-port\fP \fIport\fP
The port to use for queries over TCP, in network byte order.
The default value is 53, the standard name service port.
.It \fBuse-vc\fP \fItrue|false\fP
.It \fBuse-tcp\fP \fItrue|false\fP
Always use TCP queries (the "virtual circuit") instead of UDP queries.
Normally, TCP is only used if a UDP query yields a truncated result.
.It \fBprimary\fP \fItrue|false\fP
Only query the first server in the list of servers to query.
.It \fBignore-truncated\fP \fItrue|false\fP
If a truncated response to a UDP query is received, do not fall back to TCP;
simply continue on with the truncated response.
.It \fBrecurse\fP \fItrue|false\fP
If false do not set the "recursion desired" bit on outgoing queries,
so that the name server being contacted will not try to fetch the answer
from other servers if it doesn't know the answer locally.
Default is true.
.It \fBsearch\fP \fItrue|false\fP
If false do not use the default search domains; only query hostnames as-is or
as aliases.
Default is true.
.It \fBaliases\fP \fItrue|false\fP
If false do not honor the HOSTALIASES environment variable, which normally
specifies a file of hostname translations.
Default is true.
.It \fBedns\fP \fItrue|false\fP
Include an EDNS pseudo-resource record (RFC 2671) in generated requests.
.It \fBedns-size\fP \fIsize\fP
The message size to be advertised in EDNS.
.It \fBresolvconf-path\fP \fIpath-to-resolv.conf\fP
The path to use for reading the resolv.conf file.
The default is /etc/resolv.conf
.It \fBtimeout\fP \fIseconds\fP
The number of seconds (with a resolution of milliseconds) each name server is
given to respond to a query on the first try.
(After the first try, the timeout algorithm becomes more complicated,
but scales linearly with the value of timeout.)
The default is five seconds.
.It \fBtries\fP \fItries\fP
The number of tries the resolver will try contacting each name server before
giving up.
The default is four tries.
.It \fBndots\fP \fIndots\fP
The number of dots which must be present in a domain name for it to be
queried for "as is" prior to querying for it with the default domain
extensions appended.
The default value is 1 unless set otherwise by resolv.conf or the RES_OPTIONS
environment variable.
.It \fBrotate\fP \fItrue|false\fP
If true perform round-robin selection of the nameservers configured for
each resolution, if false always use the list of nameservers in the same order.
.It \fBlabel\fP \fIkey\fP \fIvalue\fP
Append the label \fIkey\fP=\fIvalue\fP to the submitting metrics.
Can appear multiple time in the \fBinstance\fP block.
.It \fBinterval\fP \fIseconds\fP
Sets the interval (in seconds) in which the values will be collected from this
instanced.
By default the global \fBinterval\fP setting will be used.
.It \fBquery\fP \fIquery\fP
.Bl -tag -width Ds
.It \fBclass\fP \fIIN|CHAOS|HS|ANY\fP
IN CHAOS HS ANY
.It \fBtype\fP \fIA|AAAA|NS|MX|...\fP
A NS MD MF CNAME SOA MB MG MR NULL WKS PTR HINFO MINFO MX TXT RP AFSDB X25
ISDN RT NSAP NSAP_PTR SIG KEY PX GPOS AAAA LOC SRV AXFR MAILB MAILA NAPTR
DS SSHFP RRSIG NSEC DNSKEY CAA URI ANY
.It \fBconvert-ptr\fP \fItrue|false\fP
.It \fBconvert-ptr-bit-string\fP \fItrue|false\fP
.It \fBlabel\fP \fIkey\fP \fIvalue\fP
.It \fBvalidate\fP \fIexpression\fP
.Bl -tag -width Ds
.It \fBresponse.id\fP
.It \fBresponse.flags.qr\fP
.It \fBresponse.flags.aa\fP
.It \fBresponse.flags.tc\fP
.It \fBresponse.flags.rd\fP
.It \fBresponse.flags.ra\fP
.It \fBresponse.rtime\fP
.It \fBresponse.rcode\fP
.It \fBresponse.opcode\fP
.It \fBresponse.query.length\fP
.Bl -tag -width Ds
.It \fBname\fP
.It \fBtype\fP
.It \fBclass\fP
.El
.It \fBresponse.answer.length\fP
.It \fBresponse.authority.length\fP
.It \fBresponse.additional.length\fP
.Bl -tag -width Ds
.It \fBname\fP
.It \fBtype\fP
.It \fBclass\fP
.It \fBttl\fP
.It \fBcname.name\fP
.It \fBmb.name\fP
.It \fBmd.name\fP
.It \fBmf.name\fP
.It \fBmg.name\fP
.It \fBmr.name\fP
.It \fBns.name\fP
.It \fBptr.name\fP
.It \fBhinfo.hardware\fP
.It \fBhinfo.os\fP
.It \fBminfo.mailbox\fP
.It \fBminfo.error_mailbox\fP
.It \fBmx.priority\fP
.It \fBmx.mailserver\fP
.It \fBsoa.master\fP
.It \fBsoa.responsible\fP
.It \fBsoa.serial\fP
.It \fBsoa.refresh_interval\fP
.It \fBsoa.retry_interval\fP
.It \fBsoa.expire\fP
.It \fBsoa.negative_caching_ttl\fP
.It \fBtxt.\fP
.It \fBcaa.\fP
.It \fBa.address\fP
.It \fBaaaa.address\fP
.It \fBsrv.priority\fP
.It \fBsrv.weight\fP
.It \fBsrv.port\fP
.It \fBsrv.target\fP
.It \fBuri.priority\fP
.It \fBuri.weight\fP
.It \fBuri.target\fP
.It \fBnaptr.order\fP
.It \fBnaptr.preference\fP
.It \fBnaptr.flags\fP
.It \fBnaptr.service\fP
.It \fBnaptr.regex\fP
.It \fBnaptr.replacement\fP
.El
.El
.El
.It \fBfilter\fP
Configure a filter to modify or drop the metrics.
See \fBFILTER CONFIGURATION\fP in
.Xr ncollectd.conf 5 .
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
