.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-OLSRD 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-olsrd
.Nd Documentation of ncollectd's olsrd plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP olsrd
\fBplugin\fP olsrd {
    \fBinstance\fP \fIinstance\fP {
        \fBhost\fP \fIhostname\fP
        \fBport\fP \fIport\fP
        \fBinterval\fP \fIseconds\fP
        \fBlabel\fP \fIkey\fP \fIvalue\fP
        \fBfilter\fP {
            ...
        }
    }
}
.Ed
.Sh DESCRIPTION
The \fBolsrd\fP plugin connects to the TCP port opened by
the \fItxtinfo\fP plugin of the Optimized Link State Routing daemon
and reads information about the current state of the meshed network.
.Pp
The following configuration options are understood:
.Bl -tag -width Ds
.It \fBhost\fP \fIhostname\fP
Connect to \fIhost\fP.
Defaults to \fBlocalhost\fP.
.It \fBport\fP \fIport\fP
Specifies the port to connect to.
This must be a string, even if you give the port as a number rather than
a service name.
Defaults to \f(CW2006\fP.
.It \fBinterval\fP \fIseconds\fP
Sets the interval (in seconds) in which the values will be collected
from this instance.
.It \fBlabel\fP \fIkey\fP \fIvalue\fP
Append the label \fIkey\fP=\fIvalue\fP to the submitting metrics.
.It \fBfilter\fP
Configure a filter to modify or drop the metrics.
See \fBFILTER CONFIGURATION\fP in
.Xr ncollectd.conf 5 .
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
