.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-UNBOUND 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-unbound
.Nd Documentation of ncollectd's unbound plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP unbound
\fBplugin\fP unbound {
    \fBinstance\fP \fIname\fP {
        \fBhost\fP \fIhost\fP
        \fBport\fP \fIport\fP
        \fBlabel\fP \fIkey\fP \fIvalue\fP
        \fBinterval\fP \fIseconds\fP
        \fBfilter\fP {
            ...
        }
    }
}
.Ed
.Sh DESCRIPTION
The \fBunbound\fP plugin collect metrics from the Unbound resolver.
.Pp
The configuration consists of one or more \fBinstance\fP blocks:
.Bl -tag -width Ds
.It \fBhost\fP \fIhost\fP
Hostname to connect.
.It \fBport\fP \fIport\fP
Port to connect.
.It \fBserver-name\fP \fIservername\fP
.It \fBlabel\fP \fIkey\fP \fIvalue\fP
Append the label \fIkey\fP=\fIvalue\fP to the submitting metrics.
.It \fBinterval\fP \fIseconds\fP
Sets the interval (in seconds) in which the values will be collected
from this instance.
.It \fBfilter\fP
Configure a filter to modify or drop the metrics.
See \fBFILTER CONFIGURATION\fP in
.Xr ncollectd.conf 5 .
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
