.\" SPDX-License-Identifier: GPL-2.0-only
.TH ncollectd-nfacct 5 "@NCOLLECTD_DATE@" "@NCOLLECTD_VERSION@" "ncollectd nfacct man page"
.SH NAME
ncollectd-nfacct \- Documentation of ncollectd's nfacct plugin
.SH SYNOPSIS
\fBload-plugin\fP nfacct
.SH DESCRIPTION
The \fBnfacct\fP plugin retrive netfilter accounting objects.
With the command \f(CWnfacct\fP you can create/retrieve/delete this accounting objects.
.SH "SEE ALSO"
.BR ncollectd (1)
.BR ncollectd.conf (5)
