.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-NFACCT 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-nfacct
.Nd Documentation of ncollectd's nfacct plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP nfacct
\fBplugin\fP nfacct
.Ed
.Sh DESCRIPTION
The \fBnfacct\fP plugin retrieve netfilter accounting objects.
With the command \f(CWnfacct\fP you can create/retrieve/delete
this accounting objects.
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
