.\" SPDX-License-Identifier: GPL-2.0-only
.TH ncollectd-beanstalkd 5 "@NCOLLECTD_DATE@" "@NCOLLECTD_VERSION@" "ncollectd beanstalkd man page"
.SH NAME
ncollectd-beanstalkd \- Documentation of ncollectd's beanstalkd plugin
.SH SYNOPSIS
\fBload-plugin\fP beanstalkd
.br
\fBplugin\fP beanstalkd {
    \fBinstance\fP \fIinstance\fP {
        \fBhost\fP \fIhostname\fP
        \fBport\fP \fIport\fP
        \fBlabel\fP "\fIkey\fP" "\fIvalue\fP"
        \fBtimeout\fP \fIseconds\fP
        \fBinterval\fP \fIseconds\fP
        \fBfilter\fP {
             ...
        }
    }
.br
}
.SH DESCRIPTION
The \fBbeanstalkd\fP plugin connects to an instance of \fBbeanstalkd\fP to collect
server statistics.
.PP
The configuration of the \fBbeanstalkd\fP plugin consists of one or more
\fBinstance\fP blocks. Each block requires one string argument
as the instance name.
The following options are accepted within each \fBinstance\fP block:
.TP
\fBhost\fP \fIhostname\fP
Hostname of the host running \fBbeanstalkd\fP "status" virtual server. Defaults to \fIlocalhost\fP.
.TP
\fBport\fP \fIport\fP
TCP port of the "status" virtual server to connect to. Defaults to \fB11300\fP.
.TP
\fBtimeout\fP \fIseconds\fP
The \fBtimeout\fP option sets the overall timeout for the request to the beanstalkd server.
.TP
\fBlabel\fP \fIkey\fP \fIvalue\fP
Append the label \fIkey\fP=\fIvalue\fP to the submitting metrics.
.TP
\fBinterval\fP \fIseconds\fP
Sets the interval (in seconds) in which the values will be collected.
By default the global \fBinterval\fP setting will be used.
.TP
\fBfilter\fP ...
Configure a filter to modify or drop the metrics. See \fBFILTER CONFIGURATION\fP in
.BR ncollectd.conf(5)
.SH "SEE ALSO"
.BR ncollectd (1)
.BR ncollectd.conf (5)
