.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-NGINX_VTS 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-nginx_vts
.Nd Documentation of ncollectd's nginx_vts plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP \fInginx_vts\fP
\fBplugin\fP \fInginx_vts\fP
    \fBinstance\fP \fIinstance\fP {
        \fBurl\fP  \fIurl\fP
        \fBlabels\fP \fIkey\fP \fIvalue\fP
        \fBtimeout\fP \fIseconds\fP
        \fBinterval\fP \fIseconds\fP
        \fBfilter\fP {
            ...
        }
    }
}
.Ed
.Sh DESCRIPTION
The \fBnginx_vts\fP collect the metrics exposed from the Nginx virtual
host traffic status module.
.Bl -tag -width Ds
.It \fBurl\fP  \fIurl\fP
Sets the URL of the Nginx virtual host traffic status module.
.It \fBlabels\fP \fIkey\fP \fIvalue\fP
Append the label \fIkey\fP=\fIvalue\fP to the submitting metrics.
.It \fBtimeout\fP \fIseconds\fP
The \fBtimeout\fP option sets the overall timeout for HTTP requests
to \fBURL\fP, in seconds.
By default, the configured \fBinterval\fP is used to set the timeout.
.It \fBinterval\fP \fIseconds\fP
Sets the interval (in seconds) in which the values will be collected
from this URL.
By default the global \fBinterval\fP setting will be used.
.It \fBfilter\fP
Configure a filter to modify or drop the metrics.
See \fBFILTER CONFIGURATION\fP in
.Xr ncollectd.conf 5  .
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
