.\" SPDX-License-Identifier: GPL-2.0-only
.TH ncollectd-dmi 5 "@NCOLLECTD_DATE@" "@NCOLLECTD_VERSION@" "ncollectd dmi man page"
.SH NAME
ncollectd-dmi \- Documentation of ncollectd's dmi plugin
.SH SYNOPSIS
\fBload-plugin\fP dmi
.SH DESCRIPTION
The \fBdmi\fP plugin collects DMI information that is found at \fI/sys/class/dmi/id\fP:
\*(lqBIOS\*(rq, \*(lqBase Board\*(rq, \*(lqChassis\*(rq, and \*(lqSystem Information\*(rq sections.
.SH "SEE ALSO"
.BR ncollectd (1)
.BR ncollectd.conf (5)
