.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-DMI 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-dmi
.Nd Documentation of ncollectd's dmi plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP dmi
\fBplugin\fP dmi
.Ed
.Sh DESCRIPTION
The \fBdmi\fP plugin collects DMI information that is found at
\fI/sys/class/dmi/id\fP: \*(lqBIOS\*(rq, \*(lqBase Board\*(rq,
\*(lqChassis\*(rq, and \*(lqSystem Information\*(rq sections.
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
