.\" SPDX-License-Identifier: GPL-2.0-only
.TH ncollectd-wpar 5 "@NCOLLECTD_DATE@" "@NCOLLECTD_VERSION@" "ncollectd wpar man page"
.SH NAME
ncollectd-wpar \- Documentation of ncollectd's wpar plugin
.SH SYNOPSIS
\fBload-plugin\fP wpar
.br
\fBplugin\fP wpar
.SH DESCRIPTION
The \fBwpar\fP plugin reads statistics from the \fIWorkload Partitions\fP running in the system.
.SH "SEE ALSO"
.BR ncollectd (1)
.BR ncollectd.conf (5)
