.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-WPAR 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-wpar
.Nd Documentation of ncollectd's wpar plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP wpar
\fBplugin\fP wpar
.Ed
.Sh DESCRIPTION
The \fBwpar\fP plugin reads statistics from the \fIWorkload Partitions\fP
running in the system.
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
