.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-WRITE_EXPORTER 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-write_exporter
.Nd Documentation of ncollectd's write_exporter plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP write_exporter
\fBplugin\fP write_exporter {
    \fBinstance\fP "\fIinstance\fP" {
        \fBhost\fP \fIhost\fP
        \fBport\fP \fIport\fP
        \fBstaleness-delta\fP \fIseconds\fP
        \fBprivate-key\fP \fIfile-path\fP
        \fBprivate-key-password\fP \fIpassword\fP
        \fBcertificate\fP
        \fBtls-priority\fP
        \fBauth-method\fP \fIbasic|digest\fP
        \fBuser\fP \fIuser\fP
        \fBuser-env\fP \fIenv-name\fP
        \fBpassword\fP \fIpassword\fP
        \fBpassword-env\fP \fIenv-name\fP
        \fBrealm\fP \fIrealm\fP
        \fBformat-metric\fP \fIinfluxdb|graphite|json|kairosdb|opentsdb|openmetrics|opentelemetry|remote\fP
    }
}
.Ed
.Sh DESCRIPTION
The \fBwrite_exporter\fP plugin implements a tiny webserver that can be scraped.
.Pp
The following options are accepted within each \fBinstance\fP block:
.Bl -tag -width Ds
.It \fBhost\fP \fIhost\fP
Bind to the hostname / address \fIhost\fP.
By default, the plugin will bind to the "any" address, i.e. accept packets sent
to any of the hosts addresses.
.Pp
This option is supported only for libmicrohttpd newer than 0.9.0.
.It \fBport\fP \fIport\fP
Port the embedded webserver should listen on.
Defaults to \f(CWB9103\fP.
.It \fBstaleness-delta\fP \fIseconds\fP
Time in seconds after considers a metric "stale" if it hasn't seen any
update for it.
It defaults to \f(CW300\fP seconds (5 minutes).
.It \fBprivate-key\fP \fIfile-path\fP
.It \fBprivate-key-password\fP \fIpassword\fP
.It \fBcertificate\fP
.It \fBtls-priority\fP
.It \fBauth-method\fP \fIbasic|digest\fP
.It \fBuser\fP \fIuser\fP
.It \fBuser-env\fP \fIenv-name\fP
.It \fBpassword\fP \fIpassword\fP
.It \fBpassword-env\fP \fIenv-name\fP
.It \fBrealm\fP \fIrealm\fP
.It \fBformat-metric\fP \fIinfluxdb|graphite|json|kairosdb|opentsdb|openmetrics|remote\fP
Selects the format in which metrics are served.
.Bl -tag -width Ds
.It \fBinfluxdb\fP [\fIsec|msec|usec|nsec\fP]
.It \fBgraphite\fP
.It \fBjson\fP
.It \fBkairosdb\fP [\fItelnet [sec|msec]|json\fP]
.It \fBopentsdb\fP [telnet|json]
.It \fBopenmetrics\fP [text|protob]
.It \fBopentelemetry\fP [json]
.It \fBremote\fP [metadata]
.El
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
