.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-LOG_SYSTEMD 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-log_systemd
.Nd Documentation of ncollectd's log_systemd plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP log_systemd
\fBplugin\fP log_systemd {
    \fBlog-level\fP \fIdebug|info|notice|warning|err\fP
    \fBnotify-level\fP \fIokay|warning|failure\fP
}
.Ed
.Sh DESCRIPTION
The \fBlog_systemd\fP plugin receives log messages from the daemon and send them
to the
.Xr systemd 1
journal.
.Pp
The plugin suports the following options:
.Bl -tag -width Ds
.It \fBlog-level\fP \fIdebug|info|notice|warning|err\fP
Sets the log-level.
If, for example, set to \fInotice\fP, then all events with severity
\fInotice\fP, \fIwarning\fP, \fIerr\fP will be submitted to the
systemd journal.
.Pp
Please note that \fIdebug\fP is only available if collectd has been compiled
with debugging support.
.It \fBnotify-level\fP \fIokay|warning|failure\fP
Controls which notifications should be sent to the system journal.
The default behaviour is not to send any.
Less severe notifications always imply logging more severe notifications:
Setting this to \fBokay\fP means all notifications will be sent to systemd,
setting this to \fBwarning\fP will send \fBwarning\fP and \fBfailure\fP
notifications but will dismiss \fBokay\fP notifications.
Setting this option to \fBfailure\fP will only send failures to systemd.
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
