.\" SPDX-License-Identifier: GPL-2.0-only
.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTDCTL 1
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectdctl
.Nd Control interface for ncollectd
.Sh SYNOPSIS
.Bd -literal -compact
\fBncollectdctl\fP \fIcommand\fP [\fIcommand options\fP]
.Ed
.Sh DESCRIPTION
ncollectdctl provides a control interface for ncollectd, which may be used to
interact with the daemon.
.Sh OPTIONS
ncollectdctl supports the following commands:
.Bl -tag -width Ds
.It \fBhelp\fP
Display usage information and exit.
.It \fBreaders\fP \fB[OPTIONS]\fP
.Bl -tag -width Ds
.It \fB\-u\fR \fI\,PATH\/\fR, \fB\-\-unix-socket\fR=\fI\,PATH\/\fR
Path to the UNIX socket opened by ncollectd.
.It \fB\-o\fR \fI\,FORMAT\/\fR, \fB\-\-output\fR=\fI\,FORMAT\/\fR
.It \fB\-h\fR, \fB\-\-help\fR
Display usage information for this command and exit.
.El
.It \fBwriters\fP \fB[OPTIONS]\fP
.Bl -tag -width Ds
.It \fB\-u\fR \fI\,PATH\/\fR, \fB\-\-unix-socket\fR=\fI\,PATH\/\fR
Path to the UNIX socket opened by ncollectd.
.It \fB\-o\fR \fI\,FORMAT\/\fR, \fB\-\-output\fR=\fI\,FORMAT\/\fR
.It \fB\-h\fR, \fB\-\-help\fR
Display usage information for this command and exit.
.El
.It \fBloggers\fP \fB[OPTIONS]\fP
.Bl -tag -width Ds
.It \fB\-u\fR \fI\,PATH\/\fR, \fB\-\-unix-socket\fR=\fI\,PATH\/\fR
Path to the UNIX socket opened by ncollectd.
.It \fB\-o\fR \fI\,FORMAT\/\fR, \fB\-\-output\fR=\fI\,FORMAT\/\fR
.It \fB\-h\fR, \fB\-\-help\fR
Display usage information for this command and exit.
.El
.It \fBnotifiers\fP \fB[OPTIONS]\fP
.Bl -tag -width Ds
.It \fB\-u\fR \fI\,PATH\/\fR, \fB\-\-unix-socket\fR=\fI\,PATH\/\fR
Path to the UNIX socket opened by ncollectd.
.It \fB\-o\fR \fI\,FORMAT\/\fR, \fB\-\-output\fR=\fI\,FORMAT\/\fR
.It \fB\-h\fR, \fB\-\-help\fR
Display usage information for this command and exit.
.El
.It \fBwrite\fP \fB[OPTIONS]\fP
.Bl -tag -width Ds
.It \fB\-u\fR \fI\,PATH\/\fR, \fB\-\-unix-socket\fR=\fI\,PATH\/\fR
.It \fB\-d\fR \fI\,FILENAME\/\fR, \fB\-\-data\fR=\fI\,FILENAME\/\fR
.It \fB\-h\fR, \fB\-\-help\fR
.El
.It \fBread\fP \fB[OPTIONS]\fP
.Bl -tag -width Ds
.It \fB\-u\fR \fI\,PATH\/\fR, \fB\-\-unix-socket\fR=\fI\,PATH\/\fR
.It \fB\-s\fR \fB\-\-start\fR
.It \fB\-e\fR \fB\-\-end\fR
.It \fB\-r\fR \fB\-\-resolution\fR
.It \fB\-h\fR, \fB\-\-help\fR
.El
.It \fBnotification\fP \fB[OPTIONS]\fP
.Bl -tag -width Ds
.It \fB\-u\fR \fI\,PATH\/\fR, \fB\-\-unix-socket\fR=\fI\,PATH\/\fR
.It \fB\-n\fR \fI\,NAME\/\fR, \fB\-\-name\fR=\fI\,NAME\/\fR
.It \fB\-l\fR \fI\,KEY=VALUE\/\fR, \fB\-\-label\fR=\fI\,KEY=VALUE\/\fR
.It \fB\-a\fR \fI\,KEY=VALUE\/\fR, \fB\-\-annotation\fR=\fI\,KEY=VALUE\/\fR
.It \fB\-s\fR \fI\,OKAY|WARNING|FAILURE\/\fR, \fB\-\-severity\fR=\fI\,OKAY|WARNING|FAILURE\/\fR
.It \fB\-t\fR \fI\,TIMESTAMP\/\fR, \fB\-\-time\fR=\fI\,TIMESTAMP\/\fR
.It \fB\-h\fR, \fB\-\-help\fR
.El
.It \fBseries\fP \fB[OPTIONS]\fP
.Bl -tag -width Ds
.It \fB\-u\fR \fI\,PATH\/\fR, \fB\-\-unix-socket\fR=\fI\,PATH\/\fR
.It \fB\-m\fR \fI\,MATCH\/\fR, \fB\-\-match\fR=\fI\,MATCH\/\fR
.It \fB\-o\fR \fI\,FORMAT\/\fR, \fB\-\-output\fR=\fI\,FORMAT\/\fR
.It \fB\-h\fR, \fB\-\-help\fR
.El
.It \fBfamily-metrics\fP \fB[OPTIONS]\fP
.Bl -tag -width Ds
.It \fB\-u\fR \fI\,PATH\/\fR, \fB\-\-unix-socket\fR=\fI\,PATH\/\fR
.It \fB\-m\fR \fI\,MATCH\/\fR, \fB\-\-match\fR=\fI\,MATCH\/\fR
.It \fB\-o\fR \fI\,FORMAT\/\fR, \fB\-\-output\fR=\fI\,FORMAT\/\fR
.It \fB\-h\fR, \fB\-\-help\fR
.El
.It \fBmetrics\fP [\fIOPTIONS\fP]
.Bl -tag -width Ds
.It \fB\-u\fR \fI\,PATH\/\fR, \fB\-\-unix-socket\fR=\fI\,PATH\/\fR
.It \fB\-o\fR \fI\,FORMAT\/\fR, \fB\-\-output\fR=\fI\,FORMAT\/\fR
.It \fB\-h\fR, \fB\-\-help\fR
.El
.It \fBlabels\fP [\fIOPTIONS\fP] \fImetric\fP
.Bl -tag -width Ds
.It \fB\-u\fR \fI\,PATH\/\fR, \fB\-\-unix-socket\fR=\fI\,PATH\/\fR
.It \fB\-o\fR \fI\,FORMAT\/\fR, \fB\-\-output\fR=\fI\,FORMAT\/\fR
.It \fB\-h\fR, \fB\-\-help\fR
.El
.It \fBlabel-values\fP [OPTION] \fImetric\fP \fIlabel\fP
.Bl -tag -width Ds
.It \fB\-u\fR \fI\,PATH\/\fR, \fB\-\-unix-socket\fR=\fI\,PATH\/\fR
.It \fB\-o\fR \fI\,FORMAT\/\fR, \fB\-\-output\fR=\fI\,FORMAT\/\fR
.It \fB\-h\fR, \fB\-\-help\fR
.El
.It \fBquery\fP [\fBoptions\fP] \fBquery\fP
.Bl -tag -width Ds
.It \fB\-u\fR \fI\,PATH\/\fR, \fB\-\-unix-socket\fR=\fI\,PATH\/\fR
.It \fB\-o\fR \fI\,FORMAT\/\fR, \fB\-\-output\fR=\fI\,FORMAT\/\fR
.It \fB\-t\fR \fI\,TIME\/\fR, \fB\-\-time\fR=\fI\,TIME\/\fR
.It \fB\-h\fR, \fB\-\-help\fR
.El
.It \fBquery-range\fP [\fBoptions\fP] \fBquery\fP
.Bl -tag -width Ds
.It \fB\-u\fR \fI\,PATH\/\fR, \fB\-\-unix-socket\fR=\fI\,PATH\/\fR
.It \fB\-o\fR \fI\,FORMAT\/\fR, \fB\-\-output\fR=\fI\,FORMAT\/\fR
.It \fB\-s\fR \fI\,START\/\fR, \fB\-\-start\fR=\fI\,START\/\fR
.It \fB\-e\fR \fI\,END\/\fR, \fB\-\-end\fR=\fI\,END\/\fR
.It \fB\-S\fR \fI\,STEP\/\fR, \fB\-\-step\fR=\fI\,STEP\/\fR
.It \fB\-h\fR, \fB\-\-help\fR
.El
.It \fBgraph\fP [\fBoptions\fP]
.Bl -tag -width Ds
.It \fB\-s\fR \fI\,START\/\fR, \fB\-\-start\fR=\fI\,START\/\fR
.It \fB\-e\fR \fI\,END\/\fR, \fB\-\-end\fR=\fI\,END\/\fR
.It \fB\-S\fR \fI\,STEP\/\fR, \fB\-\-step\fR=\fI\,STEP\/\fR
.It \fB\-t\fR \fI\,TITLE\/\fR, \fB\-\-title\fR=\fI\,TITLE\/\fR
.It \fB\-v\fR \fI\,LABEL\/\fR, \fB\-\-vertical-label\fR=\fI\,LABEL\/\fR
.It \fB\-\-right-axis\fR
.It \fB\-\-right-axis-label\fR
.It \fB\-\-right-axis-formatter\fR
.It \fB\-\-right-axis-format\fR
.It \fB\-w\fR \fI\,WIDTH\/\fR, \fB\-\-width\fR=\fI\,WIDTH\/\fR
.It \fB\-h\fR \fI\,HEIGHT\/\fR, \fB\-\-height\fR=\fI\,HEIGHT\/\fR
.It \fB\-j\fR, \fB\-\-only-graph\fR
.It \fB\-D\fR, \fB\-\-full-size-mode\fR
.It \fB\-u\fR \fI\,UPPER\/\fR, \fB\-\-upper-limit\fR=\fI\,UPPER\/\fR
.It \fB\-l\fR \fI\,LOWER\/\fR, \fB\-\-lower-limit\fR=\fI\,LOWER\/\fR
.It \fB\-r\fR, \fB\-\-rigid\fR
.It \fB\-\-allow-shrink\fR
.It \fB\-A\fR, \fB\-\-alt-autoscale\fR
.It \fB\-J\fR, \fB\-\-alt-autoscale-min\fR
.It \fB\-M\fR, \fB\-\-alt-autoscale-max\fR
.It \fB\-N\fR, \fB\-\-no-gridfit\fR
.It \fB\-x\fR XXX, \fB\-\-x-grid\fR=XXX
.It \fB\-\-week-fmt\fR \fI\,FORMAT\/\fR
.It \fB\-y\fR XXX, \fB\-\-y-grid\fR=XXX
.It \fB\-\-left-axis-formatter\fR \fI\,FORMAT\/\fR
.It \fB\-Y\fR  XXX, \fB\-\-alt-y-grid\fR=XXX
.It \fB\-o\fR  XXX, \fB\-\-logarithmic\fR=XXX
.It \fB\-X\fR  XXX, \fB\-\-units-exponent\fR=XXX
.It \fB\-L\fR  XXX, \fB\-\-units-length\fR=XXX
.It \fB\-\-units\fR
.It \fB\-c\fR \fI\,COLOR\/\fR, \fB\-\-color\fR=\fI\,COLOR\/\fR
.It \fB\-\-grid-dash\fR
.It \fB\-\-border\fR
.It \fB\-\-dynamic-labels\fR
.It \fB\-n\fR XXX, \fB\-\-font\fR=XXX
.It \fB\-\-zoom\fR
.It \fB\-R\fR XXX, \fB\-\-font-render-mode\fR=XXX
.It \fB\-B\fR XXX, \fB\-\-font-smoothing-threshold\fR=XXX
.It \fB\-G\fR XXX, \fB\-\-graph-render-mode\fR=XXX
.It \fB\-E\fR, \fB\-\-slope-mode\fR
.It \fB\-g\fR, \fB\-\-no-legend\fR
.It \fB\-\-legend-position\fR
.It \fB\-\-legend-direction\fR
.It \fB\-F\fR XXX, \fB\-\-force-rules-legend\fR=XXX
.It \fB\-T\fR XXX, \fB\-\-tabwidth\fR=XXX
.It \fB\-b\fR XXX, \fB\-\-base\fR=XXX
.It \fB\-W\fR \fI\,WATERMARK\/\fR, \fB\-\-watermark\fR=\fI\,WATERMARK\/\fR
.It \fB\-a\fR \fI\,FORMAT\/\fR, \fB\-\-format\fR=\fI\,FORMAT\/\fR
.It \fB\-\-line\fR
.It \fB\-\-area\fR
.It \fB\-\-vrule\fR
.It \fB\-\-hrule\fR
.It \fB\-\-tick\fR
.It \fB\-H\fR \fB\-\-help\fR
.El
.It \fBtemplate\fP
.El
.Sh "OUTPUT FORMAT"
.Bl -tag -width Ds
.It \fBjson\fP
.It \fBjson-pretty\fP
.It \fByaml\fP
.It \fBtext\fP
.It \fBtxt\fP
.It \fBtable\fP
.Bd -literal
    ┌────────┐
    │ HEADER │
    ├────────┤
    │ cell   │
    └────────┘
.Ed
.It \fBtable-bold\fP
.Bd -literal
    ┏━━━━━━━━┓
    ┃ HEADER ┃
    ┣━━━━━━━━┫
    ┃ cell   ┃
    ┗━━━━━━━━┛
.Ed
.It \fBtable-border-bold\fP
.Bd -literal
    ┏━━━━━━━━┓
    ┃ HEADER ┃
    ┠────────┨
    ┃ cell   ┃
    ┗━━━━━━━━┛
.Ed
.It \fBtable-double\fP
.Bd -literal
    ╔════════╗
    ║ HEADER ║
    ╠════════╣
    ║ cell   ║
    ╚════════╝
.Ed
.It \fBtable-border-double\fP
.Bd -literal
    ╔════════╗
    ║ HEADER ║
    ╟────────╢
    ║ cell   ║
    ╚════════╝
.Ed
.It \fBtable-round\fP
.Bd -literal
    ╭────────╮
    │ HEADER │
    ├────────┤
    │ cell   │
    ╰────────╯
.Ed
.It \fBtable-ascii\fP
.Bd -literal
    +--------+
    | HEADER |
    +--------+
    | cell   |
    +--------+
.Ed
.El
.Sh ENVIRONMENT
The behavior of \fBncollectctl\fP is affected by the following
environment variables.
.Bl -tag -width Ds
.It \fBNCOLLECTDCTL_UNIX_SOCKET\fP
.It \fBNCOLLECTDCTL_OUTPUT_FORMAT\fP
.El
.Sh "SEE ALSO"
.Xr ncollectd 1
