.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-OPENVPN 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-openvpn
.Nd Documentation of ncollectd's openvpn plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP openvpn
\fBplugin\fP openvpn {
    \fBinstance\fP \fIname\fP {
        \fBstatus-file\fP \fI/path/to/status\fP
        \fBlabel\fP \fIkey\fP \fIvalue\fP
        \fBinterval\fP \fIseconds\fP
        \fBfilter\fP {
            ...
        }
    }
}
.Ed
.Sh DESCRIPTION
The \fBopenvpn\fP plugin reads a status file maintained by OpenVPN and gathers
traffic statistics about connected clients.
.Pp
To set up OpenVPN to write to the status file periodically, use the
\f(CW--status\fP option of OpenVPN.
So, in a nutshell you need:
.Bd -literal
  $ openvpn $OTHER_OPTIONS --status "/var/run/openvpn-status" 10
.Ed
.Pp
The \fBinstance\fP block has the following options:
.Bl -tag -width Ds
.It \fBstatus-file\fP \fI/path/to/status\fP
Specifies the location of the status file.
.It \fBlabel\fP \fIkey\fP \fIvalue\fP
Append the label \fIkey\fP=\fIvalue\fP to the submitting metrics.
.It \fBinterval\fP \fIseconds\fP
Sets the interval (in seconds) in which the values will be collected
from this instance.
.It \fBfilter\fP
Configure a filter to modify or drop the metrics.
See \fBFILTER CONFIGURATION\fP in
.Xr ncollectd.conf 5 .
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
