.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-TABLE 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-table
.Nd Documentation of ncollectd's table plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP table
\fBplugin\fP table {
    \fBtable\fP \fI/path/to/file\fP {
        \fBseparator\fP  \fIstring\fP
        \fBskip-lines\fP \fIlines\fP
        \fBmetric-prefix\fP \fIprefix\fP
        \fBlabel\fP \fIkey\fP \fIvalue\fP
        \fBinterval\fP \fIseconds\fP
        \fBresult\fP {
            \fBtype\fP \fIgauge|unknow|counter|info\fP
            \fBhelp\fP \fIhelp\fP
            \fBmetric\fP \fIname\fP
            \fBmetric-prefix\fP \fIprefix\fP
            \fBmetric-from\fP \fIcolumn\fP
            \fBlabel\fP \fIkey\fP \fIvalue\fP
            \fBlabel-from\fP \fIcolumn\fP
            \fBvalue-from\fP \fIcolumn\fP
            \fBshift\fP \fIvalue\fP
            \fBscale\fP \fIvalue\fP
        }
}
.Ed
.Sh DESCRIPTION
The \fBtable\fP plugin provides generic means to parse tabular data and dispatch
user specified values.
Values are selected based on column numbers.
.Pp
The configuration consists of one or more \fBtable\fP blocks, each of which
configures one file to parse.
Within each \fBtable\fP block, there are one or more \fBresult\fP blocks,
which configure which data to select and how to interpret it.
.Pp
The following options are available inside a \fBtable\fP block:
.Bl -tag -width Ds
.It \fBseparator\fP \fIstring\fP
Any character of string is interpreted as a delimiter between the different
columns of the table.
A sequence of two or more contiguous delimiters in the table is considered
to be a single delimiter, i. e. there cannot be any empty columns.
The default separator is a space.
.Pp
A horizontal tab, newline and carriage return may be specified by \f(CW\\t\fP,
\f(CW\\n\fP and \f(CW\\r\fP respectively.
Please note that the double backslashes are required because of ncollectd's
config parsing.
.It \fBskip-lines\fP \fIlines\fP
Skip the number of \fIlines\fP at the beginning of the file.
.It \fBmetric-prefix\fP \fIprefix\fP
Prepends the \fIprefix\fP to the metric name in the block \fBresult\fP.
.It \fBlabel\fP \fIkey\fP \fIvalue\fP
Append the label \fIkey\fP=\fIvalue\fP to the submitting metrics.
Can appear multiple time in the \fBtable\fP block.
.It \fBinterval\fP \fIseconds\fP
The \fBinterval\fP option allows you to define the length of time between reads.
If this is not set, the global \fBinterval\fP will be used.
.It \fBresult\fP
.Bl -tag -width Ds
.It \fBtype\fP \fIgauge|unknow|counter|info\fP
.It \fBhelp\fP \fIhelp\fP
.It \fBmetric\fP \fIname\fP
.It \fBmetric-prefix\fP \fIprefix\fP
.It \fBmetric-from\fP \fIcolumn\fP
.It \fBlabel\fP \fIkey\fP \fIvalue\fP
.It \fBlabel-from\fP \fIcolumn\fP
Append the label \fIkey\fP=\fIvalue\fP to the submitting metrics.
.It \fBvalue-from\fP \fIcolumn\fP
.It \fBshift\fP \fIvalue\fP
Value is added to gauge metrics values.
This value is not applied to counters.
.It \fBscale\fP \fIvalue\fP
The gauge metric value are multiplied by this value.
This value is not applied to counters.
.El
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
