.\" SPDX-License-Identifier: GPL-2.0-only
.TH ncollectd-pf 5 "@NCOLLECTD_DATE@" "@NCOLLECTD_VERSION@" "ncollectd pf man page"
.SH NAME
ncollectd-pf \- Documentation of ncollectd's pf plugin
.SH SYNOPSIS
\fBload-plugin\fP pf
.SH DESCRIPTION
The \fBpf\fP plugin collects statistics about BSD's packet filter, PF.
.SH "SEE ALSO"
.BR ncollectd (1)
.BR ncollectd.conf (5)
