.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-PF 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-pf
.Nd Documentation of ncollectd's pf plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP pf
\fBplugin\fP pf
.Ed
.Sh DESCRIPTION
The \fBpf\fP plugin collects statistics about BSD's packet filter, PF.
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
