.\" SPDX-License-Identifier: GPL-2.0-only
.TH ncollectd-bcache 5 "@NCOLLECTD_DATE@" "@NCOLLECTD_VERSION@" "ncollectd bcache man page"
.SH NAME
ncollectd-bcache \- Documentation of ncollectd's bcache plugin
.SH SYNOPSIS
\fBload-plugin\fP bache
.SH DESCRIPTION
The \fBbcache\fP plugin collect statistics from the block layer cache Bcache.
.SH "SEE ALSO"
.BR ncollectd (1)
.BR ncollectd.conf (5)
