.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-BCACHE 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-bcache
.Nd Documentation of ncollectd's bcache plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP bache
\fBplugin\fP bache
.Ed
.Sh DESCRIPTION
The \fBbcache\fP plugin collect statistics from the block layer cache Bcache.
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
