.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-RESCTRL 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-resctrl
.Nd Documentation of ncollectd's resctrl plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP resctrl
\fBplugin\fP resctrl
.Ed
.Sh DESCRIPTION
The \fBresctrl\fP plugin collect performance metrics from the
\f(CW/sys/fs/resctrl\fP interface to provide information on the last level cache.
.Pp
For more information on the support of the user interface for resource control
see
.Lk https://docs.kernel.org/arch/x86/resctrl.html
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
