.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-NTPD 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-ntpd
.Nd Documentation of ncollectd's ntpd plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP ntpd
\fBplugin\fP ntpd {
    \fBinstance\fP \fIinstance\fP {
        \fBhost\fP \fIhost\fP
        \fBport\fP \fIport\fP
        \fBtimeout\fP \fIseconds\fP
        \fBinterval\fP \fIseconds\fP
        \fBlabel\fP \fIkey\fP \fIvalue\fP
        \fBcollect\fP \fIflags\fP ...
        \fBfilter\fP {
            ...
        }
    }
}
.Ed
.Sh DESCRIPTION
The \fBntpd\fP plugin collects per-peer ntp data such as time offset and time
dispersion.
.Pp
For talking to \fBntpd\fP, it mimics what the \fBntpq\fP control program does
on the wire - using \fBmode 6\fP specific requests.
.Pp
The configuration of the \fBntpd\fP plugin consists of one or more
\fBinstance\fP blocks.
Each block requires one string argument as the instance name.
.Pp
The following options are accepted within each \fBinstance\fP block:
.Bl -tag -width Ds
.It \fBhost\fP \fIhost\fP
Hostname of the host running \fBntpd\fP.
Defaults to \fBlocalhost\fP.
.It \fBport\fP \fIport\fP
UDP port to connect to.
Defaults to \fB123\fP.
.It \fBtimeout\fP \fIseconds\fP
The \fBtimeout\fP option sets the timeout for the requests to the the ntpd daemon.
The default value is 2 seconds for the first package.
.It \fBinterval\fP \fIseconds\fP
Sets the interval (in seconds) in which the values will be collected from
this instance.
.It \fBlabel\fP \fIkey\fP \fIvalue\fP
Append the label \fIkey\fP=\fIvalue\fP to the submitting metrics.
.It \fBcollect\fP \fIflags\fP ...
.Bl -tag -width Ds
.It \fBsysinfo\fP
Collect the set of metrics such as those from the command: \f(CWntpq -c sysinfo\fP.
.It \fBkerninfo\fP
Collect the set of metrics such as those from the command: \f(CWntpq -c kerninfo\fP.
.It \fBsysstats\fP
Collect the set of metrics such as those from the command: \f(CWntpq -c sysstats\fP.
.It \fBauthinfo\fP
Collect the set of metrics such as those from the command: \f(CWntpq -c authinfo\fP.
.It \fBiostats\fP
Collect the set of metrics such as those from the command: \f(CWntpq -c iostats\fP.
.It \fBntsinfo\fP
Collect the set of metrics such as those from the command: \f(CWntpq -c ntsinfo\fP.
.It \fBntskeinfo\fP
Collect the set of metrics such as those from the command: \f(CWntpq -c ntskeinfo\fP.
.It \fBpeers\fP
Collect peers metrics such as those from the command: \f(CWntpq -c peers\fP
.El
.It \fBfilter\fP
Configure a filter to modify or drop the metrics.
See \fBFILTER CONFIGURATION\fP in
.Xr ncollectd.conf 5 .
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
