when:
  - event: pull_request
  - event: push

steps:
  build-fedora-41-clang:
    image: ncollectd/ci-fedora:41
    commands:
      - CC=clang cmake -B build-fedora-41-clang -S .
      - cmake --build build-fedora-41-clang
