when:
  - event: cron

steps:
  build-coverity:
    image: ncollectd/ci-coverity:latest
    secrets:
      - source: coverity_token
        target: COVERITY_TOKEN
      - source: coverity_email
        target: COVERITY_EMAIL
    commands:
      - TAG=`git describe --tags --match "v*"`
      - cmake -B build-coverity -S .
      - cov-build --dir cov-int cmake --build build-coverity
      - tar czf ncollectd.tgz cov-int
      - curl --form token=$${COVERITY_TOKEN}
        --form email=$${COVERITY_EMAIL}
        --form file=@ncollectd.tgz
        --form version="$${TAG#v}"
        --form description="Build of $${TAG#v}"
        https://scan.coverity.com/builds?project=ncollectd
