when:
  - event: cron

steps:
  build-fedora-41-clang-analyzer:
    image: ncollectd/ci-fedora:41
    commands:
      - scan-build cmake -B build-fedora-41-clang-analyzer -S .
      - scan-build cmake --build build-fedora-41-clang-analyzer
