when:
  - event: release
  - event: manual

steps:
  package-dist:
    image: ncollectd/ci-fedora:41
    commands:
      - cmake -B package-dist -S .
      - cmake --build package-dist -- dist
      - TAG=`git describe --tags --match "v*" | sed 's/^v//;s/-/./g'`
      - echo "TAG=$${TAG}" > package-dist/envvars
  package-fedora-40:
    image: ncollectd/ci-fedora:40
    commands:
      - . ./package-dist/envvars
      - export GIT_DIR=.do-not-find-it
      - mkdir -p package-fedora-40/SOURCES
      - cp packaging/fedora/init.d-ncollectd package-fedora-40/SOURCES
      - cp packaging/fedora/systemd.ncollectd.service package-fedora-40/SOURCES
      - cp package-dist/ncollectd-$${TAG}.tar.xz package-fedora-40/SOURCES
      - rpmbuild --define "_topdir `pwd`/package-fedora-40" --define "git_tag $${TAG}" -ba packaging/fedora/ncollectd.spec
  package-fedora-41:
    image: ncollectd/ci-fedora:41
    commands:
      - . ./package-dist/envvars
      - export GIT_DIR=.do-not-find-it
      - mkdir -p package-fedora-41/SOURCES
      - cp packaging/fedora/init.d-ncollectd package-fedora-41/SOURCES
      - cp packaging/fedora/systemd.ncollectd.service package-fedora-41/SOURCES
      - cp package-dist/ncollectd-$${TAG}.tar.xz package-fedora-41/SOURCES
      - rpmbuild --define "_topdir `pwd`/package-fedora-41" --define "git_tag $${TAG}" -ba packaging/fedora/ncollectd.spec
  package-fedora-rawhide:
    image: ncollectd/ci-fedora:rawhide
    commands:
      - . ./package-dist/envvars
      - export GIT_DIR=.do-not-find-it
      - mkdir -p package-fedora-rawhide/SOURCES
      - cp packaging/fedora/init.d-ncollectd package-fedora-rawhide/SOURCES
      - cp packaging/fedora/systemd.ncollectd.service package-fedora-rawhide/SOURCES
      - cp package-dist/ncollectd-$${TAG}.tar.xz package-fedora-rawhide/SOURCES
      - rpmbuild --define "_topdir `pwd`/package-fedora-rawhide" --define "git_tag $${TAG}" -ba packaging/fedora/ncollectd.spec
  package-centos-stream8:
    image: ncollectd/ci-centos:stream8
    commands:
      - . ./package-dist/envvars
      - export GIT_DIR=.do-not-find-it
      - mkdir -p package-centos-stream8/SOURCES
      - cp packaging/fedora/init.d-ncollectd package-centos-stream8/SOURCES
      - cp packaging/fedora/systemd.ncollectd.service package-centos-stream8/SOURCES
      - cp package-dist/ncollectd-$${TAG}.tar.xz package-centos-stream8/SOURCES
      - rpmbuild --define "_topdir `pwd`/package-centos-stream8" --define "git_tag $${TAG}" -ba packaging/fedora/ncollectd.spec
  package-centos-stream9:
    image: ncollectd/ci-centos:stream9
    commands:
      - . ./package-dist/envvars
      - export GIT_DIR=.do-not-find-it
      - mkdir -p package-centos-stream9/SOURCES
      - cp packaging/fedora/init.d-ncollectd package-centos-stream9/SOURCES
      - cp packaging/fedora/systemd.ncollectd.service package-centos-stream9/SOURCES
      - cp package-dist/ncollectd-$${TAG}.tar.xz package-centos-stream9/SOURCES
      - rpmbuild --define "_topdir `pwd`/package-centos-stream9" --define "git_tag $${TAG}" -ba packaging/fedora/ncollectd.spec
  package-centos-stream10:
    image: ncollectd/ci-centos:stream10
    commands:
      - . ./package-dist/envvars
      - export GIT_DIR=.do-not-find-it
      - mkdir -p package-centos-stream10/SOURCES
      - cp packaging/fedora/init.d-ncollectd package-centos-stream10/SOURCES
      - cp packaging/fedora/systemd.ncollectd.service package-centos-stream10/SOURCES
      - cp package-dist/ncollectd-$${TAG}.tar.xz package-centos-stream10/SOURCES
      - rpmbuild --define "_topdir `pwd`/package-centos-stream10" --define "git_tag $${TAG}" -ba packaging/fedora/ncollectd.spec
  package-debian-bullseye:
    image: ncollectd/ci-debian:bullseye
    commands:
      - . ./package-dist/envvars
      - export GIT_DIR=.do-not-find-it
      - mkdir -p package-debian-bullseye
      - tar -C package-debian-bullseye -xJf package-dist/ncollectd-$${TAG}.tar.xz
      - cp package-dist/ncollectd-$${TAG}.tar.xz package-debian-bullseye/ncollectd_$${TAG}.orig.tar.xz
      - cp -r packaging/debian package-debian-bullseye/ncollectd-$${TAG}/
      - cd package-debian-bullseye/ncollectd-$${TAG}
      - sed -i '1s/^ncollectd (0.0.0-1)/ncollectd ('$${TAG}'-1)/' debian/changelog
      - sed -i '1s/^ncollectd (0.0.0-1)/ncollectd ('$${TAG}'-1)/' debian/NEWS
      - dpkg-buildpackage
      - cd ..
      - rm -rf ncollectd-$${TAG}
  package-debian-bookworm:
    image: ncollectd/ci-debian:bookworm
    commands:
      - . ./package-dist/envvars
      - export GIT_DIR=.do-not-find-it
      - mkdir -p package-debian-bookworm
      - tar -C package-debian-bookworm -xJf package-dist/ncollectd-$${TAG}.tar.xz
      - cp package-dist/ncollectd-$${TAG}.tar.xz package-debian-bookworm/ncollectd_$${TAG}.orig.tar.xz
      - cp -r packaging/debian package-debian-bookworm/ncollectd-$${TAG}/
      - cd package-debian-bookworm/ncollectd-$${TAG}
      - sed -i '1s/^ncollectd (0.0.0-1)/ncollectd ('$${TAG}'-1)/' debian/changelog
      - sed -i '1s/^ncollectd (0.0.0-1)/ncollectd ('$${TAG}'-1)/' debian/NEWS
      - dpkg-buildpackage
      - cd ..
      - rm -rf ncollectd-$${TAG}
  package-debian-trixie:
    image: ncollectd/ci-debian:trixie
    commands:
      - . ./package-dist/envvars
      - export GIT_DIR=.do-not-find-it
      - mkdir -p package-debian-trixie
      - tar -C package-debian-trixie -xJf package-dist/ncollectd-$${TAG}.tar.xz
      - cp package-dist/ncollectd-$${TAG}.tar.xz package-debian-trixie/ncollectd_$${TAG}.orig.tar.xz
      - cp -r packaging/debian package-debian-trixie/ncollectd-$${TAG}/
      - cd package-debian-trixie/ncollectd-$${TAG}
      - sed -i '1s/^ncollectd (0.0.0-1)/ncollectd ('$${TAG}'-1)/' debian/changelog
      - sed -i '1s/^ncollectd (0.0.0-1)/ncollectd ('$${TAG}'-1)/' debian/NEWS
      - sed -i '/libvarnishapi-dev/d' debian/control
      - rm -f debian/ncollectd-varnish.install
      - dpkg-buildpackage
      - cd ..
      - rm -rf ncollectd-$${TAG}
  package-ubuntu-focal:
    image: ncollectd/ci-ubuntu:focal
    commands:
      - . ./package-dist/envvars
      - export GIT_DIR=.do-not-find-it
      - mkdir -p package-ubuntu-focal
      - tar -C package-ubuntu-focal -xJf package-dist/ncollectd-$${TAG}.tar.xz
      - cp package-dist/ncollectd-$${TAG}.tar.xz package-ubuntu-focal/ncollectd_$${TAG}.orig.tar.xz
      - cp -r packaging/debian package-ubuntu-focal/ncollectd-$${TAG}/
      - cd package-ubuntu-focal/ncollectd-$${TAG}
      - sed -i '1s/^ncollectd (0.0.0-1)/ncollectd ('$${TAG}'-1)/' debian/changelog
      - sed -i '1s/^ncollectd (0.0.0-1)/ncollectd ('$${TAG}'-1)/' debian/NEWS
      - dpkg-buildpackage
      - cd ..
      - rm -rf ncollectd-$${TAG}
  package-ubuntu-jammy:
    image: ncollectd/ci-ubuntu:jammy
    commands:
      - . ./package-dist/envvars
      - export GIT_DIR=.do-not-find-it
      - mkdir -p package-ubuntu-jammy
      - tar -C package-ubuntu-jammy -xJf package-dist/ncollectd-$${TAG}.tar.xz
      - cp package-dist/ncollectd-$${TAG}.tar.xz package-ubuntu-jammy/ncollectd_$${TAG}.orig.tar.xz
      - cp -r packaging/debian package-ubuntu-jammy/ncollectd-$${TAG}/
      - cd package-ubuntu-jammy/ncollectd-$${TAG}
      - sed -i '1s/^ncollectd (0.0.0-1)/ncollectd ('$${TAG}'-1)/' debian/changelog
      - sed -i '1s/^ncollectd (0.0.0-1)/ncollectd ('$${TAG}'-1)/' debian/NEWS
      - dpkg-buildpackage
      - cd ..
      - rm -rf ncollectd-$${TAG}
  package-ubuntu-noble:
    image: ncollectd/ci-ubuntu:noble
    commands:
      - . ./package-dist/envvars
      - export GIT_DIR=.do-not-find-it
      - mkdir -p package-ubuntu-noble
      - tar -C package-ubuntu-noble -xJf package-dist/ncollectd-$${TAG}.tar.xz
      - cp package-dist/ncollectd-$${TAG}.tar.xz package-ubuntu-noble/ncollectd_$${TAG}.orig.tar.xz
      - cp -r packaging/debian package-ubuntu-noble/ncollectd-$${TAG}/
      - cd package-ubuntu-noble/ncollectd-$${TAG}
      - sed -i '1s/^ncollectd (0.0.0-1)/ncollectd ('$${TAG}'-1)/' debian/changelog
      - sed -i '1s/^ncollectd (0.0.0-1)/ncollectd ('$${TAG}'-1)/' debian/NEWS
      - dpkg-buildpackage
      - cd ..
      - rm -rf ncollectd-$${TAG}
  package-opensuse-leap:
    image: ncollectd/ci-opensuse:leap
    commands:
      - . ./package-dist/envvars
      - export GIT_DIR=.do-not-find-it
      - mkdir -p package-opensuse-leap/SOURCES
      - cp packaging/opensuse/systemd.ncollectd.service package-opensuse-leap/SOURCES
      - cp package-dist/ncollectd-$${TAG}.tar.xz package-opensuse-leap/SOURCES
      - rpmbuild --define "_topdir `pwd`/package-opensuse-leap" --define "git_tag $${TAG}" -ba packaging/opensuse/ncollectd.spec
  package-opensuse-tumbleweed:
    image: ncollectd/ci-opensuse:tumbleweed
    commands:
      - . ./package-dist/envvars
      - export GIT_DIR=.do-not-find-it
      - mkdir -p package-opensuse-tumbleweed/SOURCES
      - cp packaging/opensuse/systemd.ncollectd.service package-opensuse-tumbleweed/SOURCES
      - cp package-dist/ncollectd-$${TAG}.tar.xz package-opensuse-tumbleweed/SOURCES
      - rpmbuild --define "_topdir `pwd`/package-opensuse-tumbleweed" --define "git_tag $${TAG}" -ba packaging/opensuse/ncollectd.spec
