when:
  - event: release
  - event: manual

steps:
  package-dist:
    image: ncollectd/ci-fedora:39
    commands:
      - cmake -B package-dist -S .
      - cmake --build package-dist -- dist
      - TAG=`git describe --tags --match "v*" | sed 's/^v//;s/-/./g'`
      - echo "TAG=$${TAG}" > package-dist/envvars
  package-fedora-38:
    image: ncollectd/ci-fedora:38
    commands:
      - . ./package-dist/envvars
      - mkdir -p package-fedora-38/SOURCES
      - cp packages/fedora/init.d-ncollectd package-fedora-38/SOURCES
      - cp packages/fedora/systemd.ncollectd.service package-fedora-38/SOURCES
      - cp package-dist/ncollectd-$${TAG}.tar.xz package-fedora-38/SOURCES
      - rpmbuild --define "_topdir `pwd`/package-fedora-38" --define "git_tag $${TAG}" -ba packages/fedora/ncollectd.spec
  package-fedora-39:
    image: ncollectd/ci-fedora:39
    commands:
      - . ./package-dist/envvars
      - mkdir -p package-fedora-39/SOURCES
      - cp packages/fedora/init.d-ncollectd package-fedora-39/SOURCES
      - cp packages/fedora/systemd.ncollectd.service package-fedora-39/SOURCES
      - cp package-dist/ncollectd-$${TAG}.tar.xz package-fedora-39/SOURCES
      - rpmbuild --define "_topdir `pwd`/package-fedora-39" --define "git_tag $${TAG}" -ba packages/fedora/ncollectd.spec
  package-fedora-40:
    image: ncollectd/ci-fedora:40
    commands:
      - . ./package-dist/envvars
      - mkdir -p package-fedora-40/SOURCES
      - cp packages/fedora/init.d-ncollectd package-fedora-40/SOURCES
      - cp packages/fedora/systemd.ncollectd.service package-fedora-40/SOURCES
      - cp package-dist/ncollectd-$${TAG}.tar.xz package-fedora-40/SOURCES
      - rpmbuild --define "_topdir `pwd`/package-fedora-40" --define "git_tag $${TAG}" -ba packages/fedora/ncollectd.spec
  package-fedora-rawhide:
    image: ncollectd/ci-fedora:rawhide
    commands:
      - . ./package-dist/envvars
      - mkdir -p package-fedora-rawhide/SOURCES
      - cp packages/fedora/init.d-ncollectd package-fedora-rawhide/SOURCES
      - cp packages/fedora/systemd.ncollectd.service package-fedora-rawhide/SOURCES
      - cp package-dist/ncollectd-$${TAG}.tar.xz package-fedora-rawhide/SOURCES
      - rpmbuild --define "_topdir `pwd`/package-fedora-rawhide" --define "git_tag $${TAG}" -ba packages/fedora/ncollectd.spec
  package-centos-stream8:
    image: ncollectd/ci-centos:stream8
    commands:
      - . ./package-dist/envvars
      - mkdir -p package-centos-stream8/SOURCES
      - cp packages/fedora/init.d-ncollectd package-centos-stream8/SOURCES
      - cp packages/fedora/systemd.ncollectd.service package-centos-stream8/SOURCES
      - cp package-dist/ncollectd-$${TAG}.tar.xz package-centos-stream8/SOURCES
      - rpmbuild --define "_topdir `pwd`/package-centos-stream8" --define "git_tag $${TAG}" -ba packages/fedora/ncollectd.spec
  package-centos-stream9:
    image: ncollectd/ci-centos:stream9
    commands:
      - . ./package-dist/envvars
      - mkdir -p package-centos-stream9/SOURCES
      - cp packages/fedora/init.d-ncollectd package-centos-stream9/SOURCES
      - cp packages/fedora/systemd.ncollectd.service package-centos-stream9/SOURCES
      - cp package-dist/ncollectd-$${TAG}.tar.xz package-centos-stream9/SOURCES
      - rpmbuild --define "_topdir `pwd`/package-centos-stream9" --define "git_tag $${TAG}" -ba packages/fedora/ncollectd.spec
  package-debian-buster:
    image: ncollectd/ci-debian:buster
    commands:
      - . ./package-dist/envvars
      - mkdir -p package-debian-buster
      - tar -C package-debian-buster -xJf package-dist/ncollectd-$${TAG}.tar.xz
      - cp package-dist/ncollectd-$${TAG}.tar.xz package-debian-buster/ncollectd_$${TAG}.orig.tar.xz
      - cp -r packages/debian package-debian-buster/ncollectd-$${TAG}/
      - cd package-debian-buster/ncollectd-$${TAG}
      - sed -i '1s/^ncollectd (0.0.0-1)/ncollectd ('$${TAG}'-1)/' debian/changelog
      - sed -i '1s/^ncollectd (0.0.0-1)/ncollectd ('$${TAG}'-1)/' debian/NEWS
      - rm -f debian/ncollectd-docker.install
      - rm -f debian/ncollectd-nftables.install
      - dpkg-buildpackage
      - cd ..
      - rm -rf ncollectd-$${TAG}
  package-debian-bullseye:
    image: ncollectd/ci-debian:bullseye
    commands:
      - . ./package-dist/envvars
      - mkdir -p package-debian-bullseye
      - tar -C package-debian-bullseye -xJf package-dist/ncollectd-$${TAG}.tar.xz
      - cp package-dist/ncollectd-$${TAG}.tar.xz package-debian-bullseye/ncollectd_$${TAG}.orig.tar.xz
      - cp -r packages/debian package-debian-bullseye/ncollectd-$${TAG}/
      - cd package-debian-bullseye/ncollectd-$${TAG}
      - sed -i '1s/^ncollectd (0.0.0-1)/ncollectd ('$${TAG}'-1)/' debian/changelog
      - sed -i '1s/^ncollectd (0.0.0-1)/ncollectd ('$${TAG}'-1)/' debian/NEWS
      - dpkg-buildpackage
      - cd ..
      - rm -rf ncollectd-$${TAG}
  package-debian-bookworm:
    image: ncollectd/ci-debian:bookworm
    commands:
      - . ./package-dist/envvars
      - mkdir -p package-debian-bookworm
      - tar -C package-debian-bookworm -xJf package-dist/ncollectd-$${TAG}.tar.xz
      - cp package-dist/ncollectd-$${TAG}.tar.xz package-debian-bookworm/ncollectd_$${TAG}.orig.tar.xz
      - cp -r packages/debian package-debian-bookworm/ncollectd-$${TAG}/
      - cd package-debian-bookworm/ncollectd-$${TAG}
      - sed -i '1s/^ncollectd (0.0.0-1)/ncollectd ('$${TAG}'-1)/' debian/changelog
      - sed -i '1s/^ncollectd (0.0.0-1)/ncollectd ('$${TAG}'-1)/' debian/NEWS
      - dpkg-buildpackage
      - cd ..
      - rm -rf ncollectd-$${TAG}
  package-debian-trixie:
    image: ncollectd/ci-debian:trixie
    commands:
      - . ./package-dist/envvars
      - mkdir -p package-debian-trixie
      - tar -C package-debian-trixie -xJf package-dist/ncollectd-$${TAG}.tar.xz
      - cp package-dist/ncollectd-$${TAG}.tar.xz package-debian-trixie/ncollectd_$${TAG}.orig.tar.xz
      - cp -r packages/debian package-debian-trixie/ncollectd-$${TAG}/
      - cd package-debian-trixie/ncollectd-$${TAG}
      - sed -i '1s/^ncollectd (0.0.0-1)/ncollectd ('$${TAG}'-1)/' debian/changelog
      - sed -i '1s/^ncollectd (0.0.0-1)/ncollectd ('$${TAG}'-1)/' debian/NEWS
      - sed -i '/libvarnishapi-dev/d' debian/control
      - rm -f debian/ncollectd-varnish.install
      - dpkg-buildpackage
      - cd ..
      - rm -rf ncollectd-$${TAG}
  package-ubuntu-focal:
    image: ncollectd/ci-ubuntu:focal
    commands:
      - . ./package-dist/envvars
      - mkdir -p package-ubuntu-focal
      - tar -C package-ubuntu-focal -xJf package-dist/ncollectd-$${TAG}.tar.xz
      - cp package-dist/ncollectd-$${TAG}.tar.xz package-ubuntu-focal/ncollectd_$${TAG}.orig.tar.xz
      - cp -r packages/debian package-ubuntu-focal/ncollectd-$${TAG}/
      - cd package-ubuntu-focal/ncollectd-$${TAG}
      - sed -i '1s/^ncollectd (0.0.0-1)/ncollectd ('$${TAG}'-1)/' debian/changelog
      - sed -i '1s/^ncollectd (0.0.0-1)/ncollectd ('$${TAG}'-1)/' debian/NEWS
      - dpkg-buildpackage
      - cd ..
      - rm -rf ncollectd-$${TAG}
  package-ubuntu-jammy:
    image: ncollectd/ci-ubuntu:jammy
    commands:
      - . ./package-dist/envvars
      - mkdir -p package-ubuntu-jammy
      - tar -C package-ubuntu-jammy -xJf package-dist/ncollectd-$${TAG}.tar.xz
      - cp package-dist/ncollectd-$${TAG}.tar.xz package-ubuntu-jammy/ncollectd_$${TAG}.orig.tar.xz
      - cp -r packages/debian package-ubuntu-jammy/ncollectd-$${TAG}/
      - cd package-ubuntu-jammy/ncollectd-$${TAG}
      - sed -i '1s/^ncollectd (0.0.0-1)/ncollectd ('$${TAG}'-1)/' debian/changelog
      - sed -i '1s/^ncollectd (0.0.0-1)/ncollectd ('$${TAG}'-1)/' debian/NEWS
      - dpkg-buildpackage
      - cd ..
      - rm -rf ncollectd-$${TAG}
  package-ubuntu-mantic:
    image: ncollectd/ci-ubuntu:mantic
    commands:
      - . ./package-dist/envvars
      - mkdir -p package-ubuntu-mantic
      - tar -C package-ubuntu-mantic -xJf package-dist/ncollectd-$${TAG}.tar.xz
      - cp package-dist/ncollectd-$${TAG}.tar.xz package-ubuntu-mantic/ncollectd_$${TAG}.orig.tar.xz
      - cp -r packages/debian package-ubuntu-mantic/ncollectd-$${TAG}/
      - cd package-ubuntu-mantic/ncollectd-$${TAG}
      - sed -i '1s/^ncollectd (0.0.0-1)/ncollectd ('$${TAG}'-1)/' debian/changelog
      - sed -i '1s/^ncollectd (0.0.0-1)/ncollectd ('$${TAG}'-1)/' debian/NEWS
      - dpkg-buildpackage
      - cd ..
      - rm -rf ncollectd-$${TAG}
