include(CheckFunctionExists)
include(CheckLibraryExists)

function(check_common_libs)
    if(BUILD_SOLARIS)
        check_function_exists(socket HAVE_SOCKET_LIBC)
        if(NOT HAVE_SOCKET_LIBC)
            check_library_exists(socket socket "" HAVE_SOCKET_LIBSOCKET)
            if(HAVE_SOCKET_LIBSOCKET)
                set(CMAKE_C_STANDARD_LIBRARIES ${CMAKE_C_STANDARD_LIBRARIES} "-lsocket" PARENT_SCOPE)
            endif()
        endif()

        check_function_exists(inet_ntop HAVE_INET_NTOP_LIBC)
        if(NOT HAVE_INET_NTOP_LIBC)
            check_library_exists(nsl inet_ntop "" HAVE_INET_NTOP_LIBNSL)
            if(HAVE_INET_NTOP_LIBNSL)
                set(CMAKE_C_STANDARD_LIBRARIES ${CMAKE_C_STANDARD_LIBRARIES} "-lnsl" PARENT_SCOPE)
            endif()
        endif()
    endif()

    check_function_exists(clock_gettime HAVE_CLOCK_GETTIME)
    if(NOT HAVE_CLOCK_GETTIME)
        check_library_exists(rt clock_gettime "" HAVE_CLOCK_GETTIME)
        if(NOT HAVE_CLOCK_GETTIME)
            check_library_exists(posix4 clock_gettime "" HAVE_CLOCK_GETTIME)
            if(HAVE_CLOCK_GETTIME)
                set(CMAKE_C_STANDARD_LIBRARIES ${CMAKE_C_STANDARD_LIBRARIES} "-lposix4" PARENT_SCOPE)
            endif()
        else()
            set(CMAKE_C_STANDARD_LIBRARIES ${CMAKE_C_STANDARD_LIBRARIES} "-lrt" PARENT_SCOPE)
        endif()
    endif()

    check_function_exists(nanosleep HAVE_NANOSLEEP)
    if(NOT HAVE_NANOSLEEP)
        check_library_exists(rt nanosleep "" HAVE_NANOSLEEP)
        if(NOT HAVE_NANOSLEEP)
            check_library_exists(posix4 nanosleep "" HAVE_NANOSLEEP)
            if(HAVE_NANOSLEEP)
                if(NOT "-lposix4" IN_LIST CMAKE_C_STANDARD_LIBRARIES)
                    set(CMAKE_C_STANDARD_LIBRARIES ${CMAKE_C_STANDARD_LIBRARIES} "-lposix4" PARENT_SCOPE)
                endif()
            endif()
        else()
            if(NOT "-lrt" IN_LIST CMAKE_C_STANDARD_LIBRARIES)
                set(CMAKE_C_STANDARD_LIBRARIES ${CMAKE_C_STANDARD_LIBRARIES} "-lrt" PARENT_SCOPE)
            endif()
        endif()
    endif()
endfunction()
