include(CheckCCompilerFlag)

function(check_c_compiler_flags C_FLAG_VAR)
    set(LOCAL_C_FLAGS "")
    set(FLAG_LIST "${ARGN}")
    foreach(FLAG IN LISTS FLAG_LIST)
        string(REPLACE "=" "_" FLAG_VAR ${FLAG})
        string(REPLACE "-" "_" FLAG_VAR ${FLAG_VAR})
        string(TOUPPER ${FLAG_VAR} FLAG_VAR)
        check_c_compiler_flag(${FLAG} CC_HAVE${FLAG_VAR})
        if(${CC_HAVE${FLAG_VAR}})
            set(LOCAL_C_FLAGS "${LOCAL_C_FLAGS} ${FLAG}")
        endif()
    endforeach()
    set(${C_FLAG_VAR} "${LOCAL_C_FLAGS}" PARENT_SCOPE)
endfunction()
