=encoding UTF-8

=head1 NAME

ncollectd-fhcount - Documentation of ncollectd's C<Fhcount plugin>

=head2 Plugin C<fhcount>

The C<fhcount> plugin provides statistics about used, unused and total number of
file handles on Linux.

The I<fhcount plugin> provides the following configuration options:

=over 4

=item B<ValuesAbsolute> B<true>|B<false>

Enables or disables reporting of file handles usage in absolute numbers,
e.g. file handles used. Defaults to B<true>.

=item B<ValuesPercentage> B<false>|B<true>

Enables or disables reporting of file handles usage in percentages, e.g.
percent of file handles used. Defaults to B<false>.

=back

=head1 SEE ALSO

L<collectd(1)>,
L<collectd.conf(5)>

=cut
