.\" SPDX-License-Identifier: GPL-2.0-only
.TH ncollectd-fhcount 5 "@NCOLLECTD_DATE@" "@NCOLLECTD_VERSION@" "ncollectd fhcount man page"
.SH NAME
ncollectd-fhcount \- Documentation of ncollectd's fhcount plugin
.SH SYNOPSIS
\fBload-plugin\fP fhcount
.SH DESCRIPTION
The \fBfhcount\fP plugin provides statistics about used, unused and total number of
file handles on Linux.
.SH "SEE ALSO"
.BR ncollectd (1)
.BR ncollectd.conf (5)
