.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-JOURNAL 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-journal
.Nd Documentation of ncollectd's journal plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP journal
\fBplugin\fP journal {
    \fBinstance\fP \fIname\fP {
        \fBnamespace\fP \fInamespace\fP
        \fBpath\fP \fIpath\fP
        \fBunit\fP \fIname\fP
        \fBinterval\fP \fIseconds\fP
        \fBmatch\fP \fImatch\fP {
            ...
        }
        \fBfilter\fP {
            ...
        }
    }
}
.Ed
.Sh DESCRIPTION
The \fBjournal\fP plugin reads logs from the systemd journal and process
the lines using a match plugin.
.Pp
The configuration consists of one or more \fBinstance\fP blocks that define a
systemd journal reader and a match plugin to process the log lines.
.Pp
The \fBinstance\fP block has the following options:
.Bl -tag -width Ds
.It \fBnamespace\fP \fInamespace\fP
Set the journal namespace from which to read journal messages.
.It \fBpath\fP \fIpath\fP
Set the directory from which to read journal files.
.It \fBunit\fP \fIname\fP
Get messages for the specified systemd unit.
.It \fBinterval\fP \fIseconds\fP
Configures the interval in which to read log lines.
Defaults to the plugin's default interval.
.It \fBmatch\fP \fImatch\fP
Configure the \fImatch\fP plugin to process the log lines.
.It \fBfilter\fP
Configure a filter to modify or drop the metrics.
See \fBFILTER CONFIGURATION\fP in
.Xr ncollectd.conf 5 .
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
