.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-MMC 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-mmc
.Nd Documentation of ncollectd's mmc plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP mmc
\fBplugin\fP mmc {
    \fBdevice\fP [\fIincl|include|excl|exclude\fP] \fIdevice-name\fP
}
.Ed
.Sh DESCRIPTION
The \fBmmc\fP plugin reads the percentage of bad blocks on mmc device.
The additional values for block erases and power cycles are also read.
.Bl -tag -width Ds
.It \fBdevice\fP [\fIincl|include|excl|exclude\fP] \fIdevice-name\fP
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
