.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-TAPE 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-tape
.Nd Documentation of ncollectd's tape plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP tape
\fBplugin\fP tape {
    \fBtape\fP [\fIincl|include|excl|exclude\fP] \fIname\fP
}
.Ed
.Sh DESCRIPTION
The \fBtape\fP plugin collects information about the usage of tapes.
.Bl -tag -width Ds
.It \fBtape\fP [\fIincl|include|excl|exclude\fP] \fIname\fP
Select tape based on the devicename.
See \fBINCLUDE AND EXCLUDE LISTS\fP in
.Xr ncollectd.conf 5 .
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
