.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-NFSD 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-nfsd
.Nd Documentation of ncollectd's nfsd plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP nfsd
\fBplugin\fP nfsd {
    \fBreport-v2\fP \fItrue|false\fP
    \fBreport-v3\fP \fItrue|false\fP
    \fBreport-v4\fP \fItrue|false\fP
}
.Ed
.Sh DESCRIPTION
The \fBnfsd\fP plugin collects information about the server statistics
of the Network File System (NFS).
It counts the number of procedure calls for each procedure,
grouped by version.
.Bl -tag -width Ds
.It \fBreport-v2\fP \fItrue|false\fP
Collect NFS v2 procedure calls metrics.
.It \fBreport-v3\fP \fItrue|false\fP
Collect NFS v3 procedure calls metrics.
.It \fBreport-v4\fP \fItrue|false\fP
Collect NFS v4 procedure calls metrics.
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
