.\" SPDX-License-Identifier: GPL-2.0-only
.TH ncollectd-nfsd 5 "@NCOLLECTD_DATE@" "@NCOLLECTD_VERSION@" "ncollectd nfsd man page"
.SH NAME
ncollectd-nfsd \- Documentation of ncollectd's \*nfsd plugin
.SH SYNOPSIS
\fBload-plugin\fP nfsd
.br
\fBplugin\fP nfsd {
    \fBreport-v2\fP \fItrue|false\fP
    \fBreport-v3\fP \fItrue|false\fP
    \fBreport-v4\fP \fItrue|false\fP
.br
}
.SH DESCRIPTION
The \fBnfsd\fP plugin collects information about the server statistics of the Network
File System (NFS). It counts the number of procedure calls for each procedure,
grouped by version.
.TP
\fBreport-v2\fP \fItrue|false\fP
Collect NFS v2 procedure calls metrics.
.TP
\fBreport-v3\fP \fItrue|false\fP
Collect NFS v3 procedure calls metrics.
.TP
\fBreport-v4\fP \fItrue|false\fP
Collect NFS v4 procedure calls metrics.
.SH "SEE ALSO"
.BR ncollectd (1)
.BR ncollectd.conf (5)
