.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-LOG_SYSLOG 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-log_syslog
.Nd Documentation of ncollectd's log_syslog plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP log_syslog
\fBplugin\fP log_syslog {
    \fBinstance\fP \fIname\fP {
        \fBhost\fP \fIhost\fP
        \fBport\fP \fIport\fP
        \fBlog-level\fP [\fIdebug|info|notice|warning|err\fP]
        \fBnotify-level\fP [\fIokay|warning|failure\fP]
        \fBfacility\fP [\fIkern|user|mail|daemon|auth|syslog|lpr|news|uucp|cron|authpriv|ftp|ntp|security|console|local[0-7]\fP]
        \fBtype\fP [\fIlocal|rfc3164|rfc5424\fP]
        \fBttl\fP \fIttl\fP
    }
}
.Ed
.Sh DESCRIPTION
The \fBlog_syslog\fP plugin receives log messages from the daemon and dispatches
them to a local
.Xr syslog 3
or to a remote syslog.
.Pp
The \fBlog_syslog\fP plugin can also act as a consumer of notifications
if the \fBnotify-level\fP option is provided.
.Bl -tag -width Ds
.It \fBhost\fP \fIhost\fP
.It \fBport\fP \fIport\fP
.It \fBlog-level\fP [\fIdebug|info|notice|warning|err\fP]
Sets the log-level.
If, for example, set to \fInotice\fP, then all events with severity
\fInotice\fP, \fIwarning\fP, or \fIerr\fP will be submitted to the
syslog-daemon.
.Pp
Please note that \fIdebug\fP is only available if ncollectd has been
compiled with debugging support.
.It \fBnotify-level\fP [\fIokay|warning|failure\fP]
Controls which notifications should be sent to syslog.
The default behaviour is not to send any.
Less severe notifications always imply logging more severe notifications:
Setting this to \fIokay\fP means all notifications will be sent to syslog,
setting this to \fIwarning\fP will send \fIwarning\fP and \fIfailure\FP
notifications but will dismiss \fIokay\fP notifications.
Setting this option to \fIfailure\fP will only send failures to syslog.
.It \fBfacility\fP [\fIkern|user|mail|daemon|auth|syslog|lpr|news|uucp|cron|authpriv|ftp|ntp|security|console|local[0-7]\fP]
.It \fBtype\fP [\fIlocal|rfc3164|rfc5424\fP]
.It \fBttl\fP \fIttl\fP
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
