=encoding UTF-8

=head1 NAME

ncollectd-load - Documentation of ncollectd's C<Load plugin>

=head2 Plugin C<load>

The I<Load plugin> collects the system load. These numbers give a rough overview
over the utilization of a machine. The system load is defined as the number of
runnable tasks in the run-queue and is provided by many operating systems as a
one, five or fifteen minute average.

The following configuration options are available:

=over 4

=item B<ReportRelative> B<false>|B<true>

When enabled, system load divided by number of available CPU cores is reported
for intervals 1 min, 5 min and 15 min. Defaults to false.

=back

=head1 SEE ALSO

L<collectd(1)>,
L<collectd.conf(5)>

=cut
