.\" SPDX-License-Identifier: GPL-2.0-only
.TH ncollectd-load 5 "@NCOLLECTD_DATE@" "@NCOLLECTD_VERSION@" "ncollectd load man page"
.SH NAME
ncollectd-load \- Documentation of ncollectd's load plugin
.SH SYNOPSIS
\fBload-plugin\fP load
.SH DESCRIPTION
The \fBload\fP plugin collects the system load. These numbers give a rough overview
over the utilization of a machine. The system load is defined as the number of
runnable tasks in the run-queue and is provided by many operating systems as a
one, five or fifteen minute average.
.SH "SEE ALSO"
.BR ncollectd (1)
.BR ncollectd.conf (5)
