.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-MQ 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-mq
.Nd Documentation of ncollectd's mq plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP mq
\fBplugin\fP mq {
    \fBinstance\fP \fIname\fP {
        \fBhost\fP \fIhostname\fP
        \fBport\fP \fIport\fP
        \fBuser\fP \fIusername\fP
        \fBuser-env\fP \fIenv-name\fP
        \fBpassword\fP \fIpassword\fP
        \fBpassword-env\fP \fIenv-name\fP
        \fBqueue-manager\fP \fImanager\fP
        \fBconnection-channel\fP \fIchannel\fP
        \fBlabel\fP \fIkey\fP \fIvalue\fP
        \fBinterval\fP \fIseconds\fP
        \fBfilter\fP {
            ...
        }
    }
}
.Ed
.Sh DESCRIPTION
The \fBmq\fP plugin collect metrics from a MQ server.
.Pp
The \fBinstance\fP block support the following options.
.Bl -tag -width Ds
.It \fBhost\fP \fIhostname\fP
Hostname of the MQ server to connect to.
.It \fBport\fP \fIport\fP
Port number or service name of the MQ server to connect to.
.It \fBuser\fP \fIusername\fP
Username used when authenticating to the MQ server.
.It \fBuser-env\fP \fIenv-name\fP
Get the username used when authenticating to the MQ server from the
environment variable \fIenv-name\fP
.It \fBpassword\fP \fIpassword\fP
Password used when authenticating to the MQ server.
.It \fBpassword-env\fP \fIenv-name\fP
Get the password used when authenticating to the MQ server from the
environment variable \fIenv-name\fP
.It \fBqueue-manager\fP \fImanager\fP
Sets the \fIqueue-manger\fP name to connect.
.It \fBconnection-channel\fP \fIchannel\fP
Sets the \fIclient connection channel\fP to connect.
.It \fBlabel\fP \fIkey\fP \fIvalue\fP
Append the label \fIkey\fP=\fIvalue\fP to the submitting metrics.
.It \fBinterval\fP \fIseconds\fP
Sets the interval (in seconds) in which the values will be collected
from this instance.
.It \fBfilter\fP
Configure a filter to modify or drop the metrics.
See \fBFILTER CONFIGURATION\fP in
.Xr ncollectd.conf 5 .
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
