.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-RAPL 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-rapl
.Nd Documentation of ncollectd's rapl plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP rapl
\fBplugin\fP rapl
.Ed
.Sh DESCRIPTION
Modern processors provide Running Average Power Limit (RAPL) interfaces for
reporting the accumulated energy consumption of various power domains,
the \fBrapl\fP plugin collects this information.
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
