.\" SPDX-License-Identifier: GPL-2.0-only
.TH ncollectd-rapl 5 "@NCOLLECTD_DATE@" "@NCOLLECTD_VERSION@" "ncollectd rapl man page"
.SH NAME
ncollectd-rapl \- Documentation of ncollectd's rapl plugin
.SH SYNOPSIS
\fBload-plugin\fP rapl
.br
\fBplugin\fP rapl
.SH DESCRIPTION
Modern processors provide Running Average Power Limit (RAPL) interfaces for reporting
the accumulated energy consumption of various power domains, the \fBrapl\fP plugin collects
this information.
.SH "SEE ALSO"
.BR ncollectd (1)
.BR ncollectd.conf (5)
