.\" SPDX-License-Identifier: GPL-2.0-only
.TH ncollectd-dnsmasq 5 "@NCOLLECTD_DATE@" "@NCOLLECTD_VERSION@" "ncollectd dnsmasq man page"
.SH NAME
ncollectd-dnsmasq \- Documentation of ncollectd's dnsmasq plugin
.SH SYNOPSIS
\fBload-plugin\fP dnsmasq
.br
\fBplugin\fP dnsmasq {
    \fBinstance\fP \fIinstance\fP {
        \fBhost\fP \fIhostname\fP
        \fBport\fP \fIport\fP
        \fBlabel\fP \fIkey\fP \fIvalue\fP
        \fBtimeout\fP \fIseconds\fP
        \fBleases\fP \fI/path/to/leases\fP
        \fBinterval\fP \fIseconds\fP
    }
.br
}
.SH DESCRIPTION
The \fBdnsmasq\fP plugin collect statistics of dnsmasq daemon.
.PP
The plugin configuration consists of one or more \fBinstance\fP blocks which
specify one \fIdnsmasq\fP server each. Within the \fBinstance\fP blocks, the
following options are allowed:
.PP
.TP
\fBhost\fP \fIhostname\fP
Hostname or address to connect to. Default to \f(CW127.0.0.1\fP
.TP
\fBport\fP \fIport\fP
Service name or port number to connect to. Defaults to \f(CW43\fP
.TP
\fBlabel\fP \fIkey\fP \fIvalue\fP
Append the label \fIkey\fP=\fIvalue\fP to the submitting metrics.
.TP
\fBtimeout\fP \fIseconds\fP
Set the timeout for the DNS query to get metrics from dnsmasq. TODO
.TP
\fBleases\fP \fI/path/to/leases\fP
Leases file path. Default to \fI/var/lib/misc/dnsmasq.leases\fP. TODO
.TP
\fBinterval\fP \fIseconds\fP
Sets the interval (in seconds) in which the values will be collected from this instance.
.SH "SEE ALSO"
.BR ncollectd (1)
.BR ncollectd.conf (5)
