.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-TIMEX 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-timex
.Nd Documentation of ncollectd's timex plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP timex
\fBplugin\fP timex
.Ed
.Sh DESCRIPTION
The \fBtimex\fP plugin exports state of kernel time synchronization flag
that should be maintained by time-keeping daemon and is eventually raised
by Linux kernel if time-keeping daemon does not update it regularly.
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
