.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-ENTROPY 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-entropy
.Nd Documentation of ncollectd's entropy plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP entropy
\fBplugin\fP entropy
.Ed
.Sh DESCRIPTION
The \fBentropy\fP plugin collects the available entropy on a system.
Entropy is important to generate random numbers, which are used for encryption,
authorization and similar tasks.
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
