.\" SPDX-License-Identifier: GPL-2.0-only
.TH ncollectd-entropy 5 "@NCOLLECTD_DATE@" "@NCOLLECTD_VERSION@" "ncollectd entropy man page"
.SH NAME
ncollectd-entropy \- Documentation of ncollectd's entropy plugin
.SH SYNOPSIS
\fBload-plugin\fP entropy
.SH DESCRIPTION
The \fBentropy\fP plugin collects the available entropy on a system.
Entropy is important to generate random numbers, which are used for encryption,
authorization and similar tasks.
.SH "SEE ALSO"
.BR ncollectd (1)
.BR ncollectd.conf (5)
