.\" SPDX-License-Identifier: GPL-2.0-only
.TH ncollectd-users 5 "@NCOLLECTD_DATE@" "@NCOLLECTD_VERSION@" "ncollectd users man page"
.SH NAME
ncollectd-users \- Documentation of ncollectd's users plugin
.SH SYNOPSIS
\fBload-plugin\fP users
.SH DESCRIPTION
The \fBusers\fP plugin counts the number of users currently logged into the system.
.SH "SEE ALSO"
.BR ncollectd (1)
.BR ncollectd.conf (5)
