.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-USERS 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-users
.Nd Documentation of ncollectd's users plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP users
\fBplugin\fP users
.Ed
.Sh DESCRIPTION
The \fBusers\fP plugin counts the number of users currently logged
into the system.
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
