.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-VIRT 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-virt
.Nd Documentation of ncollectd's virt plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP virt
\fBplugin\fP virt {
    \fBinstance\fP \fIname\fP {
        \fBconnection\fP \fIuri\fP
        \fBdomain\fP [\fIincl|include|excl|exclude\fP] \fIdomain\fP
        \fBblock-device\fP [\fIincl|include|excl|exclude\fP] \fIdevice\fP
        \fBblock-device-format\fP \fItarget|source\fP
        \fBinterface-device\fP [\fIincl|include|excl|exclude\fP] \fIdevice\fP
        \fBinterface-format\fP \fIname|address|number\fP
        \fBpersistent-notification\fP \fItrue|false\fP
        \fBlabel\fP \fIkey\fP \fIvalue\fP
        \fBcollect\fP \fIflags\fP
        \fBrefresh-interval\fP \fIseconds\fP
        \fBinterval\fP \fIseconds\fP
        \fBfilter\fP {
            ...
        }
    }
}
.Ed
.Sh DESCRIPTION
The \fBvirt\fP plugin allows CPU, disk, network load and other metrics to
be collected for virtualized guests on the machine.
The statistics are collected through libvirt.
Majority of metrics can be gathered without installing any additional
software on guests, especially ncollectd, which runs only on the host system.
.Pp
In the \fBinstance\fP block only \fBconnection\fP is required.
The following options are accepted within each \fBinstance\fP block:
.Bl -tag -width Ds
.It \fBconnection\fP \fIuri\fP
Connect to the hypervisor given by \fIuri\fP.
For example if using Xen use:
.Bd -literal
    \fBconnection\fP "xen:///"
.Ed
.Pp
Details which URIs allowed are given at
.Lk http://libvirt.org/uri.html
.It \fBdomain\fP [\fIincl|include|excl|exclude\fP] \fIdomain\fP
Select which domains collected.
.It \fBblock-device\fP [\fIincl|include|excl|exclude\fP] \fIdevice\fP
Select which block devices are collected.
.It \fBblock-device-format\fP \fItarget|source\fP
If \fBblock-device-format\fP is set to \fItarget\fP, the default, then the
device name seen by the guest will be used for reporting metrics.
This corresponds to the \f(CW<target>\fP node in the XML definition of
he domain.
.Pp
If \fBBlockDeviceFormat\fP is set to \fIsource\fP, then metrics will be
reported using the path of the source, e.g. an image file.
This corresponds to the \f(CW<source>\fP node in the XML definition of
the domain.
.It \fBinterface-device\fP [\fIincl|include|excl|exclude\fP] \fIdevice\fP
Select which interface devices are collected.
.It \fBinterface-format\fP \fIname|address|number\fP
When the virt plugin logs interface data, it sets the name of the collected
data according to this setting.
The default is to use the path as provided by the hypervisor
(the "dev" property of the target node), which is equal to setting \fIname\fP.
.Pp
\fIaddress\fP means use the interface's mac address.
This is useful since the interface path might change between reboots of a
guest or across migrations.
.Pp
\fInumber\fP means use the interface's number in guest.
.Pp
\fBNote\fP: this option determines also what field will be used for
filtering over interface device (filter value in \fBinterface-device\fP
will be applied to name, address or number).
More info about filtering interfaces can be found in the description of
\fBinterface-device\fP.
.It \fBpersistent-notification\fP \fItrue|false\fP
Override default configuration to only send notifications when there is
a change in the lifecycle state of a domain.
When set to true notifications will be sent for every read cycle.
Default is false.
Does not affect the stats being dispatched.
.It \fBlabel\fP \fIkey\fP \fIvalue\fP
Append the label \fIkey\fP=\fIvalue\fP to the submitting metrics.
.It \fBcollect\fP \fIflags\fP
.Bl -tag -width Ds
.It \fBdisk\fP
Report extra statistics like number of flush operations and total
service time for read, write and flush operations.
Requires libvirt API version \fI0.9.5\fP or later.
.It \fBpcpu\fP
Report the physical user/system cpu time consumed by the hypervisor, per-vm.
Requires libvirt API version \fI0.9.11\fP or later.
.It \fBcpu_util\fP
Report CPU utilization per domain in percentage.
.It \fBdomain_state\fP
Report domain state and reason.
.It \fBperf\fP
Report performance monitoring events.
To collect performance metrics they must be enabled for domain and supported
by the platform.
Requires libvirt API version \fI1.3.3\fP :or later.
.Pp
Note: \fIperf\fP metrics can't be collected if \fIintel_rdt\fP plugin
is enabled.
.It \fBvcpupin\fP
Report pinning of domain VCPUs to host physical CPUs.
.It \fBdisk_err\fP
Report disk errors if any occured.
Requires libvirt API version \fI0.9.10\fP or later.
.It \fBfs_info\fP
Report file system information as a notification.
Requires libvirt API version \fI1.2.11\fP or later.
Can be collected only if \fIGuest Agent\fP is installed and configured
inside VM.
Make sure that installed \fIGuest Agent\fP version supports retrieving
file system information.
.It \fBdisk_allocation\fP
Report 'disk_allocation' statistic for disk device.
.Pp
Note: This statistic is only reported for disk devices with 'source' property
available.
.It \fBdisk_capacity\fP
Report statistic for disk device.
.Pp
Note: This statistic is only reported for disk devices with 'source' property
available.
.It \fBdisk_physical\fP
Report statistic for disk device.
.Pp
Note: This statistic is only reported for disk devices with 'source' property
available.
.It \fBmemory\fP
Report statistics about memory usage details, provided by libvirt
.Fn virDomainMemoryStats
function.
.It \fBvcpu\fP
Report domain virtual CPUs utilisation.
.El
.It \fBrefresh-interval\fP \fIseconds\fP
Refresh the list of domains and devices every \fIseconds\fP.
The default is 60 seconds.
Setting this to be the same or smaller than the \fIInterval\fP will cause the
list of domains and devices to be refreshed on every iteration.
.Pp
Refreshing the devices in particular is quite a costly operation, so if your
virtualization setup is static you might consider increasing this.
If this option is set to 0, refreshing is disabled completely.
.It \fBinterval\fP \fIseconds\fP
Sets the interval (in seconds) in which the values will be collected from this
instanced.
By default the global \fBinterval\fP setting will be used.
.It \fBfilter\fP
Configure a filter to modify or drop the metrics.
See \fBFILTER CONFIGURATION\fP in
.Xr ncollectd.conf 5 .
.El
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
