.\" SPDX-License-Identifier: GPL-2.0-only
.Dd @NCOLLECTD_DATE@
.Dt NCOLLECTD-SERIAL 5
.Os ncollectd @NCOLLECTD_VERSION@
.Sh NAME
.Nm ncollectd-serial
.Nd Documentation of ncollectd's serial plugin
.Sh SYNOPSIS
.Bd -literal -compact
\fBload-plugin\fP serial
\fBplugin\fP serial
.Ed
.Sh DESCRIPTION
The \fBserial\fP plugin collects statistics of the traffic on serial interfaces,
reading the file \f(CW/proc/tty/driver/serial\fP.
.Sh "SEE ALSO"
.Xr ncollectd 1 ,
.Xr ncollectd.conf 5
