.\" SPDX-License-Identifier: GPL-2.0-only
.TH ncollectd-serial 5 "@NCOLLECTD_DATE@" "@NCOLLECTD_VERSION@" "ncollectd serial man page"
.SH NAME
ncollectd-serial \- Documentation of ncollectd's serial plugin
.SH SYNOPSIS
\fBload-plugin\fP serial
.SH DESCRIPTION
The \fBserial\fP plugin collects statistics of the traffic on serial interfaces,
reading the file \f(CW/proc/tty/driver/serial\fP.
.SH "SEE ALSO"
.BR ncollectd (1)
.BR ncollectd.conf (5)
